(async()=>{
'use strict';
const VERSION='wof-hudanchor-browser-proof-v1',CHANNEL='wof-hudanchor-proof-v1',BASE='https://raw.githubusercontent.com/ouyong520/wof-ai-private/main/parallel/HUDANCHOR_PROOF/',NW=384,NH=224;
try{window.WOFHUDANCHOR?.stop?.();}catch(_){}
const canvas=window.I_GF1TC||document.getElementById('whathis'),gl=window.I_fdC8Q;if(!canvas||!gl||typeof gl.drawArrays!=='function')throw new Error('game WebGL canvas/context unavailable');
const glFactory=(0,eval)(await fetch(BASE+'wof_hudanchor_gl.js?'+Date.now()).then(r=>{if(!r.ok)throw new Error('GL helper fetch '+r.status);return r.text();}));
const bc=new BroadcastChannel(CHANNEL),round=(v,n=3)=>Number.isFinite(+v)?+(+v).toFixed(n):null,span=(a,b)=>Number.isFinite(a)&&Number.isFinite(b)?b-a:0;
let running=true,last=null,lastRx=0,focus='P1',armed=true,cal=null,decision=null,resultCache=null,raf=0,renderer=null;
let layoutBase=null,layoutLast=null,layoutChanges=0,layoutChangedAt=0,layoutRecovered=false;const layoutEvents=[],focusMs={P1:0,P2:0,P3:0};let lastFocusTick=performance.now();
const ev={x0:Infinity,x1:-Infinity,y0:Infinity,y1:-Infinity,z0:Infinity,z1:-Infinity,c0:Infinity,c1:-Infinity,n:0};
function metrics(){return renderer?.metrics?.()||{dbWidth:gl.drawingBufferWidth||canvas.width,dbHeight:gl.drawingBufferHeight||canvas.height,viewport:[0,0,gl.drawingBufferWidth||canvas.width,gl.drawingBufferHeight||canvas.height],viewportSource:'full-buffer-fallback',hookCount:0,drawCount:0,lastDrawAt:0};}
function vpInfo(){const m=metrics(),[x,y,w,h]=m.viewport.map(Number),top=m.dbHeight-(y+h),ok=m.dbWidth>0&&m.dbHeight>0&&w>0&&h>0&&x>=0&&y>=0&&x+w<=m.dbWidth+1&&y+h<=m.dbHeight+1;return{ok,dbWidth:m.dbWidth,dbHeight:m.dbHeight,x,y,width:w,height:h,top,source:m.viewportSource};}
function clientDb(cx,cy){const r=canvas.getBoundingClientRect(),v=vpInfo();return r.width>0&&r.height>0?{x:(cx-r.left)/r.width*v.dbWidth,y:(cy-r.top)/r.height*v.dbHeight}:null;}
function clientNative(cx,cy){const d=clientDb(cx,cy),v=vpInfo();return d&&v.ok?{x:(d.x-v.x)/v.width*NW,y:(d.y-v.top)/v.height*NH}:null;}
function nativeDb(x,y){const v=vpInfo();return v.ok?{x:v.x+x/NW*v.width,y:v.top+y/NH*v.height}:null;}
function inside(cx,cy){const d=clientDb(cx,cy),v=vpInfo();return !!d&&v.ok&&d.x>=v.x&&d.x<=v.x+v.width&&d.y>=v.top&&d.y<=v.top+v.height;}
const candidate=()=>last?.cameraTop?.[0]||null,locked=()=>last?.lockedCamera||null;
function resetRanges(){ev.x0=ev.y0=ev.z0=ev.c0=Infinity;ev.x1=ev.y1=ev.z1=ev.c1=-Infinity;ev.n=0;}
function calibrate(cx,cy){const p=last?.players?.P1,cam=candidate(),n=clientNative(cx,cy);if(!p)throw new Error('NO_LIVE_P1');if(!last?.cameraQuality?.ok||!cam)throw new Error(last?.cameraQuality?.reason||'CAMERA_NOT_READY');if(!n||!inside(cx,cy))throw new Error('CLICK_OUTSIDE_GAME_VIEWPORT');cal={at:Date.now(),cameraAddress:cam.address,cameraRead:cam.read||'u16be',cameraQuality:{...last.cameraQuality},nativeClick:n,player:{...p},xBias:n.x-(p.x-cam.value),minus:n.y-(p.y-p.z),plus:n.y-(p.y+p.z),none:n.y-p.y};armed=false;bc.postMessage({schema:CHANNEL,kind:'lock-camera',address:cam.address});resetRanges();layoutBase=layoutSnapshot();layoutLast=layoutBase;return cal;}
function point(name,kind){if(!cal||!last)return null;const p=last.players?.[name],cam=locked();if(!p||!cam||cam.address!==cal.cameraAddress)return null;const x=p.x-cam.value+cal.xBias,b=kind==='plus'?cal.plus:kind==='none'?cal.none:cal.minus,y=kind==='plus'?p.y+p.z+b:kind==='none'?p.y+b:p.y-p.z+b,d=nativeDb(x,y);return d?{kind,x:d.x,y:d.y,native:{x,y},player:p}:null;}
renderer=glFactory({gl,canvas,getPoints:()=>cal?['minus','plus','none'].map(k=>point(focus,k)).filter(Boolean):[]});
function layoutSnapshot(){const r=canvas.getBoundingClientRect(),m=metrics(),v=vpInfo();return{at:Date.now(),canvasCss:{left:round(r.left,2),top:round(r.top,2),width:round(r.width,2),height:round(r.height,2)},drawingBuffer:{width:m.dbWidth,height:m.dbHeight},viewport:{x:v.x,y:v.y,width:v.width,height:v.height,top:v.top,source:v.source},dpr:round(devicePixelRatio||1),fullscreen:!!document.fullscreenElement};}
const sig=x=>x?JSON.stringify([x.canvasCss.width,x.canvasCss.height,x.drawingBuffer.width,x.drawingBuffer.height,x.viewport.x,x.viewport.y,x.viewport.width,x.viewport.height,x.dpr,x.fullscreen]):'';
function updateEvidence(){const t=performance.now();focusMs[focus]+=Math.max(0,t-lastFocusTick);lastFocusTick=t;if(!cal||!last)return;const p=last.players?.P1,cam=locked();if(p&&cam){ev.x0=Math.min(ev.x0,p.x);ev.x1=Math.max(ev.x1,p.x);ev.y0=Math.min(ev.y0,p.y);ev.y1=Math.max(ev.y1,p.y);ev.z0=Math.min(ev.z0,p.z);ev.z1=Math.max(ev.z1,p.z);ev.c0=Math.min(ev.c0,cam.value);ev.c1=Math.max(ev.c1,cam.value);ev.n++;}const x=layoutSnapshot();if(!layoutBase)layoutBase=x;if(layoutLast&&sig(layoutLast)!==sig(x)){layoutChanges++;layoutChangedAt=Date.now();layoutEvents.push(x);if(layoutEvents.length>6)layoutEvents.shift();}layoutLast=x;if(layoutChanges&&Date.now()-layoutChangedAt>900&&vpInfo().ok&&point('P1','minus'))layoutRecovered=true;}
function checklist(){const extra=['P2','P3'].filter(n=>!!last?.players?.[n]),m=metrics();const c={workerFresh:!!lastRx&&Date.now()-lastRx<700,camera:!!cal&&!!cal.cameraQuality?.ok&&locked()?.address===cal.cameraAddress,horizontal:span(ev.x0,ev.x1)>=24&&span(ev.c0,ev.c1)>=6,depth:span(ev.y0,ev.y1)>=8,jump:span(ev.z0,ev.z1)>=8,drawingBuffer:m.hookCount>=30&&m.drawCount>=30&&vpInfo().ok,resize:layoutChanges>0&&layoutRecovered,p2p3:extra.length===0||extra.every(n=>focusMs[n]>=1200&&!!point(n,'minus')),extraPlayers:extra};c.all=c.workerFresh&&c.camera&&c.horizontal&&c.depth&&c.jump&&c.drawingBuffer&&c.resize&&c.p2p3;return c;}
const failMap={FAIL_X:'x_camera_transform',FAIL_DEPTH:'depth_y',FAIL_JUMP:'jump_z',FAIL_DB:'drawing_buffer',FAIL_RESIZE:'resize_fullscreen',FAIL_PLAYERS:'p2p3_reuse',FAIL_CLEARANCE:'above_character_clearance'};
function projection(code){const kind=code==='PASS_PLUS'?'plus':code==='PASS_NONE'?'none':'minus',model=kind==='minus'?'Y-Z':kind==='plus'?'Y+Z':'Y',bias=cal[kind];return{camera:{address:cal.cameraAddress,read:cal.cameraRead},native:{width:NW,height:NH,xFormula:'worldX-camera+xBias',xBias:round(cal.xBias),yModel:model,yFormula:kind==='minus'?'worldY-z+yBias':kind==='plus'?'worldY+z+yBias':'worldY+yBias',yBias:round(bias),aboveCharacterOffsetNative:round(bias),aboveCharacterOffsetMeaning:'logical constant from raw player floor/Z reference to chosen warning anchor; not sprite-height claim'},drawingBuffer:{source:'live WebGL VIEWPORT',formula:'xDb=vp.x+nativeX/384*vp.width; yDb=vp.top+nativeY/224*vp.height',viewportYConversion:'vp.top=dbHeight-(vp.y+vp.height)'}};}
function build(code=decision){const c=checklist(),f=failMap[code];let verdict;if(f)verdict='FAILED_COMPONENT:'+f;else if(code?.startsWith('PASS_')){if(!c.workerFresh)verdict='FAILED_COMPONENT:worker_bridge';else if(!c.camera)verdict='FAILED_COMPONENT:camera';else if(!c.horizontal)verdict='FAILED_COMPONENT:camera_scroll_coverage';else if(!c.depth)verdict='FAILED_COMPONENT:depth_coverage';else if(!c.jump)verdict='FAILED_COMPONENT:jump_coverage';else if(!c.drawingBuffer)verdict='FAILED_COMPONENT:drawing_buffer';else if(!c.resize)verdict='FAILED_COMPONENT:resize_fullscreen';else if(!c.p2p3)verdict='FAILED_COMPONENT:p2p3_reuse';else verdict='IMPLEMENTATION_READY';}else verdict=!last?'FAILED_COMPONENT:worker_bridge':!cal?'FAILED_COMPONENT:calibration':'FAILED_COMPONENT:visual_confirmation';const m=metrics();return{version:VERSION,verdict,operatorDecision:code||null,generatedAt:new Date().toISOString(),projection:verdict==='IMPLEMENTATION_READY'?projection(code):null,camera:{selected:locked()||candidate(),quality:last?.cameraQuality||null,top:(last?.cameraTop||[]).slice(0,5)},calibration:cal?{at:cal.at,nativeClick:{x:round(cal.nativeClick.x,2),y:round(cal.nativeClick.y,2)},playerAtClick:{x:round(cal.player.x,2),y:round(cal.player.y,2),z:round(cal.player.z,2)},xBias:round(cal.xBias),yBias:{minus:round(cal.minus),plus:round(cal.plus),none:round(cal.none)}}:null,evidence:{checklist:c,workerSamples:last?.samples||0,postCalibrationSamples:ev.n,ranges:{worldX:round(span(ev.x0,ev.x1),2),camera:round(span(ev.c0,ev.c1),2),floorY:round(span(ev.y0,ev.y1),2),z:round(span(ev.z0,ev.z1),2)},webgl:{hookCount:m.hookCount,markerDrawCount:m.drawCount,lastDrawAt:round(m.lastDrawAt,1),viewport:vpInfo()},layout:{baseline:layoutBase,current:layoutSnapshot(),changeCount:layoutChanges,recovered:layoutRecovered,events:layoutEvents},focusMs:{P1:Math.round(focusMs.P1),P2:Math.round(focusMs.P2),P3:Math.round(focusMs.P3)}},boundaries:{alphaModified:false,pixelTrackingUsed:false,combatRequired:false}};}
const root=document.createElement('div');root.style.cssText='position:fixed;left:10px;top:10px;z-index:2147483647;width:470px;max-width:calc(100vw - 20px);padding:10px 12px;background:rgba(0,0,0,.86);border:1px solid #fff;border-radius:9px;color:#fff;font:12px/1.4 system-ui;pointer-events:auto';root.innerHTML='<b style="font-size:14px">HUD Anchor Proof</b><div id="s" style="margin-top:5px">等待 Worker 数据…</div><div id="p" style="margin-top:6px;white-space:pre-wrap"></div><div id="a" style="display:none;margin-top:8px;gap:5px;flex-wrap:wrap"></div><textarea id="j" style="display:none;width:100%;height:120px;margin-top:8px;font:10px monospace"></textarea>';document.documentElement.appendChild(root);const s=root.querySelector('#s'),p=root.querySelector('#p'),a=root.querySelector('#a'),j=root.querySelector('#j'),pass=[];
function button(t,code){const b=document.createElement('button');b.textContent=t;b.style.cssText='font:12px system-ui;padding:5px 7px';b.onclick=e=>{e.preventDefault();finish(code);};a.appendChild(b);return b;}pass.push(button('PASS Y-Z','PASS_MINUS'),button('PASS Y+Z','PASS_PLUS'),button('PASS Y','PASS_NONE'));button('X/camera drift','FAIL_X');button('depth drift','FAIL_DEPTH');button('jump/Z fails','FAIL_JUMP');button('marker/DB fails','FAIL_DB');button('resize drift','FAIL_RESIZE');button('P2/P3 drift','FAIL_PLAYERS');button('clearance unstable','FAIL_CLEARANCE');
async function finish(code){decision=code;resultCache=build(code);const text=JSON.stringify(resultCache);j.style.display='block';j.value=text;a.style.display='none';s.textContent=resultCache.verdict+' — JSON 已生成';p.textContent='';try{await navigator.clipboard.writeText(text);s.textContent=resultCache.verdict+' — JSON 已复制到剪贴板';}catch(_){}console.log(text);}
bc.onmessage=e=>{const m=e.data;if(m?.schema===CHANNEL&&m.kind==='state'){last=m;lastRx=Date.now();}};bc.postMessage({schema:CHANNEL,kind:'request-state'});
function click(e){if(!running||!armed||root.contains(e.target)||!inside(e.clientX,e.clientY))return;try{calibrate(e.clientX,e.clientY);e.preventDefault();e.stopPropagation();}catch(err){s.textContent='校准未就绪：'+err.message;}}
function setFocus(n){if(['P1','P2','P3'].includes(n))focus=n;return focus;}function key(e){if(e.code==='F6'){e.preventDefault();setFocus(focus==='P1'?'P2':focus==='P2'?'P3':'P1');}else if(e.code==='F7'){e.preventDefault();cal=null;armed=true;decision=resultCache=null;j.style.display='none';bc.postMessage({schema:CHANNEL,kind:'unlock-camera'});layoutBase=layoutLast=null;layoutChanges=0;layoutRecovered=false;resetRanges();}}
addEventListener('click',click,true);addEventListener('keydown',key,true);
function loop(){if(!running)return;updateEvidence();const c=checklist(),mark=x=>x?'✓':'·';if(!resultCache){if(!last||Date.now()-lastRx>700){s.textContent='等待 Worker 数据：在 Worker Console 运行同一条 loader。';p.textContent='';a.style.display='none';}else if(!cal){const q=last.cameraQuality||{};s.textContent=q.ok?'Camera 已稳定：点击一次 P1 头顶上方希望警告中心出现的位置。':'让 P1 左右移动到背景明显滚动；Camera: '+(q.reason||'SCANNING')+'，samples '+(last.samples||0);p.textContent='camera '+(candidate()?.address||'?')+' | score '+(candidate()?.score??'?');a.style.display='none';}else{p.textContent=`${mark(c.camera)} camera  ${mark(c.horizontal)} scroll/X  ${mark(c.depth)} depth  ${mark(c.jump)} jump/Z\n${mark(c.drawingBuffer)} WebGL DB  ${mark(c.resize)} resize/fullscreen  ${mark(c.p2p3)} P2/P3(if live)`;s.textContent=!c.horizontal?'继续左右移动并让背景明显滚动。':!c.depth?'现在明显向上/向下走纵深。':!c.jump?'现在跳一次，观察 Y-Z / Y+Z / Y 哪个标记跟住头顶。':!c.resize?'现在 resize 窗口或切一次 fullscreen，再恢复。':!c.p2p3?'P2/P3 已检测到：按 F6 轮看每个 live 玩家约 1 秒。':'证据覆盖完成：点击一个最终结论。';a.style.display='flex';pass.forEach(b=>b.disabled=!c.all);}}raf=requestAnimationFrame(loop);}raf=requestAnimationFrame(loop);
window.WOFHUDANCHOR={version:VERSION,mode:'top',result(){const r=resultCache||build(decision);console.log(JSON.stringify(r));return r;},status(){return{running,focus,armed,calibrated:!!cal,lastAgeMs:lastRx?Date.now()-lastRx:null,checklist:checklist(),camera:last?.cameraQuality||null};},focus:setFocus,cycle(){return setFocus(focus==='P1'?'P2':focus==='P2'?'P3':'P1');},stop(){if(!running)return;running=false;if(raf)cancelAnimationFrame(raf);removeEventListener('click',click,true);removeEventListener('keydown',key,true);try{bc.close();}catch(_){}try{renderer.stop();}catch(_){}try{root.remove();}catch(_){};try{delete window.WOFHUDANCHOR;}catch(_){}}};
console.log('✅ HUDANCHOR proof Top ready');
})().catch(e=>console.error('❌ HUDANCHOR proof Top failed',e));
