(()=>function createHudAnchorGl({gl,canvas,getPoints}){
const is2=typeof WebGL2RenderingContext!=='undefined'&&gl instanceof WebGL2RenderingContext,proto=is2?WebGL2RenderingContext.prototype:WebGLRenderingContext.prototype,nativeDraw=proto.drawArrays;
const V=`${is2?'#version 300 es\n':''}${is2?'in':'attribute'} vec4 a;${is2?'out':'varying'} vec2 v;void main(){gl_Position=vec4(a.xy,0.,1.);v=a.zw;}`,F=`${is2?'#version 300 es\n':''}precision mediump float;${is2?'in':'varying'} vec2 v;uniform sampler2D t;${is2?'out vec4 o;':''}void main(){${is2?'o=texture(t,v);':'gl_FragColor=texture2D(t,v);'}}`;
const sh=(ty,s)=>{const x=gl.createShader(ty);gl.shaderSource(x,s);gl.compileShader(x);if(!gl.getShaderParameter(x,gl.COMPILE_STATUS))throw new Error(gl.getShaderInfoLog(x)||'shader');return x;},vs=sh(gl.VERTEX_SHADER,V),fs=sh(gl.FRAGMENT_SHADER,F),prog=gl.createProgram();gl.attachShader(prog,vs);gl.attachShader(prog,fs);gl.bindAttribLocation(prog,0,'a');gl.linkProgram(prog);gl.deleteShader(vs);gl.deleteShader(fs);if(!gl.getProgramParameter(prog,gl.LINK_STATUS))throw new Error(gl.getProgramInfoLog(prog)||'link');
const u=gl.getUniformLocation(prog,'t'),buf=gl.createBuffer(),textures={};let vp=null,hookCount=0,drawCount=0,lastDrawAt=0,running=true,inHook=false;
function snap(){const active=gl.getParameter(gl.ACTIVE_TEXTURE),activeTex=gl.getParameter(gl.TEXTURE_BINDING_2D);gl.activeTexture(gl.TEXTURE0);const tex0=gl.getParameter(gl.TEXTURE_BINDING_2D);gl.activeTexture(active);return{program:gl.getParameter(gl.CURRENT_PROGRAM),array:gl.getParameter(gl.ARRAY_BUFFER_BINDING),active,activeTex,tex0,viewport:Array.from(gl.getParameter(gl.VIEWPORT)),blend:gl.isEnabled(gl.BLEND),depth:gl.isEnabled(gl.DEPTH_TEST),cull:gl.isEnabled(gl.CULL_FACE),scissor:gl.isEnabled(gl.SCISSOR_TEST),srcRGB:gl.getParameter(gl.BLEND_SRC_RGB),dstRGB:gl.getParameter(gl.BLEND_DST_RGB),srcA:gl.getParameter(gl.BLEND_SRC_ALPHA),dstA:gl.getParameter(gl.BLEND_DST_ALPHA),eqRGB:gl.getParameter(gl.BLEND_EQUATION_RGB),eqA:gl.getParameter(gl.BLEND_EQUATION_ALPHA),mask:Array.from(gl.getParameter(gl.COLOR_WRITEMASK)),flip:gl.getParameter(gl.UNPACK_FLIP_Y_WEBGL),premul:gl.getParameter(gl.UNPACK_PREMULTIPLY_ALPHA_WEBGL),a0:{on:!!gl.getVertexAttrib(0,gl.VERTEX_ATTRIB_ARRAY_ENABLED),buf:gl.getVertexAttrib(0,gl.VERTEX_ATTRIB_ARRAY_BUFFER_BINDING),size:gl.getVertexAttrib(0,gl.VERTEX_ATTRIB_ARRAY_SIZE),type:gl.getVertexAttrib(0,gl.VERTEX_ATTRIB_ARRAY_TYPE),norm:!!gl.getVertexAttrib(0,gl.VERTEX_ATTRIB_ARRAY_NORMALIZED),stride:gl.getVertexAttrib(0,gl.VERTEX_ATTRIB_ARRAY_STRIDE),off:gl.getVertexAttribOffset(0,gl.VERTEX_ATTRIB_ARRAY_POINTER)}};}
function restore(s){s.blend?gl.enable(gl.BLEND):gl.disable(gl.BLEND);s.depth?gl.enable(gl.DEPTH_TEST):gl.disable(gl.DEPTH_TEST);s.cull?gl.enable(gl.CULL_FACE):gl.disable(gl.CULL_FACE);s.scissor?gl.enable(gl.SCISSOR_TEST):gl.disable(gl.SCISSOR_TEST);gl.blendFuncSeparate(s.srcRGB,s.dstRGB,s.srcA,s.dstA);gl.blendEquationSeparate(s.eqRGB,s.eqA);gl.colorMask(...s.mask);gl.viewport(...s.viewport);if(s.a0.buf){gl.bindBuffer(gl.ARRAY_BUFFER,s.a0.buf);gl.vertexAttribPointer(0,s.a0.size,s.a0.type,s.a0.norm,s.a0.stride,s.a0.off);}s.a0.on?gl.enableVertexAttribArray(0):gl.disableVertexAttribArray(0);gl.useProgram(s.program);gl.activeTexture(gl.TEXTURE0);gl.bindTexture(gl.TEXTURE_2D,s.tex0);gl.activeTexture(s.active);if(s.active!==gl.TEXTURE0)gl.bindTexture(gl.TEXTURE_2D,s.activeTex);gl.pixelStorei(gl.UNPACK_FLIP_Y_WEBGL,s.flip);gl.pixelStorei(gl.UNPACK_PREMULTIPLY_ALPHA_WEBGL,s.premul);gl.bindBuffer(gl.ARRAY_BUFFER,s.array);}
function texture(label){const c=document.createElement('canvas');c.width=96;c.height=34;const x=c.getContext('2d');x.fillStyle='rgba(0,0,0,.78)';x.fillRect(1,1,94,26);x.strokeStyle='#fff';x.lineWidth=2;x.strokeRect(1,1,94,26);x.fillStyle='#fff';x.font='bold 15px sans-serif';x.textAlign='center';x.textBaseline='middle';x.fillText(label,48,14);x.fillRect(46,27,4,7);const t=gl.createTexture(),s=snap();try{gl.activeTexture(gl.TEXTURE0);gl.bindTexture(gl.TEXTURE_2D,t);gl.pixelStorei(gl.UNPACK_FLIP_Y_WEBGL,true);gl.pixelStorei(gl.UNPACK_PREMULTIPLY_ALPHA_WEBGL,false);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,gl.RGBA,gl.UNSIGNED_BYTE,c);}finally{restore(s);}return t;}
textures.minus=texture('Y-Z');textures.plus=texture('Y+Z');textures.none=texture('Y');
function draw(t,cx,cy){const W=gl.drawingBufferWidth||canvas.width,H=gl.drawingBufferHeight||canvas.height,w=70,h=25;if(!(W>0&&H>0))return;const x=cx-w/2,y=cy-h,l=x/W*2-1,r=(x+w)/W*2-1,top=1-y/H*2,b=1-(y+h)/H*2,v=new Float32Array([l,top,0,1,l,b,0,0,r,b,1,0,l,top,0,1,r,b,1,0,r,top,1,1]),s=snap();try{gl.viewport(0,0,W,H);gl.disable(gl.DEPTH_TEST);gl.disable(gl.CULL_FACE);gl.disable(gl.SCISSOR_TEST);gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA);gl.colorMask(true,true,true,true);gl.useProgram(prog);gl.bindBuffer(gl.ARRAY_BUFFER,buf);gl.bufferData(gl.ARRAY_BUFFER,v,gl.STREAM_DRAW);gl.enableVertexAttribArray(0);gl.vertexAttribPointer(0,4,gl.FLOAT,false,0,0);gl.activeTexture(gl.TEXTURE0);gl.bindTexture(gl.TEXTURE_2D,t);gl.uniform1i(u,0);nativeDraw.call(gl,gl.TRIANGLES,0,6);drawCount++;lastDrawAt=performance.now();}finally{restore(s);}}
function paint(){for(const p of getPoints()||[])if(Number.isFinite(p?.x)&&Number.isFinite(p?.y)&&textures[p.kind])draw(textures[p.kind],p.x,p.y);}
const prev=gl.drawArrays;function wrap(){const r=prev.apply(this,arguments);if(this===gl&&running&&!inHook){inHook=true;try{hookCount++;const a=Array.from(gl.getParameter(gl.VIEWPORT)).map(Number);if(a.length===4&&a[2]>0&&a[3]>0)vp=a;paint();}catch(_){}finally{inHook=false;}}return r;}try{Object.defineProperty(gl,'drawArrays',{value:wrap,writable:true,configurable:true});}catch(_){gl.drawArrays=wrap;}
return{metrics(){const W=gl.drawingBufferWidth||canvas.width,H=gl.drawingBufferHeight||canvas.height,a=vp||[0,0,W,H];return{dbWidth:W,dbHeight:H,viewport:a,viewportSource:vp?'gl.VIEWPORT':'full-buffer-fallback',hookCount,drawCount,lastDrawAt};},stop(){running=false;if(gl.drawArrays===wrap){try{Object.defineProperty(gl,'drawArrays',{value:prev,writable:true,configurable:true});}catch(_){gl.drawArrays=prev;}}try{Object.values(textures).forEach(t=>gl.deleteTexture(t));gl.deleteBuffer(buf);gl.deleteProgram(prog);}catch(_){}}};
})()
