(async()=>{
'use strict';
const VERSION='wof-owner-projection-proof-v2',CHANNEL='wof-owner-projection-proof-v1',RESULT_SCHEMA='wof-owner-projection-proof-result-v2';
const NW=384,NH=224,MIN_TRACKED=36,MIN_HOLDOUT=8,MAX_TRACKED=240,MAX_CAL_MS=180000;
const TRACK_PATCH=11,TRACK_RADIUS=18,TRACK_MIN_SCORE=.70,TRACK_MIN_MARGIN=.035;
const FIT_RMS_MAX=3.25,FIT_HOLDOUT_RMS_MAX=4.0,FIT_HOLDOUT_MAX=8.0;
const ENEMY_MIN=8,ENEMY_MAD_MAX=3.5,ENEMY_ABS_MAX=28;
const SAFETY={readOnly:true,ramWrites:0,inputInjection:false,guessedConstants:false,syntheticAuthority:false};
try{window.WOFOWNERPROJECTION?.stop?.();}catch(_){}
const canvas=window.I_GF1TC||document.getElementById('whathis'),gl=window.I_fdC8Q;
if(!canvas||!gl||typeof gl.readPixels!=='function')throw new Error('game WebGL canvas/context unavailable');
const glSource=String(window.__WOF_OWNER_PROJECTION_GL_SOURCE||'');
if(!glSource)throw new Error('package-selected GL proof helper missing');
const glFactory=(0,eval)(glSource),bc=new BroadcastChannel(CHANNEL);
const round=(v,n=3)=>v==null?null:Number.isFinite(+v)?+(+v).toFixed(n):null;
const finite=v=>typeof v==='number'&&Number.isFinite(v);
const span=(a,b)=>finite(a)&&finite(b)?b-a:0;
const clamp=(v,a,b)=>Math.min(b,Math.max(a,v));
const median=a=>{if(!a.length)return null;const b=[...a].sort((x,y)=>x-y),m=b.length>>1;return b.length%2?b[m]:(b[m-1]+b[m])/2;};
const mad=a=>{const m=median(a);return m==null?null:median(a.map(x=>Math.abs(x-m)));};
let running=true,last=null,lastRx=0,workerSessionId=null,lastSequence=0,pendingCal=null,cal=null,resultCache=null,raf=0,renderer=null,uiError=null;
let p1Present=false,p1LifecycleGeneration=0,seededAt=0,tracker=null,fitState=null,fitReadyAt=0,layoutBase=null,layoutSigLast=null,layoutChangedAt=0;
const samples=[],trackerTimeline=[],localAuthorityEvents=[],enemySlots=new Map(),enemyEvidence=new Map(),suppression=[];
function localEvent(kind,payload={}){const e={eventId:'projection:'+Date.now()+':'+localAuthorityEvents.length,kind,at:Date.now(),workerSessionId,lastSequence,...payload};localAuthorityEvents.push(e);if(localAuthorityEvents.length>96)localAuthorityEvents.shift();}
function noteSuppression(reason,payload={}){const lastRow=suppression.at(-1);if(lastRow&&lastRow.reason===reason&&Date.now()-lastRow.lastAt<500){lastRow.lastAt=Date.now();lastRow.count++;return;}suppression.push({reason,at:Date.now(),lastAt:Date.now(),count:1,...payload});if(suppression.length>48)suppression.shift();}
function metrics(){return renderer?.metrics?.()||{dbWidth:gl.drawingBufferWidth||canvas.width,dbHeight:gl.drawingBufferHeight||canvas.height,viewport:[0,0,gl.drawingBufferWidth||canvas.width,gl.drawingBufferHeight||canvas.height],viewportSource:'full-buffer-fallback',hookCount:0,drawCount:0,lastDrawAt:0};}
function vpInfo(){const m=metrics(),a=Array.isArray(m.viewport)?m.viewport.map(Number):[0,0,m.dbWidth,m.dbHeight],[x,y,w,h]=a,top=m.dbHeight-(y+h),ok=[m.dbWidth,m.dbHeight,x,y,w,h,top].every(Number.isFinite)&&m.dbWidth>0&&m.dbHeight>0&&w>0&&h>0&&x>=0&&y>=0&&x+w<=m.dbWidth+1&&y+h<=m.dbHeight+1;return{ok,dbWidth:m.dbWidth,dbHeight:m.dbHeight,x,y,width:w,height:h,top,source:m.viewportSource};}
function clientDb(cx,cy){const r=canvas.getBoundingClientRect(),v=vpInfo();return r.width>0&&r.height>0?{x:(cx-r.left)/r.width*v.dbWidth,y:(cy-r.top)/r.height*v.dbHeight}:null;}
function clientNative(cx,cy){const d=clientDb(cx,cy),v=vpInfo();return d&&v.ok?{x:(d.x-v.x)/v.width*NW,y:(d.y-v.top)/v.height*NH}:null;}
function inside(cx,cy){const d=clientDb(cx,cy),v=vpInfo();return !!d&&v.ok&&d.x>=v.x&&d.x<=v.x+v.width&&d.y>=v.top&&d.y<=v.top+v.height;}
const locked=()=>last?.lockedCamera||null,readyAuthority=()=>last?.cameraAuthority||null,readyCamera=()=>last?.readyCamera||null;
const currentGuidance=()=>last?.guidance||{actionZh:'正在准备校准，请保持当前真人验证窗口打开。',nextCommandZh:'继续当前窗口。'};
function exactReadySnapshot(){
  if(!last||Date.now()-lastRx>=700)throw new Error('STALE_READY_SNAPSHOT');
  const q=last.cameraQuality||{},auth=readyAuthority(),cam=readyCamera(),p=last.players?.P1;
  if(!q.ready||!q.ok)throw new Error(q.reason||'CAMERA_NOT_READY');
  if(!q.clickReady||!p)throw new Error(q.reason||'NO_LIVE_P1');
  if(!auth||auth.state!=='READY'||!auth.authorityId||!Number.isInteger(auth.authorityGeneration)||auth.authorityGeneration<1)throw new Error('READY_AUTHORITY_MISSING');
  if(!cam||cam.authorityId!==auth.authorityId||cam.authorityGeneration!==auth.authorityGeneration||cam.address!==auth.address)throw new Error('READY_CAMERA_AUTHORITY_MISMATCH');
  if(last.workerSessionId!==workerSessionId||!Number.isInteger(last.sequence)||last.sequence!==lastSequence)throw new Error('READY_SNAPSHOT_SEQUENCE_MISMATCH');
  return{q,auth,cam,p,sequence:last.sequence,snapshotId:last.snapshotId,workerSessionId:last.workerSessionId};
}
function nativeRectToDb(x0,y0,w,h){const v=vpInfo();if(!v.ok)return null;const x=Math.floor(v.x+x0/NW*v.width),right=Math.ceil(v.x+(x0+w)/NW*v.width),top=Math.floor(v.top+y0/NH*v.height),bottom=Math.ceil(v.top+(y0+h)/NH*v.height);return{x,yTop:top,w:Math.max(1,right-x),h:Math.max(1,bottom-top),glY:Math.max(0,v.dbHeight-bottom),v};}
function captureNativeRegion(x0,y0,w,h){
  x0=Math.floor(x0);y0=Math.floor(y0);w=Math.floor(w);h=Math.floor(h);if(w<=0||h<=0)return null;
  const r=nativeRectToDb(x0,y0,w,h);if(!r)return null;
  const px=new Uint8Array(r.w*r.h*4);
  try{gl.readPixels(r.x,r.glY,r.w,r.h,gl.RGBA,gl.UNSIGNED_BYTE,px);}catch(e){uiError='FRAMEBUFFER_READ_FAILED:'+String(e?.message||e);return null;}
  const out=new Float32Array(w*h);
  for(let ny=0;ny<h;ny++)for(let nx=0;nx<w;nx++){
    const dbx=clamp(Math.floor((nx+.5)/w*r.w),0,r.w-1),dbyTop=clamp(Math.floor((ny+.5)/h*r.h),0,r.h-1),dby=r.h-1-dbyTop,i=(dby*r.w+dbx)*4;
    out[ny*w+nx]=(px[i]*.299+px[i+1]*.587+px[i+2]*.114)/255;
  }
  return{data:out,width:w,height:h,x0,y0};
}
function extractPatch(region,cx,cy,size){const half=size>>1,x=Math.round(cx)-half-region.x0,y=Math.round(cy)-half-region.y0;if(x<0||y<0||x+size>region.width||y+size>region.height)return null;const out=new Float32Array(size*size);for(let j=0;j<size;j++)for(let i=0;i<size;i++)out[j*size+i]=region.data[(y+j)*region.width+x+i];return out;}
function ncc(a,b){if(!a||!b||a.length!==b.length)return-1;let ma=0,mb=0;for(let i=0;i<a.length;i++){ma+=a[i];mb+=b[i];}ma/=a.length;mb/=b.length;let num=0,da=0,db=0;for(let i=0;i<a.length;i++){const x=a[i]-ma,y=b[i]-mb;num+=x*y;da+=x*x;db+=y*y;}return da>1e-6&&db>1e-6?num/Math.sqrt(da*db):-1;}
function seedTracker(n){const half=TRACK_PATCH>>1,r=captureNativeRegion(n.x-half,n.y-half,TRACK_PATCH,TRACK_PATCH);if(!r)return null;const patch=r.data;if(Math.max(...patch)-Math.min(...patch)<.05)return null;return{template:patch,x:n.x,y:n.y,score:1,margin:1,lost:0,lastAt:Date.now()};}
function trackHead(){if(!tracker)return null;const half=TRACK_PATCH>>1,x0=clamp(Math.floor(tracker.x-TRACK_RADIUS-half),0,NW-(TRACK_PATCH+2*TRACK_RADIUS)),y0=clamp(Math.floor(tracker.y-TRACK_RADIUS-half),0,NH-(TRACK_PATCH+2*TRACK_RADIUS)),sz=TRACK_PATCH+2*TRACK_RADIUS,reg=captureNativeRegion(x0,y0,sz,sz);if(!reg)return null;let best={score:-2,x:tracker.x,y:tracker.y},second=-2;for(let y=y0+half;y<=y0+sz-half-1;y+=2)for(let x=x0+half;x<=x0+sz-half-1;x+=2){const p=extractPatch(reg,x,y,TRACK_PATCH),s=ncc(tracker.template,p);if(s>best.score){second=best.score;best={score:s,x,y,patch:p};}else if(s>second)second=s;}best.margin=best.score-second;if(best.score<TRACK_MIN_SCORE||best.margin<TRACK_MIN_MARGIN){tracker.lost++;trackerTimeline.push({at:Date.now(),sequence:lastSequence,ok:false,score:round(best.score),margin:round(best.margin)});if(trackerTimeline.length>96)trackerTimeline.shift();noteSuppression('VISUAL_TRACKER_UNCERTAIN',{score:round(best.score),margin:round(best.margin)});return null;}tracker.x=best.x;tracker.y=best.y;tracker.score=best.score;tracker.margin=best.margin;tracker.lost=0;tracker.lastAt=Date.now();if(best.score>.86&&best.patch){for(let i=0;i<tracker.template.length;i++)tracker.template[i]=tracker.template[i]*.96+best.patch[i]*.04;}trackerTimeline.push({at:Date.now(),sequence:lastSequence,ok:true,x:round(best.x,2),y:round(best.y,2),score:round(best.score),margin:round(best.margin)});if(trackerTimeline.length>96)trackerTimeline.shift();return best;}
function requestCalibration(cx,cy){
  const r=exactReadySnapshot(),n=clientNative(cx,cy);if(!n||!inside(cx,cy))throw new Error('CLICK_OUTSIDE_GAME_VIEWPORT');
  const t=seedTracker(n);if(!t)throw new Error('VISUAL_SEED_NOT_DISTINCT');
  pendingCal={requestedAt:Date.now(),requestSequence:r.sequence,requestSnapshotId:r.snapshotId,workerSessionId:r.workerSessionId,cameraAuthority:{...r.auth},cameraAddress:r.auth.address,cameraRead:r.cam.read||'u16be',cameraValueAtClick:r.cam.value,cameraQuality:{...r.q},nativeClick:n,player:{...r.p},p1LifecycleGeneration};
  tracker=t;seededAt=Date.now();uiError=null;localEvent('VISUAL_SEED_CAPTURED',{authorityId:r.auth.authorityId,authorityGeneration:r.auth.authorityGeneration,p1LifecycleGeneration,nativeClick:{x:round(n.x,2),y:round(n.y,2)}});
  bc.postMessage({schema:CHANNEL,kind:'lock-camera',address:r.auth.address,authorityId:r.auth.authorityId,authorityGeneration:r.auth.authorityGeneration,readySnapshotSequence:r.sequence,readySnapshotId:r.snapshotId});
  return pendingCal;
}
function maybeFinalizeCalibration(){
  if(!pendingCal||cal)return;const auth=pendingCal.cameraAuthority,l=locked();
  if(last?.lockRejectReason){uiError='Camera authority lock rejected: '+String(last.lockRejectReason.reason||'UNKNOWN');localEvent('CALIBRATION_LOCK_REJECTED',{reason:last.lockRejectReason.reason||'UNKNOWN'});pendingCal=null;tracker=null;return;}
  if(!l)return;
  if(l.authorityId!==auth.authorityId||l.authorityGeneration!==auth.authorityGeneration||l.address!==auth.address){uiError='Camera lock authority mismatch';localEvent('CALIBRATION_LOCK_REJECTED',{reason:'ACK_AUTHORITY_MISMATCH'});pendingCal=null;tracker=null;return;}
  cal={...pendingCal,at:Date.now(),lockAck:{authorityId:l.authorityId,authorityGeneration:l.authorityGeneration,address:l.address,lockedAt:l.lockedAt,lockRequestSequence:l.lockRequestSequence}};pendingCal=null;samples.length=0;enemyEvidence.clear();enemySlots.clear();fitState=null;fitReadyAt=0;layoutBase=layoutSnapshot();layoutSigLast=layoutSignature(layoutBase);localEvent('CALIBRATION_LOCK_ACKED',{authorityId:auth.authorityId,authorityGeneration:auth.authorityGeneration,address:auth.address,p1LifecycleGeneration});
}
function solve3(rows,target){if(rows.length<3)return null;const A=[[0,0,0],[0,0,0],[0,0,0]],b=[0,0,0];for(let i=0;i<rows.length;i++){const r=rows[i],t=target[i];for(let a=0;a<3;a++){b[a]+=r[a]*t;for(let c=0;c<3;c++)A[a][c]+=r[a]*r[c];}}const M=A.map((r,i)=>[...r,b[i]]);for(let c=0;c<3;c++){let p=c;for(let r=c+1;r<3;r++)if(Math.abs(M[r][c])>Math.abs(M[p][c]))p=r;if(Math.abs(M[p][c])<1e-8)return null;[M[c],M[p]]=[M[p],M[c]];const d=M[c][c];for(let j=c;j<4;j++)M[c][j]/=d;for(let r=0;r<3;r++)if(r!==c){const f=M[r][c];for(let j=c;j<4;j++)M[r][j]-=f*M[c][j];}}return[M[0][3],M[1][3],M[2][3]];}
function residualStats(rows,target,c){if(!c)return null;const e=rows.map((r,i)=>target[i]-(r[0]*c[0]+r[1]*c[1]+c[2])),rms=Math.sqrt(e.reduce((s,x)=>s+x*x,0)/Math.max(1,e.length)),max=Math.max(0,...e.map(Math.abs));return{rms,max,errors:e};}
function coverage(a,key){const x=a.map(s=>s[key]).filter(finite);return x.length?{min:Math.min(...x),max:Math.max(...x),range:Math.max(...x)-Math.min(...x)}:{min:null,max:null,range:0};}
function fitProjection(all){
  if(all.length<MIN_TRACKED)return{ok:false,reason:'NEED_MORE_TRACKED_SAMPLES'};
  const train=all.filter((_,i)=>i%5!==4),hold=all.filter((_,i)=>i%5===4);if(hold.length<MIN_HOLDOUT)return{ok:false,reason:'NEED_MORE_HOLDOUT'};
  const cov={worldX:coverage(all,'worldX'),cameraRaw:coverage(all,'cameraRaw'),worldY:coverage(all,'worldY'),worldZ:coverage(all,'worldZ')};
  if(cov.worldX.range<16||cov.cameraRaw.range<4)return{ok:false,reason:'NEED_HORIZONTAL_COVERAGE',coverage:cov};
  if(cov.worldY.range<6)return{ok:false,reason:'NEED_DEPTH_COVERAGE',coverage:cov};
  if(cov.worldZ.range<6)return{ok:false,reason:'NEED_JUMP_COVERAGE',coverage:cov};
  const xr=train.map(s=>[s.worldX,s.cameraRaw,1]),xt=train.map(s=>s.headX),yr=train.map(s=>[s.worldY,s.worldZ,1]),yt=train.map(s=>s.headY),xc=solve3(xr,xt),yc=solve3(yr,yt);if(!xc||!yc)return{ok:false,reason:'AFFINE_NOT_IDENTIFIABLE',coverage:cov};
  const xTrain=residualStats(xr,xt,xc),yTrain=residualStats(yr,yt,yc),xHold=residualStats(hold.map(s=>[s.worldX,s.cameraRaw,1]),hold.map(s=>s.headX),xc),yHold=residualStats(hold.map(s=>[s.worldY,s.worldZ,1]),hold.map(s=>s.headY),yc);
  const trainRms=Math.hypot(xTrain.rms,yTrain.rms),holdoutRms=Math.hypot(xHold.rms,yHold.rms),holdoutMax=Math.max(xHold.max,yHold.max);
  if(Math.abs(xc[0])<.05||Math.abs(xc[1])<.01||Math.abs(yc[0])<.05)return{ok:false,reason:'AFFINE_DEGENERATE',coverage:cov,coefficients:{x:xc,y:yc}};
  if(trainRms>FIT_RMS_MAX||holdoutRms>FIT_HOLDOUT_RMS_MAX||holdoutMax>FIT_HOLDOUT_MAX)return{ok:false,reason:'RESIDUAL_GATE_FAILED',coverage:cov,coefficients:{x:xc,y:yc},residuals:{trainRms,holdoutRms,holdoutMax}};
  const deltas=[];for(let i=1;i<all.length;i++){const a=all[i-1],b=all[i];deltas.push({worldX:Math.abs(b.worldX-a.worldX),worldY:Math.abs(b.worldY-a.worldY),worldZ:Math.abs(b.worldZ-a.worldZ),cameraRaw:Math.abs(b.cameraRaw-a.cameraRaw)});}const p95=k=>{const a=deltas.map(x=>x[k]).sort((a,b)=>a-b);return a.length?a[Math.min(a.length-1,Math.floor(a.length*.95))]:0;};
  return{ok:true,reason:null,coefficients:{xWorld:xc[0],xCameraRaw:xc[1],xBias:xc[2],floorY:yc[0],z:yc[1],yBias:yc[2]},coverage:cov,residuals:{trainRms,holdoutRms,holdoutMax,xTrainRms:xTrain.rms,yTrainRms:yTrain.rms,xHoldoutRms:xHold.rms,yHoldoutRms:yHold.rms},motionEnvelope:{worldXStep:p95('worldX'),worldYStep:p95('worldY'),worldZStep:p95('worldZ'),cameraRawStep:p95('cameraRaw')},sampleCount:all.length,holdoutCount:hold.length};
}
function layoutSnapshot(){const r=canvas.getBoundingClientRect(),v=vpInfo();return{at:Date.now(),css:{width:round(r.width,2),height:round(r.height,2)},drawingBuffer:{width:v.dbWidth,height:v.dbHeight},viewport:{x:v.x,y:v.y,width:v.width,height:v.height,top:v.top,source:v.source},dpr:round(devicePixelRatio||1),fullscreen:!!document.fullscreenElement};}
const layoutSignature=x=>JSON.stringify([x?.css?.width,x?.css?.height,x?.drawingBuffer?.width,x?.drawingBuffer?.height,x?.viewport?.x,x?.viewport?.y,x?.viewport?.width,x?.viewport?.height,x?.dpr,x?.fullscreen]);
function updateLifecycle(){const p=last?.players?.P1,present=!!p;if(present&&!p1Present){p1LifecycleGeneration++;if(cal&&p1LifecycleGeneration!==cal.p1LifecycleGeneration){noteSuppression('P1_LIFECYCLE_REPLACED');failClosed('FAILED_COMPONENT:p1_lifecycle_replaced');}}p1Present=present;const seen=new Set();for(const e of last?.enemies||[]){if(!Number.isInteger(e.slot))continue;seen.add(e.slot);const old=enemySlots.get(e.slot);if(!old||old.type!==e.type||old.present!==true)enemySlots.set(e.slot,{type:e.type,generation:(old?.generation||0)+1,present:true});else old.present=true;}for(const [slot,row] of enemySlots)if(!seen.has(slot))row.present=false;}
function collectPair(){if(!cal||!last||!tracker)return;const l=locked(),p=last.players?.P1;if(!l||!p||Date.now()-lastRx>=700)return;if(l.authorityId!==cal.cameraAuthority.authorityId||l.authorityGeneration!==cal.cameraAuthority.authorityGeneration||l.address!==cal.cameraAddress){failClosed('FAILED_COMPONENT:camera_authority_changed');return;}if(p1LifecycleGeneration!==cal.p1LifecycleGeneration){failClosed('FAILED_COMPONENT:p1_lifecycle_replaced');return;}const pos=trackHead();if(!pos)return;const row={sequence:lastSequence,snapshotId:last.snapshotId,workerSessionId,at:Date.now(),worldX:+p.x,worldY:+p.y,worldZ:+p.z,cameraRaw:+l.value,headX:+pos.x,headY:+pos.y,trackerScore:+pos.score,trackerMargin:+pos.margin,p1LifecycleGeneration};if(![row.worldX,row.worldY,row.worldZ,row.cameraRaw,row.headX,row.headY].every(Number.isFinite))return;const prev=samples.at(-1);if(prev&&prev.sequence===row.sequence)return;samples.push(row);if(samples.length>MAX_TRACKED)samples.shift();fitState=fitProjection(samples);if(fitState.ok&&!fitReadyAt){fitReadyAt=Date.now();localEvent('AFFINE_FIT_READY',{sampleCount:fitState.sampleCount,residuals:Object.fromEntries(Object.entries(fitState.residuals).map(([k,v])=>[k,round(v,4)]),),coefficients:Object.fromEntries(Object.entries(fitState.coefficients).map(([k,v])=>[k,round(v,6)]))});}}
function currentFitPoint(o){if(!fitState?.ok||!o)return null;const c=fitState.coefficients,l=locked();if(!l)return null;return{x:c.xWorld*o.x+c.xCameraRaw*l.value+c.xBias,y:c.floorY*o.y+c.z*o.z+c.yBias};}
function enemyMotionCandidate(e){const slotState=enemySlots.get(e.slot);if(!slotState?.present)return null;const key=e.slot+':'+slotState.generation,p=currentFitPoint(e);const existing=enemyEvidence.get(key);if(existing?.lastSequence===lastSequence)return null;if(!p||p.x<8||p.x>NW-8||p.y<18||p.y>NH-18)return null;const x0=Math.floor(p.x-12),y0=Math.floor(p.y-ENEMY_ABS_MAX),w=25,h=ENEMY_ABS_MAX*2+1,reg=captureNativeRegion(x0,y0,w,h);if(!reg)return null;const prev=enemyEvidence.get(key)?.lastRegion;let row=enemyEvidence.get(key);if(!row||row.type!==e.type){row={slot:e.slot,generation:slotState.generation,type:e.type,lastRegion:null,lastSequence:0,offsets:[],samples:0};enemyEvidence.set(key,row);}row.lastRegion=reg;row.lastSequence=lastSequence;if(!prev)return null;const energy=[];for(let y=0;y<h;y++){let s=0;for(let x=0;x<w;x++)s+=Math.abs(reg.data[y*w+x]-prev.data[y*w+x]);energy.push(s/w);}const med=median(energy)||0,peak=Math.max(...energy);if(peak<med+.035)return null;let pick=-1;for(let y=1;y<h-1;y++)if(energy[y]>med+.028&&energy[y+1]>med+.02){pick=y;break;}if(pick<0)return null;const offset=(y0+pick)-p.y;if(Math.abs(offset)>ENEMY_ABS_MAX)return null;row.offsets.push(offset);if(row.offsets.length>32)row.offsets.shift();row.samples++;return{key,row,offset};}
function validateEnemies(){if(!fitState?.ok)return{};for(const e of last?.enemies||[])if(Number.isInteger(e.type)&&e.type>=0&&e.type<47)enemyMotionCandidate(e);const byType={};for(const row of enemyEvidence.values()){if(row.offsets.length<ENEMY_MIN)continue;const m=median(row.offsets),d=mad(row.offsets);if(m==null||d==null||d>ENEMY_MAD_MAX)continue;const t=String(row.type),old=byType[t];if(!old||row.offsets.length>old.sampleCount)byType[t]={offset:m,mad:d,sampleCount:row.offsets.length,slot:row.slot,lifecycleGeneration:row.generation};}return byType;}
function projectBuild(enemy){const c=fitState.coefficients,l=locked(),auth=cal.cameraAuthority,ratio=-c.xCameraRaw/c.xWorld,cameraSign=ratio>=0?1:-1,cameraScale=Math.abs(ratio),offsets={};for(const [t,v] of Object.entries(enemy))offsets[t]=round(v.offset,4);return{camera:{address:cal.cameraAddress,read:cal.cameraRead,sign:cameraSign,scale:round(cameraScale,8),authorityId:auth.authorityId,authorityGeneration:auth.authorityGeneration},native:{width:NW,height:NH,projectionKind:'world-camera-floor-z-affine-v2',worldXScale:round(c.xWorld,8),xBias:round(c.xBias,8),floorYScale:round(c.floorY,8),zScale:round(c.z,8),yBias:round(c.yBias,8)},validationEnvelope:{worldX:[round(fitState.coverage.worldX.min,4),round(fitState.coverage.worldX.max,4)],worldY:[round(fitState.coverage.worldY.min,4),round(fitState.coverage.worldY.max,4)],worldZ:[round(fitState.coverage.worldZ.min,4),round(fitState.coverage.worldZ.max,4)],cameraRaw:[round(fitState.coverage.cameraRaw.min,4),round(fitState.coverage.cameraRaw.max,4)]},motionEnvelope:Object.fromEntries(Object.entries(fitState.motionEnvelope).map(([k,v])=>[k,round(Math.max(v,1e-6),6)])),residuals:Object.fromEntries(Object.entries(fitState.residuals).map(([k,v])=>[k,round(v,5)])),enemyHeadOffsetsByType:offsets,enemyHeadEvidenceByType:Object.fromEntries(Object.entries(enemy).map(([k,v])=>[k,{sampleCount:v.sampleCount,mad:round(v.mad,4),slot:v.slot,lifecycleGeneration:v.lifecycleGeneration}]))};}
function buildResult(){const enemy=validateEnemies();if(!fitState?.ok||!Object.keys(enemy).length)return null;const p=projectBuild(enemy),m=metrics();return{schema:RESULT_SCHEMA,version:VERSION,verdict:'IMPLEMENTATION_READY',generatedAt:new Date().toISOString(),projection:p,authorityBinding:{workerSessionId,sequenceStart:samples[0]?.sequence??null,sequenceEnd:samples.at(-1)?.sequence??null,p1LifecycleGeneration:cal.p1LifecycleGeneration,cameraAuthorityId:cal.cameraAuthority.authorityId,cameraAuthorityGeneration:cal.cameraAuthority.authorityGeneration,cameraAddress:cal.cameraAddress,requestSnapshotId:cal.requestSnapshotId},calibration:{interactionMode:'ONE_CLICK_VISUAL_SEED',clickCount:1,seedNative:{x:round(cal.nativeClick.x,2),y:round(cal.nativeClick.y,2)},pairedSampleCount:samples.length,holdoutSampleCount:fitState.holdoutCount},evidence:{tracker:{acceptedCount:trackerTimeline.filter(x=>x.ok).length,rejectedCount:trackerTimeline.filter(x=>x.ok===false).length,currentScore:round(tracker?.score),currentMargin:round(tracker?.margin),timeline:trackerTimeline.slice(-64)},fit:{coefficients:p.native,residuals:p.residuals,validationEnvelope:p.validationEnvelope,motionEnvelope:p.motionEnvelope},enemyHeadEvidenceByType:p.enemyHeadEvidenceByType,authorityTimeline:localAuthorityEvents.slice(-96),suppression:suppression.slice(-48),webgl:{hookCount:m.hookCount,markerDrawCount:m.drawCount,viewport:vpInfo()},layout:{baseline:layoutBase,current:layoutSnapshot()}},boundaries:{...SAFETY,ownerModelChoice:false,simultaneousCandidateLabels:false,maxCalibrationClicksPerAuthorityGeneration:1}};}
function failClosed(verdict){if(resultCache)return;resultCache={schema:RESULT_SCHEMA,version:VERSION,verdict,generatedAt:new Date().toISOString(),projection:null,authorityBinding:cal?{workerSessionId,cameraAuthorityId:cal.cameraAuthority.authorityId,cameraAuthorityGeneration:cal.cameraAuthority.authorityGeneration,p1LifecycleGeneration:cal.p1LifecycleGeneration}:null,evidence:{trackerTimeline:trackerTimeline.slice(-64),fit:fitState,authorityTimeline:localAuthorityEvents.slice(-96),suppression:suppression.slice(-48)},boundaries:{...SAFETY,ownerModelChoice:false,simultaneousCandidateLabels:false,maxCalibrationClicksPerAuthorityGeneration:1}};localEvent('PROJECTION_FAILED',{verdict});}
function updateCompletion(){if(!cal||resultCache)return;if(Date.now()-cal.at>MAX_CAL_MS){failClosed('FAILED_COMPONENT:BOUNDED_CALIBRATION_TIMEOUT');return;}if(fitState?.ok){const enemy=validateEnemies();if(Object.keys(enemy).length){resultCache=buildResult();if(resultCache)localEvent('PROJECTION_READY',{enemyTypes:Object.keys(enemy),pairedSampleCount:samples.length,holdoutSampleCount:fitState.holdoutCount});}}}
function nextAction(){if(!last||Date.now()-lastRx>700)return'等待游戏连接，请保持当前窗口打开。';if(pendingCal)return'正在锁定 Camera，请不要再次点击。';if(!cal){const q=last.cameraQuality||{};if(q.ready&&q.clickReady)return'需要一次确认：请点一下 P1 头顶上方希望提示出现的位置。';if(q.ready)return'Camera 已准备好，等待 P1 出现在场景中。';return currentGuidance().actionZh||'正在准备 Camera，请正常玩。';}if(!fitState?.ok){const r=fitState?.reason;if(r==='NEED_HORIZONTAL_COVERAGE')return'请正常左右移动几秒。';if(r==='NEED_DEPTH_COVERAGE')return'请上下走动几秒。';if(r==='NEED_JUMP_COVERAGE')return'现在跳一次。';if(r==='RESIDUAL_GATE_FAILED'||r==='AFFINE_NOT_IDENTIFIABLE'||r==='AFFINE_DEGENERATE')return'正在继续自动校准，请正常玩。';return'正在自动校准，请正常玩。';}const e=validateEnemies();if(!Object.keys(e).length)return'头部变换已稳定；继续正常玩到至少一个敌人出现。';return'正在完成头顶位置验证，请继续正常玩。';}
renderer=glFactory({gl,canvas,getPoints:()=>[]});
const root=document.createElement('div');root.style.cssText='position:fixed;left:10px;top:10px;z-index:2147483647;width:360px;max-width:calc(100vw - 20px);padding:8px 10px;background:rgba(0,0,0,.78);border:1px solid rgba(255,255,255,.8);border-radius:8px;color:#fff;font:13px/1.4 system-ui;pointer-events:none';root.innerHTML='<b>WOF 头顶定位</b><div id="s" style="margin-top:4px"></div><div id="p" style="margin-top:3px;font-size:11px;opacity:.82"></div>';document.documentElement.appendChild(root);const s=root.querySelector('#s'),p=root.querySelector('#p');
function resetForWorkerReplacement(newSession){if(cal||pendingCal||readyAuthority())localEvent('READY_REVOKED',{reason:'WORKER_SESSION_REPLACED'});cal=null;pendingCal=null;tracker=null;fitState=null;resultCache=null;samples.length=0;enemyEvidence.clear();enemySlots.clear();p1Present=false;p1LifecycleGeneration=0;workerSessionId=newSession;lastSequence=0;uiError='runtime generation 已替换，旧 projection authority 已撤销。';}
bc.onmessage=e=>{const m=e.data;if(m?.schema!==CHANNEL||m.kind!=='state'||!m.workerSessionId||!Number.isInteger(m.sequence))return;if(workerSessionId&&m.workerSessionId!==workerSessionId)resetForWorkerReplacement(m.workerSessionId);if(!workerSessionId)workerSessionId=m.workerSessionId;if(m.workerSessionId!==workerSessionId||m.sequence<=lastSequence)return;last=m;lastSequence=m.sequence;lastRx=Date.now();updateLifecycle();maybeFinalizeCalibration();};bc.postMessage({schema:CHANNEL,kind:'request-state'});
function click(e){if(!running||pendingCal||cal||resultCache||root.contains(e.target)||!inside(e.clientX,e.clientY))return;try{const q=last?.cameraQuality||{};if(!(q.ready&&q.clickReady))return;requestCalibration(e.clientX,e.clientY);e.preventDefault();e.stopPropagation();}catch(err){uiError=String(err?.message||err);failClosed('FAILED_COMPONENT:visual_seed');s.textContent='本次无法可靠建立视觉定位，已自动保存结果。';p.textContent=uiError;}}
addEventListener('click',click,true);
let lastCollectSeq=0;
function loop(){if(!running)return;maybeFinalizeCalibration();const ls=layoutSignature(layoutSnapshot());if(layoutSigLast&&ls!==layoutSigLast){layoutChangedAt=Date.now();noteSuppression('LAYOUT_TRANSITION');}layoutSigLast=ls;if(cal&&lastSequence!==lastCollectSeq&&Date.now()-layoutChangedAt>250){lastCollectSeq=lastSequence;collectPair();if(fitState?.ok)validateEnemies();updateCompletion();}
  if(resultCache){s.textContent=resultCache.verdict==='IMPLEMENTATION_READY'?'校准完成，头顶提示已启用。':'本次无法可靠确定头顶位置，已自动保存结果；请结束本次验证。';p.textContent='详细证据会自动写入本次 WOF_LIVE_ACCEPTANCE 结果包。';}
  else{s.textContent=nextAction();if(cal){const good=trackerTimeline.filter(x=>x.ok).length,enemy=fitState?.ok?Object.keys(validateEnemies()).length:0;p.textContent=`自动样本 ${samples.length}/${MIN_TRACKED} · 视觉跟踪 ${good} · 已验证敌人类型 ${enemy}${uiError?' · '+uiError:''}`;}else{const q=last?.cameraQuality||{};p.textContent=`Camera ${q.conditioning||q.reason||'SCANNING'}${Number.isInteger(q.samples)?' · samples '+q.samples:''}${uiError?' · '+uiError:''}`;}}
  raf=requestAnimationFrame(loop);
}
raf=requestAnimationFrame(loop);
const publicApi={version:VERSION,mode:'top-auto-fit',status(){const enemy=fitState?.ok?validateEnemies():{};return{running,armed:!cal&&!pendingCal,calibrated:!!cal,pendingCalibration:!!pendingCal,lastAgeMs:lastRx?Date.now()-lastRx:null,samples:last?.samples??0,workerSessionId,lastSequence,snapshotId:last?.snapshotId||null,cameraQuality:last?.cameraQuality||null,cameraRawQuality:last?.cameraRawQuality||null,candidateStability:last?.candidateStability||null,cameraAuthority:last?.cameraAuthority||null,readyCamera:last?.readyCamera||null,lockedCamera:last?.lockedCamera||null,lockRejectReason:last?.lockRejectReason||null,sampling:last?.sampling||null,guidance:{actionZh:nextAction(),nextCommandZh:'无需做数学选择；继续当前 menu 6 真人验证。'},authorityTimeline:[...(last?.authorityTimeline||[]),...localAuthorityEvents],fit:fitState?{ok:!!fitState.ok,reason:fitState.reason,sampleCount:samples.length,residuals:fitState.residuals||null,coverage:fitState.coverage||null}:null,tracker:tracker?{score:round(tracker.score),margin:round(tracker.margin),lost:tracker.lost,accepted:trackerTimeline.filter(x=>x.ok).length,rejected:trackerTimeline.filter(x=>x.ok===false).length}:null,enemyEvidenceTypes:Object.keys(enemy),suppression:suppression.slice(-16),terminal:!!resultCache,verdict:resultCache?.verdict||null,uiError};},terminalResult(){return resultCache;},stop(){running=false;cancelAnimationFrame(raf);removeEventListener('click',click,true);try{renderer?.stop?.();}catch(_){}try{bc.close();}catch(_){}try{root.remove();}catch(_){}try{delete window.__WOF_OWNER_PROJECTION_GL_SOURCE;}catch(_){}try{delete window.WOFOWNERPROJECTION;}catch(_){}}};if(window.__WOF_PROJECTION_TEST_HOOK__===true)publicApi.__testFit=fitProjection;window.WOFOWNERPROJECTION=publicApi;
})();
