(()=>{
'use strict';
try{self.WOFSTATEALIAS?.stop?.();}catch(_){}
const RAW='https://raw.githubusercontent.com/ouyong520/wof-ai-private/main/';
const sleep=ms=>new Promise(r=>setTimeout(r,ms));let stopped=false;
const load=async f=>{const r=await fetch(RAW+f+'?x='+Date.now(),{cache:'no-store'});if(!r.ok)throw new Error('fetch failed '+r.status+' '+f);return (0,eval)(await r.text());};
async function ensure(){if(!self.__WOF_STATE_DISPATCH_LOCK)throw new Error('STATE_DISPATCH_LOCK missing');if(!self.__WOF_ROM_FOCUS_LEVEL2?.handlers?.length){await load('wof_rom_focus_level2_tables.js');await WOFFOCUSLEVEL2.run();}if(!self.__WOF_ROM_LOC_CACHE)throw new Error('ROM cache missing');}
function env(){const MOD=_0x515056,C=self.__WOF_ROM_LOC_CACHE,M=MOD.HEAPU8,base=C.base,SW=!!C.swap16,MAX=Math.min(0x100000,M.length-base),DELTA=C.offlineDelta|0;const r8=o=>M[base+(SW?(o^1):o)]>>>0,r16=o=>((r8(o)<<8)|r8(o+1))>>>0,r32=o=>(r8(o)*0x1000000+r8(o+1)*0x10000+r8(o+2)*0x100+r8(o+3))>>>0,s8=v=>v&0x80?v-0x100:v,s16=v=>v&0x8000?v-0x10000:v,h=x=>'0x'+(x>>>0).toString(16).toUpperCase().padStart(6,'0'),off=x=>h((x-DELTA)>>>0),hw=x=>'0x'+(x&0xffff).toString(16).toUpperCase().padStart(4,'0');return{MAX,r8,r16,r32,s8,s16,h,off,hw};}
function eaWords(m,r,size){if(m<=4)return 0;if(m===5||m===6)return 1;if(m===7){if(r===0||r===2||r===3)return 1;if(r===1)return 2;if(r===4)return size==='L'?2:1;}return 0;}
function decode(E,p){const w=E.r16(p),g=w>>>12,m=(w>>3)&7,r=w&7;let len=2,kind='OP',target=null,fall=true,terminal=false,call=false;if(w===0x4E75||w===0x4E73||w===0x4E77){kind='RET';terminal=true;fall=false;}else if(w===0x4E72){kind='STOP';len=4;terminal=true;fall=false;}else if((w&0xFFC0)===0x4E80){kind='JSR';call=true;len=2+eaWords(m,r,'L')*2;if(m===7&&r===0)target=E.s16(E.r16(p+2))>>>0;else if(m===7&&r===1)target=E.r32(p+2);else if(m===7&&r===2)target=(p+2+E.s16(E.r16(p+2)))>>>0;}else if((w&0xFFC0)===0x4EC0){kind='JMP';fall=false;len=2+eaWords(m,r,'L')*2;if(m===7&&r===0)target=E.s16(E.r16(p+2))>>>0;else if(m===7&&r===1)target=E.r32(p+2);else if(m===7&&r===2)target=(p+2+E.s16(E.r16(p+2)))>>>0;}else if(g===6){const cc=(w>>8)&15,d=w&255;len=d===0?4:2;target=d===0?p+2+E.s16(E.r16(p+2)):p+2+E.s8(d);kind=cc===0?'BRA':cc===1?'BSR':'BCC';if(cc===0)fall=false;if(cc===1)call=true;}else if(g===1||g===2||g===3){const size=g===1?'B':g===2?'L':'W',sm=(w>>3)&7,sr=w&7,dm=(w>>6)&7,dr=(w>>9)&7;len=2+(eaWords(sm,sr,size)+eaWords(dm,dr,size))*2;}else if(g===5){const sz=(w>>6)&3;if(sz===3&&m===1){kind='DBCC';len=4;target=(p+2+E.s16(E.r16(p+2)))>>>0;}else len=2+eaWords(m,r,sz===3?'B':sz===2?'L':sz===1?'W':'B')*2;}else if(g===0){if([0x003C,0x007C,0x023C,0x027C,0x0A3C,0x0A7C].includes(w))len=4;else if((w&0xF138)===0x0108)len=4;else if((w&0xFF00)===0x0800)len=4+eaWords(m,r,'B')*2;else if((w&0xF100)===0x0100)len=2+eaWords(m,r,'B')*2;else{const op=(w>>8)&15,sz=(w>>6)&3;if([0,2,4,6,10,12].includes(op)){const s=sz===2?'L':sz===1?'W':'B';len=2+(s==='L'?4:2)+eaWords(m,r,s)*2;}}}else if(g===4){if((w&0xFFF8)===0x4E50)len=4;else if((w&0xFB80)===0x4880&&m>=2)len=4+eaWords(m,r,(w&0x40)?'L':'W')*2;else if((w&0xF1C0)===0x41C0)len=2+eaWords(m,r,'L')*2;else if((w&0xFFC0)===0x4840&&m!==0)len=2+eaWords(m,r,'L')*2;else len=2+eaWords(m,r,((w>>6)&3)===2?'L':'W')*2;}else if(g===8){if((w&0xF1F0)!==0x8100)len=2+eaWords(m,r,((w>>6)&3)===2?'L':'W')*2;}else if(g===9||g===13){const special=(w&0xF130)===(g===9?0x9100:0xD100),a=((w>>6)&7)===3||((w>>6)&7)===7;if(!special)len=2+eaWords(m,r,a?(((w>>6)&1)?'L':'W'):(((w>>6)&3)===2?'L':'W'))*2;}else if(g===11){const cmpm=(w&0xF138)===0xB108,a=((w>>6)&7)===3||((w>>6)&7)===7;if(!cmpm)len=2+eaWords(m,r,a?(((w>>6)&1)?'L':'W'):(((w>>6)&3)===2?'L':'W'))*2;}else if(g===12){const exg=(w&0xF1F8)===0xC140||(w&0xF1F8)===0xC148||(w&0xF1F8)===0xC188,abcd=(w&0xF1F0)===0xC100;if(!exg&&!abcd)len=2+eaWords(m,r,((w>>6)&3)===2?'L':'W')*2;}else if(g===14&&((w>>6)&3)===3)len=2+eaWords(m,r,'W')*2;else if(g===10||g===15){kind='LINE';terminal=true;fall=false;}len=Math.max(2,len);const next=p+len;if(target!=null&&(target<0||target>=E.MAX))target=null;return{at:p,w,len,next,kind,target,fall,terminal,call};}
function cfg(E,start,cap=0x1800){const hi=Math.min(E.MAX,start+cap),q=[start&~1],seen=new Set(),calls=[];while(q.length&&seen.size<9000){const p=q.shift();if(p<0||p>=hi||(p&1)||seen.has(p))continue;seen.add(p);const d=decode(E,p);if((d.kind==='JSR'||d.kind==='BSR')&&d.target!=null)calls.push(d.target&~1);if(d.kind==='BRA'){if(d.target!=null&&d.target<hi)q.push(d.target&~1);continue;}if(d.kind==='BCC'||d.kind==='DBCC'){if(d.next<hi)q.push(d.next);if(d.target!=null&&d.target<hi)q.push(d.target&~1);continue;}if(d.kind==='JMP'){if(d.target!=null&&d.target<hi)q.push(d.target&~1);continue;}if(d.terminal)continue;if(d.next<hi)q.push(d.next);}return{seen,calls:[...new Set(calls)]};}
function moveMeta(E,p){const w=E.r16(p),g=w>>>12;if(g!==1&&g!==2&&g!==3)return null;const size=g===1?'B':g===2?'L':'W',sm=(w>>3)&7,sr=w&7,dm=(w>>6)&7,dr=(w>>9)&7,sw=eaWords(sm,sr,size),dstExt=p+2+sw*2;let dstDisp=0;if(dm===5)dstDisp=E.s16(E.r16(dstExt));let imm=null;if(sm===7&&sr===4){imm=size==='L'?E.r32(p+2):E.r16(p+2);if(size==='B')imm&=0xff;}return{size,sm,sr,dm,dr,sw,dstDisp,imm};}
function writeEA(E,p){const w=E.r16(p),g=w>>>12,m=(w>>3)&7,r=w&7,mm=moveMeta(E,p);if(mm&&[2,3,4,5].includes(mm.dm))return{kind:'MOVE.'+mm.size,areg:mm.dr,disp:mm.dm===5?mm.dstDisp:0,srcReg:mm.sm===0?'D'+mm.sr:mm.sm===1?'A'+mm.sr:'',imm:mm.imm};if(g===5&&((w>>6)&3)!==3&&[2,3,4,5].includes(m)){const q=((w>>9)&7)||8,sub=!!(w&0x0100),disp=m===5?E.s16(E.r16(p+2)):0;return{kind:(sub?'SUBQ.':'ADDQ.')+(((w>>6)&3)===2?'L':((w>>6)&3)===1?'W':'B'),areg:r,disp,srcReg:'',imm:q};}if(g===4&&(((w&0xff00)===0x4200)||((w&0xff00)===0x4400)||((w&0xff00)===0x4600))&&[2,3,4,5].includes(m)){const disp=m===5?E.s16(E.r16(p+2)):0;return{kind:(w&0xff00)===0x4200?'CLR':(w&0xff00)===0x4400?'NEG':'NOT',areg:r,disp,srcReg:'',imm:(w&0xff00)===0x4200?0:null};}return null;}
function stepAlias(E,p,a){const w=E.r16(p),g=w>>>12,n=a.slice(),mm=moveMeta(E,p);if(mm&&mm.dm===1){if(mm.sm===1)n[mm.dr]=a[mm.sr];else n[mm.dr]=null;return n;}if((w&0xF1C0)===0x41C0){const dst=(w>>9)&7,sm=(w>>3)&7,sr=w&7;if(sm===2)n[dst]=a[sr];else if(sm===5&&a[sr]!=null)n[dst]=a[sr]+E.s16(E.r16(p+2));else n[dst]=null;return n;}if(g===5&&((w>>6)&3)!==3&&((w>>3)&7)===1){const r=w&7,q=((w>>9)&7)||8;if(a[r]!=null)n[r]=a[r]+((w&0x0100)?-q:q);return n;}if((w&0xF1F8)===0xC148){const x=(w>>9)&7,y=w&7,[n[x],n[y]]=[a[y],a[x]];return n;}return n;}
function succ(E,p,d,hi){const out=[];if(d.kind==='BRA'){if(d.target!=null&&d.target<hi)out.push(d.target&~1);return out;}if(d.kind==='BCC'||d.kind==='DBCC'){if(d.next<hi)out.push(d.next);if(d.target!=null&&d.target<hi)out.push(d.target&~1);return out;}if(d.kind==='JMP'){if(d.target!=null&&d.target<hi)out.push(d.target&~1);return out;}if(d.terminal)return out;if(d.next<hi)out.push(d.next);return out;}
function aliasScan(E,start,FIELD,observed,cap=0x1800){const hi=Math.min(E.MAX,start+cap),hits=[];for(let seed=0;seed<7;seed++){const init=Array(7).fill(null);init[seed]=0;const q=[{p:start&~1,a:init}],seen=new Set();while(q.length&&seen.size<18000){const z=q.shift(),p=z.p;if(p<0||p>=hi||(p&1))continue;const key=p+'|'+z.a.map(v=>v==null?'x':v).join(',');if(seen.has(key))continue;seen.add(key);const d=decode(E,p),wr=writeEA(E,p);if(wr&&z.a[wr.areg]!=null){const eff=z.a[wr.areg]+wr.disp;if(eff===FIELD){const im=typeof wr.imm==='number'?wr.imm:null;hits.push({at:p,seedReg:'A'+seed,eff,kind:wr.kind,baseReg:'A'+wr.areg,srcReg:wr.srcReg||'',imm:im,matchObserved:im!=null&&observed.has(im)});}}const na=stepAlias(E,p,z.a);for(const s of succ(E,p,d,hi))q.push({p:s,a:na.slice()});}}
 return [...new Map(hits.map(x=>[x.at+'|'+x.seedReg+'|'+x.baseReg,x])).values()];}
function ctx(E,p){const out=[];for(let q=Math.max(0,p-0x18)&~1;q<=Math.min(E.MAX-2,p+0x18);q+=2)out.push({at:E.h(q),offline:E.off(q),word:E.hw(E.r16(q)),mark:q===p?'<<< ALIAS STATE WRITE':''});return out;}
async function run(){stopped=false;await ensure();const E=env(),S=self.__WOF_STATE_DISPATCH_LOCK,L2=self.__WOF_ROM_FOCUS_LEVEL2,FIELD=parseInt(S.verdict.field,16),KIND=S.verdict.kind;const observed=new Set([0]);for(const m of S.mappings||[]){const z=String(m.mapping||'').match(/@(0x[0-9A-Fa-f]+)/);if(z){const d=parseInt(z[1],16);if(Number.isFinite(d))observed.add(d/4);}}
 console.log('🧬 WOF stateIndex alias writer scan v2');console.log('FIELD',S.verdict.field,'KIND',KIND,'observed',[...observed].sort((a,b)=>a-b));
 const roots=[...new Set((L2.handlers||[]).map(x=>parseInt(x.target,16)&~1).filter(Number.isFinite))],routines=new Set(),queue=roots.map(a=>({a,d:0})),seenR=new Set();while(queue.length){const n=queue.shift(),a=n.a&~1;if(seenR.has(a)||n.d>8)continue;seenR.add(a);routines.add(a);const c=cfg(E,a);for(const t of c.calls)if(n.d<8&&!seenR.has(t))queue.push({a:t,d:n.d+1});if((seenR.size&31)===0)await sleep(0);}
 const rows=[];let i=0;for(const a of routines){if(stopped)throw new Error('stopped');for(const x of aliasScan(E,a,FIELD,observed)){const score=(x.matchObserved?300:0)+(x.srcReg?80:0)+(x.seedReg===x.baseReg?20:60);rows.push({routine:E.h(a),offlineRoutine:E.off(a),at:E.h(x.at),offlineAt:E.off(x.at),seedReg:x.seedReg,baseReg:x.baseReg,kind:x.kind,srcReg:x.srcReg,imm:x.imm==null?'':E.h(x.imm).slice(-4),matchesObserved:x.matchObserved,score});}if((++i&15)===0)await sleep(0);}
 rows.sort((a,b)=>b.score-a.score||a.at.localeCompare(b.at));console.log('=== REAL CFG STATE ALIAS WRITES ===');console.table(rows.slice(0,120));const obs=rows.filter(x=>x.matchesObserved),top=obs[0]||rows[0]||null;if(top){console.log('=== TOP ALIAS STATE WRITE CONTEXT ===');console.table(ctx(E,parseInt(top.at,16)));}
 const verdict={field:S.verdict.field,kind:KIND,encoding:S.verdict.fieldEncoding,reachableRoutines:routines.size,aliasWriteSites:rows.length,observedAliasWrites:obs.length,topAt:top?.at||'',topRoutine:top?.routine||'',topSeedReg:top?.seedReg||'',topBaseReg:top?.baseReg||'',topKind:top?.kind||'',topSrcReg:top?.srcReg||'',topImm:top?.imm||'',topMatchesObserved:top?.matchesObserved??false};console.log('=== STATE ALIAS WRITER VERDICT ===');console.table([verdict]);if(obs.length)console.log('🎯 找到真实 CFG 内通过 A-register alias 写已观测 stateIndex；下一步只追 top write 的 src/caller/player evidence。');else if(rows.length)console.warn('⚠️ 找到 alias state 写入但 immediate 未命中已观测状态；下一步追 srcReg/前序计算。');else console.warn('⚠️ handler CFG 内连 alias 写也没有；下一步不再扩静态 handler 图，转动态 state-change 时序 + shared dispatcher/upstream writer。');
 const out={version:'wof-state-writer-alias-v2',verdict,rows};self.__WOF_STATE_WRITER_ALIAS_V2=out;return out;}
self.WOFSTATEALIAS={version:'wof-state-writer-alias-v2',run,stop(){stopped=true;}};console.log('✅ WOF state writer alias v2 loaded');console.log('执行 await WOFSTATEALIAS.run()');
})();