(async()=>{
'use strict';
const RAW='https://raw.githubusercontent.com/ouyong520/wof-ai-private/main/';
const load=async f=>{const r=await fetch(RAW+f+'?x='+Date.now(),{cache:'no-store'});if(!r.ok)throw new Error('fetch failed '+r.status+' '+f);return(0,eval)(await r.text());};
if(!self.__WOF_ROM_LOC_CACHE)await load('wof_resume_dispatch_selector.js');
const C=self.__WOF_ROM_LOC_CACHE;if(!C)throw new Error('ROM cache missing');
const M=_0x515056.HEAPU8,romBase=C.base,SW=!!C.swap16,ROMMAX=Math.min(0x100000,M.length-romBase);
const r8=o=>M[romBase+(SW?(o^1):o)]>>>0;
const r16=o=>((r8(o)<<8)|r8(o+1))>>>0;
const r32=o=>(r8(o)*0x1000000+r8(o+1)*0x10000+r8(o+2)*0x100+r8(o+3))>>>0;
const validRom=v=>v>=0x2000&&v<ROMMAX&&(v&1)===0;
const gate={dispatcher25C8:r16(0x25C8)===0x3228&&r16(0x25D0)===0x287B&&r16(0x25D4)===0x2874,handoff247C:r16(0x247C)===0x2C5C&&r16(0x247E)===0x215C&&r16(0x2482)===0x321C,d0_20Source:r16(0x6A62)===0x7014&&r16(0x6A64)===0x4EB8&&r16(0x6A66)===0x25C8,attackField:true,xyFields:true};
function parseDescriptor(at){if(!validRom(at)||at+14>ROMMAX)return null;const frameEnd=r32(at)>>>0,value30=r32(at+4)>>>0,timerRaw=r16(at+8)>>>0;if(!validRom(frameEnd))return null;const flagged=!!(timerRaw&0x8000),timer=flagged?(timerRaw&0x7fff):timerRaw,next=flagged?(r32(at+10)>>>0):((at+10)>>>0);if(!validRom(next))return null;return{at,frameEnd,value30,timer,next};}
function typeMap(type){if(type<0||type>=47)return null;const table=r32(0x25DC+type*4)>>>0;if(!validRom(table))return null;const p=r32(table+20)>>>0;return{type,d20:parseDescriptor(p)};}
const R=_0x515056?.HEAPU32?.[0x2e39e4>>>2]>>>0;if(!R)throw new Error('CPS RAM base missing');
const B=a=>M[R+((((a-0xFF0000)&0xffff)^1))]>>>0;
const U16=a=>((B(a)<<8)|B(a+1))>>>0;
const U32=a=>(B(a)*0x1000000+B(a+1)*0x10000+B(a+2)*0x100+B(a+3))>>>0;
const S32=a=>{const v=U32(a);return v>=0x80000000?v-0x100000000:v;};
const PX=a=>Math.round(S32(a+4)/65536),PY=a=>Math.round(S32(a+8)/65536);
const ENEMY=0xFFC0BC,STRIDE=0xE0,SLOTS=20,PLAYERS={0:'P1',4:'P2',8:'P3'},PBASE={0:0xFFBE1C,4:0xFFBEFC,8:0xFFBFDC};
const maps=new Map(),getMap=t=>{if(!maps.has(t))maps.set(t,typeMap(t));return maps.get(t);};
function descMatches(s,d){return!!d&&s.frameEnd===d.frameEnd&&s.value30===d.value30&&s.next===d.next&&s.timer<=d.timer;}
const side=dx=>dx<-4?'LEFT':dx>4?'RIGHT':'CENTER';
const lane=dy=>dy<-4?'UP':dy>4?'DOWN':'SAME';
function geom(a,target7E){const ex=PX(a),ey=PY(a),pb=PBASE[target7E];if(!pb)return{enemyX:ex,enemyY:ey,targetX:null,targetY:null,dx:null,dy:null,absDx:null,absDy:null,side:null,lane:null};const tx=PX(pb),ty=PY(pb),dx=tx-ex,dy=ty-ey;return{enemyX:ex,enemyY:ey,targetX:tx,targetY:ty,dx,dy,absDx:Math.abs(dx),absDy:Math.abs(dy),side:side(dx),lane:lane(dy)};}
function snap(slot){const a=ENEMY+slot*STRIDE,type=U16(a+0x20);if(type>=47)return null;const frameEnd=U32(a+0x12),next=U32(a+0x2C);if(frameEnd===0&&next===0)return null;const target7E=U16(a+0x7E),d20=getMap(type)?.d20||null,s={slot,a,type,target7E,target:PLAYERS[target7E]||null,state99:B(a+0x99),action2A:B(a+0x2A),b2B:B(a+0x2B),timer:U16(a+0x34),attack:U16(a+0x70),body:U16(a+0x6E),frameEnd,next,value30:U32(a+0x30),d20StartTimer:d20?.timer??null,...geom(a,target7E)};s.inD20=descMatches(s,d20);s.d20Exact=!!(s.inD20&&d20&&s.timer===d20.timer);return s;}

// V15 empirical ACTIVE-start envelopes. These are target-relative observations, NOT hitboxes.
const ENVELOPES={
  9:{reachX:378,reachY:59,n:39,source:'V15 type P90'},
  10:{reachX:275,reachY:29,n:37,source:'V15 type P90'},
  13:{reachX:321,reachY:26,n:53,source:'V15 type P90'},
  30:{reachX:203,reachY:6,n:22,source:'V15 type P90'}
};
const RULES={
  T13_ENTRY_250:{type:13,trigger:'ENTRY',horizon:250,level:'IMMINENT',confidence:'provisional-high',evidence:'V15 D0 episodes 14/14 active with leads 41..241ms; fresh validation required'},
  T9_ENTRY_500:{type:9,trigger:'ENTRY',horizon:500,level:'DANGER_SOON',confidence:'high-observed',evidence:'V3+V14+V15 repeated <=500ms observations'},
  T10_ENTRY_500:{type:10,trigger:'ENTRY',horizon:500,level:'DANGER_SOON',confidence:'high-observed',evidence:'repeated roughly 398..420ms observations'},
  T30_ENTRY_500:{type:30,trigger:'ENTRY',horizon:500,level:'DANGER_SOON',confidence:'high-observed',evidence:'V11/V12/V15 observed <=500ms when active'},
  T33_ENTRY_500:{type:33,trigger:'ENTRY',horizon:500,level:'DANGER_SOON',confidence:'high-observed',evidence:'prior observed entry leads <=500ms; no V15 envelope yet'},
  T21_EXIT_250:{type:21,trigger:'EXIT',horizon:250,level:'IMMINENT',confidence:'provisional-high',evidence:'V10 exit leads 38/40/81/120/219ms'}
};
const ENTRY_RULE_BY_TYPE={13:'T13_ENTRY_250',9:'T9_ENTRY_500',10:'T10_ENTRY_500',30:'T30_ENTRY_500',33:'T33_ENTRY_500'};
const DURATION=120000,INTERVAL=20,MAX_WATCH=1500,POST_ACTIVE=60,start=performance.now();
const prev=new Map(),episodes=new Map(),done=[],signals=[],events=[],liveMap=new Map(),envelopeEdges=[];let epSeq=0,sigSeq=0,evSeq=0;
const diag={polls:0,enemySamples:0,d20ObservedEntries:0,d20ExactObservedEntries:0,d20LateObservedEntries:0,globalActiveEdges:0,envelopeActiveEdges:0};
function rectFor(s,env){if(!env||s.enemyX==null||s.enemyY==null)return null;let xMin,xMax;if(s.side==='LEFT'){xMin=s.enemyX-env.reachX;xMax=s.enemyX+4;}else if(s.side==='RIGHT'){xMin=s.enemyX-4;xMax=s.enemyX+env.reachX;}else{xMin=s.enemyX-env.reachX;xMax=s.enemyX+env.reachX;}return{xMin,xMax,yMin:s.enemyY-env.reachY,yMax:s.enemyY+env.reachY};}
const pointInside=(x,y,r)=>!!r&&x!=null&&y!=null&&x>=r.xMin&&x<=r.xMax&&y>=r.yMin&&y<=r.yMax;
function syncMap(){self.__WOF_FUTURE_DANGER_MAP_STATE=Object.fromEntries([...liveMap.entries()].map(([k,v])=>[k,v]));}
function log(kind,ep,s,t,extra={}){const e={id:++evSeq,rel:t,kind,episode:ep?.id??null,slot:s?.slot??ep?.slot??null,type:s?.type??ep?.type??null,target:s?.target??ep?.last?.target??null,...extra};events.push(e);console.log(`[WOF MAP] ${kind} T${e.type} slot${e.slot} -> ${e.target??'?'}${e.horizonMs!=null?' <='+e.horizonMs+'ms':''}${e.inside!=null?' inside='+e.inside:''}`);}
function mapLevel(ep){const q=ep.signals.find(x=>!x.resolved);return q?{level:q.level,horizonMs:q.horizonMs,rule:q.rule}:{level:'ATTACK_READY',horizonMs:null,rule:null};}
function updateMap(ep,s,t){const env=ENVELOPES[s.type]||null,lvl=mapLevel(ep),rect=rectFor(s,env),inside=env?pointInside(s.targetX,s.targetY,rect):null;const st={episode:ep.id,slot:ep.slot,type:ep.type,level:ep.firstAttack?'ACTIVE':lvl.level,horizonMs:ep.firstAttack?0:lvl.horizonMs,rule:ep.firstAttack?'ACTIVE':lvl.rule,target:s.target,target7E:s.target7E,enemyX:s.enemyX,enemyY:s.enemyY,targetX:s.targetX,targetY:s.targetY,dx:s.dx,dy:s.dy,side:s.side,lane:s.lane,envelope:env,rect,targetInsideEnvelope:inside,updatedRel:t};liveMap.set(ep.slot,st);syncMap();return st;}
function clearMap(ep){liveMap.delete(ep.slot);syncMap();}
function emit(ep,s,t,rule){if(ep.ruleSeen.has(rule))return;ep.ruleSeen.add(rule);const cfg=RULES[rule],q={id:++sigSeq,epId:ep.id,rule,level:cfg.level,horizonMs:cfg.horizon,atRel:t-ep.startAt,targetAtSignal:s.target,target7EAtSignal:s.target7E,sideAtSignal:s.side,resolved:false,hit:null,leadToActiveMs:null,targetSameAtActive:null,sideSameAtActive:null,envelopeInsideAtActive:null};signals.push(q);ep.signals.push(q);updateMap(ep,s,t);log(cfg.level,ep,s,t,{horizonMs:cfg.horizon,rule});}
function finish(ep,t,reason){if(ep.done)return;ep.done=true;ep.endRel=t-ep.startAt;ep.endReason=reason;for(const q of ep.signals){if(!q.resolved&&ep.endRel-q.atRel>=q.horizonMs){q.resolved=true;q.hit=false;}}done.push(ep);episodes.delete(ep.slot);clearMap(ep);}
function startEp(s,t,mode){const old=episodes.get(s.slot);if(old)finish(old,t,'retrigger');const ep={id:++epSeq,slot:s.slot,type:s.type,startAt:t,entryTarget:s.target,entryTarget7E:s.target7E,entryMode:mode,entryExact:s.d20Exact,seenEntryTimer:s.timer,firstAttack:null,exitRel:null,last:s,targetSwitches:[],signals:[],ruleSeen:new Set(),done:false};episodes.set(s.slot,ep);diag.d20ObservedEntries++;if(s.d20Exact)diag.d20ExactObservedEntries++;else diag.d20LateObservedEntries++;updateMap(ep,s,t);log('ATTACK_READY',ep,s,t,{inside:liveMap.get(ep.slot)?.targetInsideEnvelope??null});const rule=ENTRY_RULE_BY_TYPE[s.type];if(rule)emit(ep,s,t,rule);}
function recordGlobalActive(s,t,ep){diag.globalActiveEdges++;const env=ENVELOPES[s.type]||null;if(!env)return;diag.envelopeActiveEdges++;const rect=rectFor(s,env),inside=pointInside(s.targetX,s.targetY,rect);envelopeEdges.push({rel:t,slot:s.slot,type:s.type,target:s.target,attack:s.attack,absDx:s.absDx,absDy:s.absDy,side:s.side,lane:s.lane,reachX:env.reachX,reachY:env.reachY,inside,episodeId:ep?.id??null});}
function updateEp(ep,s,t){const rel=t-ep.startAt,p=ep.last;if(s.type!==ep.type){finish(ep,t,'typeChanged');return;}if(s.target7E!==p.target7E)ep.targetSwitches.push({rel,from:p.target,to:s.target});if(ep.exitRel==null&&p.inD20&&!s.inD20){ep.exitRel=rel;if(s.type===21&&s.attack===0)emit(ep,s,t,'T21_EXIT_250');}
 updateMap(ep,s,t);
 if(!ep.firstAttack&&p.attack===0&&s.attack!==0){recordGlobalActive(s,t,ep);const env=ENVELOPES[s.type]||null,rect=rectFor(s,env),inside=env?pointInside(s.targetX,s.targetY,rect):null;ep.firstAttack={rel,target:s.target,target7E:s.target7E,side:s.side,attack:s.attack,absDx:s.absDx,absDy:s.absDy,envelopeInside:inside};for(const q of ep.signals){if(q.resolved)continue;const lead=rel-q.atRel;q.leadToActiveMs=lead;q.hit=lead>=0&&lead<=q.horizonMs;q.targetSameAtActive=q.target7EAtSignal===s.target7E;q.sideSameAtActive=q.sideAtSignal===s.side;q.envelopeInsideAtActive=inside;q.resolved=true;}updateMap(ep,s,t);log('ACTIVE',ep,s,t,{inside});}
 ep.last=s;if(ep.firstAttack&&rel>=ep.firstAttack.rel+POST_ACTIVE)finish(ep,t,'activeConfirmed');else if(rel>=MAX_WATCH)finish(ep,t,'horizonComplete');}
await new Promise(resolve=>{const id=setInterval(()=>{const t=Math.round(performance.now()-start);diag.polls++;for(let i=0;i<SLOTS;i++){const s=snap(i),p=prev.get(i)||null;if(!s){const ep=episodes.get(i);if(ep)finish(ep,t,'slotGone');prev.delete(i);continue;}diag.enemySamples++;if(s.inD20&&(!p||!p.inD20))startEp(s,t,p?'transition':'bootstrap');const ep=episodes.get(i);if(ep)updateEp(ep,s,t);else if(p&&p.attack===0&&s.attack!==0)recordGlobalActive(s,t,null);prev.set(i,s);}if(t>=DURATION){clearInterval(id);for(const ep of [...episodes.values()])finish(ep,t,'captureEnd');resolve();}},INTERVAL);});
const ruleStats={};for(const q of signals){const r=(ruleStats[q.rule]??={rule:q.rule,level:q.level,horizonMs:q.horizonMs,signals:0,evaluable:0,hit:0,miss:0,censored:0,targetSame:0,targetTotal:0,sideSame:0,sideTotal:0,envelopeInside:0,envelopeTotal:0,leads:[]});r.signals++;if(!q.resolved){r.censored++;continue;}r.evaluable++;if(q.hit){r.hit++;r.leads.push(q.leadToActiveMs);}else r.miss++;if(q.targetSameAtActive!=null){r.targetTotal++;if(q.targetSameAtActive)r.targetSame++;}if(q.sideSameAtActive!=null){r.sideTotal++;if(q.sideSameAtActive)r.sideSame++;}if(q.envelopeInsideAtActive!=null){r.envelopeTotal++;if(q.envelopeInsideAtActive)r.envelopeInside++;}}
for(const r of Object.values(ruleStats)){r.precision=r.evaluable?+(r.hit/r.evaluable).toFixed(3):null;r.targetSameRate=r.targetTotal?+(r.targetSame/r.targetTotal).toFixed(3):null;r.sideStableRate=r.sideTotal?+(r.sideSame/r.sideTotal).toFixed(3):null;r.envelopeContainmentRate=r.envelopeTotal?+(r.envelopeInside/r.envelopeTotal).toFixed(3):null;r.leads.sort((a,b)=>a-b);}
const envelopeStats={};for(const e of envelopeEdges){const k='T'+e.type,b=(envelopeStats[k]??={type:e.type,edges:0,inside:0,outside:0,reachX:e.reachX,reachY:e.reachY,absDx:[],absDy:[]});b.edges++;if(e.inside)b.inside++;else b.outside++;b.absDx.push(e.absDx);b.absDy.push(e.absDy);}const median=a=>{if(!a.length)return null;const b=[...a].sort((x,y)=>x-y),m=Math.floor(b.length/2);return b.length%2?b[m]:Math.round((b[m-1]+b[m])/2);};for(const b of Object.values(envelopeStats)){b.containmentRate=b.edges?+(b.inside/b.edges).toFixed(3):null;b.activeAbsDxMedian=median(b.absDx);b.activeAbsDyMedian=median(b.absDy);delete b.absDx;delete b.absDy;}
const byType={};for(const ep of done){const k='T'+ep.type,b=(byType[k]??={type:ep.type,episodes:0,active:0,horizonComplete:0,leads:[],retargets:0});b.episodes++;b.retargets+=ep.targetSwitches.length;if(ep.firstAttack){b.active++;b.leads.push(ep.firstAttack.rel);}else if(ep.endReason==='horizonComplete')b.horizonComplete++;}for(const b of Object.values(byType))b.leads.sort((a,b)=>a-b);
const rows=done.map(ep=>({id:ep.id,slot:ep.slot,type:ep.type,entryTarget:ep.entryTarget,entryMode:ep.entryMode,entryExact:ep.entryExact,seenEntryTimer:ep.seenEntryTimer,exitRel:ep.exitRel,outcome:ep.firstAttack?'active':ep.endReason,leadToActiveMs:ep.firstAttack?.rel??null,activeTarget:ep.firstAttack?.target??null,activeAttack:ep.firstAttack?.attack??null,activeAbsDx:ep.firstAttack?.absDx??null,activeAbsDy:ep.firstAttack?.absDy??null,envelopeInsideAtActive:ep.firstAttack?.envelopeInside??null,targetSwitches:ep.targetSwitches,signals:ep.signals}));
const out={version:'wof-future-danger-map-shadow-v16',readOnly:true,ramWrites:0,gate,gateStrict:Object.values(gate).every(Boolean),durationRequestedMs:DURATION,intervalMs:INTERVAL,maxWatchMs:MAX_WATCH,model:{timing:'type-conditioned D0=20 warning rules; V15 adds T13 ENTRY<=250 candidate',geometry:'V15 type-level ACTIVE-start P90 envelopes are used prospectively as shadow danger rectangles',mapSemantics:'rectangle is an empirical warning envelope anchored to the live enemy and mirrored toward the live target side; it is NOT a proven hitbox',targetPolicy:'live enemy+0x7E authoritative; map retargets every tick'},rules:RULES,envelopes:ENVELOPES,diagnostics:diag,totals:{episodes:done.length,active:done.filter(e=>e.firstAttack).length,horizonComplete:done.filter(e=>e.endReason==='horizonComplete'&&!e.firstAttack).length,signals:signals.length,envelopeActiveEdges:envelopeEdges.length,retargets:done.reduce((n,e)=>n+e.targetSwitches.length,0)},ruleStats,envelopeStats,byType,rows,note:'First 0-1000ms Future Danger Map shadow. Validate timing precision, target/side stability and new-room envelope containment before treating any rectangle as a production danger zone or exact attack range.'};
self.__WOF_FUTURE_DANGER_MAP_SHADOW_V16=out;self.__WOF_FUTURE_DANGER_MAP_STATE={};console.log('=== FUTURE DANGER MAP SHADOW V16 JSON ===');console.log(JSON.stringify(out,null,2));return out;
})().catch(e=>{console.error('WOF_FUTURE_DANGER_MAP_SHADOW_V16_ERROR',e);throw e;});