(async()=>{
'use strict';
const RAW='https://raw.githubusercontent.com/ouyong520/wof-ai-private/main/';
const load=async f=>{const r=await fetch(RAW+f+'?x='+Date.now(),{cache:'no-store'});if(!r.ok)throw new Error('fetch failed '+r.status+' '+f);return(0,eval)(await r.text());};
if(!self.__WOF_ROM_LOC_CACHE)await load('wof_resume_dispatch_selector.js');
const C=self.__WOF_ROM_LOC_CACHE;if(!C)throw new Error('ROM cache missing');
const M=_0x515056.HEAPU8,romBase=C.base,SW=!!C.swap16,ROMMAX=Math.min(0x100000,M.length-romBase);
const r8=o=>M[romBase+(SW?(o^1):o)]>>>0;
const r16=o=>((r8(o)<<8)|r8(o+1))>>>0;
const r32=o=>(r8(o)*0x1000000+r8(o+1)*0x10000+r8(o+2)*0x100+r8(o+3))>>>0;
const validRom=v=>v>=0x2000&&v<ROMMAX&&(v&1)===0;
const gate={dispatcher25C8:r16(0x25C8)===0x3228&&r16(0x25D0)===0x287B&&r16(0x25D4)===0x2874,handoff247C:r16(0x247C)===0x2C5C&&r16(0x247E)===0x215C&&r16(0x2482)===0x321C,d0_20Source:r16(0x6A62)===0x7014&&r16(0x6A64)===0x4EB8&&r16(0x6A66)===0x25C8,attackField:true,xyFields:true};
function parseDescriptor(at){if(!validRom(at)||at+14>ROMMAX)return null;const frameEnd=r32(at)>>>0,value30=r32(at+4)>>>0,timerRaw=r16(at+8)>>>0;if(!validRom(frameEnd))return null;const flagged=!!(timerRaw&0x8000),timer=flagged?(timerRaw&0x7fff):timerRaw,next=flagged?(r32(at+10)>>>0):((at+10)>>>0);if(!validRom(next))return null;return{at,frameEnd,value30,timer,next};}
function typeMap(type){if(type<0||type>=47)return null;const table=r32(0x25DC+type*4)>>>0;if(!validRom(table))return null;const p=r32(table+20)>>>0;return{type,d20:parseDescriptor(p)};}
const R=_0x515056?.HEAPU32?.[0x2e39e4>>>2]>>>0;if(!R)throw new Error('CPS RAM base missing');
const B=a=>M[R+((((a-0xFF0000)&0xffff)^1))]>>>0;
const U16=a=>((B(a)<<8)|B(a+1))>>>0;
const U32=a=>(B(a)*0x1000000+B(a+1)*0x10000+B(a+2)*0x100+B(a+3))>>>0;
const S32=a=>{const v=U32(a);return v>=0x80000000?v-0x100000000:v;};
const PX=a=>Math.round(S32(a+4)/65536),PY=a=>Math.round(S32(a+8)/65536);
const ENEMY=0xFFC0BC,STRIDE=0xE0,SLOTS=20,PLAYERS={0:'P1',4:'P2',8:'P3'},PBASE={0:0xFFBE1C,4:0xFFBEFC,8:0xFFBFDC};
const maps=new Map(),getMap=t=>{if(!maps.has(t))maps.set(t,typeMap(t));return maps.get(t);};
function descMatches(s,d){return!!d&&s.frameEnd===d.frameEnd&&s.value30===d.value30&&s.next===d.next&&s.timer<=d.timer;}
const side=dx=>dx<-4?'LEFT':dx>4?'RIGHT':'CENTER';
const lane=dy=>dy<-4?'UP':dy>4?'DOWN':'SAME';
function geom(a,target7E){const ex=PX(a),ey=PY(a),pb=PBASE[target7E];if(!pb)return{enemyX:ex,enemyY:ey,targetX:null,targetY:null,dx:null,dy:null,absDx:null,absDy:null,side:null,lane:null};const tx=PX(pb),ty=PY(pb),dx=tx-ex,dy=ty-ey;return{enemyX:ex,enemyY:ey,targetX:tx,targetY:ty,dx,dy,absDx:Math.abs(dx),absDy:Math.abs(dy),side:side(dx),lane:lane(dy)};}
function snap(slot){const a=ENEMY+slot*STRIDE,type=U16(a+0x20);if(type>=47)return null;const frameEnd=U32(a+0x12),next=U32(a+0x2C);if(frameEnd===0&&next===0)return null;const target7E=U16(a+0x7E),d20=getMap(type)?.d20||null;const s={slot,a,type,target7E,target:PLAYERS[target7E]||null,state99:B(a+0x99),action2A:B(a+0x2A),b2B:B(a+0x2B),timer:U16(a+0x34),attack:U16(a+0x70),body:U16(a+0x6E),frameEnd,next,value30:U32(a+0x30),...geom(a,target7E)};s.inD20=descMatches(s,d20);return s;}
const coarseKey=s=>`T${s.type}|D${s.inD20?1:0}|S${s.state99}|A${s.action2A}|B${s.b2B}|BODY${s.body}`;
const descKey=s=>`${coarseKey(s)}|FE${s.frameEnd.toString(16)}|NX${s.next.toString(16)}|V${s.value30.toString(16)}`;
const fineKey=s=>`${descKey(s)}|TM${s.timer}`;
const mini=s=>({type:s.type,target:s.target,target7E:s.target7E,inD20:s.inD20,state99:s.state99,action2A:s.action2A,b2B:s.b2B,timer:s.timer,attack:s.attack,body:s.body,frameEnd:s.frameEnd,next:s.next,value30:s.value30,enemyX:s.enemyX,enemyY:s.enemyY,targetX:s.targetX,targetY:s.targetY,dx:s.dx,dy:s.dy,absDx:s.absDx,absDy:s.absDy,side:s.side,lane:s.lane});
const DURATION=120000,INTERVAL=20,HMAX=500,start=performance.now();
const prev=new Map(),lastSig=new Map(),pending=[],activeEdges=[];let watchSeq=0,activeSeq=0;
const diag={polls:0,enemySamples:0,coarseEntries:0,descriptorEntries:0,fineEntries:0,activeEdges:0,validTargetActiveEdges:0,censoredSlotGone:0,censoredTypeChange:0};
function addWatch(kind,key,s,t){const w={id:++watchSeq,kind,key,slot:s.slot,type:s.type,at:t,state:mini(s),resolved:false,hit:false,censored:false,censorReason:null,leadMs:null,activeId:null,activeAttack:null,activeTarget:null,targetSame:null,sideSame:null,activeAbsDx:null,activeAbsDy:null};pending.push(w);diag[kind+'Entries']++;}
function censorSlot(slot,reason){for(const w of pending){if(w.resolved||w.slot!==slot)continue;w.resolved=true;w.censored=true;w.censorReason=reason;if(reason==='slotGone')diag.censoredSlotGone++;else if(reason==='typeChange')diag.censoredTypeChange++;}}
function resolveExpiry(t){for(const w of pending){if(w.resolved)continue;if(t-w.at>HMAX){w.resolved=true;w.hit=false;}}}
function recordActive(s,t){const e={id:++activeSeq,rel:t,slot:s.slot,type:s.type,target:s.target,target7E:s.target7E,attack:s.attack,body:s.body,state99:s.state99,action2A:s.action2A,b2B:s.b2B,timer:s.timer,frameEnd:s.frameEnd,next:s.next,value30:s.value30,absDx:s.absDx,absDy:s.absDy,side:s.side,lane:s.lane};activeEdges.push(e);diag.activeEdges++;if(s.target)diag.validTargetActiveEdges++;for(const w of pending){if(w.resolved||w.slot!==s.slot||w.type!==s.type)continue;const lead=t-w.at;if(lead<0||lead>HMAX)continue;w.resolved=true;w.hit=true;w.leadMs=lead;w.activeId=e.id;w.activeAttack=s.attack;w.activeTarget=s.target;w.targetSame=w.state.target7E===s.target7E;w.sideSame=w.state.side===s.side;w.activeAbsDx=s.absDx;w.activeAbsDy=s.absDy;}return e;}
function updateSignatures(s,t){let z=lastSig.get(s.slot);if(!z||z.type!==s.type)z={type:s.type,coarse:null,desc:null,fine:null};if(s.attack!==0){z.coarse=z.desc=z.fine=null;lastSig.set(s.slot,z);return;}const ck=coarseKey(s),dk=descKey(s),fk=fineKey(s);if(ck!==z.coarse){addWatch('coarse',ck,s,t);z.coarse=ck;}if(dk!==z.desc){addWatch('descriptor',dk,s,t);z.desc=dk;}if(fk!==z.fine){addWatch('fine',fk,s,t);z.fine=fk;}lastSig.set(s.slot,z);}
await new Promise(resolve=>{const id=setInterval(()=>{const t=Math.round(performance.now()-start);diag.polls++;for(let i=0;i<SLOTS;i++){const s=snap(i),p=prev.get(i)||null;if(!s){if(p)censorSlot(i,'slotGone');prev.delete(i);lastSig.delete(i);continue;}diag.enemySamples++;if(p&&p.type!==s.type){censorSlot(i,'typeChange');lastSig.delete(i);}if(p&&p.attack===0&&s.attack!==0)recordActive(s,t);updateSignatures(s,t);prev.set(i,s);}resolveExpiry(t);if(t>=DURATION){clearInterval(id);for(const w of pending){if(!w.resolved){if(t-w.at>=HMAX){w.resolved=true;w.hit=false;}else{w.resolved=true;w.censored=true;w.censorReason='captureEnd';}}}resolve();}},INTERVAL);});
const median=a=>{if(!a.length)return null;const b=[...a].sort((x,y)=>x-y),m=Math.floor(b.length/2);return b.length%2?b[m]:Math.round((b[m-1]+b[m])/2);};
const pct=(a,p)=>{if(!a.length)return null;const b=[...a].sort((x,y)=>x-y),i=Math.ceil(p*b.length)-1;return b[Math.max(0,Math.min(b.length-1,i))];};
function summarize(kind){const m=new Map();for(const w of pending){if(w.kind!==kind)continue;let g=m.get(w.key);if(!g){g={kind,signature:w.key,type:w.type,exposures:0,evaluable:0,censored:0,hit500:0,hit250:0,hit100:0,miss500:0,leads:[],targetSame:0,targetTotal:0,sideSame:0,sideTotal:0,entryAbsDx:[],entryAbsDy:[],attackCounts:{}};m.set(w.key,g);}g.exposures++;if(w.censored){g.censored++;continue;}g.evaluable++;if(w.hit){g.hit500++;if(w.leadMs<=250)g.hit250++;if(w.leadMs<=100)g.hit100++;g.leads.push(w.leadMs);if(w.targetSame!=null){g.targetTotal++;if(w.targetSame)g.targetSame++;}if(w.sideSame!=null){g.sideTotal++;if(w.sideSame)g.sideSame++;}if(w.state.absDx!=null)g.entryAbsDx.push(w.state.absDx);if(w.state.absDy!=null)g.entryAbsDy.push(w.state.absDy);g.attackCounts[String(w.activeAttack)]=(g.attackCounts[String(w.activeAttack)]||0)+1;}else g.miss500++;}
const out=[];for(const g of m.values()){g.p500=g.evaluable?+(g.hit500/g.evaluable).toFixed(3):null;g.p250=g.evaluable?+(g.hit250/g.evaluable).toFixed(3):null;g.p100=g.evaluable?+(g.hit100/g.evaluable).toFixed(3):null;g.targetSameRate=g.targetTotal?+(g.targetSame/g.targetTotal).toFixed(3):null;g.sideStableRate=g.sideTotal?+(g.sideSame/g.sideTotal).toFixed(3):null;g.entryAbsDxMedian=median(g.entryAbsDx);g.entryAbsDyMedian=median(g.entryAbsDy);delete g.entryAbsDx;delete g.entryAbsDy;g.leads.sort((a,b)=>a-b);const ac=Object.entries(g.attackCounts).map(([attack,count])=>({attack:+attack,count})).sort((a,b)=>b.count-a.count);g.attackCounts=ac;g.topAttack=ac[0]?.attack??null;g.attackPurity=g.hit500&&ac.length?+(ac[0].count/g.hit500).toFixed(3):null;out.push(g);}out.sort((a,b)=>(b.evaluable-a.evaluable)||(b.p500-a.p500));return out;}
const coarseStats=summarize('coarse'),descriptorStats=summarize('descriptor'),fineStats=summarize('fine');
function candidates(stats,horizon){const pkey='p'+horizon;return stats.filter(g=>g.evaluable>=3&&g[pkey]>=0.8&&g.attackPurity!=null&&g.attackPurity>=0.67).sort((a,b)=>(b[pkey]-a[pkey])||(b.evaluable-a.evaluable)).slice(0,40).map(g=>({kind:g.kind,signature:g.signature,type:g.type,evaluable:g.evaluable,p100:g.p100,p250:g.p250,p500:g.p500,topAttack:g.topAttack,attackPurity:g.attackPurity,targetSameRate:g.targetSameRate,sideStableRate:g.sideStableRate,leads:g.leads.slice(0,30)}));}
const clusterMap=new Map();for(const e of activeEdges){const k=`T${e.type}|A${e.attack}`;let g=clusterMap.get(k);if(!g){g={key:k,type:e.type,attack:e.attack,count:0,absDx:[],absDy:[],left:0,right:0,center:0,up:0,down:0,same:0};clusterMap.set(k,g);}g.count++;if(e.absDx!=null)g.absDx.push(e.absDx);if(e.absDy!=null)g.absDy.push(e.absDy);if(e.side)g[e.side.toLowerCase()]++;if(e.lane)g[e.lane.toLowerCase()]++;}
const attackClusters=[];for(const g of clusterMap.values()){g.absDxMedian=median(g.absDx);g.absDxP90=pct(g.absDx,.9);g.absDxP95=pct(g.absDx,.95);g.absDxMax=g.absDx.length?Math.max(...g.absDx):null;g.absDyMedian=median(g.absDy);g.absDyP90=pct(g.absDy,.9);g.absDyP95=pct(g.absDy,.95);g.absDyMax=g.absDy.length?Math.max(...g.absDy):null;delete g.absDx;delete g.absDy;const mside=Math.max(g.left,g.right,g.center),mlane=Math.max(g.up,g.down,g.same);g.targetSidePurity=g.count?+(mside/g.count).toFixed(3):null;g.lanePurity=g.count?+(mlane/g.count).toFixed(3):null;attackClusters.push(g);}attackClusters.sort((a,b)=>b.count-a.count);
const byType={};for(const e of activeEdges){const k='T'+e.type,b=(byType[k]??={type:e.type,activeEdges:0,attacks:{}});b.activeEdges++;b.attacks[String(e.attack)]=(b.attacks[String(e.attack)]||0)+1;}for(const b of Object.values(byType))b.attacks=Object.entries(b.attacks).map(([attack,count])=>({attack:+attack,count})).sort((a,b)=>b.count-a.count);
const out={version:'wof-future-danger-preactive-signature-v18',readOnly:true,ramWrites:0,gate,gateStrict:Object.values(gate).every(Boolean),durationRequestedMs:DURATION,intervalMs:INTERVAL,maxPredictionHorizonMs:HMAX,model:{goal:'prospectively score pre-active state signatures instead of relying on sparse D0 entry only',exposurePolicy:'create watches on coarse/descriptor/fine signature entry while attack==0; resolve against next +0x70 active edge within 500ms',coarse:'type + inD20 + state99 + action2A + b2B + body',descriptor:'coarse + frameEnd + next + value30',fine:'descriptor + timer',targetPolicy:'live enemy+0x7E authoritative',geometry:'ACTIVE-start type+attack distributions remain empirical geometry, not proven hitboxes'},diagnostics:diag,totals:{watches:pending.length,activeEdges:activeEdges.length,coarseGroups:coarseStats.length,descriptorGroups:descriptorStats.length,fineGroups:fineStats.length},candidateRules:{h100:{coarse:candidates(coarseStats,100),descriptor:candidates(descriptorStats,100),fine:candidates(fineStats,100)},h250:{coarse:candidates(coarseStats,250),descriptor:candidates(descriptorStats,250),fine:candidates(fineStats,250)},h500:{coarse:candidates(coarseStats,500),descriptor:candidates(descriptorStats,500),fine:candidates(fineStats,500)}},coarseStats:coarseStats.slice(0,120),descriptorStats:descriptorStats.slice(0,120),fineStats:fineStats.slice(0,160),attackClusters:attackClusters.slice(0,80),byType,activeEdges:activeEdges.slice(0,400),note:'V18 is a prospective pre-active signature learner. Candidate lists are fresh-room calibration only: promote a rule only after repeated independent-room precision, stable target/side behavior and a repeated resulting attack family. ACTIVE geometry is still not exact hitbox/damage onset.'};
self.__WOF_FUTURE_DANGER_PREACTIVE_SIGNATURE_V18=out;console.log('=== FUTURE DANGER PREACTIVE SIGNATURE V18 JSON ===');console.log(JSON.stringify(out,null,2));return out;
})().catch(e=>{console.error('WOF_FUTURE_DANGER_PREACTIVE_SIGNATURE_V18_ERROR',e);throw e;});