(()=>{
'use strict';
try{self.WOFSTATE72UP?.stop?.();}catch(_){}
const RAW='https://raw.githubusercontent.com/ouyong520/wof-ai-private/main/';
const sleep=ms=>new Promise(r=>setTimeout(r,ms));let stopped=false;
const load=async f=>{const r=await fetch(RAW+f+'?x='+Date.now(),{cache:'no-store'});if(!r.ok)throw new Error('fetch failed '+r.status+' '+f);return (0,eval)(await r.text());};
async function ensure(){
 if(!self.__WOF_ROM_LOC_CACHE){await load('wof_rom_focus_inspect.js');for(let i=0;i<300&&!self.__WOF_ROM_LOC_CACHE;i++)await sleep(50);}
 if(!self.__WOF_DISPATCH_D0_CALLER?.callers?.length){await load('wof_dispatch_d0_caller_trace.js');await WOFD0CALLER.run();}
 if(!self.__WOF_ROM_LOC_CACHE||!self.__WOF_DISPATCH_D0_CALLER?.callers?.length)throw new Error('dispatcher caller state unavailable');
}
function env(){const MOD=_0x515056,C=self.__WOF_ROM_LOC_CACHE,M=MOD.HEAPU8,base=C.base,SW=!!C.swap16,MAX=Math.min(0x100000,M.length-base),DELTA=C.offlineDelta|0;const r8=o=>M[base+(SW?(o^1):o)]>>>0,r16=o=>((r8(o)<<8)|r8(o+1))>>>0,r32=o=>(r8(o)*0x1000000+r8(o+1)*0x10000+r8(o+2)*0x100+r8(o+3))>>>0,s8=v=>v&0x80?v-0x100:v,s16=v=>v&0x8000?v-0x10000:v,h=x=>'0x'+(x>>>0).toString(16).toUpperCase().padStart(6,'0'),off=x=>h((x-DELTA)>>>0);return{MAX,r8,r16,r32,s8,s16,h,off};}
function eaWords(m,r,size){if(m<=4)return 0;if(m===5||m===6)return 1;if(m===7){if(r===0||r===2||r===3)return 1;if(r===1)return 2;if(r===4)return size==='L'?2:1;}return 0;}
function decode(E,p){const w=E.r16(p),g=w>>>12,m=(w>>3)&7,r=w&7;let len=2,kind='OP',target=null,terminal=false,fall=true;
 if(w===0x4E75||w===0x4E73||w===0x4E77){kind='RET';terminal=true;fall=false;}
 else if(w===0x4E72){kind='STOP';len=4;terminal=true;fall=false;}
 else if((w&0xFFC0)===0x4E80){kind='JSR';len=2+eaWords(m,r,'L')*2;if(m===7&&r===0)target=E.s16(E.r16(p+2))>>>0;else if(m===7&&r===1)target=E.r32(p+2);else if(m===7&&r===2)target=(p+2+E.s16(E.r16(p+2)))>>>0;}
 else if((w&0xFFC0)===0x4EC0){kind='JMP';fall=false;len=2+eaWords(m,r,'L')*2;if(m===7&&r===0)target=E.s16(E.r16(p+2))>>>0;else if(m===7&&r===1)target=E.r32(p+2);else if(m===7&&r===2)target=(p+2+E.s16(E.r16(p+2)))>>>0;}
 else if(g===6){const cc=(w>>8)&15,d=w&255;len=d===0?4:2;target=d===0?(p+2+E.s16(E.r16(p+2)))>>>0:(p+2+E.s8(d))>>>0;kind=cc===0?'BRA':cc===1?'BSR':'BCC';if(cc===0)fall=false;}
 else if(g===1||g===2||g===3){const size=g===1?'B':g===2?'L':'W',sm=(w>>3)&7,sr=w&7,dm=(w>>6)&7,dr=(w>>9)&7;len=2+(eaWords(sm,sr,size)+eaWords(dm,dr,size))*2;}
 else if(g===5){const sz=(w>>6)&3;if(sz===3&&m===1){kind='DBCC';len=4;target=(p+2+E.s16(E.r16(p+2)))>>>0;}else len=2+eaWords(m,r,sz===2?'L':sz===1?'W':'B')*2;}
 else if(g===0){if([0x003C,0x007C,0x023C,0x027C,0x0A3C,0x0A7C].includes(w))len=4;else{const op=(w>>8)&15,sz=(w>>6)&3;if([0,2,4,6,10,12].includes(op)&&sz!==3){const s=sz===2?'L':sz===1?'W':'B';len=2+(s==='L'?4:2)+eaWords(m,r,s)*2;}}}
 else if(g===4){if((w&0xFFF8)===0x4E50)len=4;else if((w&0xFB80)===0x4880&&m>=2)len=4+eaWords(m,r,(w&0x40)?'L':'W')*2;else if((w&0xF1C0)===0x41C0)len=2+eaWords(m,r,'L')*2;else len=2+eaWords(m,r,((w>>6)&3)===2?'L':'W')*2;}
 else if(g===8||g===9||g===11||g===12||g===13)len=2+eaWords(m,r,((w>>6)&3)===2?'L':'W')*2;
 else if(g===14&&((w>>6)&3)===3)len=2+eaWords(m,r,'W')*2;
 else if(g===10||g===15){kind='LINE';terminal=true;fall=false;}
 len=Math.max(2,len);if(target!=null&&(target<0||target>=E.MAX))target=null;return{at:p,w,len,next:p+len,kind,target,terminal,fall};}
function graph(E,start,cap=0x1800){const hi=Math.min(E.MAX,start+cap),q=[start&~1],seen=new Set(),calls=[];while(q.length&&seen.size<9000){const p=q.shift();if(p<start||p>=hi||(p&1)||seen.has(p))continue;seen.add(p);const d=decode(E,p);if((d.kind==='JSR'||d.kind==='BSR')&&d.target!=null)calls.push({at:p,target:d.target&~1});if(d.kind==='BRA'){if(d.target!=null&&d.target>=start&&d.target<hi)q.push(d.target&~1);continue;}if(d.kind==='BCC'||d.kind==='DBCC'){if(d.next<hi)q.push(d.next);if(d.target!=null&&d.target>=start&&d.target<hi)q.push(d.target&~1);continue;}if(d.kind==='JMP'){if(d.target!=null&&d.target>=start&&d.target<hi)q.push(d.target&~1);continue;}if(d.terminal)continue;if(d.next<hi)q.push(d.next);}return{seen,calls:[...new Map(calls.map(x=>[x.at+'|'+x.target,x])).values()]};}
function findStart(E,at){for(let p=at&~1;p>=Math.max(0,at-0x500);p-=2){const w=E.r16(p);if((w&0xFFF8)===0x4E50||w===0x48E7)return p;if(w===0x4E75||w===0x4E73||w===0x4E77)return p+2;}return Math.max(0,(at-0x180)&~1);}
function rawEdges(E){const m=new Map(),add=(t,e)=>{t&=~1;if(t>=E.MAX)return;let a=m.get(t);if(!a)m.set(t,a=[]);a.push(e);};for(let p=0;p+6<E.MAX;p+=2){const w=E.r16(p),d=w&255;let t=null;if(w===0x4EB8)t=E.s16(E.r16(p+2))>>>0;else if(w===0x4EB9)t=E.r32(p+2);else if(w===0x4EBA)t=(p+2+E.s16(E.r16(p+2)))>>>0;else if((w&0xFF00)===0x6100)t=d===0?(p+2+E.s16(E.r16(p+2)))>>>0:(p+2+E.s8(d))>>>0;if(t!=null)add(t,{at:p});}return m;}
function moveMeta(E,p){const w=E.r16(p),g=w>>>12;if(![1,2,3].includes(g))return null;const size=g===1?'B':g===2?'L':'W',sm=(w>>3)&7,sr=w&7,dm=(w>>6)&7,dr=(w>>9)&7,sw=eaWords(sm,sr,size),dstExt=p+2+sw*2;let dstDisp=0;if(dm===5)dstDisp=E.s16(E.r16(dstExt));let imm=null;if(sm===7&&sr===4){imm=size==='L'?E.r32(p+2):E.r16(p+2);if(size==='B')imm&=0xff;}return{size,sm,sr,dm,dr,dstDisp,imm};}
function writeEA(E,p){const w=E.r16(p),g=w>>>12,m=(w>>3)&7,r=w&7,mm=moveMeta(E,p);if(mm&&[2,3,4,5].includes(mm.dm))return{kind:'MOVE.'+mm.size,areg:mm.dr,disp:mm.dm===5?mm.dstDisp:0,srcReg:mm.sm===0?'D'+mm.sr:mm.sm===1?'A'+mm.sr:'',imm:mm.imm,width:mm.size==='L'?4:mm.size==='W'?2:1};if(g===5&&((w>>6)&3)!==3&&[2,3,4,5].includes(m)){const q=((w>>9)&7)||8,sz=(w>>6)&3;return{kind:(w&0x0100?'SUBQ.':'ADDQ.')+(sz===2?'L':sz===1?'W':'B'),areg:r,disp:m===5?E.s16(E.r16(p+2)):0,srcReg:'',imm:q,width:sz===2?4:sz===1?2:1};}if(g===4&&(((w&0xff00)===0x4200)||((w&0xff00)===0x4400)||((w&0xff00)===0x4600))&&[2,3,4,5].includes(m)){const sz=(w>>6)&3;return{kind:(w&0xff00)===0x4200?'CLR':(w&0xff00)===0x4400?'NEG':'NOT',areg:r,disp:m===5?E.s16(E.r16(p+2)):0,srcReg:'',imm:(w&0xff00)===0x4200?0:null,width:sz===2?4:sz===1?2:1};}return null;}
function stepAlias(E,p,a){const w=E.r16(p),g=w>>>12,n=a.slice(),mm=moveMeta(E,p);if(mm&&mm.dm===1){n[mm.dr]=mm.sm===1?a[mm.sr]:null;return n;}if((w&0xF1C0)===0x41C0){const dst=(w>>9)&7,sm=(w>>3)&7,sr=w&7;if(sm===2)n[dst]=a[sr];else if(sm===5&&a[sr]!=null)n[dst]=a[sr]+E.s16(E.r16(p+2));else n[dst]=null;return n;}if(g===5&&((w>>6)&3)!==3&&((w>>3)&7)===1){const r=w&7,q=((w>>9)&7)||8;if(a[r]!=null)n[r]=a[r]+((w&0x0100)?-q:q);return n;}if((w&0xF1F8)===0xC148){const x=(w>>9)&7,y=w&7,tmp=n[x];n[x]=a[y];n[y]=tmp;return n;}return n;}
function succ(E,d,hi){const out=[];if(d.kind==='BRA'){if(d.target!=null&&d.target<hi)out.push(d.target&~1);return out;}if(d.kind==='BCC'||d.kind==='DBCC'){if(d.next<hi)out.push(d.next);if(d.target!=null&&d.target<hi)out.push(d.target&~1);return out;}if(d.kind==='JMP'){if(d.target!=null&&d.target<hi)out.push(d.target&~1);return out;}if(d.terminal)return out;if(d.next<hi)out.push(d.next);return out;}
function aliasScan(E,start,FIELD,observed){const hi=Math.min(E.MAX,start+0x1800),hits=[];for(let seed=0;seed<7;seed++){const init=Array(7).fill(null);init[seed]=0;const q=[{p:start&~1,a:init}],seen=new Set();while(q.length&&seen.size<18000){const z=q.shift(),p=z.p;if(p<start||p>=hi||(p&1))continue;const key=p+'|'+z.a.map(v=>v==null?'x':v).join(',');if(seen.has(key))continue;seen.add(key);const d=decode(E,p),wr=writeEA(E,p);if(wr&&z.a[wr.areg]!=null){const eff=z.a[wr.areg]+wr.disp;if(eff<=FIELD&&FIELD<eff+wr.width){const im=typeof wr.imm==='number'?wr.imm:null;hits.push({at:p,seedReg:'A'+seed,baseReg:'A'+wr.areg,eff,kind:wr.kind,srcReg:wr.srcReg,imm:im,matchObserved:im!=null&&observed.has(im)});}}const na=stepAlias(E,p,z.a);for(const s of succ(E,d,hi))q.push({p:s,a:na.slice()});}}return [...new Map(hits.map(x=>[x.at+'|'+x.seedReg+'|'+x.baseReg,x])).values()];}
async function run(){stopped=false;await ensure();const E=env(),D=self.__WOF_DISPATCH_D0_CALLER,FIELD=0x72,edge=rawEdges(E),cache=new Map(),get=a=>{a&=~1;if(!cache.has(a))cache.set(a,graph(E,a));return cache.get(a);};
 const observed=new Set([0]);for(const v of self.__WOF_STATE72?.values||[])if(Number.isFinite(v.stateIndex))observed.add(v.stateIndex);
 const seeds=[...new Set((D.callers||[]).map(x=>parseInt(x.callerRoutine,16)&~1).filter(Number.isFinite))];const upstream=new Map(seeds.map(a=>[a,{depth:0,via:'dispatcher-caller'}])),q=seeds.map(a=>({a,depth:0}));
 while(q.length){const n=q.shift();if(n.depth>=5)continue;for(const e of edge.get(n.a)||[]){const fs=findStart(E,e.at),g=get(fs);if(!g.seen.has(e.at))continue;const dd=decode(E,e.at);if(dd.target==null||((dd.target&~1)!==(n.a&~1)))continue;if(!upstream.has(fs)||upstream.get(fs).depth>n.depth+1){upstream.set(fs,{depth:n.depth+1,via:E.h(e.at)+' -> '+E.h(n.a)});q.push({a:fs,depth:n.depth+1});}}if((upstream.size&31)===0)await sleep(0);}
 const scanSet=new Map(upstream);for(const [a,meta] of [...upstream]){let frontier=[{a,depth:0}];const seen=new Set([a]);while(frontier.length){const n=frontier.shift();if(n.depth>=2)continue;for(const c of get(n.a).calls){const t=c.target&~1;if(seen.has(t)||t===0x25B6||t===0x25C8)continue;seen.add(t);if(!scanSet.has(t))scanSet.set(t,{depth:meta.depth,via:'helper-from '+E.h(a)});frontier.push({a:t,depth:n.depth+1});}}}
 console.log('🧭 WOF TRUE state72 upstream writer scan');console.log('dispatcher callers',seeds.length,'upstream routines',upstream.size,'scan routines incl helpers',scanSet.size,'observed states',[...observed].sort((a,b)=>a-b));
 const rows=[];let i=0;for(const [a,meta] of scanSet){if(stopped)throw new Error('stopped');for(const x of aliasScan(E,a,FIELD,observed)){rows.push({routine:E.h(a),offlineRoutine:E.off(a),upDepth:meta.depth,via:meta.via,at:E.h(x.at),offlineAt:E.off(x.at),seedReg:x.seedReg,baseReg:x.baseReg,kind:x.kind,srcReg:x.srcReg||'',imm:x.imm==null?'':x.imm,matchesObserved:x.matchObserved,score:(x.matchObserved?500:0)+(x.srcReg?100:0)+(meta.depth===0?80:Math.max(0,60-meta.depth*10))});}if((++i&15)===0)await sleep(0);}
 rows.sort((a,b)=>b.score-a.score||a.upDepth-b.upDepth||a.at.localeCompare(b.at));console.log('=== STATE72 UPSTREAM WRITERS ===');console.table(rows.slice(0,100));const obs=rows.filter(x=>x.matchesObserved),top=obs[0]||rows[0]||null;const verdict={dispatcherCallers:seeds.length,upstreamRoutines:upstream.size,scanRoutines:scanSet.size,writerSites:rows.length,observedWriterSites:obs.length,topAt:top?.at||'',topRoutine:top?.routine||'',topUpDepth:top?.upDepth??'',topVia:top?.via||'',topSeedReg:top?.seedReg||'',topBaseReg:top?.baseReg||'',topKind:top?.kind||'',topSrcReg:top?.srcReg||'',topImm:top?.imm??'',topMatchesObserved:top?.matchesObserved??false};console.log('=== STATE72 UPSTREAM VERDICT ===');console.table([verdict]);
 if(obs.length)console.log('🎯 找到上游真实 state72 writer；下一步只追 top writer 的 src/player evidence。');else if(rows.length)console.warn('⚠️ 找到上游 state72 writer，但 immediate 未命中当前观测状态；下一步追 top srcReg。');else console.warn('⚠️ 上游 direct-caller + helper 图仍无 state72 writer；下一步转动态 state-change/PC hook 或 indexed/MOVEM 写法。');self.__WOF_STATE72_UPSTREAM={version:'state72-upstream-writer-v1',verdict,rows,upstream:[...upstream].map(([a,m])=>({routine:E.h(a),...m}))};return self.__WOF_STATE72_UPSTREAM;}
self.WOFSTATE72UP={run,stop(){stopped=true;}};console.log('✅ WOF state72 upstream writer scanner loaded');console.log('执行 await WOFSTATE72UP.run()');
})();