(async()=>{
'use strict';
const COPY_ID='WOF-022';
const PROJECT='WOF-AI-PRIVATE';
const VERSION='wof-future-danger-map-production-shadow-v22';
const MARKER='=== WOF FUTURE DANGER MAP PRODUCTION SHADOW V22 JSON ===';
console.log(`[${COPY_ID}] ${PROJECT} ${VERSION}`);
const good=v=>!!(v&&v.HEAPU8 instanceof Uint8Array&&v.HEAPU32 instanceof Uint32Array&&v.HEAPU8.buffer===v.HEAPU32.buffer);
if(!good(self._0x515056)){
  const until=performance.now()+8000;let hit=null;
  while(performance.now()<until&&!hit){
    for(const k of Object.getOwnPropertyNames(self)){let v;try{v=self[k]}catch(_){continue}if(good(v)){hit={k,v};break}}
    if(!hit)await new Promise(r=>setTimeout(r,50));
  }
  if(!hit)throw new Error(`[${COPY_ID}] WOF V22 WASM module not found. Select the live gstyphoon.js Worker.`);
  self._0x515056=hit.v;self.__WOF_MODULE_GLOBAL_KEY=hit.k;console.log(`[${COPY_ID}] ✅ module ${hit.k} -> _0x515056`);
}
const M=self._0x515056.HEAPU8,R=self._0x515056.HEAPU32?.[0x2e39e4>>>2]>>>0;if(!R)throw new Error(`[${COPY_ID}] CPS RAM base missing`);
const B=a=>M[R+((((a-0xFF0000)&0xffff)^1))]>>>0;
const U16=a=>((B(a)<<8)|B(a+1))>>>0;
const U32=a=>(B(a)*0x1000000+B(a+1)*0x10000+B(a+2)*0x100+B(a+3))>>>0;
const S32=a=>{const v=U32(a);return v>=0x80000000?v-0x100000000:v;};
const X=a=>Math.round(S32(a+4)/65536),Y=a=>Math.round(S32(a+8)/65536);
const ENEMY=0xFFC0BC,STRIDE=0xE0,SLOTS=20,PLAYERS={0:'P1',4:'P2',8:'P3'},PBASE={0:0xFFBE1C,4:0xFFBEFC,8:0xFFBFDC};
const side=dx=>dx<-4?'LEFT':dx>4?'RIGHT':'CENTER',lane=dy=>dy<-4?'UP':dy>4?'DOWN':'SAME';
function snap(i){const a=ENEMY+i*STRIDE,type=U16(a+0x20);if(type>=47)return null;const frameEnd=U32(a+0x12),next=U32(a+0x2C);if(!frameEnd&&!next)return null;const t7=U16(a+0x7E),pb=PBASE[t7],ex=X(a),ey=Y(a),tx=pb?X(pb):null,ty=pb?Y(pb):null,dx=tx==null?null:tx-ex,dy=ty==null?null:ty-ey;return{slot:i,type,target7E:t7,target:PLAYERS[t7]||null,state99:B(a+0x99),action2A:B(a+0x2A),b2B:B(a+0x2B),body:U16(a+0x6E),attack:U16(a+0x70),frameEnd,next,value30:U32(a+0x30),enemyX:ex,enemyY:ey,targetX:tx,targetY:ty,dx,dy,absDx:dx==null?null:Math.abs(dx),absDy:dy==null?null:Math.abs(dy),side:dx==null?null:side(dx),lane:dy==null?null:lane(dy)};}
const FAST=new Set(['0/4/2','0/4/4','2/4/2','2/4/4','2/0/0','4/4/2','4/4/4','4/0/0']);
const RULES=[
{id:'T16_FAST_100',type:16,horizon:100,level:'IMMINENT',status:'production-shadow',envelope:{reachX:320,reachY:25,basis:'V21 signal/ACTIVE empirical P90; not hitbox'},match:s=>s.type===16&&s.attack===0&&s.body===4856&&s.frameEnd===0x851ae&&s.next===0x84c44&&s.value30===0xffff&&FAST.has(`${s.state99}/${s.action2A}/${s.b2B}`)},
{id:'T16_MID_250',type:16,horizon:250,level:'IMMINENT',status:'provisional-high',envelope:{reachX:320,reachY:15,basis:'V21 empirical P90; not hitbox'},match:s=>s.type===16&&s.attack===0&&s.body===4856&&s.state99===2&&s.action2A===4&&s.b2B===2&&s.frameEnd===0x85240&&s.next===0x84c3a&&s.value30===0x100000},
{id:'T30_FAST_100',type:30,horizon:100,level:'IMMINENT',status:'provisional-high',envelope:{reachX:300,reachY:12,basis:'V20/V21 empirical branch signal/ACTIVE range; not hitbox'},match:s=>s.type===30&&s.attack===0&&s.body===1800&&s.state99===0&&s.action2A===0&&s.b2B===0}
];
const DURATION=120000,INTERVAL=20,start=performance.now(),prev=new Map(),cycle=new Map(),armed=new Map(),watches=[],events=[],attackEdges=[];let wid=0;
const diag={polls:0,enemySamples:0,activeEdges:0,validTargetActiveEdges:0,signals:0,retargets:0,expired:0,copyId:COPY_ID};
const rawMatchSamples={},transitionEntries={},typeSamples={};for(const r of RULES){rawMatchSamples[r.id]=0;transitionEntries[r.id]=0;}
function armKey(slot,id){return `${slot}|${id}`;}
function publish(now){const entries=[];for(const w of watches){if(w.resolved)continue;const s=prev.get(w.slot);if(!s||s.type!==w.type)continue;const remaining=Math.max(0,w.horizon-(now-w.at)),inside=s.absDx!=null&&s.absDy!=null&&s.absDx<=w.envelope.reachX&&s.absDy<=w.envelope.reachY;entries.push({copyId:COPY_ID,rule:w.rule,status:w.status,level:w.level,slot:w.slot,type:w.type,target:s.target,target7E:s.target7E,horizonMs:w.horizon,remainingMs:remaining,enemyX:s.enemyX,enemyY:s.enemyY,targetX:s.targetX,targetY:s.targetY,dx:s.dx,dy:s.dy,absDx:s.absDx,absDy:s.absDy,side:s.side,lane:s.lane,envelope:w.envelope,insideEmpiricalEnvelope:inside});}
const state={copyId:COPY_ID,project:PROJECT,version:VERSION,atMs:now,entries};self.__WOF_FUTURE_DANGER_MAP_STATE=state;self.__WOF_FUTURE_DANGER_MAP_STATE_V22=state;self.__WOF_FUTURE_DANGER_LIVE_STATE=state;}
function arm(r,s,t){const c=cycle.get(s.slot)||0,k=armKey(s.slot,r.id);if(armed.get(k)===c)return;armed.set(k,c);const w={id:++wid,rule:r.id,status:r.status,level:r.level,type:s.type,slot:s.slot,cycle:c,horizon:r.horizon,envelope:r.envelope,at:t,entryTarget7E:s.target7E,entryTarget:s.target,entrySide:s.side,entryLane:s.lane,entryAbsDx:s.absDx,entryAbsDy:s.absDy,resolved:false,hit:false,censored:false,censorReason:null,leadMs:null,activeAttack:null,targetSame:null,sideSame:null,retargets:[]};watches.push(w);diag.signals++;events.push({kind:'SIGNAL',rel:t,rule:r.id,status:r.status,slot:s.slot,type:s.type,target:s.target});console.log(`[WOF V22][${COPY_ID}] ${r.status} SIGNAL ${r.id} slot${s.slot}${s.target?' -> '+s.target:''} <=${r.horizon}ms`);}
function resolveActive(s,t){diag.activeEdges++;if(s.target)diag.validTargetActiveEdges++;attackEdges.push({rel:t,slot:s.slot,type:s.type,attack:s.attack,target:s.target,absDx:s.absDx,absDy:s.absDy,side:s.side,lane:s.lane});for(const w of watches){if(w.resolved||w.slot!==s.slot||w.type!==s.type)continue;const lead=t-w.at;if(lead<0||lead>w.horizon)continue;w.resolved=true;w.hit=true;w.leadMs=lead;w.activeAttack=s.attack;w.targetSame=w.entryTarget7E===s.target7E;w.sideSame=w.entrySide===s.side;w.activeTarget=s.target;w.activeAbsDx=s.absDx;w.activeAbsDy=s.absDy;w.insideEnvelope=s.absDx!=null&&s.absDy!=null&&s.absDx<=w.envelope.reachX&&s.absDy<=w.envelope.reachY;events.push({kind:'HIT',rel:t,rule:w.rule,slot:s.slot,type:s.type,leadMs:lead,attack:s.attack,target:s.target,insideEnvelope:w.insideEnvelope});console.log(`[WOF V22][${COPY_ID}] HIT ${w.rule} slot${s.slot} ${lead}ms attack=${s.attack}`);}cycle.set(s.slot,(cycle.get(s.slot)||0)+1);}
function expire(t){for(const w of watches){if(w.resolved)continue;if(t-w.at>w.horizon){w.resolved=true;w.hit=false;diag.expired++;events.push({kind:'MISS',rel:t,rule:w.rule,slot:w.slot,type:w.type,leadMs:t-w.at});console.log(`[WOF V22][${COPY_ID}] MISS ${w.rule} slot${w.slot}`);}}}
await new Promise(resolve=>{const id=setInterval(()=>{const t=Math.round(performance.now()-start);diag.polls++;for(let i=0;i<SLOTS;i++){const s=snap(i),p=prev.get(i)||null;if(!s){if(p){for(const w of watches)if(!w.resolved&&w.slot===i){w.resolved=true;w.censored=true;w.censorReason='slotGone';}}prev.delete(i);continue;}diag.enemySamples++;typeSamples['T'+s.type]=(typeSamples['T'+s.type]||0)+1;if(p&&p.type!==s.type){for(const w of watches)if(!w.resolved&&w.slot===i){w.resolved=true;w.censored=true;w.censorReason='typeChange';}cycle.set(i,(cycle.get(i)||0)+1);}if(p&&p.attack===0&&s.attack!==0)resolveActive(s,t);for(const r of RULES){if(r.type!==s.type)continue;const m=r.match(s),pm=!!(p&&p.type===s.type&&r.match(p));if(m)rawMatchSamples[r.id]++;if(m&&!pm){transitionEntries[r.id]++;arm(r,s,t);}}for(const w of watches){if(w.resolved||w.slot!==i||w.type!==s.type)continue;if(w.entryTarget7E!==s.target7E){const last=w.retargets.at(-1)?.to7E??w.entryTarget7E;if(last!==s.target7E){w.retargets.push({rel:t,from7E:last,to7E:s.target7E,from:PLAYERS[last]||null,to:s.target});diag.retargets++;}}}prev.set(i,s);}expire(t);publish(t);if(t>=DURATION){clearInterval(id);for(const w of watches)if(!w.resolved){w.resolved=true;w.censored=true;w.censorReason='captureEnd';}publish(t);resolve();}},INTERVAL);});
const median=a=>{if(!a.length)return null;const b=[...a].sort((x,y)=>x-y),m=Math.floor(b.length/2);return b.length%2?b[m]:Math.round((b[m-1]+b[m])/2);};
const pct=(a,p)=>{if(!a.length)return null;const b=[...a].sort((x,y)=>x-y),i=Math.ceil(p*b.length)-1;return b[Math.max(0,Math.min(b.length-1,i))];};
const ruleStats={};for(const r of RULES)ruleStats[r.id]={rule:r.id,status:r.status,horizonMs:r.horizon,signals:0,evaluable:0,hit:0,miss:0,censored:0,precision:null,leads:[],targetSame:0,targetTotal:0,sideSame:0,sideTotal:0,envelopeHit:0,envelopeTotal:0,attackCounts:{},retargets:0,entryAbsDx:[],entryAbsDy:[],activeAbsDx:[],activeAbsDy:[]};
for(const w of watches){const q=ruleStats[w.rule];q.signals++;q.retargets+=w.retargets.length;if(w.censored){q.censored++;continue;}q.evaluable++;if(w.hit){q.hit++;q.leads.push(w.leadMs);q.attackCounts[String(w.activeAttack)]=(q.attackCounts[String(w.activeAttack)]||0)+1;if(w.targetSame!=null){q.targetTotal++;if(w.targetSame)q.targetSame++;}if(w.sideSame!=null){q.sideTotal++;if(w.sideSame)q.sideSame++;}q.envelopeTotal++;if(w.insideEnvelope)q.envelopeHit++;if(w.entryAbsDx!=null)q.entryAbsDx.push(w.entryAbsDx);if(w.entryAbsDy!=null)q.entryAbsDy.push(w.entryAbsDy);if(w.activeAbsDx!=null)q.activeAbsDx.push(w.activeAbsDx);if(w.activeAbsDy!=null)q.activeAbsDy.push(w.activeAbsDy);}else q.miss++;}
for(const q of Object.values(ruleStats)){q.precision=q.evaluable?+(q.hit/q.evaluable).toFixed(3):null;q.targetSameRate=q.targetTotal?+(q.targetSame/q.targetTotal).toFixed(3):null;q.sideStableRate=q.sideTotal?+(q.sideSame/q.sideTotal).toFixed(3):null;q.envelopeCoverage=q.envelopeTotal?+(q.envelopeHit/q.envelopeTotal).toFixed(3):null;q.attackCounts=Object.entries(q.attackCounts).map(([attack,count])=>({attack:+attack,count})).sort((a,b)=>b.count-a.count);q.leads.sort((a,b)=>a-b);q.entryAbsDxMedian=median(q.entryAbsDx);q.entryAbsDxP90=pct(q.entryAbsDx,.9);q.entryAbsDyMedian=median(q.entryAbsDy);q.entryAbsDyP90=pct(q.entryAbsDy,.9);q.activeAbsDxMedian=median(q.activeAbsDx);q.activeAbsDxP90=pct(q.activeAbsDx,.9);q.activeAbsDyMedian=median(q.activeAbsDy);q.activeAbsDyP90=pct(q.activeAbsDy,.9);delete q.entryAbsDx;delete q.entryAbsDy;delete q.activeAbsDx;delete q.activeAbsDy;}
const split={};for(const e of attackEdges){const k=`T${e.type}|A${e.attack}`;let g=split[k];if(!g)g=split[k]={key:k,type:e.type,attack:e.attack,count:0,absDx:[],absDy:[]};g.count++;if(e.absDx!=null)g.absDx.push(e.absDx);if(e.absDy!=null)g.absDy.push(e.absDy);}for(const g of Object.values(split)){g.absDxMedian=median(g.absDx);g.absDxP90=pct(g.absDx,.9);g.absDxP95=pct(g.absDx,.95);g.absDyMedian=median(g.absDy);g.absDyP90=pct(g.absDy,.9);g.absDyP95=pct(g.absDy,.95);delete g.absDx;delete g.absDy;}
const out={copyId:COPY_ID,project:PROJECT,version:VERSION,expectedMarker:MARKER,readOnly:true,ramWrites:0,durationRequestedMs:DURATION,intervalMs:INTERVAL,model:{timingPromotion:'T16_FAST_100 production-shadow timing only; attack identity is not hard-coded because V21 saw 61/63 attack6432 plus one4832 and one4840',t16Mid:'provisional-high after V20+V21 perfect fresh samples but fewer independent rooms',t30Fast:'provisional-high; V20 2/2 and V21 6/6 <=100ms',targetPolicy:'live enemy+0x7E authoritative including pending retargets',geometry:'empirical envelopes and ACTIVE-start clusters only; not exact hitboxes'},diagnostics:{...diag,typeSamples,rawMatchSamples,transitionEntries},ruleStats,attackClusters:Object.values(split).sort((a,b)=>b.count-a.count),watches,events:events.slice(-300),note:'Use copyId+project+version+marker to reject wrong-paste results before analysis. Promote Safe Path only from high-precision timing plus stable live target/side; do not treat empirical envelopes as proven hitboxes.'};self.__WOF_FUTURE_DANGER_MAP_PRODUCTION_SHADOW_V22=out;console.log(MARKER);console.log(JSON.stringify(out,null,2));return out;
})().catch(e=>{console.error('[WOF-022] WOF_V22_ERROR',e);throw e;});