(async()=>{
'use strict';
const DB='wof-focus-multiroom-v1',STORE='sessions',MAX_AGE=12*60*60*1000;
const KNOWN={0x4:'X',0x6:'X.low',0x8:'Y',0xA:'Y.low',0x20:'type',0x28:'state',0x2A:'state',0x70:'attack',0x82:'HP/flags',0x84:'HP-near'};
function openDb(){return new Promise((res,rej)=>{const q=indexedDB.open(DB,1);q.onsuccess=()=>res(q.result);q.onerror=()=>rej(q.error);});}
function getAll(db){return new Promise((res,rej)=>{const q=db.transaction(STORE,'readonly').objectStore(STORE).getAll();q.onsuccess=()=>res(q.result||[]);q.onerror=()=>rej(q.error);});}
const db=await openDb(),now=Date.now(),all=(await getAll(db)).filter(r=>(r.startedAt||0)>=now-MAX_AGE);db.close();if(!all.length){console.warn('没有最近12小时 Focus multiroom 数据');return null;}
const getSnap=r=>r.final||r.latestSnapshot||null,versions=['focus-multiroom-v3','focus-multiroom-v2','focus-multiroom-v1'];let snapshotVersion=null,sessions=[];for(const v of versions){const a=all.filter(r=>getSnap(r)?.version===v);if(a.length){snapshotVersion=v;sessions=a;break;}}if(!sessions.length){console.warn('找到session但没有可恢复焦点快照');return null;}
const agg=Array.from({length:0xE0/2},(_,i)=>({offset:i*2,total:0,targets:[0,0,0],exact:0,wrongPlayer:0,values:new Map(),switchN:0,switchChanged:0,switchAfter:new Map()}));
let strongLabels=0,playerCountHist=[0,0,0,0],complete=0,switchCount=0,stableCommits=0,rejectedJitter=0;
for(const r of sessions){if(r.status==='complete')complete++;const f=getSnap(r);strongLabels+=+f.strongLabels||0;stableCommits+=+f.stableCommits||0;rejectedJitter+=+f.rejectedJitter||0;for(let i=0;i<4;i++)playerCountHist[i]+=+(f.playerCountHist?.[i]||0);for(const w of f.words||[]){const a=agg[w.offset>>1];a.total+=+w.total||0;a.exact+=+w.exact||0;a.wrongPlayer+=+w.wrongPlayer||0;for(let i=0;i<3;i++)a.targets[i]+=+(w.targets?.[i]||0);for(const x of w.values||[]){let c=a.values.get(x.v);if(!c){c=[0,0,0];a.values.set(x.v,c);}for(let i=0;i<3;i++)c[i]+=+(x.c?.[i]||0);}}for(const sw of f.switches||[]){if(!Array.isArray(sw.beforeWords)||!Array.isArray(sw.afterWords))continue;switchCount++;const ti={P1:0,P2:1,P3:2}[sw.to];if(ti==null)continue;for(let i=0;i<agg.length;i++){const a=agg[i],bv=sw.beforeWords[i],av=sw.afterWords[i];if(bv==null||av==null)continue;a.switchN++;if(bv!==av)a.switchChanged++;let c=a.switchAfter.get(av);if(!c){c=[0,0,0];a.switchAfter.set(av,c);}c[ti]++;}}}
function purityOf(map,total,minN=1){let good=0,rows=[];for(const [v,c] of map){const n=c[0]+c[1]+c[2];if(!n)continue;let bi=0;if(c[1]>c[bi])bi=1;if(c[2]>c[bi])bi=2;good+=c[bi];if(n>=minN)rows.push({v:'0x'+(+v).toString(16).toUpperCase().padStart(4,'0'),target:['P1','P2','P3'][bi],share:+(c[bi]/n).toFixed(3),n,c});}rows.sort((a,b)=>b.n-a.n);return{purity:total?good/total:0,rows};}
function metric(a){if(!a.total)return null;const mp=purityOf(a.values,a.total,5),exact=a.exact/a.total,wrong=a.wrongPlayer/a.total,coverage=a.targets.filter(x=>x>=10).length,chg=a.switchN?a.switchChanged/a.switchN:0,sp=purityOf(a.switchAfter,a.switchN,2),sw=chg*sp.purity,known=KNOWN[a.offset]||null;let score=exact*6-wrong*7+sw*6+(coverage===3?.8:coverage===2?.4:0)+Math.max(0,mp.purity-.70);if(known)score-=2.5;return{offset:'0x'+a.offset.toString(16).toUpperCase(),knownField:known,total:a.total,targets:a.targets,exact:+exact.toFixed(4),wrongPlayer:+wrong.toFixed(4),purity:+mp.purity.toFixed(4),coverage,switchN:a.switchN,switchChangeRate:+chg.toFixed(4),switchPurity:+sp.purity.toFixed(4),switchEvidence:+sw.toFixed(4),score:+score.toFixed(3),map:mp.rows.slice(0,10),switchMap:sp.rows.slice(0,10)};}
const candidates=agg.map(metric).filter(Boolean).sort((a,b)=>b.score-a.score||b.switchEvidence-a.switchEvidence||b.total-a.total);
console.table(candidates.slice(0,30).map(x=>({offset:x.offset,known:x.knownField||'',total:x.total,P1:x.targets[0],P2:x.targets[1],P3:x.targets[2],exact:x.exact,wrong:x.wrongPlayer,purity:x.purity,switchN:x.switchN,chg:x.switchChangeRate,swPur:x.switchPurity,swEv:x.switchEvidence,score:x.score,map:x.map.slice(0,3).map(m=>m.v+'→'+m.target+' '+m.share).join(' | '),switchMap:x.switchMap.slice(0,3).map(m=>m.v+'→'+m.target+' '+m.share).join(' | ')})));
const bundle={schema:'wof-focus-multiroom-export-v3',exportedAt:now,snapshotVersion,sessionCount:all.length,usableSessionCount:sessions.length,ignoredOtherVersions:all.length-sessions.length,completeCount:complete,strongLabels,stableCommits,rejectedJitter,playerCountHist,switchCount,candidates,sessions};
const text=JSON.stringify(bundle,null,2),name='wof_focus_multiroom_v3_'+new Date().toISOString().replace(/[:.]/g,'-')+'.json',blob=new Blob([text],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.style.display='none';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);
console.log('✅ Focus multiroom v3 已下载',name,'snapshot',snapshotVersion,'usable',sessions.length,'labels',strongLabels,'stableSwitches',switchCount,'jitterRejected',rejectedJitter);return bundle;
})().catch(e=>console.error('❌ Focus multiroom v3 export failed',e));