(async()=>{
'use strict';
const RAW='https://raw.githubusercontent.com/ouyong520/wof-ai-private/main/';
const load=async f=>{const r=await fetch(RAW+f+'?x='+Date.now(),{cache:'no-store'});if(!r.ok)throw new Error('fetch failed '+r.status+' '+f);return(0,eval)(await r.text());};
async function ensureWasmModule(){const good=v=>!!(v&&v.HEAPU8 instanceof Uint8Array&&v.HEAPU32 instanceof Uint32Array&&v.HEAPU8.buffer===v.HEAPU32.buffer);if(good(self._0x515056))return self._0x515056;const until=performance.now()+8000;while(performance.now()<until){for(const k of Object.getOwnPropertyNames(self)){let v;try{v=self[k]}catch(_){continue}if(good(v)){self._0x515056=v;self.__WOF_MODULE_GLOBAL_KEY=k;return v;}}await new Promise(r=>setTimeout(r,50));}throw new Error('WOF WASM module not found; select live gstyphoon.js Worker.');}
await ensureWasmModule();if(!self.__WOF_DISPATCH_INCOMING){await load('wof_dispatch_incoming_edges.js');await WOFDISPIN.run();}if(!self.__WOF_ROM_LOC_CACHE)throw new Error('ROM cache missing after resume');
const current={
 version:'wof-resume-dispatch-selector-v36',copyIdPolicy:'Reject returned data unless copyId/project/version/marker match the expected run.',selectorSolved:true,selectorField:'enemy+0x7E authoritative target;0/4/8=P1/P2/P3',selectedPointerCache:'enemy+0x6A supporting only when BE1C/BEFC/BFDC',activeAttackField:'enemy+0x70 U16 0->nonzero ACTIVE-start convention, not exact damage/hitbox onset',xyFields:'object+4/+8 confirmed X/Y 16.16; Z unconfirmed',retargetPolicy:'Always use live enemy+0x7E',
 v21Result:'T16_FAST_100 63/63 <=100ms; target/side63/63; attack6432 61/63 plus4832/4840. T16_MID_250 14/14. T30_FAST_100 6/6.',
 v22Result:'T16_FAST 63/68 strict<=100; MID17/20<=250; T30 0/1<=100. Several misses only barely exceeded deadlines: FAST101/105 etc, MID259, T30119.',
 v23Result:'59 signals,58 on-time,1 late,0 hard misses. T16_FAST 46/47 strict<=100, one late103ms(+3), tail47/47; MID10/10<=250; T30 2/2<=100. Only FAST late tuple S4/A0/B0.',
 v24Result:'Correct WOF-024 at10ms polling. Room contained no T16, so it does not resolve T16 jitter yet. T30_FAST_100 had5 independent transition signals and5/5 strict hits at9.2,12.5,20.4,20.9,30.7ms; all attack2536, targetSame5/5, sideStable5/5, no jitter-band/late/hard miss. T30 fresh strict evidence is now strong across V20,V21,V23,V24; keep production-shadow candidate because V22 had one119ms unresolved-at-deadline observation.',
 productionCorrection:'T16_FAST remains production-shadow timing under jitter review, not production-final. T16_MID provisional-high. T30_FAST upgraded to production-shadow candidate but not final because one V22 borderline observation remains unexplained. Attack identities are never hard-coded globally.',
 v25Plan:'Use10ms polling but focus only T16 FAST/MID. Add a30s coverage gate: if no T16 appears, stop early and report NO_T16_IN_FIRST_30S so the user can change room without wasting120s. If T16 appears, continue to120s and classify strict/jitter(+15)/realLate/hardMiss with tuple split.',
 nextScript:'wof_future_danger_t16_coverage_jitter_validator_v25.js',nextCopyId:'WOF-025',nextMarker:'=== WOF FUTURE DANGER T16 COVERAGE JITTER VALIDATOR V25 JSON ===',
 exclusions:'Do not restart selector/identity/pointer proofs, Focus Multiroom,44-edge scan,0x0080F2,0x11C26, universal timer/next1 assumptions, exact-start-timer gating, T30 type-wide warning, or call empirical geometry exact hitboxes.'
};self.__WOF_RESUME_FRONTIER=current;console.log('=== CURRENT SELECTOR FRONTIER ===');console.table([current]);console.log('NEXT:',current.nextCopyId,current.nextScript);return current;
})().catch(e=>{console.error('WOF_RESUME_ERROR',e);throw e;});