(()=>{
'use strict';
try{self.WOFSTATE72PTR?.stop?.();}catch(_){}
const RAW='https://raw.githubusercontent.com/ouyong520/wof-ai-private/main/';
const sleep=ms=>new Promise(r=>setTimeout(r,ms));let stopped=false;
const load=async f=>{const r=await fetch(RAW+f+'?x='+Date.now(),{cache:'no-store'});if(!r.ok)throw new Error('fetch failed '+r.status+' '+f);return (0,eval)(await r.text());};
async function ensure(){if(!self.__WOF_ROM_LOC_CACHE){await load('wof_rom_focus_inspect.js');for(let i=0;i<300&&!self.__WOF_ROM_LOC_CACHE;i++)await sleep(50);}if(!self.__WOF_ROM_LOC_CACHE)throw new Error('ROM cache unavailable');}
function env(){const MOD=_0x515056,C=self.__WOF_ROM_LOC_CACHE,M=MOD.HEAPU8,base=C.base,SW=!!C.swap16,MAX=Math.min(0x100000,M.length-base),DELTA=C.offlineDelta|0;const r8=o=>M[base+(SW?(o^1):o)]>>>0,r16=o=>((r8(o)<<8)|r8(o+1))>>>0,r32=o=>(r8(o)*0x1000000+r8(o+1)*0x10000+r8(o+2)*0x100+r8(o+3))>>>0,s8=v=>v&0x80?v-0x100:v,s16=v=>v&0x8000?v-0x10000:v,h=x=>'0x'+(x>>>0).toString(16).toUpperCase().padStart(6,'0'),off=x=>h((x-DELTA)>>>0),hw=x=>'0x'+(x&0xffff).toString(16).toUpperCase().padStart(4,'0');return{MAX,r8,r16,r32,s8,s16,h,off,hw};}
function eaWords(m,r,size){if(m<=4)return 0;if(m===5||m===6)return 1;if(m===7){if(r===0||r===2||r===3)return 1;if(r===1)return 2;if(r===4)return size==='L'?2:1;}return 0;}
function decode(E,p){const w=E.r16(p),g=w>>>12,m=(w>>3)&7,r=w&7;let len=2,kind='OP',target=null,terminal=false,fall=true;
 if(w===0x4E75||w===0x4E73||w===0x4E77){kind='RET';terminal=true;fall=false;}
 else if(w===0x4E72){kind='STOP';len=4;terminal=true;fall=false;}
 else if((w&0xFFC0)===0x4E80){kind='JSR';len=2+eaWords(m,r,'L')*2;if(m===7&&r===0)target=E.s16(E.r16(p+2))>>>0;else if(m===7&&r===1)target=E.r32(p+2);else if(m===7&&r===2)target=(p+2+E.s16(E.r16(p+2)))>>>0;}
 else if((w&0xFFC0)===0x4EC0){kind='JMP';fall=false;len=2+eaWords(m,r,'L')*2;if(m===7&&r===0)target=E.s16(E.r16(p+2))>>>0;else if(m===7&&r===1)target=E.r32(p+2);else if(m===7&&r===2)target=(p+2+E.s16(E.r16(p+2)))>>>0;}
 else if(g===6){const cc=(w>>8)&15,d=w&255;len=d===0?4:2;target=d===0?(p+2+E.s16(E.r16(p+2)))>>>0:(p+2+E.s8(d))>>>0;kind=cc===0?'BRA':cc===1?'BSR':'BCC';if(cc===0)fall=false;}
 else if(g===1||g===2||g===3){const size=g===1?'B':g===2?'L':'W',sm=(w>>3)&7,sr=w&7,dm=(w>>6)&7,dr=(w>>9)&7;len=2+(eaWords(sm,sr,size)+eaWords(dm,dr,size))*2;}
 else if(g===5){const sz=(w>>6)&3;if(sz===3&&m===1){kind='DBCC';len=4;target=(p+2+E.s16(E.r16(p+2)))>>>0;}else len=2+eaWords(m,r,sz===2?'L':sz===1?'W':'B')*2;}
 else if(g===0){if([0x003C,0x007C,0x023C,0x027C,0x0A3C,0x0A7C].includes(w))len=4;else{const op=(w>>8)&15,sz=(w>>6)&3;if([0,2,4,6,10,12].includes(op)&&sz!==3){const s=sz===2?'L':sz===1?'W':'B';len=2+(s==='L'?4:2)+eaWords(m,r,s)*2;}}}
 else if(g===4){if((w&0xFFF8)===0x4E50)len=4;else if((w&0xFB80)===0x4880&&m>=2)len=4+eaWords(m,r,(w&0x40)?'L':'W')*2;else if((w&0xF1C0)===0x41C0)len=2+eaWords(m,r,'L')*2;else if((w&0xFFC0)===0x4840&&m!==0)len=2+eaWords(m,r,'L')*2;else len=2+eaWords(m,r,((w>>6)&3)===2?'L':'W')*2;}
 else if(g===8||g===9||g===11||g===12||g===13)len=2+eaWords(m,r,((w>>6)&3)===2?'L':'W')*2;
 else if(g===14&&((w>>6)&3)===3)len=2+eaWords(m,r,'W')*2;
 else if(g===10||g===15){kind='LINE';terminal=true;fall=false;}
 len=Math.max(2,len);if(target!=null&&(target<0||target>=E.MAX))target=null;return{at:p,w,len,next:p+len,kind,target,terminal,fall,m,r};}
function findStart(E,at){for(let p=at&~1;p>=Math.max(0,at-0x500);p-=2){const w=E.r16(p);if((w&0xFFF8)===0x4E50||w===0x48E7)return p;if(w===0x4E75||w===0x4E73||w===0x4E77)return p+2;}return Math.max(0,(at-0x180)&~1);}
function graph(E,start,cap=0x1800){const hi=Math.min(E.MAX,start+cap),q=[start&~1],seen=new Set(),dec=new Map();while(q.length&&seen.size<10000){const p=q.shift();if(p<start||p>=hi||(p&1)||seen.has(p))continue;seen.add(p);const d=decode(E,p);dec.set(p,d);if(d.kind==='BRA'){if(d.target!=null&&d.target>=start&&d.target<hi)q.push(d.target&~1);continue;}if(d.kind==='BCC'||d.kind==='DBCC'){if(d.next<hi)q.push(d.next);if(d.target!=null&&d.target>=start&&d.target<hi)q.push(d.target&~1);continue;}if(d.kind==='JMP'){if(d.target!=null&&d.target>=start&&d.target<hi)q.push(d.target&~1);continue;}if(d.terminal)continue;if(d.next<hi)q.push(d.next);}return{seen,dec};}
function ptrPrep(E,p){const w=E.r16(p),m=(w>>3)&7,r=w&7;
 if((w&0xF1C0)===0x41C0&&m===5&&E.r16(p+2)===0x0072)return{kind:'LEA',srcReg:'A'+r,dstReg:'A'+((w>>9)&7),len:4};
 if((w&0xFFC0)===0x4840&&m===5&&E.r16(p+2)===0x0072)return{kind:'PEA',srcReg:'A'+r,dstReg:'SP',len:4};
 return null;}
function helperWrites(E,start,areg){const g=graph(E,start,0x1000),rows=[];for(const p of g.seen){const w=E.r16(p),gr=w>>>12;if(gr!==1&&gr!==2&&gr!==3)continue;const size=gr===1?'B':gr===2?'L':'W',sm=(w>>3)&7,sr=w&7,dm=(w>>6)&7,dr=(w>>9)&7,sw=eaWords(sm,sr,size);if(dr!==areg||![2,3,4,5].includes(dm))continue;const disp=dm===5?E.s16(E.r16(p+2+sw*2)):0;if(disp!==0)continue;let imm=null;if(sm===7&&sr===4){imm=size==='L'?E.r32(p+2):E.r16(p+2);if(size==='B')imm&=0xff;}rows.push({at:p,size,mode:dm,srcReg:sm===0?'D'+sr:sm===1?'A'+sr:'',imm});}
 return rows;}
async function run(){stopped=false;await ensure();const E=env(),preps=[];for(let p=0;p+6<E.MAX;p+=2){const z=ptrPrep(E,p);if(z)preps.push({at:p,...z});}console.log('raw +0x72 pointer preps',preps.length);
 const cache=new Map(),rows=[];for(const z of preps){if(stopped)throw new Error('stopped');const fs=findStart(E,z.at);let g=cache.get(fs);if(!g){g=graph(E,fs);cache.set(fs,g);}if(!g.seen.has(z.at))continue;const dst=z.dstReg==='SP'?-1:+z.dstReg.slice(1);for(let p=z.at+z.len;p<Math.min(E.MAX,z.at+0x40);){const d=decode(E,p);if((d.kind==='JSR'||d.kind==='BSR')&&d.target!=null){if(dst>=0){const hw=helperWrites(E,d.target&~1,dst);for(const q of hw){const sv=q.imm==null?'':q.imm,match=q.imm===35||q.imm===3;rows.push({prepAt:E.h(z.at),offlinePrep:E.off(z.at),prepKind:z.kind,enemyReg:z.srcReg,fieldReg:z.dstReg,callAt:E.h(p),helper:E.h(d.target&~1),helperWriteAt:E.h(q.at),writeSize:q.size,srcReg:q.srcReg,stateValue:sv,matches35or3:match,score:(match?800:0)+(q.size==='B'?200:0)+(z.kind==='LEA'?100:0)});}}break;}if(d.terminal||d.kind==='BRA'||d.kind==='JMP')break;p+=Math.max(2,d.len);} }
 rows.sort((a,b)=>b.score-a.score||a.prepAt.localeCompare(b.prepAt));console.log('=== STATE72 POINTER-HELPER CANDIDATES ===');console.table(rows.slice(0,80));const exact=rows.filter(x=>x.matches35or3),top=exact[0]||rows[0]||null;const verdict={rawPointerPreps:preps.length,validatedPointerHelpers:rows.length,exact35or3Helpers:exact.length,topPrepAt:top?.prepAt||'',topPrepKind:top?.prepKind||'',topEnemyReg:top?.enemyReg||'',topFieldReg:top?.fieldReg||'',topCallAt:top?.callAt||'',topHelper:top?.helper||'',topHelperWriteAt:top?.helperWriteAt||'',topSrcReg:top?.srcReg||'',topStateValue:top?.stateValue??''};console.log('=== STATE72 POINTER HELPER VERDICT ===');console.table([verdict]);if(exact.length)console.log('🎯 找到 +0x72 字段指针传入 helper，并由 helper 生成 state 35/3；下一步只追 top helper/caller。');else if(rows.length)console.warn('⚠️ 找到 +0x72 pointer-helper 写链，但值不是直接 35/3；下一步追 helper srcReg/table source。');else console.warn('⚠️ 没有 LEA/PEA +0x72 → direct helper 写链；下一步查 indexed destination / indirect trampoline / 动态 PC。');self.__WOF_STATE72_PTR_HELPER={version:'state72-pointer-helper-v1',verdict,rows,preps:preps.map(x=>({...x,at:E.h(x.at)}))};return self.__WOF_STATE72_PTR_HELPER;}
self.WOFSTATE72PTR={run,stop(){stopped=true;}};console.log('✅ WOF state72 pointer-helper scanner loaded');console.log('执行 await WOFSTATE72PTR.run()');
})();