(()=>{
'use strict';
try{self.WOFFOCUSSELECTOREA?.stop?.();}catch(_){}
const RAW='https://raw.githubusercontent.com/ouyong520/wof-ai-private/main/';
const sleep=ms=>new Promise(r=>setTimeout(r,ms));let stopped=false;
const load=async f=>{const r=await fetch(RAW+f+'?x='+Math.random());if(!r.ok)throw new Error('fetch failed '+r.status+' '+f);return (0,eval)(await r.text());};
async function ensure(){if(!self.__WOF_ROM_FOCUS_LEVEL2?.handlers?.length){await load('wof_rom_focus_level2_tables.js');await WOFFOCUSLEVEL2.run();}if(!self.__WOF_ROM_LOC_CACHE)throw new Error('ROM state unavailable');}
function env(){const MOD=_0x515056,C=self.__WOF_ROM_LOC_CACHE,M=MOD.HEAPU8,base=C.base,SW=!!C.swap16,MAX=Math.min(0x100000,M.length-base),DELTA=C.offlineDelta|0;
 const r8=o=>M[base+(SW?(o^1):o)]>>>0,r16=o=>((r8(o)<<8)|r8(o+1))>>>0,r32=o=>(r8(o)*0x1000000+r8(o+1)*0x10000+r8(o+2)*0x100+r8(o+3))>>>0,s8=v=>v&0x80?v-0x100:v,s16=v=>v&0x8000?v-0x10000:v,h=x=>'0x'+(x>>>0).toString(16).toUpperCase().padStart(6,'0'),off=x=>h((x-DELTA)>>>0),hw=x=>'0x'+(x&0xffff).toString(16).toUpperCase().padStart(4,'0');
 return{MAX,r8,r16,r32,s8,s16,h,off,hw,P:{P1:0xFFBE1C,P2:0xFFBEFC,P3:0xFFBFDC}};}
function eaWords(m,r,size){if(m<=4)return 0;if(m===5||m===6)return 1;if(m===7){if(r===0||r===2||r===3)return 1;if(r===1)return 2;if(r===4)return size==='L'?2:1;}return 0;}
function decode(E,p){const w=E.r16(p),g=w>>>12,m=(w>>3)&7,r=w&7;let len=2,kind='OP',target=null,fall=true,terminal=false,call=false,branch=false,cmp=false,indirect=false;
 if(w===0x4E75||w===0x4E73||w===0x4E77){kind='RET';terminal=true;fall=false;}
 else if(w===0x4E72){kind='STOP';len=4;terminal=true;fall=false;}
 else if((w&0xFFC0)===0x4E80){kind='JSR';call=true;len=2+eaWords(m,r,'L')*2;if(m===7&&r===0)target=E.s16(E.r16(p+2))>>>0;else if(m===7&&r===1)target=E.r32(p+2);else if(m===7&&r===2)target=(p+2+E.s16(E.r16(p+2)))>>>0;else indirect=true;}
 else if((w&0xFFC0)===0x4EC0){kind='JMP';fall=false;len=2+eaWords(m,r,'L')*2;if(m===7&&r===0)target=E.s16(E.r16(p+2))>>>0;else if(m===7&&r===1)target=E.r32(p+2);else if(m===7&&r===2)target=(p+2+E.s16(E.r16(p+2)))>>>0;else indirect=true;}
 else if(g===6){const cc=(w>>8)&15,d=w&255;len=d===0?4:2;target=d===0?p+2+E.s16(E.r16(p+2)):p+2+E.s8(d);kind=cc===0?'BRA':cc===1?'BSR':'BCC';branch=true;if(cc===0)fall=false;if(cc===1)call=true;}
 else if(g===1||g===2||g===3){const size=g===1?'B':g===2?'L':'W',sm=(w>>3)&7,sr=w&7,dm=(w>>6)&7,dr=(w>>9)&7;kind='MOVE';len=2+(eaWords(sm,sr,size)+eaWords(dm,dr,size))*2;}
 else if(g===5){const sz=(w>>6)&3;if(sz===3&&m===1){kind='DBCC';len=4;target=(p+2+E.s16(E.r16(p+2)))>>>0;branch=true;}else len=2+eaWords(m,r,sz===3?'B':sz===2?'L':sz===1?'W':'B')*2;}
 else if(g===0){if([0x003C,0x007C,0x023C,0x027C,0x0A3C,0x0A7C].includes(w))len=4;else if((w&0xF138)===0x0108)len=4;else if((w&0xFF00)===0x0800)len=4+eaWords(m,r,'B')*2;else if((w&0xF100)===0x0100)len=2+eaWords(m,r,'B')*2;else{const op=(w>>8)&15,sz=(w>>6)&3;if([0,2,4,6,10,12].includes(op)){const s=sz===2?'L':sz===1?'W':'B';len=2+(s==='L'?4:2)+eaWords(m,r,s)*2;}}}
 else if(g===4){if((w&0xFFF8)===0x4E50)len=4;else if((w&0xFB80)===0x4880&&m>=2)len=4+eaWords(m,r,(w&0x40)?'L':'W')*2;else if((w&0xF1C0)===0x41C0)len=2+eaWords(m,r,'L')*2;else if((w&0xFFC0)===0x4840&&m!==0)len=2+eaWords(m,r,'L')*2;else len=2+eaWords(m,r,((w>>6)&3)===2?'L':'W')*2;}
 else if(g===8){if((w&0xF1F0)!==0x8100)len=2+eaWords(m,r,((w>>6)&3)===2?'L':'W')*2;}
 else if(g===9||g===13){const special=(w&0xF130)===(g===9?0x9100:0xD100),a=((w>>6)&7)===3||((w>>6)&7)===7;if(!special)len=2+eaWords(m,r,a?(((w>>6)&1)?'L':'W'):(((w>>6)&3)===2?'L':'W'))*2;}
 else if(g===11){const cmpm=(w&0xF138)===0xB108,a=((w>>6)&7)===3||((w>>6)&7)===7;cmp=true;kind='CMP';if(!cmpm)len=2+eaWords(m,r,a?(((w>>6)&1)?'L':'W'):(((w>>6)&3)===2?'L':'W'))*2;}
 else if(g===12){const exg=(w&0xF1F8)===0xC140||(w&0xF1F8)===0xC148||(w&0xF1F8)===0xC188,abcd=(w&0xF1F0)===0xC100;if(!exg&&!abcd)len=2+eaWords(m,r,((w>>6)&3)===2?'L':'W')*2;}
 else if(g===14&&((w>>6)&3)===3)len=2+eaWords(m,r,'W')*2;
 else if(g===10||g===15){kind='LINE';terminal=true;fall=false;}
 len=Math.max(2,len);const next=p+len;if(target!=null&&(target<0||target>=E.MAX))target=null;return{at:p,w,len,next,kind,target,fall,terminal,call,branch,cmp,indirect,m,r};}
function refs(E,d){const out=[],seen=new Set();for(let q=d.at+2;q+1<d.next;q+=2){const w=E.r16(q),a16=(w&0x8000)?(0xFF0000|w):w;for(const [name,a] of Object.entries(E.P))if(a16===a){const k=name+'|'+q+'|W';if(!seen.has(k)){seen.add(k);out.push({player:name,at:q,enc:'W',raw:E.hw(w)});}}if(q+3<d.next){const v=E.r32(q);for(const [name,a] of Object.entries(E.P))if(v===a){const k=name+'|'+q+'|L';if(!seen.has(k)){seen.add(k);out.push({player:name,at:q,enc:'L',raw:E.h(v)});}}}}
 return out;}
function routine(E,start,cap=0x1400){const hi=Math.min(E.MAX,start+cap),q=[start&~1],seen=new Set(),calls=[],indirect=[],prefs=[],stride=[];let cmp=0,branches=0;
 while(q.length&&seen.size<7000){const p=q.shift();if(p<start||p>=hi||(p&1)||seen.has(p))continue;seen.add(p);const d=decode(E,p);if(d.cmp)cmp++;if(d.branch)branches++;for(const z of refs(E,d))prefs.push({player:z.player,insn:p,at:z.at,enc:z.enc,raw:z.raw,op:d.w});for(let x=d.at+2;x+1<d.next;x+=2){const v=E.r16(x);if(v===0x00E0||v===0x01C0||v===0x02A0||v===0x0380)stride.push({insn:p,at:x,value:v});}
  if((d.kind==='JSR'||d.kind==='BSR')&&d.target!=null)calls.push({at:p,target:d.target&~1,kind:d.kind});if(d.indirect)indirect.push({at:p,kind:d.kind,m:d.m,r:d.r});
  if(d.kind==='BRA'){if(d.target!=null&&d.target>=start&&d.target<hi)q.push(d.target&~1);continue;}if(d.kind==='BCC'||d.kind==='DBCC'){if(d.next<hi)q.push(d.next);if(d.target!=null&&d.target>=start&&d.target<hi)q.push(d.target&~1);continue;}if(d.kind==='JMP'){if(!d.indirect&&d.target!=null&&d.target>=start&&d.target<hi)q.push(d.target&~1);continue;}if(d.terminal)continue;if(d.next<hi)q.push(d.next);
 }
 const players=[...new Set(prefs.map(x=>x.player))].sort();return{decoded:seen.size,calls:[...new Map(calls.map(x=>[x.at+'|'+x.target,x])).values()],indirect:[...new Map(indirect.map(x=>[x.at+'|'+x.kind,x])).values()],prefs,stride,players,cmp,branches};}
async function run(){stopped=false;await ensure();const E=env(),L2=self.__WOF_ROM_FOCUS_LEVEL2;console.log('🎯 WOF selector EA scan v2 · abs.W/abs.L + player stride');
 const raw=(L2.handlers||[]).map(x=>({addr:parseInt(x.target,16)&~1,type:x.type,d0:x.d0})).filter(x=>Number.isFinite(x.addr)),roots=[...new Map(raw.map(x=>[x.addr+'|'+x.type+'|'+x.d0,x])).values()],cache=new Map(),prov=new Map();const get=a=>{a&=~1;if(!cache.has(a))cache.set(a,routine(E,a));return cache.get(a);};
 for(let i=0;i<roots.length;i++){const root=roots[i],q=[{a:root.addr,d:0}],seen=new Set();while(q.length){const n=q.shift(),a=n.a&~1;if(seen.has(a)||n.d>7)continue;seen.add(a);let pr=prov.get(a);if(!pr)prov.set(a,pr={types:new Set(),states:new Set(),min:n.d});pr.types.add(root.type);pr.states.add(root.type+':'+root.d0);pr.min=Math.min(pr.min,n.d);for(const c of get(a).calls)if(n.d<7&&!seen.has(c.target))q.push({a:c.target,d:n.d+1});}if(i%24===23)await sleep(0);}
 const rows=[];for(const [a,r] of cache){const pr=prov.get(a);if(!pr)continue;const ps=new Set(r.players),all3=['P1','P2','P3'].every(x=>ps.has(x)),arrayish=ps.has('P1')&&r.stride.length>0,score=ps.size*150+(all3?500:0)+(arrayish?260:0)+Math.min(30,r.cmp)*10+Math.min(30,r.branches)*2+r.indirect.length*40+Math.min(20,pr.types.size)*3-Math.min(6,pr.min)*2;if(ps.size||arrayish||r.indirect.length||r.cmp>=4)rows.push({routine:E.h(a),offline:E.off(a),score,players:r.players.join(','),refs:r.prefs.length,absW:r.prefs.filter(x=>x.enc==='W').length,absL:r.prefs.filter(x=>x.enc==='L').length,strideE0:r.stride.length,all3,arrayish,cmp:r.cmp,branches:r.branches,indirect:r.indirect.length,typeIds:[...pr.types].sort((x,y)=>x-y).join(','),states:pr.states.size,minDepth:pr.min});}
 rows.sort((a,b)=>b.score-a.score||b.all3-a.all3||b.arrayish-a.arrayish||b.refs-a.refs||b.cmp-a.cmp);console.log('=== EA-AWARE SELECTOR CANDIDATES ===');console.table(rows.slice(0,100));const strong=rows.filter(x=>(x.all3||x.arrayish)&&x.cmp>=2),top=strong[0]||rows[0]||null;
 if(top){const a=parseInt(top.routine,16),r=cache.get(a);console.log('=== TOP EA PLAYER REFS ===');console.table(r.prefs.map(x=>({player:x.player,insn:E.h(x.insn),offline:E.off(x.insn),at:E.h(x.at),enc:x.enc,raw:x.raw,op:E.hw(x.op)})));console.log('=== TOP PLAYER STRIDE WORDS ===');console.table(r.stride.map(x=>({insn:E.h(x.insn),offline:E.off(x.insn),at:E.h(x.at),value:E.hw(x.value)})));}
 const verdict={level2Pointers:(L2.handlers||[]).length,uniqueRootHandlers:new Set(raw.map(x=>x.addr)).size,reachableRoutines:cache.size,candidates:rows.length,strongCandidates:strong.length,topRoutine:top?.routine||'',topPlayers:top?.players||'',topAbsW:top?.absW??0,topAbsL:top?.absL??0,topStrideE0:top?.strideE0??0,topAll3:top?.all3??false,topArrayish:top?.arrayish??false,topCmp:top?.cmp??0,topBranches:top?.branches??0,topIndirect:top?.indirect??0,topTypeIds:top?.typeIds||'',topStates:top?.states??0};console.log('=== SELECTOR EA VERDICT ===');console.table([verdict]);
 if(strong.length)console.log('🎯 找到 abs.W/abs.L 或 P1+0xE0 玩家数组 selector 候选；下一步只解 topRoutine 的寄存器数据流。');else console.warn('⚠️ EA-aware 扫描仍无玩家 selector；下一步转查 shared RAM player-pointer table / 上游 selector。');const out={version:'rom-focus-selector-ea-v2',verdict,candidates:rows,top};self.__WOF_ROM_FOCUS_SELECTOR_EA=out;return out;}
self.WOFFOCUSSELECTOREA={version:'rom-focus-selector-ea-v2',run,stop(){stopped=true;}};console.log('✅ WOF selector EA scan v2 loaded');console.log('执行 await WOFFOCUSSELECTOREA.run()');
})();