(()=>{
'use strict';
try{self.WOFD0CALLER?.stop?.();}catch(_){}
const RAW='https://raw.githubusercontent.com/ouyong520/wof-ai-private/main/';
const sleep=ms=>new Promise(r=>setTimeout(r,ms));let stopped=false;
const load=async f=>{const r=await fetch(RAW+f+'?x='+Date.now(),{cache:'no-store'});if(!r.ok)throw new Error('fetch failed '+r.status+' '+f);return (0,eval)(await r.text());};
async function ensure(){if(!self.__WOF_ROM_LOC_CACHE)await load('wof_rom_focus_inspect.js');for(let i=0;i<300&&!self.__WOF_ROM_LOC_CACHE;i++)await sleep(50);if(!self.__WOF_ROM_LOC_CACHE)throw new Error('ROM cache unavailable');}
function env(){const MOD=_0x515056,C=self.__WOF_ROM_LOC_CACHE,M=MOD.HEAPU8,base=C.base,SW=!!C.swap16,MAX=Math.min(0x100000,M.length-base),DELTA=C.offlineDelta|0;const r8=o=>M[base+(SW?(o^1):o)]>>>0,r16=o=>((r8(o)<<8)|r8(o+1))>>>0,r32=o=>(r8(o)*0x1000000+r8(o+1)*0x10000+r8(o+2)*0x100+r8(o+3))>>>0,s8=v=>v&0x80?v-0x100:v,s16=v=>v&0x8000?v-0x10000:v,h=x=>'0x'+(x>>>0).toString(16).toUpperCase().padStart(6,'0'),off=x=>h((x-DELTA)>>>0),hw=x=>'0x'+(x&0xffff).toString(16).toUpperCase().padStart(4,'0');return{MAX,r8,r16,r32,s8,s16,h,off,hw};}
function eaWords(m,r,size){if(m<=4)return 0;if(m===5||m===6)return 1;if(m===7){if(r===0||r===2||r===3)return 1;if(r===1)return 2;if(r===4)return size==='L'?2:1;}return 0;}
function eaText(E,p,m,r,size){if(m===0)return'D'+r;if(m===1)return'A'+r;if(m===2)return'(A'+r+')';if(m===3)return'(A'+r+')+';if(m===4)return'-(A'+r+')';if(m===5)return E.s16(E.r16(p))+'(A'+r+')';if(m===6){const x=E.r16(p),ix=(x&0x8000?'A':'D')+((x>>12)&7)+(x&0x0800?'.L':'.W'),d=E.s8(x&255);return d+'(A'+r+','+ix+')';}if(m===7&&r===0)return'$'+E.hw(E.r16(p))+'.W';if(m===7&&r===1)return'$'+E.h(E.r32(p))+'.L';if(m===7&&r===2)return E.s16(E.r16(p))+'(PC)';if(m===7&&r===3){const x=E.r16(p),ix=(x&0x8000?'A':'D')+((x>>12)&7)+(x&0x0800?'.L':'.W'),d=E.s8(x&255);return d+'(PC,'+ix+')';}if(m===7&&r===4){if(size==='L')return'#'+E.h(E.r32(p));return'#'+E.hw(E.r16(p));}return'EA';}
function decode(E,p){const w=E.r16(p),g=w>>>12,m=(w>>3)&7,r=w&7;let len=2,kind='OP',target=null,fall=true,terminal=false,call=false,branch=false,text='DC.W '+E.hw(w),d0=null;
 if(w===0x4E75||w===0x4E73||w===0x4E77){kind='RET';terminal=true;fall=false;text='RET';}
 else if(w===0x4E72){kind='STOP';len=4;terminal=true;fall=false;text='STOP';}
 else if((w&0xFFC0)===0x4E80){kind='JSR';call=true;len=2+eaWords(m,r,'L')*2;if(m===7&&r===0)target=E.s16(E.r16(p+2))>>>0;else if(m===7&&r===1)target=E.r32(p+2);else if(m===7&&r===2)target=(p+2+E.s16(E.r16(p+2)))>>>0;text='JSR '+eaText(E,p+2,m,r,'L');}
 else if((w&0xFFC0)===0x4EC0){kind='JMP';fall=false;len=2+eaWords(m,r,'L')*2;if(m===7&&r===0)target=E.s16(E.r16(p+2))>>>0;else if(m===7&&r===1)target=E.r32(p+2);else if(m===7&&r===2)target=(p+2+E.s16(E.r16(p+2)))>>>0;text='JMP '+eaText(E,p+2,m,r,'L');}
 else if(g===6){const cc=(w>>8)&15,d=w&255;len=d===0?4:2;target=d===0?p+2+E.s16(E.r16(p+2)):p+2+E.s8(d);kind=cc===0?'BRA':cc===1?'BSR':'BCC';branch=true;if(cc===0)fall=false;if(cc===1)call=true;text=kind+' '+E.h(target);}
 else if(g===1||g===2||g===3){const size=g===1?'B':g===2?'L':'W',sm=(w>>3)&7,sr=w&7,dm=(w>>6)&7,dr=(w>>9)&7,sw=eaWords(sm,sr,size),dw=eaWords(dm,dr,size),src=eaText(E,p+2,sm,sr,size),dst=eaText(E,p+2+sw*2,dm,dr,size);len=2+(sw+dw)*2;kind='MOVE';text='MOVE.'+size+' '+src+','+dst;if(dm===0&&dr===0){const meta={type:'root',source:src,baseReg:'',disp:''};if(sm===2||sm===3||sm===4)meta.baseReg='A'+sr;if(sm===5){meta.baseReg='A'+sr;meta.disp=E.s16(E.r16(p+2));}if(sm===6){meta.baseReg='A'+sr;meta.disp=E.s8(E.r16(p+2)&255);}d0=meta;}}
 else if((w&0xF100)===0x7000){const dr=(w>>9)&7,imm=E.s8(w&255);kind='MOVEQ';text='MOVEQ #'+imm+',D'+dr;if(dr===0)d0={type:'root',source:'#'+imm,baseReg:'',disp:''};}
 else if((w&0xFFF8)===0x4200){const reg=w&7;text='CLR.B D'+reg;if(reg===0)d0={type:'root',source:'#0',baseReg:'',disp:''};}
 else if((w&0xFFF8)===0x4240){const reg=w&7;text='CLR.W D'+reg;if(reg===0)d0={type:'root',source:'#0',baseReg:'',disp:''};}
 else if((w&0xFFF8)===0x4280){const reg=w&7;text='CLR.L D'+reg;if(reg===0)d0={type:'root',source:'#0',baseReg:'',disp:''};}
 else if(g===14){const sz=(w>>6)&3,reg=w&7;if(sz!==3){const cnt=(w>>9)&7||8,dir=(w&0x0100)?'L':'R',typ=(w>>3)&3,op=['AS','LS','ROX','RO'][typ]+dir,size=sz===2?'L':sz===1?'W':'B';text=op+'.'+size+' #'+cnt+',D'+reg;if(reg===0)d0={type:'transform',source:'D0',baseReg:'',disp:''};}else len=2+eaWords(m,r,'W')*2;}
 else if(g===5&&((w>>6)&3)!==3){const q=((w>>9)&7)||8,sub=!!(w&0x0100),sz=(w>>6)&3,size=sz===2?'L':sz===1?'W':'B',dst=eaText(E,p+2,m,r,size);len=2+eaWords(m,r,size)*2;text=(sub?'SUBQ.':'ADDQ.')+size+' #'+q+','+dst;if(m===0&&r===0)d0={type:'transform',source:'D0',baseReg:'',disp:''};}
 else if(g===0){const op=(w>>8)&15,sz=(w>>6)&3;if([0,2,4,6,10,12].includes(op)&&sz!==3){const size=sz===2?'L':sz===1?'W':'B',iw=size==='L'?2:1,nm={0:'ORI',2:'ANDI',4:'SUBI',6:'ADDI',10:'EORI',12:'CMPI'}[op],dst=eaText(E,p+2+iw*2,m,r,size);len=2+iw*2+eaWords(m,r,size)*2;text=nm+'.'+size+' ...,'+dst;if(m===0&&r===0&&nm!=='CMPI')d0={type:'transform',source:'D0',baseReg:'',disp:''};}}
 else if(g===8||g===9||g===12||g===13){const dr=(w>>9)&7,op=g===8?'OR':g===9?'SUB':g===12?'AND':'ADD',sz=(w>>6)&3,size=sz===2?'L':sz===1?'W':'B',src=eaText(E,p+2,m,r,size);len=2+eaWords(m,r,size)*2;text=op+'.'+size+' '+src+',D'+dr;if(dr===0)d0={type:'transform',source:'D0',baseReg:'',disp:''};}
 else if(g===5&&((w>>6)&3)===3&&m===1){kind='DBCC';len=4;target=(p+2+E.s16(E.r16(p+2)))>>>0;branch=true;text='DBCC '+E.h(target);}
 else if(g===4){if((w&0xFFF8)===0x4E50)len=4;else if((w&0xFB80)===0x4880&&m>=2)len=4+eaWords(m,r,(w&0x40)?'L':'W')*2;else if((w&0xF1C0)===0x41C0)len=2+eaWords(m,r,'L')*2;else len=2+eaWords(m,r,((w>>6)&3)===2?'L':'W')*2;}
 else if(g===10||g===15){kind='LINE';terminal=true;fall=false;}
 len=Math.max(2,len);const next=p+len;if(target!=null&&(target<0||target>=E.MAX))target=null;return{at:p,w,len,next,kind,target,fall,terminal,call,branch,text,d0};}
function findStart(E,at){for(let p=at&~1;p>=Math.max(0,at-0x500);p-=2){const w=E.r16(p);if((w&0xFFF8)===0x4E50||w===0x48E7)return p;if(w===0x4E75||w===0x4E73||w===0x4E77)return p+2;}return Math.max(0,(at-0x180)&~1);}
function graph(E,start,cap=0x1800){const hi=Math.min(E.MAX,start+cap),q=[start&~1],seen=new Set(),dec=new Map(),pred=new Map();const edge=(a,b)=>{if(b==null||b<start||b>=hi||(b&1))return;let s=pred.get(b);if(!s)pred.set(b,s=[]);s.push(a);q.push(b);};while(q.length&&seen.size<10000){const p=q.shift();if(p<start||p>=hi||(p&1)||seen.has(p))continue;seen.add(p);const d=decode(E,p);dec.set(p,d);if(d.kind==='BRA'){edge(p,d.target);continue;}if(d.kind==='BCC'||d.kind==='DBCC'){edge(p,d.next);edge(p,d.target);continue;}if(d.kind==='JMP'){if(d.target!=null)edge(p,d.target);continue;}if(d.terminal)continue;edge(p,d.next);}return{start,seen,dec,pred};}
function rawEdges(E){const map=new Map();const add=(t,e)=>{t&=~1;if(t<0||t>=E.MAX)return;let a=map.get(t);if(!a)map.set(t,a=[]);a.push(e);};for(let p=0;p+6<E.MAX;p+=2){const w=E.r16(p),d=w&255;let t=null,k='';if(w===0x4EB8){t=E.s16(E.r16(p+2))>>>0;k='JSR.W';}else if(w===0x4EB9){t=E.r32(p+2);k='JSR.L';}else if(w===0x4EBA){t=(p+2+E.s16(E.r16(p+2)))>>>0;k='JSR.PC';}else if((w&0xFF00)===0x6100){t=d===0?(p+2+E.s16(E.r16(p+2)))>>>0:(p+2+E.s8(d))>>>0;k=d===0?'BSR.W':'BSR.S';}if(t!=null)add(t,{at:p,kind:k});}return map;}
function traceD0(E,g,callAt,maxDepth=48){const out=[],q=[{p:callAt,chain:[],depth:0}],seen=new Set();while(q.length&&out.length<24){const z=q.shift();if(z.depth>=maxDepth)continue;for(const p of g.pred.get(z.p)||[]){const key=p+'|'+z.chain.length;if(seen.has(key))continue;seen.add(key);const d=g.dec.get(p);if(!d)continue;if(d.d0){const step=E.h(p)+' '+d.text;if(d.d0.type==='root'){out.push({rootAt:p,rootText:d.text,rootSource:d.d0.source,rootBaseReg:d.d0.baseReg,rootDisp:d.d0.disp,transforms:[...z.chain].reverse().join(' -> '),depth:z.depth+1});continue;}q.push({p,chain:[step,...z.chain],depth:z.depth+1});}else q.push({p,chain:z.chain,depth:z.depth+1});}}
 return [...new Map(out.map(x=>[x.rootAt+'|'+x.transforms,x])).values()].sort((a,b)=>a.depth-b.depth);}
async function run(){stopped=false;await ensure();const E=env(),targets=[0x25B6,0x25C8],idx=rawEdges(E),callers=[],chains=[];const cache=new Map();
 console.log('🔙 WOF dispatcher caller-side D0 trace v1');
 for(const t of targets){for(const e of idx.get(t)||[]){if(stopped)throw new Error('stopped');const fs=findStart(E,e.at);let g=cache.get(fs);if(!g){g=graph(E,fs);cache.set(fs,g);}if(!g.seen.has(e.at))continue;const d=g.dec.get(e.at);if(!d||d.target==null||((d.target&~1)!==t))continue;const cr={target:E.h(t),callerRoutine:E.h(fs),offlineCaller:E.off(fs),callAt:E.h(e.at),offlineCall:E.off(e.at),kind:e.kind};callers.push(cr);for(const x of traceD0(E,g,e.at)){chains.push({...cr,rootAt:E.h(x.rootAt),offlineRoot:E.off(x.rootAt),rootText:x.rootText,rootSource:x.rootSource,rootBaseReg:x.rootBaseReg||'',rootDisp:x.rootDisp===''?'':x.rootDisp,transforms:x.transforms,depth:x.depth});}}
 }
 console.log('=== DIRECT DISPATCH CALLERS ===');console.table(callers);
 chains.sort((a,b)=>a.depth-b.depth||a.callAt.localeCompare(b.callAt));console.log('=== CALLER-SIDE D0 ROOT CHAINS ===');console.table(chains.slice(0,80));
 const mem=chains.filter(x=>x.rootBaseReg),freq=new Map();for(const x of mem){const k=x.rootSource+'|'+x.rootBaseReg+'|'+x.rootDisp;freq.set(k,(freq.get(k)||0)+1);}const common=[...freq.entries()].sort((a,b)=>b[1]-a[1])[0]||null,top=mem[0]||chains[0]||null;
 const verdict={dispatcherTargets:targets.map(E.h).join(','),directCallers:callers.length,tracedCallsites:[...new Set(chains.map(x=>x.callAt))].length,d0RootChains:chains.length,memoryRootChains:mem.length,commonRootSource:common?.[0]||'',commonRootCount:common?.[1]||0,topTarget:top?.target||'',topCaller:top?.callerRoutine||'',topCallAt:top?.callAt||'',topRootAt:top?.rootAt||'',topRootText:top?.rootText||'',topRootBaseReg:top?.rootBaseReg||'',topRootDisp:top?.rootDisp??'',topTransforms:top?.transforms||''};
 console.log('=== DISPATCH CALLER D0 VERDICT ===');console.table([verdict]);
 if(mem.length)console.log('🎯 D0 已追到 caller 侧内存源；下一步锁定 top/common base+disp，并确认它对应 enemy struct 哪个字段。');else if(chains.length)console.log('🧭 D0 已追到 caller 侧寄存器/立即数根；下一步继续反追 rootSource。');else if(callers.length)console.warn('⚠️ 找到 direct caller，但 D0 在可追窗口内没有 root；下一步跨 caller 再追一层。');else console.warn('⚠️ 0x25B6/0x25C8 没有验证通过的 direct callers；下一步转 indirect/shared trampoline caller。');
 const out={version:'wof-dispatch-d0-caller-trace-v1',verdict,callers,chains};self.__WOF_DISPATCH_D0_CALLER=out;return out;}
self.WOFD0CALLER={version:'wof-dispatch-d0-caller-trace-v1',run,stop(){stopped=true;}};console.log('✅ WOF dispatcher caller-side D0 trace v1 loaded');console.log('执行 await WOFD0CALLER.run()');
})();