(async()=>{
'use strict';
const COPY_ID='WOF-023';
const PROJECT='WOF-AI-PRIVATE';
const VERSION='wof-future-danger-deadline-tail-validator-v23';
const MARKER='=== WOF FUTURE DANGER DEADLINE TAIL VALIDATOR V23 JSON ===';
console.log(`[${COPY_ID}] ${PROJECT} ${VERSION}`);
const good=v=>!!(v&&v.HEAPU8 instanceof Uint8Array&&v.HEAPU32 instanceof Uint32Array&&v.HEAPU8.buffer===v.HEAPU32.buffer);
if(!good(self._0x515056)){
  const until=performance.now()+8000;let hit=null;
  while(performance.now()<until&&!hit){for(const k of Object.getOwnPropertyNames(self)){let v;try{v=self[k]}catch(_){continue}if(good(v)){hit={k,v};break}}if(!hit)await new Promise(r=>setTimeout(r,50));}
  if(!hit)throw new Error(`[${COPY_ID}] WASM module not found. Select the live gstyphoon.js Worker.`);
  self._0x515056=hit.v;self.__WOF_MODULE_GLOBAL_KEY=hit.k;console.log(`[${COPY_ID}] ✅ module ${hit.k} -> _0x515056`);
}
const M=self._0x515056.HEAPU8,R=self._0x515056.HEAPU32?.[0x2e39e4>>>2]>>>0;if(!R)throw new Error(`[${COPY_ID}] CPS RAM base missing`);
const B=a=>M[R+((((a-0xFF0000)&0xffff)^1))]>>>0;
const U16=a=>((B(a)<<8)|B(a+1))>>>0;
const U32=a=>(B(a)*0x1000000+B(a+1)*0x10000+B(a+2)*0x100+B(a+3))>>>0;
const S32=a=>{const v=U32(a);return v>=0x80000000?v-0x100000000:v;};
const X=a=>Math.round(S32(a+4)/65536),Y=a=>Math.round(S32(a+8)/65536);
const ENEMY=0xFFC0BC,STRIDE=0xE0,SLOTS=20,PLAYERS={0:'P1',4:'P2',8:'P3'},PBASE={0:0xFFBE1C,4:0xFFBEFC,8:0xFFBFDC};
const side=dx=>dx<-4?'LEFT':dx>4?'RIGHT':'CENTER',lane=dy=>dy<-4?'UP':dy>4?'DOWN':'SAME';
function snap(i){const a=ENEMY+i*STRIDE,type=U16(a+0x20);if(type>=47)return null;const frameEnd=U32(a+0x12),next=U32(a+0x2C);if(!frameEnd&&!next)return null;const t7=U16(a+0x7E),pb=PBASE[t7],ex=X(a),ey=Y(a),tx=pb?X(pb):null,ty=pb?Y(pb):null,dx=tx==null?null:tx-ex,dy=ty==null?null:ty-ey;return{slot:i,type,target7E:t7,target:PLAYERS[t7]||null,state99:B(a+0x99),action2A:B(a+0x2A),b2B:B(a+0x2B),body:U16(a+0x6E),attack:U16(a+0x70),frameEnd,next,value30:U32(a+0x30),enemyX:ex,enemyY:ey,targetX:tx,targetY:ty,dx,dy,absDx:dx==null?null:Math.abs(dx),absDy:dy==null?null:Math.abs(dy),side:dx==null?null:side(dx),lane:dy==null?null:lane(dy)};}
const FAST=new Set(['0/4/2','0/4/4','2/4/2','2/4/4','2/0/0','4/4/2','4/4/4','4/0/0']);
const RULES=[
{id:'T16_FAST_100',type:16,warningHorizon:100,tailHorizon:500,status:'production-shadow-under-review',level:'IMMINENT',match:s=>s.type===16&&s.attack===0&&s.body===4856&&s.frameEnd===0x851ae&&s.next===0x84c44&&s.value30===0xffff&&FAST.has(`${s.state99}/${s.action2A}/${s.b2B}`)},
{id:'T16_MID_250',type:16,warningHorizon:250,tailHorizon:500,status:'provisional',level:'IMMINENT',match:s=>s.type===16&&s.attack===0&&s.body===4856&&s.state99===2&&s.action2A===4&&s.b2B===2&&s.frameEnd===0x85240&&s.next===0x84c3a&&s.value30===0x100000},
{id:'T30_FAST_100',type:30,warningHorizon:100,tailHorizon:500,status:'provisional',level:'IMMINENT',match:s=>s.type===30&&s.attack===0&&s.body===1800&&s.state99===0&&s.action2A===0&&s.b2B===0}
];
const DURATION=120000,INTERVAL=20,start=performance.now(),prev=new Map(),cycle=new Map(),armed=new Map(),watches=[],events=[],attackEdges=[];let wid=0;
const diag={polls:0,enemySamples:0,activeEdges:0,validTargetActiveEdges:0,signals:0,warningExpired:0,onTimeHits:0,lateHits:0,hardMisses:0,retargets:0,copyId:COPY_ID};
const rawMatchSamples={},transitionEntries={},typeSamples={};for(const r of RULES){rawMatchSamples[r.id]=0;transitionEntries[r.id]=0;}
const armKey=(slot,id)=>`${slot}|${id}`;
function publish(now){const entries=[];for(const w of watches){if(w.resolved||w.warningExpired)continue;const s=prev.get(w.slot);if(!s||s.type!==w.type)continue;const remaining=Math.max(0,w.warningHorizon-(now-w.at));entries.push({copyId:COPY_ID,rule:w.rule,status:w.status,level:w.level,slot:w.slot,type:w.type,target:s.target,target7E:s.target7E,warningHorizonMs:w.warningHorizon,remainingMs:remaining,enemyX:s.enemyX,enemyY:s.enemyY,targetX:s.targetX,targetY:s.targetY,dx:s.dx,dy:s.dy,absDx:s.absDx,absDy:s.absDy,side:s.side,lane:s.lane,tuple:w.tuple});}
const state={copyId:COPY_ID,project:PROJECT,version:VERSION,atMs:now,entries};self.__WOF_FUTURE_DANGER_MAP_STATE=state;self.__WOF_FUTURE_DANGER_MAP_STATE_V23=state;self.__WOF_FUTURE_DANGER_LIVE_STATE=state;}
function arm(r,s,t){const c=cycle.get(s.slot)||0,k=armKey(s.slot,r.id);if(armed.get(k)===c)return;armed.set(k,c);const tuple=`S${s.state99}/A${s.action2A}/B${s.b2B}`;const w={id:++wid,rule:r.id,status:r.status,level:r.level,type:s.type,slot:s.slot,cycle:c,warningHorizon:r.warningHorizon,tailHorizon:r.tailHorizon,at:t,tuple,state99:s.state99,action2A:s.action2A,b2B:s.b2B,body:s.body,frameEnd:s.frameEnd,next:s.next,value30:s.value30,entryTarget7E:s.target7E,entryTarget:s.target,entrySide:s.side,entryLane:s.lane,entryAbsDx:s.absDx,entryAbsDy:s.absDy,resolved:false,warningExpired:false,outcome:null,leadMs:null,lateByMs:null,activeAttack:null,targetSame:null,sideSame:null,retargets:[],censored:false,censorReason:null};watches.push(w);diag.signals++;events.push({kind:'SIGNAL',rel:t,rule:r.id,status:r.status,slot:s.slot,type:s.type,target:s.target,tuple});console.log(`[WOF V23][${COPY_ID}] SIGNAL ${r.id} ${tuple} slot${s.slot} <=${r.warningHorizon}ms`);}
function resolveActive(s,t){diag.activeEdges++;if(s.target)diag.validTargetActiveEdges++;attackEdges.push({rel:t,slot:s.slot,type:s.type,attack:s.attack,target:s.target,absDx:s.absDx,absDy:s.absDy,side:s.side,lane:s.lane});for(const w of watches){if(w.resolved||w.slot!==s.slot||w.type!==s.type)continue;const lead=t-w.at;if(lead<0||lead>w.tailHorizon)continue;w.resolved=true;w.leadMs=lead;w.activeAttack=s.attack;w.targetSame=w.entryTarget7E===s.target7E;w.sideSame=w.entrySide===s.side;w.activeTarget=s.target;w.activeAbsDx=s.absDx;w.activeAbsDy=s.absDy;if(lead<=w.warningHorizon){w.outcome='onTimeHit';diag.onTimeHits++;events.push({kind:'HIT',rel:t,rule:w.rule,slot:s.slot,type:s.type,leadMs:lead,attack:s.attack,target:s.target,tuple:w.tuple});console.log(`[WOF V23][${COPY_ID}] HIT ${w.rule} ${w.tuple} ${lead}ms attack=${s.attack}`);}else{w.outcome='lateHit';w.lateByMs=lead-w.warningHorizon;diag.lateHits++;events.push({kind:'LATE_HIT',rel:t,rule:w.rule,slot:s.slot,type:s.type,leadMs:lead,lateByMs:w.lateByMs,attack:s.attack,target:s.target,tuple:w.tuple});console.log(`[WOF V23][${COPY_ID}] LATE ${w.rule} ${w.tuple} ${lead}ms (+${w.lateByMs})`);}}cycle.set(s.slot,(cycle.get(s.slot)||0)+1);}
function deadlines(t){for(const w of watches){if(w.resolved)continue;const age=t-w.at;if(!w.warningExpired&&age>w.warningHorizon){w.warningExpired=true;diag.warningExpired++;events.push({kind:'WARNING_EXPIRE',rel:t,rule:w.rule,slot:w.slot,type:w.type,ageMs:age,tuple:w.tuple});}if(age>w.tailHorizon){w.resolved=true;w.outcome='hardMiss';diag.hardMisses++;events.push({kind:'HARD_MISS',rel:t,rule:w.rule,slot:w.slot,type:w.type,ageMs:age,tuple:w.tuple});console.log(`[WOF V23][${COPY_ID}] HARD_MISS ${w.rule} ${w.tuple}`);}}}
await new Promise(resolve=>{const id=setInterval(()=>{const t=Math.round(performance.now()-start);diag.polls++;for(let i=0;i<SLOTS;i++){const s=snap(i),p=prev.get(i)||null;if(!s){if(p){for(const w of watches)if(!w.resolved&&w.slot===i){w.resolved=true;w.censored=true;w.censorReason='slotGone';w.outcome='censored';}}prev.delete(i);continue;}diag.enemySamples++;typeSamples['T'+s.type]=(typeSamples['T'+s.type]||0)+1;if(p&&p.type!==s.type){for(const w of watches)if(!w.resolved&&w.slot===i){w.resolved=true;w.censored=true;w.censorReason='typeChange';w.outcome='censored';}cycle.set(i,(cycle.get(i)||0)+1);}if(p&&p.attack===0&&s.attack!==0)resolveActive(s,t);for(const r of RULES){if(r.type!==s.type)continue;const m=r.match(s),pm=!!(p&&p.type===s.type&&r.match(p));if(m)rawMatchSamples[r.id]++;if(m&&!pm){transitionEntries[r.id]++;arm(r,s,t);}}for(const w of watches){if(w.resolved||w.slot!==i||w.type!==s.type)continue;if(w.entryTarget7E!==s.target7E){const last=w.retargets.at(-1)?.to7E??w.entryTarget7E;if(last!==s.target7E){w.retargets.push({rel:t,from7E:last,to7E:s.target7E,from:PLAYERS[last]||null,to:s.target});diag.retargets++;}}}prev.set(i,s);}deadlines(t);publish(t);if(t>=DURATION){clearInterval(id);for(const w of watches)if(!w.resolved){w.resolved=true;w.censored=true;w.censorReason='captureEnd';w.outcome='censored';}publish(t);resolve();}},INTERVAL);});
const median=a=>{if(!a.length)return null;const b=[...a].sort((x,y)=>x-y),m=Math.floor(b.length/2);return b.length%2?b[m]:Math.round((b[m-1]+b[m])/2);};
const pct=(a,p)=>{if(!a.length)return null;const b=[...a].sort((x,y)=>x-y),i=Math.ceil(p*b.length)-1;return b[Math.max(0,Math.min(b.length-1,i))];};
const blank=(r,id=r.id)=>({rule:id,status:r.status,warningHorizonMs:r.warningHorizon,tailHorizonMs:r.tailHorizon,signals:0,evaluable:0,onTimeHit:0,lateHit:0,hardMiss:0,censored:0,onTimeRate:null,tailHitRate:null,leadsOnTime:[],leadsLate:[],lateBy:[],attackCounts:{},targetSame:0,targetTotal:0,sideSame:0,sideTotal:0,entryAbsDx:[],entryAbsDy:[],activeAbsDx:[],activeAbsDy:[]});
const ruleStats={};for(const r of RULES)ruleStats[r.id]=blank(r);
const tupleStats={};
for(const w of watches){const r=RULES.find(x=>x.id===w.rule),q=ruleStats[w.rule],tk=`${w.rule}|${w.tuple}`;if(!tupleStats[tk])tupleStats[tk]=blank(r,tk);for(const z of [q,tupleStats[tk]]){z.signals++;if(w.censored){z.censored++;continue;}z.evaluable++;if(w.outcome==='onTimeHit'){z.onTimeHit++;z.leadsOnTime.push(w.leadMs);}else if(w.outcome==='lateHit'){z.lateHit++;z.leadsLate.push(w.leadMs);z.lateBy.push(w.lateByMs);}else if(w.outcome==='hardMiss')z.hardMiss++;if(w.outcome==='onTimeHit'||w.outcome==='lateHit'){z.attackCounts[String(w.activeAttack)]=(z.attackCounts[String(w.activeAttack)]||0)+1;if(w.targetSame!=null){z.targetTotal++;if(w.targetSame)z.targetSame++;}if(w.sideSame!=null){z.sideTotal++;if(w.sideSame)z.sideSame++;}if(w.entryAbsDx!=null)z.entryAbsDx.push(w.entryAbsDx);if(w.entryAbsDy!=null)z.entryAbsDy.push(w.entryAbsDy);if(w.activeAbsDx!=null)z.activeAbsDx.push(w.activeAbsDx);if(w.activeAbsDy!=null)z.activeAbsDy.push(w.activeAbsDy);}}}
for(const q of [...Object.values(ruleStats),...Object.values(tupleStats)]){q.onTimeRate=q.evaluable?+(q.onTimeHit/q.evaluable).toFixed(3):null;q.tailHitRate=q.evaluable?+((q.onTimeHit+q.lateHit)/q.evaluable).toFixed(3):null;q.targetSameRate=q.targetTotal?+(q.targetSame/q.targetTotal).toFixed(3):null;q.sideStableRate=q.sideTotal?+(q.sideSame/q.sideTotal).toFixed(3):null;q.attackCounts=Object.entries(q.attackCounts).map(([attack,count])=>({attack:+attack,count})).sort((a,b)=>b.count-a.count);q.leadsOnTime.sort((a,b)=>a-b);q.leadsLate.sort((a,b)=>a-b);q.lateBy.sort((a,b)=>a-b);q.lateByMedian=median(q.lateBy);q.lateByP90=pct(q.lateBy,.9);q.entryAbsDxMedian=median(q.entryAbsDx);q.entryAbsDxP90=pct(q.entryAbsDx,.9);q.entryAbsDyP90=pct(q.entryAbsDy,.9);q.activeAbsDxMedian=median(q.activeAbsDx);q.activeAbsDxP90=pct(q.activeAbsDx,.9);q.activeAbsDyP90=pct(q.activeAbsDy,.9);delete q.lateBy;delete q.entryAbsDx;delete q.entryAbsDy;delete q.activeAbsDx;delete q.activeAbsDy;}
const split={};for(const e of attackEdges){const k=`T${e.type}|A${e.attack}`;let g=split[k];if(!g)g=split[k]={key:k,type:e.type,attack:e.attack,count:0,absDx:[],absDy:[]};g.count++;if(e.absDx!=null)g.absDx.push(e.absDx);if(e.absDy!=null)g.absDy.push(e.absDy);}for(const g of Object.values(split)){g.absDxMedian=median(g.absDx);g.absDxP90=pct(g.absDx,.9);g.absDxP95=pct(g.absDx,.95);g.absDyMedian=median(g.absDy);g.absDyP90=pct(g.absDy,.9);g.absDyP95=pct(g.absDy,.95);delete g.absDx;delete g.absDy;}
const out={copyId:COPY_ID,project:PROJECT,version:VERSION,expectedMarker:MARKER,readOnly:true,ramWrites:0,durationRequestedMs:DURATION,intervalMs:INTERVAL,model:{purpose:'Determine whether V22 misses are true false positives or near-deadline late ACTIVE events without widening live warnings yet.',liveWarningPolicy:'Keep original 100/250ms live warning deadlines; warning expires on schedule, but measurement watch continues to500ms.',tupleSplit:'Record S/A/B tuple for every T16 FAST signal to identify weak variants.',targetPolicy:'live enemy+0x7E authoritative',geometry:'empirical ACTIVE-start distributions only; not hitboxes'},diagnostics:{...diag,typeSamples,rawMatchSamples,transitionEntries},ruleStats,tupleStats:Object.values(tupleStats).sort((a,b)=>b.signals-a.signals),attackClusters:Object.values(split).sort((a,b)=>b.count-a.count),watches,events:events.slice(-400),note:'Do not widen production horizons from V22 alone. If V23 late hits cluster just beyond deadlines, validate a widened shadow rule separately; if hard misses or weak tuples appear, split/drop those variants.'};
self.__WOF_FUTURE_DANGER_DEADLINE_TAIL_V23=out;console.log(MARKER);console.log(JSON.stringify(out,null,2));return out;
})().catch(e=>{console.error('[WOF-023] V23_ERROR',e);throw e;});