(()=>{
'use strict';
try{self.WOFDISPEDGE?.stop?.();}catch(_){}
const RAW='https://raw.githubusercontent.com/ouyong520/wof-ai-private/main/';
const sleep=ms=>new Promise(r=>setTimeout(r,ms));let stopped=false;
const load=async f=>{const r=await fetch(RAW+f+'?x='+Date.now(),{cache:'no-store'});if(!r.ok)throw new Error('fetch failed '+r.status+' '+f);return (0,eval)(await r.text());};
async function ensure(){if(!self.__WOF_DISPATCH_INCOMING){await load('wof_dispatch_incoming_edges.js');await WOFDISPIN.run();}if(!self.__WOF_ROM_LOC_CACHE)await load('wof_rom_focus_inspect.js');for(let i=0;i<300&&!self.__WOF_ROM_LOC_CACHE;i++)await sleep(50);if(!self.__WOF_ROM_LOC_CACHE)throw new Error('ROM cache unavailable');}
function env(){const MOD=_0x515056,C=self.__WOF_ROM_LOC_CACHE,M=MOD.HEAPU8,base=C.base,SW=!!C.swap16,MAX=Math.min(0x100000,M.length-base),DELTA=C.offlineDelta|0;const r8=o=>M[base+(SW?(o^1):o)]>>>0,r16=o=>((r8(o)<<8)|r8(o+1))>>>0,r32=o=>(r8(o)*0x1000000+r8(o+1)*0x10000+r8(o+2)*0x100+r8(o+3))>>>0,s8=v=>v&0x80?v-0x100:v,s16=v=>v&0x8000?v-0x10000:v,h=x=>'0x'+(x>>>0).toString(16).toUpperCase().padStart(6,'0'),off=x=>h((x-DELTA)>>>0),hw=x=>'0x'+(x&0xffff).toString(16).toUpperCase().padStart(4,'0');return{MAX,r8,r16,r32,s8,s16,h,off,hw};}
function eaWords(m,r,size){if(m<=4)return 0;if(m===5||m===6)return 1;if(m===7){if(r===0||r===2||r===3)return 1;if(r===1)return 2;if(r===4)return size==='L'?2:1;}return 0;}
function decode(E,p){const w=E.r16(p),g=w>>>12,m=(w>>3)&7,r=w&7;let len=2,kind='OP',writesD0=false,d0Root='',d0Transform='',cmp=false,bcc=false,terminal=false;
 if(w===0x4E75||w===0x4E73||w===0x4E77){kind='RET';terminal=true;}
 else if((w&0xFFC0)===0x4E80||(w&0xFFC0)===0x4EC0){kind=(w&0xFFC0)===0x4E80?'JSR':'JMP';len=2+eaWords(m,r,'L')*2;terminal=kind==='JMP';}
 else if(g===6){const d=w&255;len=d===0?4:2;kind=((w>>8)&15)===0?'BRA':((w>>8)&15)===1?'BSR':'BCC';bcc=kind==='BCC';if(kind==='BRA')terminal=true;}
 else if(g===1||g===2||g===3){const size=g===1?'B':g===2?'L':'W',sm=(w>>3)&7,sr=w&7,dm=(w>>6)&7,dr=(w>>9)&7;len=2+(eaWords(sm,sr,size)+eaWords(dm,dr,size))*2;if(dm===0&&dr===0){writesD0=true;if(sm===0)d0Root='D'+sr;else if(sm===1)d0Root='A'+sr;else if(sm===2)d0Root='(A'+sr+')';else if(sm===3)d0Root='(A'+sr+')+';else if(sm===4)d0Root='-(A'+sr+')';else if(sm===5)d0Root=E.s16(E.r16(p+2))+'(A'+sr+')';else if(sm===6)d0Root='indexed(A'+sr+')';else if(sm===7&&sr===4)d0Root='#IMM';else d0Root='EA';}}
 else if((w&0xF100)===0x7000){kind='MOVEQ';if(((w>>9)&7)===0){writesD0=true;d0Root='#'+E.s8(w&255);}}
 else if(g===14){const sz=(w>>6)&3;if(sz!==3){if((w&7)===0){writesD0=true;const cnt=((w>>9)&7)||8,dir=(w&0x0100)?'L':'R',typ=['AS','LS','ROX','RO'][(w>>3)&3];d0Transform=typ+dir+'#'+cnt;}}else len=2+eaWords(m,r,'W')*2;}
 else if(g===13||g===9||g===8||g===12||g===11){const sz=(w>>6)&3,size=sz===2?'L':sz===1?'W':'B';len=2+eaWords(m,r,size)*2;const dr=(w>>9)&7;if(g===11)cmp=true;else if(dr===0){writesD0=true;d0Transform=(g===13?'ADD':g===9?'SUB':g===8?'OR':'AND')+'-D0';}}
 else if(g===5){const sz=(w>>6)&3;if(sz===3&&m===1){len=4;kind='DBCC';bcc=true;}else{const size=sz===2?'L':sz===1?'W':'B';len=2+eaWords(m,r,size)*2;if(m===0&&r===0){writesD0=true;d0Transform=((w&0x0100)?'SUBQ':'ADDQ')+'#'+(((w>>9)&7)||8);}}}
 else if(g===0){const op=(w>>8)&15,sz=(w>>6)&3;if([0,2,4,6,10,12].includes(op)&&sz!==3){const size=sz===2?'L':sz===1?'W':'B';len=2+(size==='L'?4:2)+eaWords(m,r,size)*2;if(op===12)cmp=true;else if(m===0&&r===0){writesD0=true;d0Transform=['ORI','','ANDI','','SUBI','','ADDI','','','','EORI'][op]+'-D0';}}}
 else if(g===4){if((w&0xFFF8)===0x4E50)len=4;else if((w&0xFB80)===0x4880&&m>=2)len=4+eaWords(m,r,(w&0x40)?'L':'W')*2;else if((w&0xF1C0)===0x41C0)len=2+eaWords(m,r,'L')*2;else len=2+eaWords(m,r,'W')*2;}
 len=Math.max(2,len);return{at:p,w,len,next:p+len,kind,writesD0,d0Root,d0Transform,cmp,bcc,terminal};}
function linearBack(E,at,maxIns=48,maxBytes=0x120){let cur=at,rev=[];for(let n=0;n<maxIns&&cur>0;n++){const c=[];for(let p=Math.max(0,cur-10)&~1;p<cur;p+=2){const d=decode(E,p);if(d.next===cur)c.push(d);}if(!c.length)break;const d=c[c.length-1];rev.push(d);cur=d.at;if(at-cur>=maxBytes||d.kind==='RET'||d.kind==='BRA'||d.kind==='JMP')break;}return rev.reverse();}
const P=[{id:'P1',w:0xBE1C,l:0xFFBE1C},{id:'P2',w:0xBEFC,l:0xFFBEFC},{id:'P3',w:0xBFDC,l:0xFFBFDC}];
function playerEvidence(E,chain){const s=new Set(),refs=[];for(const d of chain){for(let q=d.at;q<Math.min(d.next,E.MAX-3);q+=2){const w=E.r16(q),l=E.r32(q);for(const p of P){if(w===p.w||l===p.l){s.add(p.id);refs.push(p.id+'@'+E.h(d.at));}}}}return{players:[...s],refs};}
function d0Prov(chain){let root='',rootAt='',trans=[];for(const d of chain){if(!d.writesD0)continue;if(d.d0Root){root=d.d0Root;rootAt=d.at;trans=[];}else if(d.d0Transform)trans.push(d.d0Transform+'@'+d.at.toString(16));}return{root,rootAt,trans};}
async function run(){stopped=false;await ensure();const E=env(),IN=self.__WOF_DISPATCH_INCOMING,rows=[];for(const e of IN.edges||[]){const at=parseInt(e.at,16),chain=linearBack(E,at),pe=playerEvidence(E,chain),pr=d0Prov(chain),cmp=chain.filter(x=>x.cmp).length,bcc=chain.filter(x=>x.bcc).length,score=pe.players.length*100+cmp*8+bcc*4+(pr.root&& !pr.root.startsWith('#')?25:0);rows.push({target:e.target,at:e.at,kind:e.kind,chainStart:chain.length?E.h(chain[0].at):'',chainIns:chain.length,players:pe.players.join(','),playerRefs:pe.refs.join(' '),cmp,bcc,d0Root:pr.root,d0RootAt:pr.rootAt!==''?E.h(pr.rootAt):'',d0Transforms:pr.trans.join(' '),score});}
 rows.sort((a,b)=>b.score-a.score||a.at.localeCompare(b.at));console.log('=== DISPATCH EDGE SELECTOR CANDIDATES ===');console.table(rows);
 const strong=rows.filter(r=>r.players&&r.cmp>0),top=strong[0]||rows[0]||null;const verdict={edges:rows.length,edgesWithPlayerRefs:rows.filter(r=>r.players).length,edgesWithCmp:rows.filter(r=>r.cmp).length,strongPlayerCmpEdges:strong.length,nonImmediateD0:rows.filter(r=>r.d0Root&&!r.d0Root.startsWith('#')).length,topAt:top?.at||'',topTarget:top?.target||'',topPlayers:top?.players||'',topCmp:top?.cmp??0,topBcc:top?.bcc??0,topD0Root:top?.d0Root||'',topD0Transforms:top?.d0Transforms||''};console.log('=== DISPATCH EDGE SELECTOR VERDICT ===');console.table([verdict]);
 if(strong.length)console.log('🎯 incoming edge 中出现玩家引用 + CMP；下一步只反汇编 top edge 所在路径，追玩家选择和 D0 state 决策。');else if(rows.some(r=>r.players))console.warn('⚠️ 有玩家引用但未和 CMP 同路径；下一步扩展 top player edge 的 CFG 分支范围。');else console.warn('⚠️ 44 条 dispatcher incoming edge 的局部真实路径没有直接玩家引用；下一步从这些 edge 的上游 caller/branch predecessors 扩一层。');
 const out={version:'wof-dispatch-edge-selector-v1',verdict,rows};self.__WOF_DISPATCH_EDGE_SELECTOR=out;return out;}
self.WOFDISPEDGE={version:'wof-dispatch-edge-selector-v1',run,stop(){stopped=true;}};console.log('✅ WOF dispatcher edge selector scan loaded');console.log('执行 await WOFDISPEDGE.run()');
})();