(()=>{
'use strict';
try{self.WOFD0TRACE?.stop?.();}catch(_){}
const RAW='https://raw.githubusercontent.com/ouyong520/wof-ai-private/main/';
const sleep=ms=>new Promise(r=>setTimeout(r,ms));let stopped=false;
const load=async f=>{const r=await fetch(RAW+f+'?x='+Date.now(),{cache:'no-store'});if(!r.ok)throw new Error('fetch failed '+r.status+' '+f);return (0,eval)(await r.text());};
async function ensure(){if(!self.__WOF_ROM_LOC_CACHE)await load('wof_rom_focus_inspect.js');for(let i=0;i<300&&!self.__WOF_ROM_LOC_CACHE;i++)await sleep(50);if(!self.__WOF_ROM_LOC_CACHE)throw new Error('ROM cache unavailable');}
function env(){const MOD=_0x515056,C=self.__WOF_ROM_LOC_CACHE,M=MOD.HEAPU8,base=C.base,SW=!!C.swap16,MAX=Math.min(0x100000,M.length-base),DELTA=C.offlineDelta|0;const r8=o=>M[base+(SW?(o^1):o)]>>>0,r16=o=>((r8(o)<<8)|r8(o+1))>>>0,r32=o=>(r8(o)*0x1000000+r8(o+1)*0x10000+r8(o+2)*0x100+r8(o+3))>>>0,s8=v=>v&0x80?v-0x100:v,s16=v=>v&0x8000?v-0x10000:v,h=x=>'0x'+(x>>>0).toString(16).toUpperCase().padStart(6,'0'),off=x=>h((x-DELTA)>>>0),hw=x=>'0x'+(x&0xffff).toString(16).toUpperCase().padStart(4,'0');return{MAX,r8,r16,r32,s8,s16,h,off,hw};}
function eaWords(m,r,size){if(m<=4)return 0;if(m===5||m===6)return 1;if(m===7){if(r===0||r===2||r===3)return 1;if(r===1)return 2;if(r===4)return size==='L'?2:1;}return 0;}
function eaText(E,p,m,r,size){if(m===0)return'D'+r;if(m===1)return'A'+r;if(m===2)return'(A'+r+')';if(m===3)return'(A'+r+')+';if(m===4)return'-(A'+r+')';if(m===5)return E.s16(E.r16(p))+'(A'+r+')';if(m===6){const x=E.r16(p),ix=(x&0x8000?'A':'D')+((x>>12)&7)+(x&0x0800?'.L':'.W'),d=E.s8(x&255);return d+'(A'+r+','+ix+')';}if(m===7&&r===0)return'$'+E.hw(E.r16(p))+'.W';if(m===7&&r===1)return'$'+E.h(E.r32(p))+'.L';if(m===7&&r===2)return E.s16(E.r16(p))+'(PC)';if(m===7&&r===3){const x=E.r16(p),ix=(x&0x8000?'A':'D')+((x>>12)&7)+(x&0x0800?'.L':'.W'),d=E.s8(x&255);return d+'(PC,'+ix+')';}if(m===7&&r===4){if(size==='L')return'#'+E.h(E.r32(p));return'#'+E.hw(E.r16(p));}return'EA';}
function decode(E,p){const w=E.r16(p),g=w>>>12,m=(w>>3)&7,r=w&7;let len=2,text='DC.W '+E.hw(w),writesD0=false,d0Source='',kind='OP';
 if(g===1||g===2||g===3){const size=g===1?'B':g===2?'L':'W',sm=(w>>3)&7,sr=w&7,dm=(w>>6)&7,dr=(w>>9)&7,sw=eaWords(sm,sr,size),dw=eaWords(dm,dr,size),src=eaText(E,p+2,sm,sr,size),dst=eaText(E,p+2+sw*2,dm,dr,size);len=2+(sw+dw)*2;text='MOVE.'+size+' '+src+','+dst;kind='MOVE';if(dm===0&&dr===0){writesD0=true;d0Source=src;}}
 else if((w&0xF100)===0x7000){const dr=(w>>9)&7,imm=E.s8(w&255);text='MOVEQ #'+imm+',D'+dr;kind='MOVEQ';if(dr===0){writesD0=true;d0Source='#'+imm;}}
 else if(g===14){const sz=(w>>6)&3,reg=w&7;if(sz!==3){const cnt=(w>>9)&7||8,dir=(w&0x0100)?'L':'R',typ=(w>>3)&3,op=['AS','LS','ROX','RO'][typ]+dir,size=sz===2?'L':sz===1?'W':'B';text=op+'.'+size+' #'+cnt+',D'+reg;if(reg===0){writesD0=true;d0Source='D0 '+op+' #'+cnt;}}else{const ew=eaWords(m,r,'W');len=2+ew*2;text='SHIFT/ROT EA';}}
 else if(g===13||g===9||g===8||g===12||g===11){const dr=(w>>9)&7,op=g===13?'ADD':g===9?'SUB':g===8?'OR':g===12?'AND':'CMP',sz=(w>>6)&3,size=sz===2?'L':sz===1?'W':'B',src=eaText(E,p+2,m,r,size);len=2+eaWords(m,r,size)*2;text=op+'.'+size+' '+src+',D'+dr;if(dr===0&&op!=='CMP'){writesD0=true;d0Source=op+'('+src+')';}}
 else if(g===5&&((w>>6)&3)!==3){const q=((w>>9)&7)||8,sub=!!(w&0x0100),sz=(w>>6)&3,size=sz===2?'L':sz===1?'W':'B',dst=eaText(E,p+2,m,r,size);len=2+eaWords(m,r,size)*2;text=(sub?'SUBQ.':'ADDQ.')+size+' #'+q+','+dst;if(m===0&&r===0){writesD0=true;d0Source=(sub?'D0-'+q:'D0+'+q);}}
 else if(g===0){const op=(w>>8)&15,sz=(w>>6)&3,size=sz===2?'L':sz===1?'W':'B';if([0,2,4,6,10,12].includes(op)&&sz!==3){const immWords=size==='L'?2:1,imm=size==='L'?E.h(E.r32(p+2)):E.hw(E.r16(p+2)),dst=eaText(E,p+2+immWords*2,m,r,size),nm={0:'ORI',2:'ANDI',4:'SUBI',6:'ADDI',10:'EORI',12:'CMPI'}[op];len=2+immWords*2+eaWords(m,r,size)*2;text=nm+'.'+size+' #'+imm+','+dst;if(m===0&&r===0&&nm!=='CMPI'){writesD0=true;d0Source=nm+' D0';}}}
 else if((w&0xFFC0)===0x4E80){const ew=eaWords(m,r,'L');len=2+ew*2;text='JSR '+eaText(E,p+2,m,r,'L');kind='JSR';}
 else if((w&0xFFC0)===0x4EC0){const ew=eaWords(m,r,'L');len=2+ew*2;text='JMP '+eaText(E,p+2,m,r,'L');kind='JMP';}
 else if(g===6){const cc=(w>>8)&15,d=w&255;len=d===0?4:2;const disp=d===0?E.s16(E.r16(p+2)):E.s8(d),t=p+2+disp;text=(cc===0?'BRA':cc===1?'BSR':'Bcc')+' '+E.h(t);kind='BR';}
 return{at:p,w,len,text,writesD0,d0Source,kind};}
function seq(E,start,end){const out=[];let p=start&~1,guard=0;while(p<end&&guard++<160){const d=decode(E,p);out.push({at:E.h(p),offline:E.off(p),word:E.hw(d.w),len:d.len,text:d.text,writesD0:d.writesD0,d0Source:d.d0Source,mark:(p===0x25C2||p===0x25D4)?'<<< L2 DISPATCH':''});p+=Math.max(2,d.len);}return out;}
function rawD0Writers(E,lo,hi){const out=[];for(let p=lo&~1;p<hi;p+=2){const d=decode(E,p);if(d.writesD0)out.push({at:E.h(p),offline:E.off(p),word:E.hw(d.w),text:d.text,d0Source:d.d0Source,distanceTo25C2:0x25C2-p,distanceTo25D4:0x25D4-p});}return out;}
async function run(){stopped=false;await ensure();const E=env();console.log('🎯 WOF level2 dispatcher D0 producer trace v1');
 const a=seq(E,0x25B6,0x25C8),b=seq(E,0x25C8,0x25DA);console.log('=== DISPATCH ROUTINE 0x25B6 ===');console.table(a);console.log('=== DISPATCH ROUTINE 0x25C8 ===');console.table(b);
 const cand=rawD0Writers(E,0x2580,0x25D8).sort((x,y)=>Math.min(Math.abs(x.distanceTo25C2),Math.abs(x.distanceTo25D4))-Math.min(Math.abs(y.distanceTo25C2),Math.abs(y.distanceTo25D4)));console.log('=== D0 WRITER CANDIDATES NEAR BOTH DISPATCHERS ===');console.table(cand);
 const before1=cand.filter(x=>parseInt(x.at,16)<0x25C2).sort((x,y)=>parseInt(y.at,16)-parseInt(x.at,16))[0]||null;const before2=cand.filter(x=>parseInt(x.at,16)<0x25D4).sort((x,y)=>parseInt(y.at,16)-parseInt(x.at,16))[0]||null;
 const verdict={dispatch1:'0x0025C2',dispatch2:'0x0025D4',nearestD0Writer1:before1?.at||'',nearestD0Source1:before1?.d0Source||'',nearestD0Text1:before1?.text||'',nearestD0Writer2:before2?.at||'',nearestD0Source2:before2?.d0Source||'',nearestD0Text2:before2?.text||'',sameProducer:!!(before1&&before2&&before1.at===before2.at),candidateCount:cand.length};console.log('=== DISPATCH D0 TRACE VERDICT ===');console.table([verdict]);
 const out={version:'wof-dispatch-d0-trace-v1',verdict,dispatch25B6:a,dispatch25C8:b,candidates:cand};self.__WOF_DISPATCH_D0_TRACE=out;return out;}
self.WOFD0TRACE={version:'wof-dispatch-d0-trace-v1',run,stop(){stopped=true;}};console.log('✅ WOF dispatcher D0 trace v1 loaded');console.log('执行 await WOFD0TRACE.run()');
})();