(async()=>{
'use strict';
const COPY_ID='WOF-041R';
const PROJECT='WOF-AI-PRIVATE';
const VERSION='wof-future-danger-cycle-validator-v41r';
const MARKER='=== WOF FUTURE DANGER CYCLE VALIDATOR V41R JSON ===';
const BASE={copyId:'WOF-038',project:'WOF-AI-PRIVATE',version:'wof-future-danger-descriptor-family-validator-v38',marker:'=== WOF FUTURE DANGER DESCRIPTOR FAMILY VALIDATOR V38 JSON ==='};
const BASE_URL='https://raw.githubusercontent.com/ouyong520/wof-ai-private/main/wof_future_danger_descriptor_family_validator_v38.js';
console.log(`[${COPY_ID}] ${PROJECT} ${VERSION}`);
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const good=v=>!!(v&&v.HEAPU8 instanceof Uint8Array&&v.HEAPU32 instanceof Uint32Array&&v.HEAPU8.buffer===v.HEAPU32.buffer);
async function ensureModule(){if(good(self._0x515056))return self._0x515056;const until=performance.now()+8000;while(performance.now()<until){for(const k of Object.getOwnPropertyNames(self)){let v;try{v=self[k]}catch(_){continue}if(good(v)){self._0x515056=v;self.__WOF_MODULE_GLOBAL_KEY=k;return v;}}await sleep(50);}throw new Error(`[${COPY_ID}] WASM module not found. Select a live gstyphoon.js Worker.`);}
const MOD=await ensureModule(),M=MOD.HEAPU8,R=MOD.HEAPU32?.[0x2e39e4>>>2]>>>0;if(!R)throw new Error(`[${COPY_ID}] CPS RAM base missing`);
const B=a=>M[R+((((a-0xFF0000)&0xffff)^1))]>>>0,U16=a=>((B(a)<<8)|B(a+1))>>>0,U32=a=>(B(a)*0x1000000+B(a+1)*0x10000+B(a+2)*0x100+B(a+3))>>>0,S32=a=>{const v=U32(a);return v>=0x80000000?v-0x100000000:v;},X=a=>Math.round(S32(a+4)/65536),Y=a=>Math.round(S32(a+8)/65536);
const ENEMY=0xFFC0BC,STRIDE=0xE0,SLOTS=20,PBASE={0:0xFFBE1C,4:0xFFBEFC,8:0xFFBFDC},PN={0:'P1',4:'P2',8:'P3'};
const side=dx=>dx==null?null:dx<-4?'LEFT':dx>4?'RIGHT':'CENTER';
function snap(i){const a=ENEMY+i*STRIDE,type=U16(a+0x20);if(type>=47)return null;const fe=U32(a+0x12),nx=U32(a+0x2C);if(!fe&&!nx)return null;const t=U16(a+0x7E),pb=PBASE[t],ex=X(a),tx=pb?X(pb):null,dx=tx==null?null:tx-ex;return{slot:i,type,target7E:t,target:PN[t]||null,side:side(dx),state99:B(a+0x99),action2A:B(a+0x2A),b2B:B(a+0x2B),body:U16(a+0x6E),attack:U16(a+0x70),frameEnd:fe,next:nx,value30:U32(a+0x30),timer34:U16(a+0x34),payload6C:U16(a+0x6C)};}
const fp=s=>`S${s.state99}/A${s.action2A}/B${s.b2B}|BODY${s.body}|FE${s.frameEnd.toString(16)}|NX${s.next.toString(16)}|V${s.value30.toString(16)}|TM${s.timer34}|P6C${s.payload6C}`;
const r1=x=>Math.round(x*10)/10,med=a=>{if(!a.length)return null;const b=[...a].sort((x,y)=>x-y),m=b.length>>1;return b.length%2?b[m]:+(0.5*(b[m-1]+b[m])).toFixed(1);};
async function runCycleMiner(){const DURATION=120000,INTERVAL=10,start=performance.now(),prev=new Map(),cycles=new Map(),agg=new Map();const diag={polls:0,enemySamples:0,attackZeroStarts:0,activeEdges:0,cycleStatesObserved:0,resolvedCycles:0};
  const add=(s,active,t,c)=>{diag.resolvedCycles++;for(const rec of c.states.values()){const first=r1(t-rec.firstAt),last=r1(t-rec.lastAt);if(first<0||last<0)continue;const k=`T${s.type}|A${active}|${rec.signature}`,q=agg.get(k)||{type:s.type,activeAttack:active,signature:rec.signature,cycleCount:0,firstLeadSamples:[],lastLeadSamples:[],targetSame:0,targetTotal:0,sideSame:0,sideTotal:0};q.cycleCount++;if(q.firstLeadSamples.length<60)q.firstLeadSamples.push(first);if(q.lastLeadSamples.length<60)q.lastLeadSamples.push(last);q.targetTotal++;if(rec.lastTarget7E===s.target7E)q.targetSame++;if(rec.lastSide!=null&&s.side!=null){q.sideTotal++;if(rec.lastSide===s.side)q.sideSame++;}agg.set(k,q);}};
  await new Promise(resolve=>{const id=setInterval(()=>{const t=performance.now()-start;diag.polls++;for(let i=0;i<SLOTS;i++){const s=snap(i),p=prev.get(i)||null;if(!s){prev.delete(i);cycles.delete(i);continue;}diag.enemySamples++;if(p&&p.type!==s.type)cycles.delete(i);if(s.attack===0){let c=cycles.get(i);if(!c||!p||p.type!==s.type||p.attack!==0){c={type:s.type,startAt:t,states:new Map()};cycles.set(i,c);diag.attackZeroStarts++;}const sig=fp(s);let rec=c.states.get(sig);if(!rec){rec={signature:sig,firstAt:t,lastAt:t,firstTarget7E:s.target7E,lastTarget7E:s.target7E,firstSide:s.side,lastSide:s.side,samples:1};c.states.set(sig,rec);diag.cycleStatesObserved++;}else{rec.lastAt=t;rec.lastTarget7E=s.target7E;rec.lastSide=s.side;rec.samples++;}}if(p&&p.type===s.type&&p.attack===0&&s.attack!==0){diag.activeEdges++;const c=cycles.get(i);if(c)add(s,s.attack,t,c);cycles.delete(i);}prev.set(i,s);}if(t>=DURATION){clearInterval(id);resolve();}},INTERVAL);});
  const top=[...agg.values()].map(q=>{q.firstLeadSamples.sort((a,b)=>a-b);q.lastLeadSamples.sort((a,b)=>a-b);return{...q,attackZeroOnly:true,targetSameRate:q.targetTotal?+(q.targetSame/q.targetTotal).toFixed(3):null,sideStableRate:q.sideTotal?+(q.sideSame/q.sideTotal).toFixed(3):null,firstLeadMin:q.firstLeadSamples[0]??null,firstLeadMedian:med(q.firstLeadSamples),firstLeadMax:q.firstLeadSamples.at(-1)??null,lastLeadMin:q.lastLeadSamples[0]??null,lastLeadMedian:med(q.lastLeadSamples),lastLeadMax:q.lastLeadSamples.at(-1)??null};}).sort((a,b)=>b.cycleCount-a.cycleCount||(b.lastLeadMedian??0)-(a.lastLeadMedian??0)).slice(0,100);
  return{durationRequestedMs:DURATION,actualDurationMs:r1(performance.now()-start),intervalMs:INTERVAL,diagnostics:diag,cyclePrecursorTop:top};}
async function runBase(){let code=await fetch(BASE_URL+'?x='+Date.now(),{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error('base validator fetch '+r.status);return r.text();});
  code=code.replace("console.log(`[${COPY_ID}] ${PROJECT} ${VERSION}`);",'');
  code=code.replace("self.__WOF_V38_RESULT=out;console.log(MARKER);console.log(JSON.stringify(out,null,2));return out;","self.__WOF_V38_RESULT=out;return out;");
  code=code.replace("id:'T16_6432_B4_40',status:'production-shadow'","id:'T16_B4_DANGER_40',status:'production-shadow-imminent-danger'");
  code=code.replace("id:'T20_5136_B0_TO_B255_700',status:'production-shadow-candidate',horizon:700","id:'T20_5136_B0_TO_B255_850',status:'production-shadow-candidate',horizon:850");
  code=code.replace("id:'D867BA_3232_TM6_120',status:'prospective-descriptor-family',horizon:120","id:'D867BA_3232_TM6_220',status:'production-shadow-candidate',horizon:220");
  code=code.replace("id:'D8811E_3232_TM6_120',status:'prospective-descriptor-family',horizon:120","id:'D8811E_3232_TM6_120',status:'production-shadow',horizon:120");
  const out=await(0,eval)(code),ok=!!out&&out.copyId===BASE.copyId&&out.project===BASE.project&&out.version===BASE.version&&out.expectedMarker===BASE.marker&&out.readOnly===true&&out.ramWrites===0;if(!ok)throw new Error(`[${COPY_ID}] embedded WOF-038 identity mismatch`);return out;}
const [base,cycle]=await Promise.all([runBase(),runCycleMiner()]);
const out={copyId:COPY_ID,project:PROJECT,version:VERSION,expectedMarker:MARKER,readOnly:true,ramWrites:0,durationRequestedMs:120000,actualDurationMs:Math.max(base.actualDurationMs||0,cycle.actualDurationMs||0),intervalMs:10,jitterToleranceMs:base.jitterToleranceMs,model:{purpose:'Prospective production-shadow validation plus same-cycle attack-zero precursor mining. The cycle miner only attributes states observed while enemy+0x70==0 in the same cycle that later transitions 0->nonzero.',t16Policy:'T16 exact B4 is treated as imminent-danger production-shadow. expectedAttackRate remains an A6432 specificity audit, not a requirement for danger validity.',d867Policy:'D867BA descriptor family uses a 220ms warning horizon after WOF-040 observed one clean A3232 at 200ms; do not derive a distance timing law.',d881Policy:'D8811E descriptor family is production-shadow after clean cross-type/multi-target WOF-040 evidence.',t20Policy:'T20 B0->B255 A5136 warning horizon is 850ms; still coarse early warning, not countdown.',cyclePolicy:'cyclePrecursorTop is same-cycle forward-chain evidence, unlike fixed-lag fingerprintTop which remains retrospective/correlation only.',targetPolicy:'live enemy+0x7E authoritative',activeConvention:'enemy+0x70 U16 0->nonzero; not exact damage/hitbox onset'},diagnostics:{...base.diagnostics,cycleMiner:cycle.diagnostics},ruleStats:base.ruleStats,terminalTop:base.terminalTop,fingerprintTop:base.fingerprintTop,cyclePrecursorTop:cycle.cyclePrecursorTop,watches:base.watches,events:base.events};
self.__WOF_V41R_RESULT=out;console.log(MARKER);console.log(JSON.stringify(out,null,2));return out;
})().catch(e=>{console.error('[WOF-041R] ERROR',e);throw e;});