(async()=>{
'use strict';
const COPY_ID='WOF-039';
const PROJECT='WOF-AI-PRIVATE';
const VERSION='wof-future-danger-multiroom-batch-v39';
const MARKER='=== WOF FUTURE DANGER MULTIROOM BATCH V39 JSON ===';
const EMBED={copyId:'WOF-038',project:'WOF-AI-PRIVATE',version:'wof-future-danger-descriptor-family-validator-v38',marker:'=== WOF FUTURE DANGER DESCRIPTOR FAMILY VALIDATOR V38 JSON ==='};
const CFG={db:'wof-future-danger-multiroom-v1',dbVersion:1,controlStore:'control',roomStore:'rooms',activeKey:'active',maxRooms:5,joinWindowMs:45000,embeddedDurationMs:120000,finalizeGraceMs:150000,heartbeatMs:5000,contextSampleMs:250,contextSnapshotMs:2000,maxPresenceChanges:80,maxContextEntries:180,validatorUrl:'https://raw.githubusercontent.com/ouyong520/wof-ai-private/main/wof_future_danger_descriptor_family_validator_v38.js'};
console.log(`[${COPY_ID}] ${PROJECT} ${VERSION}`);
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const rid=()=>{try{return crypto.randomUUID().slice(0,12)}catch(_){return Math.random().toString(36).slice(2,14)}};
function openDb(){return new Promise((res,rej)=>{const q=indexedDB.open(CFG.db,CFG.dbVersion);q.onupgradeneeded=()=>{const db=q.result;if(!db.objectStoreNames.contains(CFG.controlStore))db.createObjectStore(CFG.controlStore,{keyPath:'key'});if(!db.objectStoreNames.contains(CFG.roomStore)){const s=db.createObjectStore(CFG.roomStore,{keyPath:'key'});s.createIndex('batchId','batchId',{unique:false});}};q.onsuccess=()=>res(q.result);q.onerror=()=>rej(q.error);});}
function reqp(req){return new Promise((res,rej)=>{req.onsuccess=()=>res(req.result);req.onerror=()=>rej(req.error);});}
async function getControl(db){const tx=db.transaction(CFG.controlStore,'readonly');return reqp(tx.objectStore(CFG.controlStore).get(CFG.activeKey));}
async function putRoom(db,row){return new Promise((res,rej)=>{const tx=db.transaction(CFG.roomStore,'readwrite');tx.objectStore(CFG.roomStore).put(row);tx.oncomplete=()=>res();tx.onerror=()=>rej(tx.error);tx.onabort=()=>rej(tx.error||new Error('room tx aborted'));});}
async function getBatchRooms(db,batchId){const tx=db.transaction(CFG.roomStore,'readonly'),s=tx.objectStore(CFG.roomStore);if(s.indexNames.contains('batchId'))return reqp(s.index('batchId').getAll(batchId));const all=await reqp(s.getAll());return all.filter(x=>x.batchId===batchId);}
async function joinBatch(db){const now=Date.now(),roomId='r-'+rid();return new Promise((resolve,reject)=>{const tx=db.transaction([CFG.controlStore,CFG.roomStore],'readwrite'),cs=tx.objectStore(CFG.controlStore),rs=tx.objectStore(CFG.roomStore);let answer=null;const q=cs.get(CFG.activeKey);q.onerror=()=>reject(q.error);q.onsuccess=()=>{let c=q.result;const stale=!c||c.finalizedAt||now>c.joinUntil||now>(c.createdAt||0)+10*60*1000;if(stale){const batchId='b-'+rid();c={key:CFG.activeKey,batchId,createdAt:now,joinUntil:now+CFG.joinWindowMs,finalizeDeadline:now+CFG.joinWindowMs+CFG.finalizeGraceMs,maxRooms:CFG.maxRooms,roomKeys:[],finalizedBy:null,finalizedAt:null,combined:null};}if(c.roomKeys.length>=CFG.maxRooms){reject(new Error(`[${COPY_ID}] active batch ${c.batchId} already has ${CFG.maxRooms} rooms`));try{tx.abort()}catch(_){}return;}const ordinal=c.roomKeys.length+1,roomKey=`${c.batchId}|${roomId}`;c.roomKeys.push(roomKey);cs.put(c);const row={key:roomKey,batchId:c.batchId,roomId,ordinal,status:'running',copyId:COPY_ID,project:PROJECT,version:VERSION,readOnly:true,ramWrites:0,startedAt:now,heartbeatAt:now,completedAt:null,workerLocation:String(self.location?.href||''),playerCountHist:[0,0,0,0],peakPlayers:0,presenceChanges:[],contextTimeline:[],embeddedResult:null,embeddedValidation:null,error:null};rs.put(row);answer={control:c,row};};tx.oncomplete=()=>resolve(answer);tx.onerror=()=>reject(tx.error);tx.onabort=()=>{};});}
const good=v=>!!(v&&v.HEAPU8 instanceof Uint8Array&&v.HEAPU32 instanceof Uint32Array&&v.HEAPU8.buffer===v.HEAPU32.buffer);
async function ensureModule(){if(good(self._0x515056))return self._0x515056;const until=performance.now()+8000;while(performance.now()<until){for(const k of Object.getOwnPropertyNames(self)){let v;try{v=self[k]}catch(_){continue}if(good(v)){self._0x515056=v;self.__WOF_MODULE_GLOBAL_KEY=k;return v;}}await sleep(50);}throw new Error(`[${COPY_ID}] WASM module not found. Select a live gstyphoon.js Worker.`);}
const db=await openDb();const joined=await joinBatch(db),control=joined.control,row=joined.row;console.log(`🟢 [${COPY_ID}] joined ${control.batchId} room ${row.ordinal}/${CFG.maxRooms}; paste SAME command into the other room Workers before join window closes.`);
const MOD=await ensureModule(),M=MOD.HEAPU8,R=MOD.HEAPU32?.[0x2e39e4>>>2]>>>0;if(!R)throw new Error(`[${COPY_ID}] CPS RAM base missing`);const B=a=>M[R+((((a-0xFF0000)&0xffff)^1))]>>>0;const U16=a=>((B(a)<<8)|B(a+1))>>>0;const U32=a=>(B(a)*0x1000000+B(a+1)*0x10000+B(a+2)*0x100+B(a+3))>>>0;const PBASE=[0xFFBE1C,0xFFBEFC,0xFFBFDC],PN=['P1','P2','P3'],ENEMY=0xFFC0BC,STRIDE=0xE0,SLOTS=20;
function playersPresent(){const a=[];for(let i=0;i<3;i++)if(B(PBASE[i]))a.push(PN[i]);return a;}
function contextSnapshot(){const players=playersPresent(),types={},targets={P1:0,P2:0,P3:0,other:0};for(let i=0;i<SLOTS;i++){const a=ENEMY+i*STRIDE,type=U16(a+0x20),fe=U32(a+0x12),nx=U32(a+0x2C);if(type>=47||(!fe&&!nx))continue;types['T'+type]=(types['T'+type]||0)+1;const t=U16(a+0x7E);if(t===0)targets.P1++;else if(t===4)targets.P2++;else if(t===8)targets.P3++;else targets.other++;}return{players,playerCount:players.length,enemyTypes:types,targetCounts:targets};}
let lastPresence='',lastContext='',lastContextAt=0,contextTimer=null,heartbeatTimer=null;function sampleContext(force=false){const now=Date.now(),c=contextSnapshot(),pk=c.players.join(',');row.playerCountHist[c.playerCount]=(row.playerCountHist[c.playerCount]||0)+1;row.peakPlayers=Math.max(row.peakPlayers,c.playerCount);if(pk!==lastPresence){lastPresence=pk;if(row.presenceChanges.length<CFG.maxPresenceChanges)row.presenceChanges.push({tMs:now-row.startedAt,players:c.players,playerCount:c.playerCount});}if(force||now-lastContextAt>=CFG.contextSnapshotMs){const sig=JSON.stringify([c.players,c.enemyTypes,c.targetCounts]);if(sig!==lastContext||force){lastContext=sig;lastContextAt=now;if(row.contextTimeline.length<CFG.maxContextEntries)row.contextTimeline.push({tMs:now-row.startedAt,...c});}}}
contextTimer=setInterval(()=>{try{sampleContext(false)}catch(e){}},CFG.contextSampleMs);sampleContext(true);heartbeatTimer=setInterval(()=>{row.heartbeatAt=Date.now();putRoom(db,row).catch(()=>{});},CFG.heartbeatMs);
async function runEmbedded(){let code=await fetch(CFG.validatorUrl+'?x='+Date.now(),{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error('validator fetch '+r.status);return r.text();});code=code.replace("console.log(`[${COPY_ID}] ${PROJECT} ${VERSION}`);",'');code=code.replace("self.__WOF_V38_RESULT=out;console.log(MARKER);console.log(JSON.stringify(out,null,2));return out;","self.__WOF_V38_RESULT=out;return out;");const out=await(0,eval)(code);const ok=!!out&&out.copyId===EMBED.copyId&&out.project===EMBED.project&&out.version===EMBED.version&&out.expectedMarker===EMBED.marker&&out.readOnly===true&&out.ramWrites===0;return{ok,out};}
try{const e=await runEmbedded();row.embeddedValidation={ok:e.ok,expected:EMBED,actual:e.out?{copyId:e.out.copyId,project:e.out.project,version:e.out.version,expectedMarker:e.out.expectedMarker,readOnly:e.out.readOnly,ramWrites:e.out.ramWrites}:null};if(!e.ok)throw new Error(`[${COPY_ID}] embedded WOF-038 identity mismatch`);row.embeddedResult=e.out;row.status='complete';row.completedAt=Date.now();row.heartbeatAt=row.completedAt;sampleContext(true);await putRoom(db,row);console.log(`✅ [${COPY_ID}] ${control.batchId} room ${row.ordinal} complete; waiting for batch merge.`);}catch(e){row.status='error';row.error=String(e?.stack||e);row.completedAt=Date.now();row.heartbeatAt=row.completedAt;try{sampleContext(true)}catch(_){}await putRoom(db,row);console.error(`[${COPY_ID}] room ${row.ordinal} failed`,e);}finally{if(contextTimer)clearInterval(contextTimer);if(heartbeatTimer)clearInterval(heartbeatTimer);}
const addObj=(dst,src)=>{for(const [k,v] of Object.entries(src||{}))dst[k]=(dst[k]||0)+(Number(v)||0);return dst;};
function mergeDiagnostics(rooms){const d={polls:0,enemySamples:0,activeEdges:0,signals:0,strictHits:0,jitterBandHits:0,realLateHits:0,hardMisses:0,censored:0,retargets:0,typeSamples:{},attackTypeCounts:{},rawMatchSamples:{},transitionEntries:{}};for(const r of rooms){const x=r.embeddedResult?.diagnostics;if(!x)continue;for(const k of ['polls','enemySamples','activeEdges','signals','strictHits','jitterBandHits','realLateHits','hardMisses','censored','retargets'])d[k]+=Number(x[k]||0);addObj(d.typeSamples,x.typeSamples);addObj(d.attackTypeCounts,x.attackTypeCounts);addObj(d.rawMatchSamples,x.rawMatchSamples);addObj(d.transitionEntries,x.transitionEntries);}return d;}
function mergeRules(rooms){const out={};for(const r of rooms){const rs=r.embeddedResult?.ruleStats||{};for(const [id,q] of Object.entries(rs)){const z=out[id]||(out[id]={rule:id,status:q.status,horizonMs:q.horizonMs,tailMs:q.tailMs,jitterToleranceMs:q.jitterToleranceMs,signals:0,evaluable:0,strictHit:0,jitterBandHit:0,realLateHit:0,hardMiss:0,censored:0,expectedAttack:0,expectedAttackTotal:0,targetSame:0,targetTotal:0,sideSame:0,sideTotal:0,leads:[],attackCounts:{},entryTargetCounts:{},entrySideCounts:{},entryTypeCounts:{},roomsWithSignal:[],roomsWithRawMatch:[],perRoom:[]});for(const k of ['signals','evaluable','strictHit','jitterBandHit','realLateHit','hardMiss','censored','expectedAttack','expectedAttackTotal','targetSame','targetTotal','sideSame','sideTotal'])z[k]+=Number(q[k]||0);z.leads.push(...(q.leads||[]));for(const a of q.attackCounts||[])z.attackCounts[String(a.attack)]=(z.attackCounts[String(a.attack)]||0)+Number(a.count||0);addObj(z.entryTargetCounts,q.entryTargetCounts);addObj(z.entrySideCounts,q.entrySideCounts);addObj(z.entryTypeCounts,q.entryTypeCounts);if(q.signals>0)z.roomsWithSignal.push(r.roomId);if((r.embeddedResult?.diagnostics?.rawMatchSamples?.[id]||0)>0)z.roomsWithRawMatch.push(r.roomId);z.perRoom.push({roomId:r.roomId,ordinal:r.ordinal,signals:q.signals,evaluable:q.evaluable,strictHit:q.strictHit,jitterBandHit:q.jitterBandHit,realLateHit:q.realLateHit,hardMiss:q.hardMiss,censored:q.censored,expectedAttackRate:q.expectedAttackRate,targetSameRate:q.targetSameRate,sideStableRate:q.sideStableRate,leads:q.leads,entryTypeCounts:q.entryTypeCounts,entryTargetCounts:q.entryTargetCounts,entrySideCounts:q.entrySideCounts});}}for(const z of Object.values(out)){z.strictRate=z.evaluable?+(z.strictHit/z.evaluable).toFixed(3):null;z.jitterCorrectedRate=z.evaluable?+((z.strictHit+z.jitterBandHit)/z.evaluable).toFixed(3):null;z.tailHitRate=z.evaluable?+((z.strictHit+z.jitterBandHit+z.realLateHit)/z.evaluable).toFixed(3):null;z.expectedAttackRate=z.expectedAttackTotal?+(z.expectedAttack/z.expectedAttackTotal).toFixed(3):null;z.targetSameRate=z.targetTotal?+(z.targetSame/z.targetTotal).toFixed(3):null;z.sideStableRate=z.sideTotal?+(z.sideSame/z.sideTotal).toFixed(3):null;z.leads.sort((a,b)=>a-b);z.attackCounts=Object.entries(z.attackCounts).map(([attack,count])=>({attack:+attack,count})).sort((a,b)=>b.count-a.count);}return out;}
async function claimFinalizer(db,batchId,roomKey){return new Promise((resolve,reject)=>{const tx=db.transaction(CFG.controlStore,'readwrite'),s=tx.objectStore(CFG.controlStore);let won=false;const q=s.get(CFG.activeKey);q.onsuccess=()=>{const c=q.result;if(c&&c.batchId===batchId&&!c.finalizedBy){c.finalizedBy=roomKey;c.finalizedAt=Date.now();s.put(c);won=true;}};q.onerror=()=>reject(q.error);tx.oncomplete=()=>resolve(won);tx.onerror=()=>reject(tx.error);});}
async function saveCombined(db,batchId,out){return new Promise((res,rej)=>{const tx=db.transaction(CFG.controlStore,'readwrite'),s=tx.objectStore(CFG.controlStore),q=s.get(CFG.activeKey);q.onsuccess=()=>{const c=q.result;if(c&&c.batchId===batchId){c.combined=out;c.finalizedAt=Date.now();s.put(c);}};q.onerror=()=>rej(q.error);tx.oncomplete=()=>res();tx.onerror=()=>rej(tx.error);});}
async function buildCombined(ctrl,rooms){const complete=rooms.filter(r=>r.status==='complete'&&r.embeddedValidation?.ok),errors=rooms.filter(r=>r.status==='error'),unfinished=rooms.filter(r=>r.status==='running');const playerCountHist=[0,0,0,0];for(const r of rooms)for(let i=0;i<4;i++)playerCountHist[i]+=Number(r.playerCountHist?.[i]||0);return{copyId:COPY_ID,project:PROJECT,version:VERSION,expectedMarker:MARKER,readOnly:true,ramWrites:0,batchId:ctrl.batchId,batchCreatedAt:ctrl.createdAt,joinUntil:ctrl.joinUntil,joinedRoomCount:ctrl.roomKeys.length,completedRoomCount:complete.length,errorRoomCount:errors.length,interruptedRoomCount:unfinished.length,maxRooms:CFG.maxRooms,embeddedValidator:EMBED,model:{purpose:'One logical multiroom Future Danger batch. Each room runs the same WOF-038 validator independently for 120s, then results are merged without losing room boundaries.',roomPolicy:'Different player counts/scenes are preserved per room. No authoritative scene ID is claimed; contextTimeline records player presence, enemy-type composition, and target distribution as a context fingerprint.',targetPolicy:'enemy+0x7E authoritative',activeConvention:'enemy+0x70 U16 0->nonzero; not exact damage/hitbox onset'},aggregateDiagnostics:mergeDiagnostics(complete),aggregateRuleStats:mergeRules(complete),aggregatePlayerCountHist:playerCountHist,rooms:rooms.sort((a,b)=>a.ordinal-b.ordinal).map(r=>({roomId:r.roomId,ordinal:r.ordinal,status:r.status,startedAt:r.startedAt,completedAt:r.completedAt,workerLocation:r.workerLocation,playerCountHist:r.playerCountHist,peakPlayers:r.peakPlayers,presenceChanges:r.presenceChanges,contextTimeline:r.contextTimeline,embeddedValidation:r.embeddedValidation,error:r.error,result:r.embeddedResult}))};}
async function finalizeLoop(){while(true){const c=await getControl(db);if(!c||c.batchId!==control.batchId)return null;if(c.combined){self.__WOF_V39_RESULT=c.combined;console.log(`🟦 [${COPY_ID}] batch already merged by another room.`);return c.combined;}const rooms=await getBatchRooms(db,control.batchId),now=Date.now(),joinedClosed=now>=c.joinUntil,allSettled=rooms.length===c.roomKeys.length&&rooms.every(r=>r.status!=='running'),deadline=now>=c.finalizeDeadline;if(joinedClosed&&(allSettled||deadline)){const won=await claimFinalizer(db,control.batchId,row.key);if(won){const fresh=await getBatchRooms(db,control.batchId),out=await buildCombined(c,fresh);await saveCombined(db,control.batchId,out);self.__WOF_V39_RESULT=out;console.log(MARKER);console.log(JSON.stringify(out,null,2));return out;}}await sleep(2000);}}
const final=await finalizeLoop();try{db.close()}catch(_){}return final||{copyId:COPY_ID,batchId:control.batchId,roomId:row.roomId,status:row.status};
})().catch(e=>{console.error('[WOF-039] ERROR',e);throw e;});