(async()=>{
'use strict';
try{await self.__WOF_FOCUS_MULTIROOM?.finish?.('restart');}catch(_){}
const CFG={db:'wof-focus-multiroom-v1',store:'sessions',durationMs:10*60*1000,sampleMs:100,checkpointMs:10000,maxValuesPerOffset:64,maxSwitchEvents:400,rawConf:.72,stableHoldMs:700,learnAfterMs:300,graceMs:1200,maxOldEvidenceAgeMs:1800};
const PLAYERS={P1:0xFFBE1C,P2:0xFFBEFC,P3:0xFFBFDC},PN=['P1','P2','P3'],PI={P1:0,P2:1,P3:2};
const POOL=0xFFC0BC,STRIDE=0xE0,N=20;
const M=_0x515056?.HEAPU8,R=_0x515056?.HEAPU32?.[0x2e39e4>>>2]>>>0;if(!M||!R)throw new Error('CPS RAM unavailable');
const B=a=>M[R+((((a-0xFF0000)&0xffff)^1))],U16=a=>((B(a)<<8)|B(a+1))>>>0,U32=a=>(B(a)*0x1000000+B(a+1)*0x10000+B(a+2)*0x100+B(a+3))>>>0,S32=a=>{const v=U32(a);return v>=0x80000000?v-0x100000000:v;},W=v=>v/65536,clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const player=n=>{const b=PLAYERS[n];return B(b)?{n,x:W(S32(b+4)),y:W(S32(b+8)),hp:B(b+0x83)}:null;};
const actor=slot=>{const b=POOL+slot*STRIDE;if(!B(b))return null;return{slot,b,type:U16(b+0x20),x:W(S32(b+4)),y:W(S32(b+8)),attack:U16(b+0x70)};};
function openDb(){return new Promise((res,rej)=>{const q=indexedDB.open(CFG.db,1);q.onupgradeneeded=()=>{const db=q.result;if(!db.objectStoreNames.contains(CFG.store)){const s=db.createObjectStore(CFG.store,{keyPath:'id'});s.createIndex('startedAt','startedAt',{unique:false});}};q.onsuccess=()=>res(q.result);q.onerror=()=>rej(q.error);});}
function put(db,row){return new Promise((res,rej)=>{const tx=db.transaction(CFG.store,'readwrite');tx.objectStore(CFG.store).put(row);tx.oncomplete=()=>res();tx.onerror=()=>rej(tx.error);tx.onabort=()=>rej(tx.error||new Error('IndexedDB transaction aborted'));});}
const id=()=>{try{return crypto.randomUUID().slice(0,8)}catch(_){return Math.random().toString(36).slice(2,10)}};
const freshH=()=>({last:null,dist:{},ema:{P1:0,P2:0,P3:0},lastMoveAt:0,rawTarget:null,rawConf:0,candidate:null,candidateSince:0,stableTarget:null,stableSince:0,lastStableAt:0,lastStableWords:null,lastStableType:null});
const H=Array.from({length:N},freshH),WS=Array.from({length:STRIDE/2},()=>({total:0,targets:[0,0,0],exact:0,wrongPlayer:0,values:new Map()}));
const playerCountHist=[0,0,0,0],switches=[],typeTargets=new Map();
let running=true,samples=0,strongLabels=0,stableCommits=0,rejectedJitter=0,startedAt=Date.now(),sampleTimer=null,checkpointTimer=null,finishing=false;
const wordsOf=o=>Array.from({length:STRIDE/2},(_,i)=>U16(o.b+i*2));
function rawInfer(h,o,ps,now){const live=PN.filter(n=>ps[n]);if(!live.length){h.rawTarget=null;h.rawConf=0;h.last={x:o.x,y:o.y};return null;}if(h.last){const mx=o.x-h.last.x,my=o.y-h.last.y,m=Math.hypot(mx,my);for(const n of live){const p=ps[n],d=Math.hypot(p.x-o.x,p.y-o.y),pd=h.dist[n];let q=0;if(m>=.08&&d>=1){const dx=p.x-o.x,dy=p.y-o.y,align=(mx*dx+my*dy)/(m*d),gain=pd==null?0:(pd-d)/Math.max(.08,m);q=.62*clamp(align,-1,1)+.38*clamp(gain,-1,1);h.lastMoveAt=now;}h.ema[n]=h.ema[n]*.80+q*.20;h.dist[n]=d;}for(const n of PN)if(!ps[n])h.ema[n]*=.9;}h.last={x:o.x,y:o.y};const ranked=live.map(n=>[n,h.ema[n]]).sort((a,b)=>b[1]-a[1]),best=ranked[0],second=ranked[1]?.[1]??-.5,margin=best[1]-second,conf=live.length===1?0:clamp((best[1]-.03)/.52,0,1)*clamp((margin-.06)/.28,0,1);h.rawTarget=best[0];h.rawConf=conf;return{best:best[0],score:best[1],conf,live:live.length};}
function addValue(s,v,ti){let a=s.values.get(v);if(!a){if(s.values.size>=CFG.maxValuesPerOffset)return;a=[0,0,0];s.values.set(v,a);}a[ti]++;}
function learnWords(o,target,words){const ti=PI[target];strongLabels++;for(let i=0;i<words.length;i++){const s=WS[i],v=words[i];s.total++;s.targets[ti]++;if(v===(PLAYERS[target]&0xffff))s.exact++;else if(PN.some(n=>n!==target&&v===(PLAYERS[n]&0xffff)))s.wrongPlayer++;addValue(s,v,ti);}const k=String(o.type),t=typeTargets.get(k)||[0,0,0];t[ti]++;typeTargets.set(k,t);}
function process(slot,o,ps,live,now){const h=H[slot],r=rawInfer(h,o,ps,now),approach=now-h.lastMoveAt<=220,valid=!!r&&live>=2&&approach&&o.attack===0&&r.conf>=CFG.rawConf&&r.score>=.22;
  if(!valid){if(h.candidate&&now-h.candidateSince<CFG.stableHoldMs)rejectedJitter++;h.candidate=null;h.candidateSince=0;if(h.stableTarget&&now-h.lastStableAt>CFG.graceMs){h.stableTarget=null;h.stableSince=0;h.lastStableWords=null;h.lastStableType=null;}return;}
  if(h.candidate!==r.best){if(h.candidate&&now-h.candidateSince<CFG.stableHoldMs)rejectedJitter++;h.candidate=r.best;h.candidateSince=now;}
  const held=now-h.candidateSince;
  if(!h.stableTarget&&held>=CFG.stableHoldMs){h.stableTarget=r.best;h.stableSince=now;stableCommits++;}
  else if(h.stableTarget!==r.best&&held>=CFG.stableHoldMs){const old=h.stableTarget,oldWords=h.lastStableWords,oldAt=h.lastStableAt,oldType=h.lastStableType,newWords=wordsOf(o);h.stableTarget=r.best;h.stableSince=now;stableCommits++;if(oldWords&&oldType===o.type&&now-oldAt<=CFG.maxOldEvidenceAgeMs&&switches.length<CFG.maxSwitchEvents){switches.push({t:+((now-startedAt)/1000).toFixed(2),slot,type:o.type,from:old,to:r.best,conf:+r.conf.toFixed(2),candidateHoldMs:held,oldEvidenceAgeMs:now-oldAt,beforeWords:oldWords,afterWords:newWords});}}
  if(h.stableTarget===r.best){const words=wordsOf(o);h.lastStableAt=now;h.lastStableWords=words;h.lastStableType=o.type;if(now-h.stableSince>=CFG.learnAfterMs)learnWords(o,h.stableTarget,words);}
}
function tick(){if(!running)return;const now=Date.now(),ps=Object.fromEntries(PN.map(n=>[n,player(n)])),live=PN.filter(n=>ps[n]).length;playerCountHist[live]++;for(let slot=0;slot<N;slot++){const o=actor(slot);if(!o){H[slot]=freshH();continue;}process(slot,o,ps,live,now);}samples++;}
function snap(){const words=WS.map((s,i)=>({offset:i*2,total:s.total,targets:s.targets,exact:s.exact,wrongPlayer:s.wrongPlayer,values:[...s.values.entries()].map(([v,c])=>({v,c})).sort((a,b)=>b.c.reduce((x,y)=>x+y,0)-a.c.reduce((x,y)=>x+y,0)).slice(0,24)}));return{version:'focus-multiroom-v3',samples,strongLabels,stableCommits,rejectedJitter,playerCountHist:[...playerCountHist],words,switches:[...switches],typeTargets:Object.fromEntries(typeTargets)};}
const db=await openDb(),sid='focus3-'+id(),row={id:sid,schema:'wof-focus-multiroom-v3',collectorVersion:'focus-multiroom-v3',status:'running',startedAt,latestAt:startedAt,plannedEndAt:startedAt+CFG.durationMs,completedAt:null,worker:String(self.location?.href||''),checkpoints:[],latestSnapshot:snap(),final:null};await put(db,row);
async function checkpoint(){row.latestAt=Date.now();row.latestSnapshot=snap();row.checkpoints.push({at:row.latestAt,samples,strongLabels,stableCommits,rejectedJitter,playerCountHist:[...playerCountHist],switches:switches.length});if(row.checkpoints.length>72)row.checkpoints.shift();await put(db,row);}
async function finish(reason='complete'){if(finishing)return;finishing=true;running=false;if(sampleTimer)clearInterval(sampleTimer);if(checkpointTimer)clearInterval(checkpointTimer);row.status=reason==='complete'?'complete':'stopped';row.completedAt=Date.now();row.latestAt=row.completedAt;row.final=snap();row.latestSnapshot=row.final;await put(db,row);try{db.close()}catch(_){}console.log('✅ Focus multiroom v3结束',sid,row.status,'labels',strongLabels,'stableSwitches',switches.length);}
sampleTimer=setInterval(tick,CFG.sampleMs);tick();checkpointTimer=setInterval(()=>{checkpoint().catch(console.error);if(Date.now()>=row.plannedEndAt)finish('complete').catch(console.error);},CFG.checkpointMs);
self.__WOF_FOCUS_MULTIROOM={version:'focus-multiroom-v3',id:sid,get running(){return running},status(){return{id:sid,version:'focus-multiroom-v3',running,samples,strongLabels,stableCommits,rejectedJitter,switches:switches.length,playerCountHist:[...playerCountHist],seconds:+((Date.now()-startedAt)/1000).toFixed(1)}},snapshot:snap,checkpoint,finish};
console.log('🟢 Focus multiroom v3 started',sid,'| 700ms持续锁定才确认焦点 | 过滤100ms抖动');
return self.__WOF_FOCUS_MULTIROOM.status();
})().catch(e=>console.error('❌ Focus multiroom v3 failed',e));