(()=>{
'use strict';
try{self.WOFCALLD0?.stop?.();}catch(_){}
const RAW='https://raw.githubusercontent.com/ouyong520/wof-ai-private/main/';
const sleep=ms=>new Promise(r=>setTimeout(r,ms));let stopped=false;
const load=async f=>{const r=await fetch(RAW+f+'?x='+Date.now(),{cache:'no-store'});if(!r.ok)throw new Error('fetch failed '+r.status+' '+f);return (0,eval)(await r.text());};
async function ensure(){if(!self.__WOF_ROM_LOC_CACHE)await load('wof_rom_focus_inspect.js');for(let i=0;i<300&&!self.__WOF_ROM_LOC_CACHE;i++)await sleep(50);if(!self.__WOF_ROM_LOC_CACHE)throw new Error('ROM cache unavailable');if(!self.__WOF_ROM_FOCUS_LEVEL2?.handlers?.length){await load('wof_rom_focus_level2_tables.js');await WOFFOCUSLEVEL2.run();}}
function env(){const MOD=_0x515056,C=self.__WOF_ROM_LOC_CACHE,M=MOD.HEAPU8,base=C.base,SW=!!C.swap16,MAX=Math.min(0x100000,M.length-base),DELTA=C.offlineDelta|0;const r8=o=>M[base+(SW?(o^1):o)]>>>0,r16=o=>((r8(o)<<8)|r8(o+1))>>>0,r32=o=>(r8(o)*0x1000000+r8(o+1)*0x10000+r8(o+2)*0x100+r8(o+3))>>>0,s8=v=>v&0x80?v-0x100:v,s16=v=>v&0x8000?v-0x10000:v,h=x=>'0x'+(x>>>0).toString(16).toUpperCase().padStart(6,'0'),off=x=>h((x-DELTA)>>>0),hw=x=>'0x'+(x&0xffff).toString(16).toUpperCase().padStart(4,'0');return{MAX,r8,r16,r32,s8,s16,h,off,hw};}
function eaWords(m,r,size){if(m<=4)return 0;if(m===5||m===6)return 1;if(m===7){if(r===0||r===2||r===3)return 1;if(r===1)return 2;if(r===4)return size==='L'?2:1;}return 0;}
function eaText(E,p,m,r,size){if(m===0)return'D'+r;if(m===1)return'A'+r;if(m===2)return'(A'+r+')';if(m===3)return'(A'+r+')+';if(m===4)return'-(A'+r+')';if(m===5)return E.s16(E.r16(p))+'(A'+r+')';if(m===6){const x=E.r16(p),ix=(x&0x8000?'A':'D')+((x>>12)&7)+(x&0x0800?'.L':'.W'),d=E.s8(x&255);return d+'(A'+r+','+ix+')';}if(m===7&&r===0)return'$'+E.hw(E.r16(p))+'.W';if(m===7&&r===1)return'$'+E.h(E.r32(p))+'.L';if(m===7&&r===2)return E.s16(E.r16(p))+'(PC)';if(m===7&&r===3){const x=E.r16(p),ix=(x&0x8000?'A':'D')+((x>>12)&7)+(x&0x0800?'.L':'.W'),d=E.s8(x&255);return d+'(PC,'+ix+')';}if(m===7&&r===4)return size==='L'?'#'+E.h(E.r32(p)):'#'+E.hw(E.r16(p));return'EA';}
function decode(E,p){const w=E.r16(p),g=w>>>12,m=(w>>3)&7,r=w&7;let len=2,text='DC.W '+E.hw(w),kind='OP',target=null,fall=true,terminal=false,call=false,writesD0=false,d0Source='';
 if(w===0x4E75||w===0x4E73||w===0x4E77){kind='RET';terminal=true;fall=false;text='RTS/RTE/RTR';}
 else if(w===0x4E72){kind='STOP';len=4;terminal=true;fall=false;text='STOP';}
 else if((w&0xFFC0)===0x4E80){kind='JSR';call=true;len=2+eaWords(m,r,'L')*2;text='JSR '+eaText(E,p+2,m,r,'L');if(m===7&&r===0)target=E.s16(E.r16(p+2))>>>0;else if(m===7&&r===1)target=E.r32(p+2);else if(m===7&&r===2)target=(p+2+E.s16(E.r16(p+2)))>>>0;}
 else if((w&0xFFC0)===0x4EC0){kind='JMP';fall=false;len=2+eaWords(m,r,'L')*2;text='JMP '+eaText(E,p+2,m,r,'L');if(m===7&&r===0)target=E.s16(E.r16(p+2))>>>0;else if(m===7&&r===1)target=E.r32(p+2);else if(m===7&&r===2)target=(p+2+E.s16(E.r16(p+2)))>>>0;}
 else if(g===6){const cc=(w>>8)&15,d=w&255;len=d===0?4:2;const disp=d===0?E.s16(E.r16(p+2)):E.s8(d);target=p+2+disp;kind=cc===0?'BRA':cc===1?'BSR':'BCC';call=cc===1;if(cc===0)fall=false;text=kind+' '+E.h(target);}
 else if(g===1||g===2||g===3){const size=g===1?'B':g===2?'L':'W',sm=(w>>3)&7,sr=w&7,dm=(w>>6)&7,dr=(w>>9)&7,sw=eaWords(sm,sr,size),dw=eaWords(dm,dr,size),src=eaText(E,p+2,sm,sr,size),dst=eaText(E,p+2+sw*2,dm,dr,size);len=2+(sw+dw)*2;text='MOVE.'+size+' '+src+','+dst;if(dm===0&&dr===0){writesD0=true;d0Source=src;}}
 else if((w&0xF100)===0x7000){const dr=(w>>9)&7,imm=E.s8(w&255);text='MOVEQ #'+imm+',D'+dr;if(dr===0){writesD0=true;d0Source='#'+imm;}}
 else if(g===14){const sz=(w>>6)&3,reg=w&7;if(sz!==3){const cnt=(w>>9)&7||8,dir=(w&0x0100)?'L':'R',typ=(w>>3)&3,op=['AS','LS','ROX','RO'][typ]+dir,size=sz===2?'L':sz===1?'W':'B';text=op+'.'+size+' #'+cnt+',D'+reg;if(reg===0){writesD0=true;d0Source='D0 '+op+' #'+cnt;}}else{len=2+eaWords(m,r,'W')*2;text='SHIFT/ROT EA';}}
 else if(g===13||g===9||g===8||g===12||g===11){const dr=(w>>9)&7,op=g===13?'ADD':g===9?'SUB':g===8?'OR':g===12?'AND':'CMP',sz=(w>>6)&3,size=sz===2?'L':sz===1?'W':'B',src=eaText(E,p+2,m,r,size);len=2+eaWords(m,r,size)*2;text=op+'.'+size+' '+src+',D'+dr;if(dr===0&&op!=='CMP'){writesD0=true;d0Source=op+'('+src+')';}}
 else if(g===5&&((w>>6)&3)!==3){const q=((w>>9)&7)||8,sub=!!(w&0x0100),sz=(w>>6)&3,size=sz===2?'L':sz===1?'W':'B',dst=eaText(E,p+2,m,r,size);len=2+eaWords(m,r,size)*2;text=(sub?'SUBQ.':'ADDQ.')+size+' #'+q+','+dst;if(m===0&&r===0){writesD0=true;d0Source=sub?'D0-'+q:'D0+'+q;}}
 else if(g===0){const op=(w>>8)&15,sz=(w>>6)&3;if([0,2,4,6,10,12].includes(op)&&sz!==3){const size=sz===2?'L':sz===1?'W':'B',iw=size==='L'?2:1,imm=size==='L'?E.h(E.r32(p+2)):E.hw(E.r16(p+2)),dst=eaText(E,p+2+iw*2,m,r,size),nm={0:'ORI',2:'ANDI',4:'SUBI',6:'ADDI',10:'EORI',12:'CMPI'}[op];len=2+iw*2+eaWords(m,r,size)*2;text=nm+'.'+size+' #'+imm+','+dst;if(m===0&&r===0&&nm!=='CMPI'){writesD0=true;d0Source=nm+' D0';}}}
 else if(g===4){if((w&0xFFF8)===0x4E50)len=4;else if((w&0xFB80)===0x4880&&m>=2)len=4+eaWords(m,r,(w&0x40)?'L':'W')*2;else if((w&0xF1C0)===0x41C0)len=2+eaWords(m,r,'L')*2;else if((w&0xFFC0)===0x4840&&m!==0)len=2+eaWords(m,r,'L')*2;else len=2+eaWords(m,r,((w>>6)&3)===2?'L':'W')*2;}
 else if(g===10||g===15){kind='LINE';terminal=true;fall=false;}
 len=Math.max(2,len);const next=p+len;if(target!=null&&(target<0||target>=E.MAX))target=null;return{at:p,w,len,next,text,kind,target,fall,terminal,call,writesD0,d0Source};}
function cfg(E,start,cap=0x1800){const hi=Math.min(E.MAX,start+cap),q=[start&~1],seen=new Set(),ins=new Map(),calls=[];while(q.length&&seen.size<9000){const p=q.shift();if(p<0||p>=hi||(p&1)||seen.has(p))continue;seen.add(p);const d=decode(E,p);ins.set(p,d);if((d.kind==='JSR'||d.kind==='BSR')&&d.target!=null)calls.push({at:p,target:d.target});if(d.kind==='BRA'){if(d.target!=null&&d.target<hi)q.push(d.target&~1);continue;}if(d.kind==='BCC'){if(d.next<hi)q.push(d.next);if(d.target!=null&&d.target<hi)q.push(d.target&~1);continue;}if(d.kind==='JMP'){if(d.target!=null&&d.target<hi)q.push(d.target&~1);continue;}if(d.terminal)continue;if(d.next<hi)q.push(d.next);}return{seen,ins,calls};}
function linearWindow(E,start,callAt){const out=[];let p=Math.max(start,callAt-0x70)&~1,guard=0;while(p<=callAt&&guard++<120){const d=decode(E,p);out.push({at:E.h(p),offline:E.off(p),text:d.text,writesD0:d.writesD0,d0Source:d.d0Source,mark:p===callAt?'<<< CALL':''});p+=Math.max(2,d.len);}return out;}
async function run(){stopped=false;await ensure();const E=env(),L2=self.__WOF_ROM_FOCUS_LEVEL2,TARGETS=new Set([0x25B6,0x25C8]);console.log('📞 WOF dispatcher caller → D0 provenance trace');
 const roots=[...new Set((L2.handlers||[]).map(x=>parseInt(x.target,16)&~1).filter(Number.isFinite))],queue=roots.map(a=>({a,d:0})),seenR=new Set(),routines=new Map();while(queue.length){const n=queue.shift(),a=n.a&~1;if(seenR.has(a)||n.d>10)continue;seenR.add(a);const c=cfg(E,a);routines.set(a,c);for(const z of c.calls)if(n.d<10&&!seenR.has(z.target&~1))queue.push({a:z.target&~1,d:n.d+1});if((seenR.size&31)===0)await sleep(0);}
 const hits=[];for(const [root,c] of routines){for(const z of c.calls){if(!TARGETS.has(z.target))continue;const prior=[...c.ins.values()].filter(d=>d.at<z.at&&d.at>=z.at-0x100&&d.writesD0).sort((a,b)=>b.at-a.at).slice(0,8);hits.push({caller:E.h(root),callAt:E.h(z.at),target:E.h(z.target),nearestD0At:prior[0]?E.h(prior[0].at):'',nearestD0Text:prior[0]?.text||'',nearestD0Source:prior[0]?.d0Source||'',d0Chain:prior.map(d=>E.h(d.at)+' '+d.text).join(' | ')});}}
 hits.sort((a,b)=>a.target.localeCompare(b.target)||a.callAt.localeCompare(b.callAt));console.log('=== DISPATCH DIRECT CALLERS ===');console.table(hits);
 for(const h of hits.slice(0,24)){const r=parseInt(h.caller,16),ca=parseInt(h.callAt,16);console.log('=== CALLER CONTEXT '+h.caller+' → '+h.target+' @ '+h.callAt+' ===');console.table(linearWindow(E,r,ca));}
 const verdict={reachableRoutines:routines.size,callerSites:hits.length,callers25B6:hits.filter(x=>x.target==='0x0025B6').length,callers25C8:hits.filter(x=>x.target==='0x0025C8').length,withD0Producer:hits.filter(x=>x.nearestD0At).length,topCaller:hits[0]?.caller||'',topCallAt:hits[0]?.callAt||'',topTarget:hits[0]?.target||'',topD0At:hits[0]?.nearestD0At||'',topD0Text:hits[0]?.nearestD0Text||'',topD0Source:hits[0]?.nearestD0Source||''};console.log('=== DISPATCH CALLER D0 VERDICT ===');console.table([verdict]);
 const out={version:'wof-dispatch-caller-d0-v1',verdict,hits};self.__WOF_DISPATCH_CALLER_D0=out;return out;}
self.WOFCALLD0={version:'wof-dispatch-caller-d0-v1',run,stop(){stopped=true;}};console.log('✅ WOF dispatcher caller D0 trace loaded');console.log('执行 await WOFCALLD0.run()');
})();