(async()=>{
'use strict';
const COPY_ID='WOF-040';
const PROJECT='WOF-AI-PRIVATE';
const VERSION='wof-future-danger-multiroom-coordinator-v40';
const MARKER='=== WOF FUTURE DANGER MULTIROOM COORDINATOR V40 JSON ===';
const EMBED={copyId:'WOF-038',project:'WOF-AI-PRIVATE',version:'wof-future-danger-descriptor-family-validator-v38',marker:'=== WOF FUTURE DANGER DESCRIPTOR FAMILY VALIDATOR V38 JSON ==='};
const CFG={db:'wof-future-danger-multiroom-v2',dbVersion:1,controlStore:'control',roomStore:'rooms',activeKey:'active',maxRooms:5,batchMaxAgeMs:30*60*1000,staleHeartbeatMs:15000,heartbeatMs:5000,contextSampleMs:250,contextSnapshotMs:2000,maxPresenceChanges:80,maxContextEntries:180,validatorUrl:'https://raw.githubusercontent.com/ouyong520/wof-ai-private/main/wof_future_danger_descriptor_family_validator_v38.js'};
const IS_TOP=typeof document!=='undefined'&&typeof window!=='undefined';
console.log(`[${COPY_ID}] ${PROJECT} ${VERSION} mode=${IS_TOP?'TOP-FINALIZE':'ROOM-COLLECT'}`);
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const uid=()=>{try{return crypto.randomUUID().slice(0,12)}catch(_){return Math.random().toString(36).slice(2,14)}};
function openDb(){return new Promise((res,rej)=>{const q=indexedDB.open(CFG.db,CFG.dbVersion);q.onupgradeneeded=()=>{const db=q.result;if(!db.objectStoreNames.contains(CFG.controlStore))db.createObjectStore(CFG.controlStore,{keyPath:'key'});if(!db.objectStoreNames.contains(CFG.roomStore)){const s=db.createObjectStore(CFG.roomStore,{keyPath:'key'});s.createIndex('batchId','batchId',{unique:false});}};q.onsuccess=()=>res(q.result);q.onerror=()=>rej(q.error);});}
function reqp(req){return new Promise((res,rej)=>{req.onsuccess=()=>res(req.result);req.onerror=()=>rej(req.error);});}
async function getControl(db){const tx=db.transaction(CFG.controlStore,'readonly');return reqp(tx.objectStore(CFG.controlStore).get(CFG.activeKey));}
async function getBatchRooms(db,batchId){const tx=db.transaction(CFG.roomStore,'readonly'),s=tx.objectStore(CFG.roomStore);return reqp(s.index('batchId').getAll(batchId));}
async function putRoom(db,row){return new Promise((res,rej)=>{const tx=db.transaction(CFG.roomStore,'readwrite');tx.objectStore(CFG.roomStore).put(row);tx.oncomplete=()=>res();tx.onerror=()=>rej(tx.error);tx.onabort=()=>rej(tx.error||new Error('room tx aborted'));});}
async function joinBatch(db){const now=Date.now(),roomId='r-'+uid();return new Promise((resolve,reject)=>{const tx=db.transaction([CFG.controlStore,CFG.roomStore],'readwrite'),cs=tx.objectStore(CFG.controlStore),rs=tx.objectStore(CFG.roomStore);let answer=null;const q=cs.get(CFG.activeKey);q.onerror=()=>reject(q.error);q.onsuccess=()=>{let c=q.result;const stale=!c||c.finalizedAt||c.status==='finalized'||now-(c.createdAt||0)>CFG.batchMaxAgeMs;if(stale){const batchId='b-'+uid();c={key:CFG.activeKey,batchId,status:'collecting',createdAt:now,lastJoinAt:now,maxRooms:CFG.maxRooms,roomKeys:[],finalizedAt:null,combined:null};}if(c.roomKeys.length>=CFG.maxRooms){reject(new Error(`[${COPY_ID}] active batch ${c.batchId} already has ${CFG.maxRooms} rooms; return to top and finalize it first`));try{tx.abort()}catch(_){}return;}const ordinal=c.roomKeys.length+1,roomKey=`${c.batchId}|${roomId}`;c.roomKeys.push(roomKey);c.lastJoinAt=now;cs.put(c);const row={key:roomKey,batchId:c.batchId,roomId,ordinal,status:'running',copyId:COPY_ID,project:PROJECT,version:VERSION,readOnly:true,ramWrites:0,startedAt:now,heartbeatAt:now,completedAt:null,workerLocation:String(self.location?.href||''),playerCountHist:[0,0,0,0],peakPlayers:0,presenceChanges:[],contextTimeline:[],embeddedResult:null,embeddedValidation:null,error:null};rs.put(row);answer={control:c,row};};tx.oncomplete=()=>resolve(answer);tx.onerror=()=>reject(tx.error);tx.onabort=()=>{};});}
const addObj=(dst,src)=>{for(const [k,v] of Object.entries(src||{}))dst[k]=(dst[k]||0)+(Number(v)||0);return dst;};
function mergeDiagnostics(rooms){const d={polls:0,enemySamples:0,activeEdges:0,signals:0,strictHits:0,jitterBandHits:0,realLateHits:0,hardMisses:0,censored:0,retargets:0,typeSamples:{},attackTypeCounts:{},rawMatchSamples:{},transitionEntries:{}};for(const r of rooms){const x=r.embeddedResult?.diagnostics;if(!x)continue;for(const k of ['polls','enemySamples','activeEdges','signals','strictHits','jitterBandHits','realLateHits','hardMisses','censored','retargets'])d[k]+=Number(x[k]||0);addObj(d.typeSamples,x.typeSamples);addObj(d.attackTypeCounts,x.attackTypeCounts);addObj(d.rawMatchSamples,x.rawMatchSamples);addObj(d.transitionEntries,x.transitionEntries);}return d;}
function mergeRules(rooms){const out={};for(const r of rooms){const rs=r.embeddedResult?.ruleStats||{};for(const [id,q] of Object.entries(rs)){const z=out[id]||(out[id]={rule:id,status:q.status,horizonMs:q.horizonMs,tailMs:q.tailMs,jitterToleranceMs:q.jitterToleranceMs,signals:0,evaluable:0,strictHit:0,jitterBandHit:0,realLateHit:0,hardMiss:0,censored:0,expectedAttack:0,expectedAttackTotal:0,targetSame:0,targetTotal:0,sideSame:0,sideTotal:0,leads:[],attackCounts:{},entryTargetCounts:{},entrySideCounts:{},entryTypeCounts:{},roomsWithSignal:[],roomsWithRawMatch:[],perRoom:[]});for(const k of ['signals','evaluable','strictHit','jitterBandHit','realLateHit','hardMiss','censored','expectedAttack','expectedAttackTotal','targetSame','targetTotal','sideSame','sideTotal'])z[k]+=Number(q[k]||0);z.leads.push(...(q.leads||[]));for(const a of q.attackCounts||[])z.attackCounts[String(a.attack)]=(z.attackCounts[String(a.attack)]||0)+Number(a.count||0);addObj(z.entryTargetCounts,q.entryTargetCounts);addObj(z.entrySideCounts,q.entrySideCounts);addObj(z.entryTypeCounts,q.entryTypeCounts);if(q.signals>0)z.roomsWithSignal.push(r.roomId);if((r.embeddedResult?.diagnostics?.rawMatchSamples?.[id]||0)>0)z.roomsWithRawMatch.push(r.roomId);z.perRoom.push({roomId:r.roomId,ordinal:r.ordinal,signals:q.signals,evaluable:q.evaluable,strictHit:q.strictHit,jitterBandHit:q.jitterBandHit,realLateHit:q.realLateHit,hardMiss:q.hardMiss,censored:q.censored,expectedAttackRate:q.expectedAttackRate,targetSameRate:q.targetSameRate,sideStableRate:q.sideStableRate,leads:q.leads,entryTypeCounts:q.entryTypeCounts,entryTargetCounts:q.entryTargetCounts,entrySideCounts:q.entrySideCounts});}}for(const z of Object.values(out)){z.strictRate=z.evaluable?+(z.strictHit/z.evaluable).toFixed(3):null;z.jitterCorrectedRate=z.evaluable?+((z.strictHit+z.jitterBandHit)/z.evaluable).toFixed(3):null;z.tailHitRate=z.evaluable?+((z.strictHit+z.jitterBandHit+z.realLateHit)/z.evaluable).toFixed(3):null;z.expectedAttackRate=z.expectedAttackTotal?+(z.expectedAttack/z.expectedAttackTotal).toFixed(3):null;z.targetSameRate=z.targetTotal?+(z.targetSame/z.targetTotal).toFixed(3):null;z.sideStableRate=z.sideTotal?+(z.sideSame/z.sideTotal).toFixed(3):null;z.leads.sort((a,b)=>a-b);z.attackCounts=Object.entries(z.attackCounts).map(([attack,count])=>({attack:+attack,count})).sort((a,b)=>b.count-a.count);}return out;}
function effectiveRoom(r,now){if(r.status!=='running')return r;const age=now-(r.heartbeatAt||r.startedAt||0);return age>CFG.staleHeartbeatMs?{...r,status:'interrupted',interruptedAt:r.heartbeatAt||null,heartbeatAgeMs:age}:r;}
async function buildCombined(ctrl,rooms){const complete=rooms.filter(r=>r.status==='complete'&&r.embeddedValidation?.ok),errors=rooms.filter(r=>r.status==='error'),interrupted=rooms.filter(r=>r.status==='interrupted');const playerCountHist=[0,0,0,0];for(const r of rooms)for(let i=0;i<4;i++)playerCountHist[i]+=Number(r.playerCountHist?.[i]||0);return{copyId:COPY_ID,project:PROJECT,version:VERSION,expectedMarker:MARKER,readOnly:true,ramWrites:0,batchId:ctrl.batchId,batchCreatedAt:ctrl.createdAt,finalizedAt:Date.now(),joinedRoomCount:ctrl.roomKeys.length,completedRoomCount:complete.length,errorRoomCount:errors.length,interruptedRoomCount:interrupted.length,maxRooms:CFG.maxRooms,embeddedValidator:EMBED,model:{purpose:'Manual-finalize multiroom Future Danger batch. Run this same script in each room Worker to collect 120s. After desired rooms finish, switch DevTools context to top and run the same script once to merge and download exactly one JSON.',roomPolicy:'No join-window timeout. 1P/2P/3P rooms may join the same active batch until maxRooms or top finalization. Room boundaries are preserved.',closePolicy:'A room that disappears stops heartbeats; top finalization marks it interrupted without corrupting completed rooms.',targetPolicy:'enemy+0x7E authoritative',activeConvention:'enemy+0x70 U16 0->nonzero; not exact damage/hitbox onset'},aggregateDiagnostics:mergeDiagnostics(complete),aggregateRuleStats:mergeRules(complete),aggregatePlayerCountHist:playerCountHist,rooms:rooms.sort((a,b)=>a.ordinal-b.ordinal).map(r=>({roomId:r.roomId,ordinal:r.ordinal,status:r.status,startedAt:r.startedAt,completedAt:r.completedAt,heartbeatAt:r.heartbeatAt,workerLocation:r.workerLocation,playerCountHist:r.playerCountHist,peakPlayers:r.peakPlayers,presenceChanges:r.presenceChanges,contextTimeline:r.contextTimeline,embeddedValidation:r.embeddedValidation,error:r.error,result:r.embeddedResult}))};}
async function saveFinal(db,batchId,out){return new Promise((res,rej)=>{const tx=db.transaction(CFG.controlStore,'readwrite'),s=tx.objectStore(CFG.controlStore),q=s.get(CFG.activeKey);q.onsuccess=()=>{const c=q.result;if(!c||c.batchId!==batchId){rej(new Error(`[${COPY_ID}] active batch changed during finalize`));try{tx.abort()}catch(_){}return;}c.status='finalized';c.finalizedAt=Date.now();c.combined=out;s.put(c);};q.onerror=()=>rej(q.error);tx.oncomplete=()=>res();tx.onerror=()=>rej(tx.error);});}
async function topFinalize(){const db=await openDb();try{const ctrl=await getControl(db);if(!ctrl||!ctrl.batchId)throw new Error(`[${COPY_ID}] no active batch found`);if(ctrl.finalizedAt&&ctrl.combined){const out=ctrl.combined;download(out);console.log('🟦 Existing finalized batch downloaded again',ctrl.batchId);return out;}const raw=await getBatchRooms(db,ctrl.batchId);if(!raw.length)throw new Error(`[${COPY_ID}] active batch has no rooms`);const now=Date.now(),rooms=raw.map(r=>effectiveRoom(r,now)),live=rooms.filter(r=>r.status==='running');if(live.length){console.table(live.map(r=>({room:r.ordinal,roomId:r.roomId,heartbeatAgeSec:+((now-(r.heartbeatAt||now))/1000).toFixed(1),status:r.status})));throw new Error(`[${COPY_ID}] ${live.length} room(s) still collecting. Wait until they complete, or close them and wait ${Math.ceil(CFG.staleHeartbeatMs/1000)}s before finalizing.`);}const out=await buildCombined(ctrl,rooms);await saveFinal(db,ctrl.batchId,out);download(out);console.log(MARKER);console.table(out.rooms.map(r=>({room:r.ordinal,status:r.status,peakPlayers:r.peakPlayers,signals:r.result?.diagnostics?.signals||0,activeEdges:r.result?.diagnostics?.activeEdges||0})));console.log(`✅ [${COPY_ID}] merged ${out.completedRoomCount}/${out.joinedRoomCount} complete rooms into ONE JSON; interrupted=${out.interruptedRoomCount}, errors=${out.errorRoomCount}`);self.__WOF_V40_RESULT=out;return out;}finally{try{db.close()}catch(_){}}}
function download(out){const name=`WOF-040_${out.batchId||'batch'}.json`,url=URL.createObjectURL(new Blob([JSON.stringify(out,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=name;a.style.display='none';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);console.log('✅ downloaded',name);}
if(IS_TOP)return topFinalize();
if(self.__WOF_V40_ROOM?.running){console.log('🟦 WOF-040 already running in this Worker',self.__WOF_V40_ROOM.status());return self.__WOF_V40_ROOM.status();}
const good=v=>!!(v&&v.HEAPU8 instanceof Uint8Array&&v.HEAPU32 instanceof Uint32Array&&v.HEAPU8.buffer===v.HEAPU32.buffer);
async function ensureModule(){if(good(self._0x515056))return self._0x515056;const until=performance.now()+8000;while(performance.now()<until){for(const k of Object.getOwnPropertyNames(self)){let v;try{v=self[k]}catch(_){continue}if(good(v)){self._0x515056=v;self.__WOF_MODULE_GLOBAL_KEY=k;return v;}}await sleep(50);}throw new Error(`[${COPY_ID}] WASM module not found. Select a live gstyphoon.js Worker.`);}
const db=await openDb(),joined=await joinBatch(db),control=joined.control,row=joined.row;let running=true,contextTimer=null,heartbeatTimer=null;self.__WOF_V40_ROOM={get running(){return running},batchId:control.batchId,roomId:row.roomId,ordinal:row.ordinal,status(){return{copyId:COPY_ID,batchId:control.batchId,roomId:row.roomId,ordinal:row.ordinal,running,status:row.status,startedAt:row.startedAt,heartbeatAt:row.heartbeatAt}}};
console.log(`🟢 [${COPY_ID}] joined ${control.batchId} room ${row.ordinal}/${CFG.maxRooms}; NO join-window limit. 1P/2P/3P are accepted.`);
const MOD=await ensureModule(),M=MOD.HEAPU8,R=MOD.HEAPU32?.[0x2e39e4>>>2]>>>0;if(!R)throw new Error(`[${COPY_ID}] CPS RAM base missing`);const B=a=>M[R+((((a-0xFF0000)&0xffff)^1))]>>>0,U16=a=>((B(a)<<8)|B(a+1))>>>0,U32=a=>(B(a)*0x1000000+B(a+1)*0x10000+B(a+2)*0x100+B(a+3))>>>0,PBASE=[0xFFBE1C,0xFFBEFC,0xFFBFDC],PN=['P1','P2','P3'],ENEMY=0xFFC0BC,STRIDE=0xE0,SLOTS=20;
function playersPresent(){const a=[];for(let i=0;i<3;i++)if(B(PBASE[i]))a.push(PN[i]);return a;}
function contextSnapshot(){const players=playersPresent(),types={},targets={P1:0,P2:0,P3:0,other:0};for(let i=0;i<SLOTS;i++){const a=ENEMY+i*STRIDE,type=U16(a+0x20),fe=U32(a+0x12),nx=U32(a+0x2C);if(type>=47||(!fe&&!nx))continue;types['T'+type]=(types['T'+type]||0)+1;const t=U16(a+0x7E);if(t===0)targets.P1++;else if(t===4)targets.P2++;else if(t===8)targets.P3++;else targets.other++;}return{players,playerCount:players.length,enemyTypes:types,targetCounts:targets};}
let lastPresence='',lastContext='',lastContextAt=0;function sampleContext(force=false){const now=Date.now(),c=contextSnapshot(),pk=c.players.join(',');row.playerCountHist[c.playerCount]=(row.playerCountHist[c.playerCount]||0)+1;row.peakPlayers=Math.max(row.peakPlayers,c.playerCount);if(pk!==lastPresence){lastPresence=pk;if(row.presenceChanges.length<CFG.maxPresenceChanges)row.presenceChanges.push({tMs:now-row.startedAt,players:c.players,playerCount:c.playerCount});}if(force||now-lastContextAt>=CFG.contextSnapshotMs){const sig=JSON.stringify([c.players,c.enemyTypes,c.targetCounts]);if(sig!==lastContext||force){lastContext=sig;lastContextAt=now;if(row.contextTimeline.length<CFG.maxContextEntries)row.contextTimeline.push({tMs:now-row.startedAt,...c});}}}
contextTimer=setInterval(()=>{try{sampleContext(false)}catch(_){}},CFG.contextSampleMs);sampleContext(true);heartbeatTimer=setInterval(()=>{row.heartbeatAt=Date.now();putRoom(db,row).catch(()=>{});},CFG.heartbeatMs);
async function runEmbedded(){let code=await fetch(CFG.validatorUrl+'?x='+Date.now(),{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error('validator fetch '+r.status);return r.text();});code=code.replace("console.log(`[${COPY_ID}] ${PROJECT} ${VERSION}`);",'');code=code.replace("self.__WOF_V38_RESULT=out;console.log(MARKER);console.log(JSON.stringify(out,null,2));return out;","self.__WOF_V38_RESULT=out;return out;");const out=await(0,eval)(code),ok=!!out&&out.copyId===EMBED.copyId&&out.project===EMBED.project&&out.version===EMBED.version&&out.expectedMarker===EMBED.marker&&out.readOnly===true&&out.ramWrites===0;return{ok,out};}
try{const e=await runEmbedded();row.embeddedValidation={ok:e.ok,expected:EMBED,actual:e.out?{copyId:e.out.copyId,project:e.out.project,version:e.out.version,expectedMarker:e.out.expectedMarker,readOnly:e.out.readOnly,ramWrites:e.out.ramWrites}:null};if(!e.ok)throw new Error(`[${COPY_ID}] embedded WOF-038 identity mismatch`);row.embeddedResult=e.out;row.status='complete';row.completedAt=Date.now();row.heartbeatAt=row.completedAt;sampleContext(true);await putRoom(db,row);console.log(`✅ [${COPY_ID}] room ${row.ordinal} complete. After ALL desired rooms complete, switch Console context to top and run the SAME WOF-040 command once.`);}catch(e){row.status='error';row.error=String(e?.stack||e);row.completedAt=Date.now();row.heartbeatAt=row.completedAt;try{sampleContext(true)}catch(_){}await putRoom(db,row);console.error(`[${COPY_ID}] room ${row.ordinal} failed`,e);}finally{running=false;if(contextTimer)clearInterval(contextTimer);if(heartbeatTimer)clearInterval(heartbeatTimer);try{db.close()}catch(_){}}
return self.__WOF_V40_ROOM.status();
})().catch(e=>{console.error('[WOF-040] ERROR',e);throw e;});