(async()=>{
'use strict';
const RAW='https://raw.githubusercontent.com/ouyong520/wof-ai-private/main/';
const load=async f=>{const r=await fetch(RAW+f+'?x='+Date.now(),{cache:'no-store'});if(!r.ok)throw new Error('fetch failed '+r.status+' '+f);return(0,eval)(await r.text());};
async function ensureWasmModule(){const good=v=>!!(v&&v.HEAPU8 instanceof Uint8Array&&v.HEAPU32 instanceof Uint32Array&&v.HEAPU8.buffer===v.HEAPU32.buffer);if(good(self._0x515056))return self._0x515056;const until=performance.now()+8000;while(performance.now()<until){for(const k of Object.getOwnPropertyNames(self)){let v;try{v=self[k]}catch(_){continue}if(good(v)){self._0x515056=v;self.__WOF_MODULE_GLOBAL_KEY=k;return v;}}await new Promise(r=>setTimeout(r,50));}throw new Error('WOF WASM module not found; select live gstyphoon.js Worker.');}
await ensureWasmModule();if(!self.__WOF_DISPATCH_INCOMING){await load('wof_dispatch_incoming_edges.js');await WOFDISPIN.run();}if(!self.__WOF_ROM_LOC_CACHE)throw new Error('ROM cache missing after resume');
const current={
 version:'wof-resume-dispatch-selector-v42',copyIdPolicy:'Reject returned data unless copyId/project/version/marker match the expected run.',selectorSolved:true,selectorField:'enemy+0x7E authoritative target;0/4/8=P1/P2/P3',selectedPointerCache:'enemy+0x6A supporting only when BE1C/BEFC/BFDC',activeAttackField:'enemy+0x70 U16 0->nonzero ACTIVE-start convention, not exact damage/hitbox onset',xyFields:'object+4/+8 confirmed X/Y 16.16; Z unconfirmed',retargetPolicy:'Always use live enemy+0x7E',
 v25Result:'10ms polling falsified broad T16 FAST<=100 and MID<=250 as universal. FAST6/11 strict with late180.2/260/440.4 and2 hard misses; MID6/9 strict with320.4 late and2 hard misses. Tuple alone insufficient.',
 v26Result:'Correct WOF-026 with strong T16 coverage: FAST17 evaluable=>16 strict,1 late119.9,0 hardMiss; MID3/3 strict. All16 strict FAST resolved as attack6432 and every trace reached exact pre-active phase FE851AE/NX84C44/VFFFF, timer34=1, action2A=4,b2B=4 about10.3..20.4ms before ACTIVE. Sole late FAST was attack4840 and diverged to FE851AE/NX84DD0/V200.',
 v30Result:'Correct WOF-030,120s,10ms. T16_6432_B4_40 had65/65 strict <=40ms, all attack6432, targetSame65/65, sideStable65/65, leads9.0..21.1ms; promote exact B4 phase to production-shadow. T30_FAST_100 had3/3 strict at19.0/20.0/20.1ms; keep production-shadow-candidate because old V22 119ms remains unresolved. T16_4840_DIVERGE_80 remains discovery-only.',
 v31Result:'Correct WOF-031,120s,10ms,51115 enemy samples and282 ACTIVE edges. Existing T16/T30 live rules had zero entries in this room, but fingerprint mining produced strong new candidates. T27 attack5064 repeatedly used exact BODY5048/FE9A32C/NX99CB0/VFFFF/TM1/P6C5056; B4 occurred near20ms and also around100ms, so test a conservative <=130ms prospective gate rather than assume20ms. T34 attack3232 showed an unusually clean countdown phase BODY2872/FE8811E/NX879E2/V100000/P6C2784 with timer34 approximately TM15~250ms, TM6~100ms, TM3~50ms, TM1/2~20ms; this is the strongest next-rule candidate. T33 has a lower-count analogous 3232 countdown at FE867BA/NX85ECE. T23 attack5888 has a lower-count exact B4 phase BODY4936/FE84060/NX83C60/VFFFF/TM1/P6C4944. T20 attack5136 broad signature persists from20 through500ms and is therefore not treated as an imminent terminal gate. T34 attack5336 broad TM60 signature is also present hundreds of ms earlier and overlaps long-horizon states, so do not promote it as an attack-specific imminent rule.',
 productionCorrection:'T16 exact terminal B4 remains production-shadow. Broad T16 FAST/MID remain discovery only. T30_FAST remains production-shadow-candidate. WOF-031 fingerprints are correlation/discovery evidence only until prospective validation.',
 v32Plan:'Prospectively validate four strongest mined candidates while retaining T16/T30 shadow rules: T34_3232_TM6_130 exact countdown gate; T27_5064_B4_130 exact B4 gate; lower-count T33_3232_TM6_130 analogue; lower-count T23_5888_B4_120. Use exact descriptor/body/value/payload fields, live +0x7E target, 10ms polling, expected attack identity, target/side stability, strict+jitter+late+hard-miss classification. Do not test T20 broad phase or T34 5336 broad TM60 as imminent warnings yet.',
 nextScript:'wof_future_danger_next_rule_prospective_validator_v32.js',nextCopyId:'WOF-032',nextMarker:'=== WOF FUTURE DANGER NEXT RULE PROSPECTIVE VALIDATOR V32 JSON ===',
 exclusions:'Do not treat mined lag fingerprints as causal proof; do not promote persistent T20 5136 or T34 5336 phases as imminent just because they appear at sampled lags; do not demote validated T16 B4; do not promote 4840 divergence; do not restart selector/identity/pointer proofs, Focus Multiroom,44-edge scan,0x0080F2,0x11C26, broad T16 FAST/MID as production, T30 type-wide warning, or call empirical geometry exact hitboxes.'
};self.__WOF_RESUME_FRONTIER=current;console.log('=== CURRENT SELECTOR FRONTIER ===');console.table([current]);console.log('NEXT:',current.nextCopyId,current.nextScript);return current;
})().catch(e=>{console.error('WOF_RESUME_ERROR',e);throw e;});