(async()=>{
'use strict';
const PROJECT='WOF-AI-PRIVATE',VERSION='wof-future-danger-live-rule-shadow-v21',MARKER='=== WOF FUTURE DANGER LIVE RULE SHADOW V21 JSON ===';
console.log('=== WOF PROJECT | V21 | LIVE RULE SHADOW | gstyphoon.js Worker ONLY ===');
console.log('EXPECTED VERSION:',VERSION);console.log('EXPECTED RESULT MARKER:',MARKER);
const good=v=>!!(v&&v.HEAPU8 instanceof Uint8Array&&v.HEAPU32 instanceof Uint32Array&&v.HEAPU8.buffer===v.HEAPU32.buffer);
if(!good(self._0x515056)){const until=performance.now()+8000;let hit=null;while(performance.now()<until&&!hit){for(const k of Object.getOwnPropertyNames(self)){let v;try{v=self[k]}catch(_){continue}if(good(v)){hit={k,v};break}}if(!hit)await new Promise(r=>setTimeout(r,50));}if(!hit)throw new Error('WOF V21: WASM module not found. Wrong Console context: select the live gstyphoon.js Worker.');self._0x515056=hit.v;self.__WOF_MODULE_GLOBAL_KEY=hit.k;console.log('✅ WOF V21 module:',hit.k,'→ _0x515056');}
const M=self._0x515056.HEAPU8,R=self._0x515056.HEAPU32?.[0x2e39e4>>>2]>>>0;if(!R)throw new Error('WOF V21: CPS RAM base missing');
const B=a=>M[R+((((a-0xFF0000)&0xffff)^1))]>>>0,U16=a=>((B(a)<<8)|B(a+1))>>>0,U32=a=>(B(a)*0x1000000+B(a+1)*0x10000+B(a+2)*0x100+B(a+3))>>>0,S32=a=>{const v=U32(a);return v>=0x80000000?v-0x100000000:v;};
const X=a=>Math.round(S32(a+4)/65536),Y=a=>Math.round(S32(a+8)/65536),ENEMY=0xFFC0BC,STRIDE=0xE0,SLOTS=20,PLAYERS={0:'P1',4:'P2',8:'P3'},PBASE={0:0xFFBE1C,4:0xFFBEFC,8:0xFFBFDC};
const side=dx=>dx<-4?'LEFT':dx>4?'RIGHT':'CENTER',lane=dy=>dy<-4?'UP':dy>4?'DOWN':'SAME';
function snap(i){const a=ENEMY+i*STRIDE,type=U16(a+0x20);if(type>=47)return null;const frameEnd=U32(a+0x12),next=U32(a+0x2C);if(!frameEnd&&!next)return null;const t7=U16(a+0x7E),pb=PBASE[t7],ex=X(a),ey=Y(a),tx=pb?X(pb):null,ty=pb?Y(pb):null,dx=tx==null?null:tx-ex,dy=ty==null?null:ty-ey;return{slot:i,type,target7E:t7,target:PLAYERS[t7]||null,state99:B(a+0x99),action2A:B(a+0x2A),b2B:B(a+0x2B),body:U16(a+0x6E),attack:U16(a+0x70),frameEnd,next,value30:U32(a+0x30),enemyX:ex,enemyY:ey,targetX:tx,targetY:ty,dx,dy,absDx:dx==null?null:Math.abs(dx),absDy:dy==null?null:Math.abs(dy),side:dx==null?null:side(dx),lane:dy==null?null:lane(dy)};}
const FAST=new Set(['0/4/2','0/4/4','2/4/2','2/4/4','2/0/0','4/4/2','4/4/4','4/0/0']);
const RULES=[
{id:'T16_FAST_100',type:16,horizon:100,level:'IMMINENT',status:'production-candidate',expected:[6432],reachX:365,reachY:25,match:s=>s.type===16&&s.attack===0&&s.body===4856&&s.frameEnd===0x851ae&&s.next===0x84c44&&s.value30===0xffff&&FAST.has(`${s.state99}/${s.action2A}/${s.b2B}`)},
{id:'T16_MID_250',type:16,horizon:250,level:'IMMINENT',status:'provisional',expected:[6432],reachX:365,reachY:25,match:s=>s.type===16&&s.attack===0&&s.body===4856&&s.state99===2&&s.action2A===4&&s.b2B===2&&s.frameEnd===0x85240&&s.next===0x84c3a&&s.value30===0x100000},
{id:'T30_FAST_100',type:30,horizon:100,level:'IMMINENT',status:'provisional-high',expected:[2528,2536],reachX:191,reachY:10,match:s=>s.type===30&&s.attack===0&&s.body===1800&&s.state99===0&&s.action2A===0&&s.b2B===0}
];
const DURATION=120000,INTERVAL=20,start=performance.now(),prev=new Map(),cycle=new Map(),armed=new Map(),watches=[],events=[];let idn=0;
const diag={polls:0,enemySamples:0,activeEdges:0,signals:0,typeSamples:{},rawMatchSamples:{},transitionEntries:{}};
const live={project:PROJECT,version:VERSION,updatedRel:0,entries:{}};self.__WOF_FUTURE_DANGER_MAP_STATE=live;
const key=(slot,rule)=>slot+'|'+rule;
function arm(r,s,t,p){const c=cycle.get(s.slot)||0,k=key(s.slot,r.id);if(armed.get(k)===c)return;armed.set(k,c);const w={id:++idn,rule:r.id,status:r.status,type:r.type,slot:s.slot,cycle:c,horizonMs:r.horizon,at:t,target7E:s.target7E,target:s.target,side:s.side,lane:s.lane,expected:r.expected,entry:{enemyX:s.enemyX,enemyY:s.enemyY,targetX:s.targetX,targetY:s.targetY,dx:s.dx,dy:s.dy,absDx:s.absDx,absDy:s.absDy},prevMotion:p?{enemyDx:s.enemyX-p.enemyX,enemyDy:s.enemyY-p.enemyY,targetDx:s.targetX!=null&&p.targetX!=null?s.targetX-p.targetX:null,targetDy:s.targetY!=null&&p.targetY!=null?s.targetY-p.targetY:null}:null,resolved:false,hit:null,censored:false};watches.push(w);diag.signals++;live.entries[k]={rule:r.id,status:r.status,level:r.level,horizonMs:r.horizon,deadlineRel:t+r.horizon,target:s.target,enemyX:s.enemyX,enemyY:s.enemyY,targetX:s.targetX,targetY:s.targetY,dx:s.dx,dy:s.dy,side:s.side,lane:s.lane,empiricalReachX:r.reachX,empiricalReachY:r.reachY,insideEmpiricalEnvelope:s.absDx!=null&&s.absDy!=null&&s.absDx<=r.reachX&&s.absDy<=r.reachY};events.push({kind:'SIGNAL',rel:t,rule:r.id,status:r.status,slot:s.slot,type:s.type,target:s.target});console.log(`[WOF V21][${r.status}] SIGNAL ${r.id} slot${s.slot} -> ${s.target||'?'} horizon<=${r.horizon}ms`);}
function resolveActive(s,t){diag.activeEdges++;for(const w of watches){if(w.resolved||w.slot!==s.slot||w.type!==s.type)continue;const lead=t-w.at;if(lead<0||lead>w.horizonMs)continue;w.resolved=true;w.hit=true;w.leadMs=lead;w.activeAttack=s.attack;w.attackExpected=w.expected.includes(s.attack);w.targetSame=w.target7E===s.target7E;w.sideSame=w.side===s.side;w.active={enemyX:s.enemyX,enemyY:s.enemyY,targetX:s.targetX,targetY:s.targetY,dx:s.dx,dy:s.dy,absDx:s.absDx,absDy:s.absDy};w.delta={enemyX:s.enemyX-w.entry.enemyX,enemyY:s.enemyY-w.entry.enemyY,targetX:s.targetX!=null&&w.entry.targetX!=null?s.targetX-w.entry.targetX:null,targetY:s.targetY!=null&&w.entry.targetY!=null?s.targetY-w.entry.targetY:null,dx:s.dx!=null&&w.entry.dx!=null?s.dx-w.entry.dx:null,dy:s.dy!=null&&w.entry.dy!=null?s.dy-w.entry.dy:null};events.push({kind:'HIT',rel:t,rule:w.rule,slot:s.slot,type:s.type,leadMs:lead,attack:s.attack,target:s.target});delete live.entries[key(w.slot,w.rule)];console.log(`[WOF V21] HIT ${w.rule} slot${s.slot} ${lead}ms attack=${s.attack}`);}cycle.set(s.slot,(cycle.get(s.slot)||0)+1);}
function expire(t){for(const w of watches){if(w.resolved)continue;if(t-w.at>w.horizonMs){w.resolved=true;w.hit=false;events.push({kind:'MISS',rel:t,rule:w.rule,slot:w.slot,type:w.type});delete live.entries[key(w.slot,w.rule)];console.log(`[WOF V21] MISS ${w.rule} slot${w.slot}`);}}}
await new Promise(resolve=>{const timer=setInterval(()=>{const t=Math.round(performance.now()-start);diag.polls++;live.updatedRel=t;for(let i=0;i<SLOTS;i++){const s=snap(i),p=prev.get(i)||null;if(!s){if(p){for(const w of watches)if(!w.resolved&&w.slot===i){w.resolved=true;w.censored=true;w.censorReason='slotGone';delete live.entries[key(w.slot,w.rule)];}}prev.delete(i);continue;}diag.enemySamples++;diag.typeSamples['T'+s.type]=(diag.typeSamples['T'+s.type]||0)+1;if(p&&p.attack===0&&s.attack!==0)resolveActive(s,t);for(const r of RULES){if(s.type!==r.type)continue;const m=r.match(s),pm=!!(p&&p.type===s.type&&r.match(p));if(m)diag.rawMatchSamples[r.id]=(diag.rawMatchSamples[r.id]||0)+1;if(m&&!pm){diag.transitionEntries[r.id]=(diag.transitionEntries[r.id]||0)+1;arm(r,s,t,p);}}prev.set(i,s);}expire(t);if(t>=DURATION){clearInterval(timer);for(const w of watches)if(!w.resolved){w.resolved=true;w.censored=true;w.censorReason='captureEnd';delete live.entries[key(w.slot,w.rule)];}resolve();}},INTERVAL);});
const median=a=>{if(!a.length)return null;const b=[...a].sort((x,y)=>x-y),m=b.length>>1;return b.length%2?b[m]:Math.round((b[m-1]+b[m])/2)},pct=(a,p)=>{if(!a.length)return null;const b=[...a].sort((x,y)=>x-y);return b[Math.max(0,Math.ceil(p*b.length)-1)]};
const stats={};for(const r of RULES)stats[r.id]={rule:r.id,status:r.status,horizonMs:r.horizon,signals:0,evaluable:0,hit:0,miss:0,censored:0,precision:null,leads:[],attackExpected:0,attackTotal:0,targetSame:0,targetTotal:0,sideSame:0,sideTotal:0,entryAbsDx:[],entryAbsDy:[],activeAbsDx:[],activeAbsDy:[],enemyMoveX:[],enemyMoveY:[],targetMoveX:[],targetMoveY:[]};
for(const w of watches){const q=stats[w.rule];q.signals++;if(w.censored){q.censored++;continue;}q.evaluable++;if(w.hit){q.hit++;q.leads.push(w.leadMs);q.attackTotal++;if(w.attackExpected)q.attackExpected++;q.targetTotal++;if(w.targetSame)q.targetSame++;q.sideTotal++;if(w.sideSame)q.sideSame++;if(w.entry.absDx!=null)q.entryAbsDx.push(w.entry.absDx);if(w.entry.absDy!=null)q.entryAbsDy.push(w.entry.absDy);if(w.active?.absDx!=null)q.activeAbsDx.push(w.active.absDx);if(w.active?.absDy!=null)q.activeAbsDy.push(w.active.absDy);if(w.delta){q.enemyMoveX.push(w.delta.enemyX);q.enemyMoveY.push(w.delta.enemyY);if(w.delta.targetX!=null)q.targetMoveX.push(w.delta.targetX);if(w.delta.targetY!=null)q.targetMoveY.push(w.delta.targetY);}}else q.miss++;}
for(const q of Object.values(stats)){q.precision=q.evaluable?+(q.hit/q.evaluable).toFixed(3):null;q.attackExpectedRate=q.attackTotal?+(q.attackExpected/q.attackTotal).toFixed(3):null;q.targetSameRate=q.targetTotal?+(q.targetSame/q.targetTotal).toFixed(3):null;q.sideStableRate=q.sideTotal?+(q.sideSame/q.sideTotal).toFixed(3):null;q.leads.sort((a,b)=>a-b);for(const [name,a] of Object.entries({entryAbsDx:q.entryAbsDx,entryAbsDy:q.entryAbsDy,activeAbsDx:q.activeAbsDx,activeAbsDy:q.activeAbsDy,enemyMoveX:q.enemyMoveX,enemyMoveY:q.enemyMoveY,targetMoveX:q.targetMoveX,targetMoveY:q.targetMoveY})){q[name+'Median']=median(a);q[name+'P90']=pct(a,.9);delete q[name];}}
const out={project:PROJECT,version:VERSION,expectedMarker:MARKER,readOnly:true,ramWrites:0,durationRequestedMs:DURATION,intervalMs:INTERVAL,copySafety:{expectedProject:PROJECT,expectedVersion:VERSION,expectedMarker:MARKER,requiredContext:'gstyphoon.js Worker',instruction:'If any returned version/marker differs, treat it as a wrong paste and do not interpret it as this run.'},model:{productionCandidate:'T16_FAST_100 only',provisional:['T16_MID_250','T30_FAST_100'],geometry:'empirical ACTIVE-start/signal distributions; not exact hitboxes'},diagnostics:diag,ruleStats:stats,watches,events:events.slice(-120),note:'V21 is shadow/read-only. T16_FAST_100 is promoted to production-candidate shadow after fresh-room V20 independent-cycle 17/17 <=100ms with attack/target/side all 1.0. T7 candidates were dropped after V20 precision degraded.'};
self.__WOF_FUTURE_DANGER_LIVE_RULE_SHADOW_V21=out;console.log(MARKER);console.log(JSON.stringify(out,null,2));return out;
})().catch(e=>{console.error('WOF_V21_ERROR',e);throw e;});