(()=>{
'use strict';
try{self.WOFTARGETXYCLUSTER?.stop?.();}catch(_){}
const RAW='https://raw.githubusercontent.com/ouyong520/wof-ai-private/main/';
const sleep=ms=>new Promise(r=>setTimeout(r,ms));let stopped=false;
const load=async f=>{const r=await fetch(RAW+f+'?x='+Math.random());if(!r.ok)throw new Error('fetch failed '+r.status+' '+f);return (0,eval)(await r.text());};
async function ensure(){if(!self.__WOF_TARGET_XY_GLOBAL?.pairs?.length){await load('wof_target_xy_global_write_scan.js');await WOFTARGETXYGLOBAL.run();}if(!self.__WOF_ROM_LOC_CACHE)throw new Error('ROM state unavailable');}
function env(){const MOD=_0x515056,C=self.__WOF_ROM_LOC_CACHE,M=MOD.HEAPU8,base=C.base,SW=!!C.swap16,MAX=Math.min(0x100000,M.length-base),DELTA=C.offlineDelta|0;
 const r8=o=>M[base+(SW?(o^1):o)]>>>0,r16=o=>((r8(o)<<8)|r8(o+1))>>>0,r32=o=>(r8(o)*0x1000000+r8(o+1)*0x10000+r8(o+2)*0x100+r8(o+3))>>>0,s8=v=>v&0x80?v-0x100:v,s16=v=>v&0x8000?v-0x10000:v;
 const h=x=>'0x'+(x>>>0).toString(16).toUpperCase().padStart(6,'0'),off=x=>h((x-DELTA)>>>0),hw=x=>'0x'+(x&0xffff).toString(16).toUpperCase().padStart(4,'0');return{MAX,r8,r16,r32,s8,s16,h,off,hw};}
function eaWords(m,r,size){if(m<=4)return 0;if(m===5||m===6)return 1;if(m===7){if(r===0||r===2||r===3)return 1;if(r===1)return 2;if(r===4)return size==='L'?2:1;}return 0;}
function eaName(E,p,m,r,size){if(m===0)return'D'+r;if(m===1)return'A'+r;if(m===2)return'(A'+r+')';if(m===3)return'(A'+r+')+';if(m===4)return'-(A'+r+')';if(m===5)return E.s16(E.r16(p))+'(A'+r+')';if(m===6)return'd8(A'+r+',Xn)';if(m===7&&r===0)return E.s16(E.r16(p))+'.W';if(m===7&&r===1)return E.h(E.r32(p));if(m===7&&r===2)return E.s16(E.r16(p))+'(PC)';if(m===7&&r===3)return'd8(PC,Xn)';if(m===7&&r===4)return'#imm';return'EA';}
function decode(E,p){const w=E.r16(p),g=w>>>12,m=(w>>3)&7,r=w&7;let len=2,kind='OP',target=null,fall=true,terminal=false,call=false,branch=false,text=E.hw(w),write=null;
 if(w===0x4E75||w===0x4E73||w===0x4E77){kind='RET';terminal=true;fall=false;text=kind;}
 else if(w===0x4E72){kind='STOP';len=4;terminal=true;fall=false;text='STOP';}
 else if((w&0xFFC0)===0x4E80){kind='JSR';call=true;len=2+eaWords(m,r,'L')*2;if(m===7&&r===0)target=E.s16(E.r16(p+2))>>>0;else if(m===7&&r===1)target=E.r32(p+2);else if(m===7&&r===2)target=(p+2+E.s16(E.r16(p+2)))>>>0;text='JSR';}
 else if((w&0xFFC0)===0x4EC0){kind='JMP';fall=false;len=2+eaWords(m,r,'L')*2;if(m===7&&r===0)target=E.s16(E.r16(p+2))>>>0;else if(m===7&&r===1)target=E.r32(p+2);else if(m===7&&r===2)target=(p+2+E.s16(E.r16(p+2)))>>>0;text='JMP';}
 else if(g===6){const cc=(w>>8)&15,d=w&255;len=d===0?4:2;target=d===0?p+2+E.s16(E.r16(p+2)):p+2+E.s8(d);kind=cc===0?'BRA':cc===1?'BSR':'BCC';branch=true;if(cc===0)fall=false;if(cc===1)call=true;text=kind;}
 else if(g===1||g===2||g===3){const size=g===1?'B':g===2?'L':'W',sm=(w>>3)&7,sr=w&7,dm=(w>>6)&7,dr=(w>>9)&7,sw=eaWords(sm,sr,size),dw=eaWords(dm,dr,size),srcExt=p+2,dstExt=p+2+sw*2;len=2+(sw+dw)*2;kind='MOVE';text='MOVE.'+size+' '+eaName(E,srcExt,sm,sr,size)+','+eaName(E,dstExt,dm,dr,size);if(dm===5){const disp=E.s16(E.r16(dstExt));write={disp,baseReg:'A'+dr,kind:'MOVE.'+size,src:eaName(E,srcExt,sm,sr,size),srcReg:sm<=1?(sm===0?'D':'A')+sr:''};}}
 else if(g===5){const sz=(w>>6)&3;if(sz===3&&m===1){kind='DBCC';len=4;target=(p+2+E.s16(E.r16(p+2)))>>>0;branch=true;text='DBCC';}else{const size=sz===2?'L':sz===1?'W':'B';len=2+eaWords(m,r,size)*2;kind='QEA';if(m===5){const disp=E.s16(E.r16(p+2)),sub=!!(w&0x0100),q=((w>>9)&7)||8;write={disp,baseReg:'A'+r,kind:(sub?'SUBQ.':'ADDQ.')+size,src:'#'+q};text=write.kind+' #'+q+','+disp+'(A'+r+')';}}}
 else if(g===0){if([0x003C,0x007C,0x023C,0x027C,0x0A3C,0x0A7C].includes(w))len=4;else if((w&0xF138)===0x0108)len=4;else if((w&0xFF00)===0x0800)len=4+eaWords(m,r,'B')*2;else if((w&0xF100)===0x0100)len=2+eaWords(m,r,'B')*2;else{const op=(w>>8)&15,sz=(w>>6)&3;if([0,2,4,6,10,12].includes(op)){const size=sz===2?'L':sz===1?'W':'B',iw=size==='L'?2:1;len=2+iw*2+eaWords(m,r,size)*2;const names={0:'ORI',2:'ANDI',4:'SUBI',6:'ADDI',10:'EORI',12:'CMPI'},nm=names[op]||'IMM';if(m===5&&op!==12){const ext=p+2+iw*2,disp=E.s16(E.r16(ext)),imm=size==='L'?E.r32(p+2):E.r16(p+2);write={disp,baseReg:'A'+r,kind:nm+'.'+size,src:'#'+(size==='L'?E.h(imm):E.hw(imm))};text=write.kind+' '+write.src+','+disp+'(A'+r+')';}}}}
 else if(g===4){if((w&0xFFF8)===0x4E50)len=4;else if((w&0xFB80)===0x4880&&m>=2)len=4+eaWords(m,r,(w&0x40)?'L':'W')*2;else if((w&0xF1C0)===0x41C0)len=2+eaWords(m,r,'L')*2;else if((w&0xFFC0)===0x4840&&m!==0)len=2+eaWords(m,r,'L')*2;else{const size=((w>>6)&3)===2?'L':'W';len=2+eaWords(m,r,size)*2;if(m===5&&(((w&0xff00)===0x4200)||((w&0xff00)===0x4400)||((w&0xff00)===0x4600))){const disp=E.s16(E.r16(p+2)),nm=(w&0xff00)===0x4200?'CLR':(w&0xff00)===0x4400?'NEG':'NOT';write={disp,baseReg:'A'+r,kind:nm+'.'+size,src:''};text=write.kind+' '+disp+'(A'+r+')';}}}
 else if(g===8){if((w&0xF1F0)!==0x8100)len=2+eaWords(m,r,((w>>6)&3)===2?'L':'W')*2;}
 else if(g===9||g===13){const special=(w&0xF130)===(g===9?0x9100:0xD100),a=((w>>6)&7)===3||((w>>6)&7)===7;if(!special)len=2+eaWords(m,r,a?(((w>>6)&1)?'L':'W'):(((w>>6)&3)===2?'L':'W'))*2;}
 else if(g===11){const cmpm=(w&0xF138)===0xB108,a=((w>>6)&7)===3||((w>>6)&7)===7;if(!cmpm)len=2+eaWords(m,r,a?(((w>>6)&1)?'L':'W'):(((w>>6)&3)===2?'L':'W'))*2;}
 else if(g===12){const exg=(w&0xF1F8)===0xC140||(w&0xF1F8)===0xC148||(w&0xF1F8)===0xC188,abcd=(w&0xF1F0)===0xC100;if(!exg&&!abcd)len=2+eaWords(m,r,((w>>6)&3)===2?'L':'W')*2;}
 else if(g===14&&((w>>6)&3)===3)len=2+eaWords(m,r,'W')*2;
 else if(g===10||g===15){kind='LINE';terminal=true;fall=false;}
 len=Math.max(2,len);const next=p+len;if(target!=null&&(target<0||target>=E.MAX))target=null;return{at:p,w,len,next,kind,target,fall,terminal,call,branch,text,write};}
function walk(E,start,lo,hi,targets){const q=[start&~1],seen=new Set(),calls=[];while(q.length&&seen.size<5000){const p=q.shift();if(p<lo||p>=hi||(p&1)||seen.has(p))continue;seen.add(p);const d=decode(E,p);if((d.kind==='JSR'||d.kind==='BSR')&&d.target!=null)calls.push({at:p,target:d.target&~1,kind:d.kind});if(d.kind==='BRA'){if(d.target!=null&&d.target>=lo&&d.target<hi)q.push(d.target&~1);continue;}if(d.kind==='BCC'||d.kind==='DBCC'){if(d.next<hi)q.push(d.next);if(d.target!=null&&d.target>=lo&&d.target<hi)q.push(d.target&~1);continue;}if(d.kind==='JMP'){if(d.target!=null&&d.target>=lo&&d.target<hi)q.push(d.target&~1);continue;}if(d.terminal)continue;if(d.next<hi)q.push(d.next);}return{seen,calls,hits:targets.map(t=>seen.has(t))};}
function candidateStarts(E,lo,hi){const s=new Set([lo&~1]);for(let p=lo&~1;p<hi-2;p+=2){const w=E.r16(p);if((w&0xFFF8)===0x4E50||w===0x48E7)s.add(p);if(w===0x4E75||w===0x4E73||w===0x4E77)s.add(p+2);}return[...s].filter(x=>x>=lo&&x<hi).sort((a,b)=>a-b);}
function validatePair(E,pair){const x=pair.xAt&~1,y=pair.yAt&~1,lo=Math.max(0,Math.min(x,y)-0x300),hi=Math.min(E.MAX,Math.max(x,y)+0x300),starts=candidateStarts(E,lo,Math.min(x,y)+2);let best=null;for(const s of starts){const w=walk(E,s,lo,hi,[x,y]);if(w.hits[0]||w.hits[1]){const score=(w.hits[0]?10:0)+(w.hits[1]?10:0)+(s<=Math.min(x,y)?2:0)-Math.min(4,(Math.min(x,y)-s)/128);if(!best||score>best.score)best={start:s,score,...w};}}
 const dx=decode(E,x),dy=decode(E,y),xWrite=dx.write&&dx.write.disp===0x3e&&dx.write.baseReg===pair.baseReg,yWrite=dy.write&&dy.write.disp===0x42&&dy.write.baseReg===pair.baseReg;
 return{pair,best,dx,dy,xBoundary:!!best?.seen.has(x),yBoundary:!!best?.seen.has(y),sameRoutine:!!(best?.seen.has(x)&&best?.seen.has(y)),xWrite:!!xWrite,yWrite:!!yWrite};}
function directCallers(E,target){const out=[];for(let p=0;p+6<E.MAX;p+=2){const w=E.r16(p);let t=null,kind='';if(w===0x4EB8){t=E.s16(E.r16(p+2))>>>0;kind='JSR abs.W';}else if(w===0x4EB9){t=E.r32(p+2);kind='JSR abs.L';}else if(w===0x4EBA){t=p+2+E.s16(E.r16(p+2));kind='JSR d16(PC)';}else if((w&0xFF00)===0x6100){const d=w&255;t=d===0?p+2+E.s16(E.r16(p+2)):p+2+E.s8(d);kind=d===0?'BSR.W':'BSR.S';}if(t!=null&&(t&~1)===(target&~1))out.push({at:p,kind});}return out;}
function context(E,p){const out=[];for(let q=Math.max(0,p-0x18)&~1;q<=Math.min(E.MAX-2,p+0x18);q+=2)out.push({at:E.h(q),offline:E.off(q),word:E.hw(E.r16(q)),mark:q===p?'<<<':''});return out;}
async function run(){stopped=false;await ensure();const E=env(),G=self.__WOF_TARGET_XY_GLOBAL,pairs=(G.pairs||[]).slice(0,3);console.log('🧪 WOF target XY cluster validation v1 · top 3 global pairs');const vals=[];
 for(let i=0;i<pairs.length;i++){if(stopped)throw new Error('stopped');const v=validatePair(E,pairs[i]);let callers=[];if(v.best)callers=directCallers(E,v.best.start);vals.push({rank:i+1,xAt:E.h(v.pair.xAt),yAt:E.h(v.pair.yAt),offlineX:E.off(v.pair.xAt),offlineY:E.off(v.pair.yAt),baseReg:v.pair.baseReg,distance:v.pair.distance,xBoundary:v.xBoundary,yBoundary:v.yBoundary,sameRoutine:v.sameRoutine,xWrite:v.xWrite,yWrite:v.yWrite,routine:v.best?E.h(v.best.start):'',offlineRoutine:v.best?E.off(v.best.start):'',xText:v.dx.text,yText:v.dy.text,xKind:v.dx.write?.kind||'',yKind:v.dy.write?.kind||'',xSrc:v.dx.write?.src||'',ySrc:v.dy.write?.src||'',directCallers:callers.length,_v:v,_callers:callers});await sleep(0);}
 console.log('=== XY CLUSTER VALIDATION ===');console.table(vals.map(({_v,_callers,...x})=>x));const good=vals.filter(x=>x.sameRoutine&&x.xWrite&&x.yWrite),top=good[0]||vals[0]||null;
 if(top){console.log('=== SELECTED CLUSTER X CONTEXT ===');console.table(context(E,parseInt(top.xAt,16)));console.log('=== SELECTED CLUSTER Y CONTEXT ===');console.table(context(E,parseInt(top.yAt,16)));console.log('=== SELECTED ROUTINE DIRECT CALLERS ===');console.table((top._callers||[]).map(x=>({at:E.h(x.at),offline:E.off(x.at),kind:x.kind})).slice(0,80));}
 const verdict={pairsTested:vals.length,realSameRoutinePairs:good.length,selectedRank:top?.rank??'',selectedRoutine:top?.routine||'',selectedOffline:top?.offlineRoutine||'',selectedXAt:top?.xAt||'',selectedYAt:top?.yAt||'',selectedBaseReg:top?.baseReg||'',selectedXKind:top?.xKind||'',selectedYKind:top?.yKind||'',selectedXSrc:top?.xSrc||'',selectedYSrc:top?.ySrc||'',selectedCallers:top?.directCallers??0};console.log('=== XY CLUSTER VALIDATION VERDICT ===');console.table([verdict]);
 if(good.length)console.log('🎯 至少一个 global pair 同时通过真实指令边界 + 同一 CFG/routine + 精确 +0x3E/+0x42 写入验证；下一步只追 selected cluster 的 source/caller。');else console.warn('❌ top 3 global distance clusters 都未通过同一真实 CFG pair 验证；这些是全 ROM 2-byte 扫描的聚类假阳性，停止追它们，转动态 waypoint-change→state/action 映射。');
 const out={version:'wof-target-xy-cluster-validate-v1',verdict,rows:vals.map(({_v,_callers,...x})=>x)};self.__WOF_TARGET_XY_CLUSTER=out;return out;}
self.WOFTARGETXYCLUSTER={version:'wof-target-xy-cluster-validate-v1',run,stop(){stopped=true;}};console.log('✅ WOF target XY cluster validator v1 loaded');console.log('执行 await WOFTARGETXYCLUSTER.run()');
})();