(async()=>{
'use strict';
const COPY_ID='WOF-045R';
const PROJECT='WOF-AI-PRIVATE';
const VERSION='wof-future-danger-cycle-validator-v45r';
const MARKER='=== WOF FUTURE DANGER CYCLE VALIDATOR V45R JSON ===';
const SRC='https://raw.githubusercontent.com/ouyong520/wof-ai-private/main/wof_future_danger_cycle_validator_v44r.js';
console.log(`[${COPY_ID}] ${PROJECT} ${VERSION}`);
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const good=v=>!!(v&&v.HEAPU8 instanceof Uint8Array&&v.HEAPU32 instanceof Uint32Array&&v.HEAPU8.buffer===v.HEAPU32.buffer);
async function ensureModule(){if(good(self._0x515056))return self._0x515056;const until=performance.now()+8000;while(performance.now()<until){for(const k of Object.getOwnPropertyNames(self)){let v;try{v=self[k]}catch(_){continue}if(good(v)){self._0x515056=v;self.__WOF_MODULE_GLOBAL_KEY=k;return v;}}await sleep(50);}throw new Error(`[${COPY_ID}] WASM module not found. Select a live gstyphoon.js Worker.`);}
const MOD=await ensureModule(),M=MOD.HEAPU8,R=MOD.HEAPU32?.[0x2e39e4>>>2]>>>0;if(!R)throw new Error(`[${COPY_ID}] CPS RAM base missing`);
const B=a=>M[R+((((a-0xFF0000)&0xffff)^1))]>>>0,U16=a=>((B(a)<<8)|B(a+1))>>>0,U32=a=>(B(a)*0x1000000+B(a+1)*0x10000+B(a+2)*0x100+B(a+3))>>>0,S32=a=>{const v=U32(a);return v>=0x80000000?v-0x100000000:v;},X=a=>Math.round(S32(a+4)/65536);
const ENEMY=0xFFC0BC,STRIDE=0xE0,SLOTS=20,PBASE={0:0xFFBE1C,4:0xFFBEFC,8:0xFFBFDC},PN={0:'P1',4:'P2',8:'P3'};
const side=dx=>dx==null?null:dx<-4?'LEFT':dx>4?'RIGHT':'CENTER';
function snap(i){const a=ENEMY+i*STRIDE,type=U16(a+0x20);if(type>=47)return null;const fe=U32(a+0x12),nx=U32(a+0x2C);if(!fe&&!nx)return null;const t=U16(a+0x7E),pb=PBASE[t],ex=X(a),tx=pb?X(pb):null,dx=tx==null?null:tx-ex;return{slot:i,type,target7E:t,target:PN[t]||null,side:side(dx),state99:B(a+0x99),action2A:B(a+0x2A),b2B:B(a+0x2B),body:U16(a+0x6E),attack:U16(a+0x70),frameEnd:fe,next:nx,value30:U32(a+0x30),timer34:U16(a+0x34),payload6C:U16(a+0x6C)};}
const fp=s=>`S${s.state99}/A${s.action2A}/B${s.b2B}|BODY${s.body}|FE${s.frameEnd.toString(16)}|NX${s.next.toString(16)}|V${s.value30.toString(16)}|TM${s.timer34}|P6C${s.payload6C}`;
const r1=x=>Math.round(x*10)/10,med=a=>{if(!a.length)return null;const b=[...a].sort((x,y)=>x-y),m=b.length>>1;return b.length%2?b[m]:+(0.5*(b[m-1]+b[m])).toFixed(1);};
const T18_RULES=[
  {id:'T18_5440_CYCLE_BODY7512_TM4_LEVEL_90',status:'prospective-cycle-level-candidate',horizon:90,tail:250,expected:5440,base:s=>s&&s.type===18&&s.attack===0&&s.state99===2&&s.action2A===2&&s.b2B===4&&s.body===7512&&s.frameEnd===0x8bbb2&&s.next===0x8b290&&s.value30===0x180001&&s.timer34===4&&s.payload6C===0},
  {id:'T18_5424_CYCLE_BODY7520_TM4_LEVEL_90',status:'prospective-cycle-level-candidate',horizon:90,tail:250,expected:5424,base:s=>s&&s.type===18&&s.attack===0&&s.state99===2&&s.action2A===2&&s.b2B===4&&s.body===7520&&s.frameEnd===0x8bbde&&s.next===0x8b2a4&&s.value30===0x180001&&s.timer34===4&&s.payload6C===0}
];
function emptyRule(r){return{rule:r.id,status:r.status,horizonMs:r.horizon,tailMs:r.tail,jitterToleranceMs:15,signals:0,evaluable:0,strictHit:0,jitterBandHit:0,realLateHit:0,hardMiss:0,censored:0,expectedAttack:0,expectedAttackTotal:0,targetSame:0,targetTotal:0,sideSame:0,sideTotal:0,leads:[],attackCounts:[],entryTargetCounts:{},entrySideCounts:{},entryTypeCounts:{},strictRate:null,jitterCorrectedRate:null,tailHitRate:null,expectedAttackRate:null,targetSameRate:null,sideStableRate:null};}
function finalizeRule(st,attackMap){st.leads.sort((a,b)=>a-b);st.attackCounts=[...attackMap.entries()].map(([attack,count])=>({attack:+attack,count})).sort((a,b)=>b.count-a.count);st.strictRate=st.evaluable?+(st.strictHit/st.evaluable).toFixed(3):null;st.jitterCorrectedRate=st.evaluable?+((st.strictHit+st.jitterBandHit)/st.evaluable).toFixed(3):null;st.tailHitRate=st.evaluable?+((st.strictHit+st.jitterBandHit+st.realLateHit)/st.evaluable).toFixed(3):null;st.expectedAttackRate=st.expectedAttackTotal?+(st.expectedAttack/st.expectedAttackTotal).toFixed(3):null;st.targetSameRate=st.targetTotal?+(st.targetSame/st.targetTotal).toFixed(3):null;st.sideStableRate=st.sideTotal?+(st.sideSame/st.sideTotal).toFixed(3):null;return st;}
async function runFocusProbe(){
  const DURATION=120000,INTERVAL=10,start=performance.now(),prev=new Map(),cycles=new Map(),agg=new Map(),cycleSeq=new Map(),armed=new Map(),watches=[];let wid=0;
  const diag={polls:0,enemySamples:0,activeEdges:0,attackZeroStarts:0,cycleStatesObserved:0,resolvedCycles:0,signals:0,strictHits:0,jitterBandHits:0,realLateHits:0,hardMisses:0,censored:0,retargets:0,rawMatchSamples:{},transitionEntries:{}};
  const stats={},attackMaps={};for(const r of T18_RULES){stats[r.id]=emptyRule(r);attackMaps[r.id]=new Map();diag.rawMatchSamples[r.id]=0;diag.transitionEntries[r.id]=0;}
  const addCycle=(s,active,t,c)=>{diag.resolvedCycles++;for(const rec of c.states.values()){const first=r1(t-rec.firstAt),last=r1(t-rec.lastAt);if(first<0||last<0)continue;const k=`T${s.type}|A${active}|${rec.signature}`,q=agg.get(k)||{type:s.type,activeAttack:active,signature:rec.signature,cycleCount:0,firstLeadSamples:[],lastLeadSamples:[],targetSame:0,targetTotal:0,sideSame:0,sideTotal:0};q.cycleCount++;if(q.firstLeadSamples.length<120)q.firstLeadSamples.push(first);if(q.lastLeadSamples.length<120)q.lastLeadSamples.push(last);q.targetTotal++;if(rec.lastTarget7E===s.target7E)q.targetSame++;if(rec.lastSide!=null&&s.side!=null){q.sideTotal++;if(rec.lastSide===s.side)q.sideSame++;}agg.set(k,q);}};
  const arm=(r,s,t)=>{const c=cycleSeq.get(s.slot)||0,k=`${s.slot}|${r.id}`;if(armed.get(k)===c)return;armed.set(k,c);diag.transitionEntries[r.id]++;diag.signals++;const st=stats[r.id];st.signals++;st.entryTargetCounts[s.target]=(st.entryTargetCounts[s.target]||0)+1;st.entrySideCounts[s.side]=(st.entrySideCounts[s.side]||0)+1;st.entryTypeCounts['T'+s.type]=(st.entryTypeCounts['T'+s.type]||0)+1;watches.push({id:++wid,rule:r,slot:s.slot,type:s.type,cycle:c,at:t,entryTarget7E:s.target7E,entrySide:s.side,resolved:false,retargets:[]});};
  const censorSlot=i=>{for(const w of watches){if(w.resolved||w.slot!==i)continue;w.resolved=true;const st=stats[w.rule.id];st.censored++;diag.censored++;}};
  const deadlines=t=>{for(const w of watches){if(w.resolved)continue;if(t-w.at>w.rule.tail){w.resolved=true;const st=stats[w.rule.id];st.hardMiss++;st.evaluable++;diag.hardMisses++;}}};
  await new Promise(resolve=>{const id=setInterval(()=>{const t=performance.now()-start;diag.polls++;deadlines(t);for(let i=0;i<SLOTS;i++){const s=snap(i),p=prev.get(i)||null;if(!s){if(p)censorSlot(i);prev.delete(i);cycles.delete(i);continue;}diag.enemySamples++;if(p&&p.type!==s.type){censorSlot(i);cycles.delete(i);cycleSeq.set(i,(cycleSeq.get(i)||0)+1);}if(s.attack===0){if(!p||p.type!==s.type||p.attack!==0){cycleSeq.set(i,(cycleSeq.get(i)||0)+1);if(s.type===23||s.type===18){cycles.set(i,{type:s.type,startAt:t,states:new Map()});diag.attackZeroStarts++;}}if(s.type===23||s.type===18){let c=cycles.get(i);if(!c){c={type:s.type,startAt:t,states:new Map()};cycles.set(i,c);diag.attackZeroStarts++;}const sig=fp(s);let rec=c.states.get(sig);if(!rec){rec={signature:sig,firstAt:t,lastAt:t,lastTarget7E:s.target7E,lastSide:s.side};c.states.set(sig,rec);diag.cycleStatesObserved++;}else{rec.lastAt=t;rec.lastTarget7E=s.target7E;rec.lastSide=s.side;}}
        if(s.type===18)for(const r of T18_RULES){if(r.base(s)){diag.rawMatchSamples[r.id]++;arm(r,s,t);}}
      }
      for(const w of watches){if(w.resolved||w.slot!==i||w.type!==s.type)continue;const last=w.retargets.at(-1)?.to7E??w.entryTarget7E;if(last!==s.target7E){w.retargets.push({rel:r1(t-w.at),from7E:last,to7E:s.target7E});diag.retargets++;}}
      if(p&&p.type===s.type&&p.attack===0&&s.attack!==0){diag.activeEdges++;const c=cycles.get(i);if(c&&(s.type===23||s.type===18))addCycle(s,s.attack,t,c);cycles.delete(i);for(const w of watches){if(w.resolved||w.slot!==i||w.type!==s.type)continue;const lead=t-w.at;if(lead<0||lead>w.rule.tail)continue;w.resolved=true;const st=stats[w.rule.id];st.evaluable++;st.leads.push(r1(lead));st.expectedAttackTotal++;const ok=s.attack===w.rule.expected;if(ok)st.expectedAttack++;st.targetTotal++;if(w.entryTarget7E===s.target7E)st.targetSame++;if(w.entrySide!=null&&s.side!=null){st.sideTotal++;if(w.entrySide===s.side)st.sideSame++;}attackMaps[w.rule.id].set(s.attack,(attackMaps[w.rule.id].get(s.attack)||0)+1);if(lead<=w.rule.horizon){st.strictHit++;diag.strictHits++;}else if(lead<=w.rule.horizon+15){st.jitterBandHit++;diag.jitterBandHits++;}else{st.realLateHit++;diag.realLateHits++;}}
      }
      prev.set(i,s);
    }if(t>=DURATION){clearInterval(id);resolve();}},INTERVAL);});
  for(let i=0;i<SLOTS;i++)censorSlot(i);
  const ranked=[...agg.values()].map(q=>{q.firstLeadSamples.sort((a,b)=>a-b);q.lastLeadSamples.sort((a,b)=>a-b);return{...q,attackZeroOnly:true,targetSameRate:q.targetTotal?+(q.targetSame/q.targetTotal).toFixed(3):null,sideStableRate:q.sideTotal?+(q.sideSame/q.sideTotal).toFixed(3):null,firstLeadMin:q.firstLeadSamples[0]??null,firstLeadMedian:med(q.firstLeadSamples),firstLeadMax:q.firstLeadSamples.at(-1)??null,lastLeadMin:q.lastLeadSamples[0]??null,lastLeadMedian:med(q.lastLeadSamples),lastLeadMax:q.lastLeadSamples.at(-1)??null};}).sort((a,b)=>b.cycleCount-a.cycleCount||(b.firstLeadMedian??0)-(a.firstLeadMedian??0));
  for(const r of T18_RULES)finalizeRule(stats[r.id],attackMaps[r.id]);
  return{durationRequestedMs:DURATION,actualDurationMs:r1(performance.now()-start),diagnostics:diag,cyclePrecursorFocus:{T23:ranked.filter(q=>q.type===23).slice(0,120),T18:ranked.filter(q=>q.type===18).slice(0,120)},ruleStats:stats};
}
let code=await fetch(SRC+'?x='+Date.now(),{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error('WOF-045R base validator fetch '+r.status);return r.text();});
code=code.replaceAll('WOF-044R','WOF-045R').replaceAll('wof-future-danger-cycle-validator-v44r','wof-future-danger-cycle-validator-v45r').replaceAll('=== WOF FUTURE DANGER CYCLE VALIDATOR V44R JSON ===','=== WOF FUTURE DANGER CYCLE VALIDATOR V45R JSON ===').replaceAll('__WOF_V44R_RESULT','__WOF_V45R_RESULT');
const [out,focus]=await Promise.all([(0,eval)(code),runFocusProbe()]);
if(!out||out.copyId!==COPY_ID||out.project!==PROJECT||out.version!==VERSION||out.expectedMarker!==MARKER||out.readOnly!==true||out.ramWrites!==0)throw new Error(`[${COPY_ID}] embedded identity mismatch`);
out.cyclePrecursorFocus=focus.cyclePrecursorFocus;out.focusDiagnostics=focus.diagnostics;
for(const [id,st] of Object.entries(focus.ruleStats))out.ruleStats[id]=st;
out.diagnostics.rawMatchSamples=out.diagnostics.rawMatchSamples||{};out.diagnostics.transitionEntries=out.diagnostics.transitionEntries||{};for(const [id,n] of Object.entries(focus.diagnostics.rawMatchSamples))out.diagnostics.rawMatchSamples[id]=n;for(const [id,n] of Object.entries(focus.diagnostics.transitionEntries))out.diagnostics.transitionEntries[id]=n;
for(const k of ['signals','strictHits','jitterBandHits','realLateHits','hardMisses','censored','retargets'])out.diagnostics[k]=Number(out.diagnostics[k]||0)+Number(focus.diagnostics[k]||0);
out.model.focusPolicy='WOF-045R runs an independent same-cycle focus miner in parallel, and emits a real cyclePrecursorFocus object with up to120 T23 and120 T18 candidates per room; this fixes the WOF-044 export bug where only model text mentioned the field.';
out.model.t18Policy='WOF-044 discovered two T18 same-cycle TM4 candidates, each 9/9 in one room: BODY7512 FE8BBB2 NX8B290 -> A5440 and BODY7520 FE8BBDE NX8B2A4 -> A5424. WOF-045R validates both with once-per-zero-cycle level triggers at 90ms audit horizon.';
out.model.d881Policy='D8811E remains production-shadow. WOF-044 had 14/14 eventual A3232/target/side, with one clean 209.5ms tail hit beyond the 135ms audit horizon; 135ms is not a causal boundary.';
self.__WOF_V45R_RESULT=out;console.log(MARKER);console.log(JSON.stringify(out,null,2));return out;
})().catch(e=>{console.error('[WOF-045R] ERROR',e);throw e;});
