(async()=>{
'use strict';
const RAW='https://raw.githubusercontent.com/ouyong520/wof-ai-private/main/';
const load=async f=>{const r=await fetch(RAW+f+'?x='+Date.now(),{cache:'no-store'});if(!r.ok)throw new Error('fetch failed '+r.status+' '+f);return(0,eval)(await r.text());};
if(!self.__WOF_ROM_LOC_CACHE)await load('wof_resume_dispatch_selector.js');
const C=self.__WOF_ROM_LOC_CACHE;if(!C)throw new Error('ROM cache missing');
const M=_0x515056.HEAPU8,romBase=C.base,SW=!!C.swap16,ROMMAX=Math.min(0x100000,M.length-romBase);
const r8=o=>M[romBase+(SW?(o^1):o)]>>>0;
const r16=o=>((r8(o)<<8)|r8(o+1))>>>0;
const r32=o=>(r8(o)*0x1000000+r8(o+1)*0x10000+r8(o+2)*0x100+r8(o+3))>>>0;
const validRom=v=>v>=0x2000&&v<ROMMAX&&(v&1)===0;
const gate={dispatcher25C8:r16(0x25C8)===0x3228&&r16(0x25D0)===0x287B&&r16(0x25D4)===0x2874,handoff247C:r16(0x247C)===0x2C5C&&r16(0x247E)===0x215C&&r16(0x2482)===0x321C,d0_20Source:r16(0x6A62)===0x7014&&r16(0x6A64)===0x4EB8&&r16(0x6A66)===0x25C8,attackField:true};
function parseDescriptor(at){if(!validRom(at)||at+14>ROMMAX)return null;const frameEnd=r32(at)>>>0,value30=r32(at+4)>>>0,timerRaw=r16(at+8)>>>0;if(!validRom(frameEnd))return null;const flagged=!!(timerRaw&0x8000),timer=flagged?(timerRaw&0x7fff):timerRaw,next=flagged?(r32(at+10)>>>0):((at+10)>>>0);if(!validRom(next))return null;return{at,frameEnd,value30,timerRaw,flagged,timer,next};}
function typeMap(type){if(type<0||type>=47)return null;const table=r32(0x25DC+type*4)>>>0;if(!validRom(table))return null;const p=r32(table+20)>>>0;return{type,table,d20:parseDescriptor(p)};}
const R=_0x515056?.HEAPU32?.[0x2e39e4>>>2]>>>0;if(!R)throw new Error('CPS RAM base missing');
const B=a=>M[R+((((a-0xFF0000)&0xffff)^1))]>>>0;
const U16=a=>((B(a)<<8)|B(a+1))>>>0;
const U32=a=>(B(a)*0x1000000+B(a+1)*0x10000+B(a+2)*0x100+B(a+3))>>>0;
const ENEMY=0xFFC0BC,STRIDE=0xE0,SLOTS=20,PLAYERS={0:'P1',4:'P2',8:'P3'};
const maps=new Map(),getMap=t=>{if(!maps.has(t))maps.set(t,typeMap(t));return maps.get(t);};
function descMatches(s,d){return!!d&&s.frameEnd===d.frameEnd&&s.value30===d.value30&&s.next===d.next&&s.timer<=d.timer;}
function snap(slot){const a=ENEMY+slot*STRIDE,type=U16(a+0x20);if(type>=47)return null;const frameEnd=U32(a+0x12),next=U32(a+0x2C);if(frameEnd===0&&next===0)return null;const target7E=U16(a+0x7E),map=getMap(type),d20=map?.d20||null,s={slot,type,target7E,target:PLAYERS[target7E]||null,state99:B(a+0x99),action2A:B(a+0x2A),b2B:B(a+0x2B),timer:U16(a+0x34),attack:U16(a+0x70),body:U16(a+0x6E),frameEnd,next,value30:U32(a+0x30),d20StartTimer:d20?.timer??null};s.inD20=descMatches(s,d20);s.d20Exact=!!(s.inD20&&d20&&s.timer===d20.timer);return s;}
const DURATION=120000,INTERVAL=20,MAX_EPISODES=60,MAX_WATCH=1200,POST_ACTIVE=60,start=performance.now();
const RULES={T21_EXIT_250:{type:21,trigger:'D20_EXIT',horizon:250,level:'IMMINENT'},T33_ENTRY_500:{type:33,trigger:'D20_ENTRY_OBSERVED',horizon:500,level:'DANGER_SOON'},T30_ENTRY_500:{type:30,trigger:'D20_ENTRY_OBSERVED',horizon:500,level:'DANGER_SOON'}};
const prev=new Map(),episodes=new Map(),done=[],signals=[],events=[],live=new Map(),typesSeen=new Set();let epSeq=0,sigSeq=0,evSeq=0;
const diag={polls:0,enemySamples:0,d20Samples:0,d20ObservedEntries:0,d20ExactObservedEntries:0,d20LateObservedEntries:0,d20BootstrapEntries:0,globalActiveEdges:0,typesSeen:[]};
function syncLive(){self.__WOF_FUTURE_DANGER_LIVE_STATE=Object.fromEntries([...live.entries()].map(([k,v])=>[k,v]));}
function logEvent(kind,ep,s,t,extra={}){const e={id:++evSeq,rel:t,kind,episode:ep?.id??null,slot:s?.slot??ep?.slot??null,type:s?.type??ep?.type??null,target:s?.target??ep?.last?.target??null,target7E:s?.target7E??ep?.last?.target7E??null,...extra};events.push(e);const hz=e.horizonMs!=null?' <='+e.horizonMs+'ms':'';console.log(`[WOF FD] ${kind}${hz} T${e.type} slot${e.slot} -> ${e.target??'?'}${e.reason?' | '+e.reason:''}`);return e;}
function setLive(ep,s,t,level,horizonMs,reason){live.set(ep.slot,{episode:ep.id,slot:ep.slot,type:ep.type,level,horizonMs,target:s.target,target7E:s.target7E,sinceRel:t,reason});syncLive();logEvent(level,ep,s,t,{horizonMs,reason});}
function clearLive(ep){live.delete(ep.slot);syncLive();}
function emitSignal(ep,s,t,rule){if(ep.ruleSeen.has(rule))return;ep.ruleSeen.add(rule);const cfg=RULES[rule],q={id:++sigSeq,epId:ep.id,rule,level:cfg.level,horizonMs:cfg.horizon,atRel:t-ep.startAt,targetAtSignal:s.target,target7EAtSignal:s.target7E,resolved:false,hit:null,leadToActiveMs:null,activeTarget:null,targetSameAtActive:null};signals.push(q);ep.signals.push(q);setLive(ep,s,t,cfg.level,cfg.horizon,rule);}
function finishEp(ep,t,reason){if(ep.done)return;ep.done=true;ep.endRel=t-ep.startAt;ep.endReason=reason;for(const q of ep.signals){if(!q.resolved&&ep.endRel-q.atRel>=q.horizonMs){q.resolved=true;q.hit=false;}}done.push(ep);episodes.delete(ep.slot);clearLive(ep);}
function startEp(s,t,mode){const old=episodes.get(s.slot);if(old)finishEp(old,t,'retrigger');const staticTimer=s.d20StartTimer,seenTimer=s.timer,ep={id:++epSeq,slot:s.slot,type:s.type,startAt:t,entryTarget:s.target,entryMode:mode,entryExact:s.d20Exact,staticStartTimer:staticTimer,seenEntryTimer:seenTimer,observedLagTicks:staticTimer==null?null:Math.max(0,staticTimer-seenTimer),exitRel:null,firstAttack:null,last:s,targetSwitches:[],ruleSeen:new Set(),signals:[],done:false};episodes.set(s.slot,ep);diag.d20ObservedEntries++;if(mode==='bootstrap')diag.d20BootstrapEntries++;if(s.d20Exact)diag.d20ExactObservedEntries++;else diag.d20LateObservedEntries++;setLive(ep,s,t,'ATTACK_READY',null,`structural D0=20 ${mode}; timer ${seenTimer}/${staticTimer}`);if(s.type===33)emitSignal(ep,s,t,'T33_ENTRY_500');if(s.type===30)emitSignal(ep,s,t,'T30_ENTRY_500');}
function updateEp(ep,s,t){const rel=t-ep.startAt,p=ep.last;if(s.type!==ep.type){finishEp(ep,t,'typeChanged');return;}if(s.target7E!==p.target7E){ep.targetSwitches.push({rel,from:p.target,to:s.target});const st=live.get(ep.slot);if(st){st.target=s.target;st.target7E=s.target7E;syncLive();logEvent('RETARGET',ep,s,t,{reason:(p.target||'?')+' -> '+(s.target||'?'),level:st.level,horizonMs:st.horizonMs});}}if(ep.exitRel==null&&p.inD20&&!s.inD20){ep.exitRel=rel;if(s.type===21&&s.attack===0)emitSignal(ep,s,t,'T21_EXIT_250');}if(!ep.firstAttack&&p.attack===0&&s.attack!==0){ep.firstAttack={rel,attack:s.attack,target:s.target,target7E:s.target7E};for(const q of ep.signals){if(q.resolved)continue;const lead=rel-q.atRel;q.leadToActiveMs=lead;q.activeTarget=s.target;q.targetSameAtActive=q.target7EAtSignal===s.target7E;q.hit=lead>=0&&lead<=q.horizonMs;q.resolved=true;}setLive(ep,s,t,'ACTIVE',0,'enemy+0x70 0->nonzero');}ep.last=s;if(ep.firstAttack&&rel>=ep.firstAttack.rel+POST_ACTIVE)finishEp(ep,t,'activeConfirmed');else if(rel>=MAX_WATCH)finishEp(ep,t,'horizonComplete');}
await new Promise(resolve=>{const id=setInterval(()=>{const t=Math.round(performance.now()-start);diag.polls++;for(let i=0;i<SLOTS;i++){const s=snap(i),p=prev.get(i)||null;if(!s){const ep=episodes.get(i);if(ep)finishEp(ep,t,'slotGone');prev.delete(i);continue;}diag.enemySamples++;typesSeen.add(s.type);if(s.inD20)diag.d20Samples++;if(p&&p.attack===0&&s.attack!==0)diag.globalActiveEdges++;if(s.inD20&&(!p||!p.inD20))startEp(s,t,p?'transition':'bootstrap');const ep=episodes.get(i);if(ep)updateEp(ep,s,t);prev.set(i,s);}if(t>=DURATION||(epSeq>=MAX_EPISODES&&episodes.size===0)){clearInterval(id);for(const ep of [...episodes.values()])finishEp(ep,t,'captureEnd');resolve();}},INTERVAL);});
diag.typesSeen=[...typesSeen].sort((a,b)=>a-b);
const ruleStats={};for(const q of signals){const r=(ruleStats[q.rule]??={rule:q.rule,level:q.level,horizonMs:q.horizonMs,signals:0,evaluable:0,hit:0,miss:0,censored:0,targetSameHits:0,targetSameTotal:0,leads:[]});r.signals++;if(!q.resolved){r.censored++;continue;}r.evaluable++;if(q.hit){r.hit++;r.leads.push(q.leadToActiveMs);r.targetSameTotal++;if(q.targetSameAtActive)r.targetSameHits++;}else r.miss++;}for(const r of Object.values(ruleStats)){r.precision=r.evaluable?+(r.hit/r.evaluable).toFixed(3):null;r.targetSameRate=r.targetSameTotal?+(r.targetSameHits/r.targetSameTotal).toFixed(3):null;r.leads.sort((a,b)=>a-b);}
const byType={};for(const ep of done){const k='T'+ep.type,b=(byType[k]??={type:ep.type,episodes:0,exactEntry:0,lateEntry:0,bootstrap:0,active:0,horizonComplete:0,entryLeads:[]});b.episodes++;if(ep.entryExact)b.exactEntry++;else b.lateEntry++;if(ep.entryMode==='bootstrap')b.bootstrap++;if(ep.firstAttack){b.active++;b.entryLeads.push(ep.firstAttack.rel);}else if(ep.endReason==='horizonComplete')b.horizonComplete++;}for(const b of Object.values(byType))b.entryLeads.sort((a,b)=>a-b);
const rows=done.map(ep=>({id:ep.id,slot:ep.slot,type:ep.type,entryTarget:ep.entryTarget,entryMode:ep.entryMode,entryExact:ep.entryExact,staticStartTimer:ep.staticStartTimer,seenEntryTimer:ep.seenEntryTimer,observedLagTicks:ep.observedLagTicks,exitRel:ep.exitRel,outcome:ep.firstAttack?'active':ep.endReason,leadToActiveMs:ep.firstAttack?.rel??null,activeTarget:ep.firstAttack?.target??null,targetSwitches:ep.targetSwitches,signals:ep.signals}));
const out={version:'wof-future-danger-live-shadow-v14',readOnly:true,ramWrites:0,gate,gateStrict:Object.values(gate).every(Boolean),durationRequestedMs:DURATION,intervalMs:INTERVAL,maxEpisodes:MAX_EPISODES,maxWatchMs:MAX_WATCH,model:{entryCapture:'structural D0=20 transition; exact timer equality is recorded but no longer required',ATTACK_READY:'observed structural D0=20',DANGER_SOON:'T33/T30 observed D0 entry <=500ms',IMMINENT:'T21 D0 exit <=250ms provisional',ACTIVE:'enemy+0x70 0->nonzero',targetPolicy:'live enemy+0x7E authoritative'},rules:RULES,diagnostics:diag,totals:{episodes:done.length,active:done.filter(e=>e.firstAttack).length,horizonComplete:done.filter(e=>e.endReason==='horizonComplete'&&!e.firstAttack).length,signals:signals.length,retargets:done.reduce((n,e)=>n+e.targetSwitches.length,0),events:events.length},ruleStats,byType,rows,events,note:'V14 fixes V13 zero-episode fragility by starting on structural D0=20 entry even if the first 20ms sample sees timer below the static start timer. Exact-vs-late capture is preserved in diagnostics, and global active edges/type presence are counted so a zero-episode run is diagnosable.'};
self.__WOF_FUTURE_DANGER_LIVE_SHADOW_V14=out;self.__WOF_FUTURE_DANGER_LIVE_STATE={};console.log('=== FUTURE DANGER LIVE SHADOW V14 JSON ===');console.log(JSON.stringify(out,null,2));return out;
})().catch(e=>{console.error('WOF_FUTURE_DANGER_LIVE_SHADOW_V14_ERROR',e);throw e;});