(()=>{
'use strict';
try{self.WOFDISPSEED?.stop?.();}catch(_){}
const RAW='https://raw.githubusercontent.com/ouyong520/wof-ai-private/main/';
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
let stopped=false;
const load=async f=>{const r=await fetch(RAW+f+'?x='+Date.now(),{cache:'no-store'});if(!r.ok)throw new Error('fetch failed '+r.status+' '+f);return(0,eval)(await r.text());};
async function quiet(fn){const L=console.log,T=console.table,W=console.warn;try{console.log=()=>{};console.table=()=>{};console.warn=()=>{};return await fn();}finally{console.log=L;console.table=T;console.warn=W;}}
async function ensure(){await quiet(async()=>{if(!self.__WOF_DISPATCH_INCOMING?.edges?.length)await load('wof_resume_dispatch_selector.js');});if(!self.__WOF_DISPATCH_INCOMING?.edges?.length)throw new Error('incoming edges unavailable');if(!self.__WOF_ROM_LOC_CACHE)throw new Error('ROM cache unavailable');}
function env(){const MOD=_0x515056,C=self.__WOF_ROM_LOC_CACHE,M=MOD.HEAPU8,base=C.base,SW=!!C.swap16,MAX=Math.min(0x100000,M.length-base);const r8=o=>M[base+(SW?(o^1):o)]>>>0,r16=o=>((r8(o)<<8)|r8(o+1))>>>0,r32=o=>(r8(o)*0x1000000+r8(o+1)*0x10000+r8(o+2)*0x100+r8(o+3))>>>0,s8=v=>v&0x80?v-0x100:v,s16=v=>v&0x8000?v-0x10000:v,h=x=>'0x'+(x>>>0).toString(16).toUpperCase().padStart(6,'0'),hw=x=>'0x'+(x&0xffff).toString(16).toUpperCase().padStart(4,'0');return{MAX,r8,r16,r32,s8,s16,h,hw};}
function eaWords(m,r,size){if(m<=4)return 0;if(m===5||m===6)return 1;if(m===7){if(r===0||r===2||r===3)return 1;if(r===1)return 2;if(r===4)return size==='L'?2:1;}return 0;}
function decode(E,p){if(p<0||p+1>=E.MAX)return null;const w=E.r16(p),g=w>>>12,m=(w>>3)&7,r=w&7;let len=2,kind='OP',target=null,fall=true,terminal=false,call=false,cmp=false,bcc=false;
 if(w===0x4E75||w===0x4E73||w===0x4E77){kind='RET';terminal=true;fall=false;}
 else if(w===0x4E72){kind='STOP';len=4;terminal=true;fall=false;}
 else if((w&0xFFC0)===0x4E80){kind='JSR';call=true;len=2+eaWords(m,r,'L')*2;if(m===7&&r===0)target=E.s16(E.r16(p+2))>>>0;else if(m===7&&r===1)target=E.r32(p+2);else if(m===7&&r===2)target=(p+2+E.s16(E.r16(p+2)))>>>0;}
 else if((w&0xFFC0)===0x4EC0){kind='JMP';fall=false;len=2+eaWords(m,r,'L')*2;if(m===7&&r===0)target=E.s16(E.r16(p+2))>>>0;else if(m===7&&r===1)target=E.r32(p+2);else if(m===7&&r===2)target=(p+2+E.s16(E.r16(p+2)))>>>0;}
 else if(g===6){const cc=(w>>8)&15,d=w&255;len=d===0?4:2;target=d===0?p+2+E.s16(E.r16(p+2)):p+2+E.s8(d);kind=cc===0?'BRA':cc===1?'BSR':'BCC';bcc=cc>=2;if(cc===0)fall=false;if(cc===1)call=true;}
 else if(g===1||g===2||g===3){const size=g===1?'B':g===2?'L':'W',sm=(w>>3)&7,sr=w&7,dm=(w>>6)&7,dr=(w>>9)&7;len=2+(eaWords(sm,sr,size)+eaWords(dm,dr,size))*2;}
 else if(g===5){const sz=(w>>6)&3;if(sz===3&&m===1){kind='DBCC';bcc=true;len=4;target=(p+2+E.s16(E.r16(p+2)))>>>0;}else len=2+eaWords(m,r,sz===3?'B':sz===2?'L':sz===1?'W':'B')*2;}
 else if(g===0){if([0x003C,0x007C,0x023C,0x027C,0x0A3C,0x0A7C].includes(w))len=4;else if((w&0xF138)===0x0108)len=4;else if((w&0xFF00)===0x0800)len=4+eaWords(m,r,'B')*2;else if((w&0xF100)===0x0100)len=2+eaWords(m,r,'B')*2;else{const op=(w>>8)&15,sz=(w>>6)&3;if([0,2,4,6,10,12].includes(op)){const s=sz===2?'L':sz===1?'W':'B';len=2+(s==='L'?4:2)+eaWords(m,r,s)*2;if(op===12)cmp=true;}}}
 else if(g===4){if((w&0xFFF8)===0x4E50)len=4;else if((w&0xFB80)===0x4880&&m>=2)len=4+eaWords(m,r,(w&0x40)?'L':'W')*2;else if((w&0xF1C0)===0x41C0)len=2+eaWords(m,r,'L')*2;else if((w&0xFFC0)===0x4840&&m!==0)len=2+eaWords(m,r,'L')*2;else len=2+eaWords(m,r,((w>>6)&3)===2?'L':'W')*2;}
 else if(g===8){if((w&0xF1F0)!==0x8100)len=2+eaWords(m,r,((w>>6)&3)===2?'L':'W')*2;}
 else if(g===9||g===13){const special=(w&0xF130)===(g===9?0x9100:0xD100),a=((w>>6)&7)===3||((w>>6)&7)===7;if(!special)len=2+eaWords(m,r,a?(((w>>6)&1)?'L':'W'):(((w>>6)&3)===2?'L':'W'))*2;}
 else if(g===11){cmp=true;const cmpm=(w&0xF138)===0xB108,a=((w>>6)&7)===3||((w>>6)&7)===7;if(!cmpm)len=2+eaWords(m,r,a?(((w>>6)&1)?'L':'W'):(((w>>6)&3)===2?'L':'W'))*2;}
 else if(g===12){const exg=(w&0xF1F8)===0xC140||(w&0xF1F8)===0xC148||(w&0xF1F8)===0xC188,abcd=(w&0xF1F0)===0xC100;if(!exg&&!abcd)len=2+eaWords(m,r,((w>>6)&3)===2?'L':'W')*2;}
 else if(g===14&&((w>>6)&3)===3)len=2+eaWords(m,r,'W')*2;
 else if(g===10||g===15){kind='LINE';terminal=true;fall=false;}
 len=Math.max(2,len);const next=p+len;if(target!=null&&(target<0||target>=E.MAX))target=null;return{at:p,w,len,next,kind,target,fall,terminal,call,cmp,bcc};}
const PLAYERS=[{id:'P1',a:0xFFBE1C},{id:'P2',a:0xFFBEFC},{id:'P3',a:0xFFBFDC}];
function absAddr(E,p,m,r,size){if(m!==7)return null;if(r===0)return E.s16(E.r16(p+2))&0xFFFFFF;if(r===1)return E.r32(p+2)&0xFFFFFF;return null;}
function insEvidence(E,d){const out={players:[],refs:[],stride:0,ramHi:0,cmp:d.cmp?1:0,bcc:d.bcc?1:0};const p=d.at,w=d.w,g=w>>>12,m=(w>>3)&7,r=w&7;const addAbs=(a,tag)=>{if(a==null)return;for(const x of PLAYERS)if((a&0xFFFFFF)===x.a){out.players.push(x.id);out.refs.push(x.id+'@'+E.h(p)+':'+tag);}};
 if(g===1||g===2||g===3){const size=g===1?'B':g===2?'L':'W',sm=(w>>3)&7,sr=w&7,dm=(w>>6)&7,dr=(w>>9)&7;addAbs(absAddr(E,p,sm,sr,size),'src');const sp=2+eaWords(sm,sr,size)*2;if(dm===7){const q=p+sp;addAbs(absAddr(E,q,dm,dr,size),'dst');}}
 else if((w&0xF1C0)===0x41C0){addAbs(absAddr(E,p,m,r,'L'),'LEA');}
 else if(g===11||g===8||g===9||g===13||g===12){const sz=(w>>6)&3,size=sz===2?'L':sz===1?'W':'B';addAbs(absAddr(E,p,m,r,size),'EA');}
 else if(g===0){const op=(w>>8)&15,sz=(w>>6)&3;if([0,2,4,6,10,12].includes(op)&&sz!==3){const size=sz===2?'L':sz===1?'W':'B',q=p+2+(size==='L'?4:2);addAbs(absAddr(E,q,m,r,size),'immEA');}}
 for(let q=p;q<Math.min(d.next,E.MAX-1);q+=2){const v=E.r16(q);if(v===0x00E0)out.stride++;if(v===0xFFBE||v===0xFFBF)out.ramHi++;}
 out.players=[...new Set(out.players)];out.refs=[...new Set(out.refs)];return out;}
function mergeEv(a,b){return{players:[...new Set(a.players.concat(b.players))],refs:[...new Set(a.refs.concat(b.refs))],stride:a.stride+b.stride,ramHi:a.ramHi+b.ramHi,cmp:a.cmp+b.cmp,bcc:a.bcc+b.bcc};}
function evScore(e){return e.players.length*900+(e.stride?420:0)+(e.ramHi?180:0)+(e.players.length&&e.stride?700:0)+Math.min(e.cmp,6)*25+Math.min(e.bcc,10)*10;}
function forwardHelper(E,start,cache){start&=~1;if(cache.has(start))return cache.get(start);const hi=Math.min(E.MAX,start+0x900),q=[start],seen=new Set();let ev={players:[],refs:[],stride:0,ramHi:0,cmp:0,bcc:0};while(q.length&&seen.size<900){const p=q.shift();if(p<start||p>=hi||(p&1)||seen.has(p))continue;seen.add(p);const d=decode(E,p);if(!d)continue;ev=mergeEv(ev,insEvidence(E,d));if(d.kind==='BRA'){if(d.target!=null&&d.target>=start&&d.target<hi)q.push(d.target&~1);continue;}if(d.kind==='BCC'||d.kind==='DBCC'){if(d.next<hi)q.push(d.next);if(d.target!=null&&d.target>=start&&d.target<hi)q.push(d.target&~1);continue;}if(d.kind==='JMP'){if(d.target!=null&&d.target>=start&&d.target<hi)q.push(d.target&~1);continue;}if(d.terminal)continue;if(d.next<hi)q.push(d.next);}const z={start,seen:seen.size,...ev,score:evScore(ev)};cache.set(start,z);return z;}
function buildControlPreds(E,lo,hi){const map=new Map();for(let p=lo&~1;p<hi-6;p+=2){const d=decode(E,p);if(!d||d.target==null)continue;if(!['BRA','BCC','BSR','JSR','JMP','DBCC'].includes(d.kind))continue;if(d.target<lo||d.target>hi)continue;let a=map.get(d.target);if(!a){a=[];map.set(d.target,a);}a.push(d);}return map;}
function prevFall(E,cur,lo){const out=[];for(let p=Math.max(lo,cur-10)&~1;p<cur;p+=2){const d=decode(E,p);if(d&&d.fall&&d.next===cur)out.push(d);}return out;}
function scanEdge(E,edge,helperCache){const edgeAt=parseInt(edge.at,16),lo=Math.max(0,edgeAt-0x2800),ctrl=buildControlPreds(E,lo,edgeAt+2);const seed={cur:edgeAt,steps:0,anchors:0,ev:{players:[],refs:[],stride:0,ramHi:0,cmp:0,bcc:0},helpers:[],path:[E.h(edgeAt)],score:0};const q=[seed],seen=new Map(),hits=[];let qi=0,visited=0;
 while(qi<q.length&&visited<5200&&!stopped){const s=q[qi++];visited++;if(s.steps>=130||s.cur<=lo)continue;const preds=[];for(const d of prevFall(E,s.cur,lo))preds.push({d,ctl:false});for(const d of ctrl.get(s.cur)||[])preds.push({d,ctl:true});for(const x of preds){const ie=insEvidence(E,x.d),ev=mergeEv(s.ev,ie);let helpers=s.helpers.slice(),helperBonus=0;if(x.d.call&&x.d.target!=null&&x.d.target!==0x25B6&&x.d.target!==0x25C8){const he=forwardHelper(E,x.d.target,helperCache);if(he.score>0){helpers=[{callAt:E.h(x.d.at),target:E.h(x.d.target),players:he.players.join(','),stride:he.stride,ramHi:he.ramHi,cmp:he.cmp,score:he.score},...helpers].slice(0,4);helperBonus=Math.round(he.score*0.8);}}
 const ns={cur:x.d.at,steps:s.steps+1,anchors:s.anchors+(x.ctl?1:0),ev,helpers,path:s.path.length<18?[E.h(x.d.at),...s.path]:s.path,score:evScore(ev)+helperBonus};const key=ns.cur+'|'+ns.ev.players.join(',')+'|'+Math.min(ns.ev.stride,2)+'|'+Math.min(ns.ev.cmp,2)+'|'+(helpers[0]?.target||'');const old=seen.get(key);if(old!=null&&old>=ns.score)continue;seen.set(key,ns.score);q.push(ns);if(ns.ev.players.length||ns.ev.stride||helpers.length)hits.push(ns);}}
 hits.sort((a,b)=>b.score-a.score||b.anchors-a.anchors||b.steps-a.steps);const top=hits[0]||null;return{edgeAt:E.h(edgeAt),visited,hits:hits.length,top};}
async function run(){stopped=false;await ensure();const E=env(),IN=self.__WOF_DISPATCH_INCOMING,helperCache=new Map(),rows=[];let n=0;for(const edge of IN.edges||[]){if(stopped)throw new Error('stopped');const z=scanEdge(E,edge,helperCache),t=z.top;rows.push({edgeAt:edge.at,target:edge.target,kind:edge.kind,prevD0:edge.prevD0||'',visited:z.visited,signalHits:z.hits,topAt:t?E.h(t.cur):'',players:t?t.ev.players.join(','):'',refs:t?t.ev.refs.slice(0,8).join(' '):'',stride:t?t.ev.stride:0,ramHi:t?t.ev.ramHi:0,cmp:t?t.ev.cmp:0,bcc:t?t.ev.bcc:0,anchors:t?t.anchors:0,helper:t?.helpers?.[0]?.target||'',helperPlayers:t?.helpers?.[0]?.players||'',helperStride:t?.helpers?.[0]?.stride||0,helperCmp:t?.helpers?.[0]?.cmp||0,score:t?.score||0,path:t?t.path.join(' <- '):''});if((++n&3)===0)await sleep(0);}
 rows.sort((a,b)=>b.score-a.score||a.edgeAt.localeCompare(b.edgeAt));const direct=rows.filter(r=>r.players),stride=rows.filter(r=>r.stride),helper=rows.filter(r=>r.helperPlayers||r.helperStride),signal=rows.filter(r=>r.score>0),top=signal[0]||rows[0]||null;console.log('=== EDGE-SEEDED REVERSE SELECTOR TOP 24 ===');console.table(rows.slice(0,24));const verdict={incomingEdges:(IN.edges||[]).length,edgesScanned:rows.length,totalStates:rows.reduce((s,r)=>s+r.visited,0),edgesWithDirectPlayerEvidence:direct.length,edgesWithDirectStrideEvidence:stride.length,edgesWithHelperEvidence:helper.length,edgesWithAnySignal:signal.length,helperCache:helperCache.size,topEdgeAt:top?.edgeAt||'',topAt:top?.topAt||'',topPlayers:top?.players||'',topStride:top?.stride||0,topHelper:top?.helper||'',topHelperPlayers:top?.helperPlayers||'',topHelperStride:top?.helperStride||0,topCmp:top?.cmp||0,topScore:top?.score||0};console.log('=== EDGE-SEEDED REVERSE SELECTOR VERDICT ===');console.table([verdict]);const out={version:'wof-dispatch-edge-seed-reverse-selector-v1',verdict,rows};self.__WOF_DISPATCH_EDGE_SEED_SELECTOR=out;console.log('=== EDGE-SEEDED REVERSE SELECTOR JSON ===');console.log(JSON.stringify({verdict,rows:rows.slice(0,24)},null,2));return out;}
self.WOFDISPSEED={version:'wof-dispatch-edge-seed-reverse-selector-v1',run,stop(){stopped=true;}};console.log('✅ WOF edge-seeded reverse selector loaded');console.log('执行 await WOFDISPSEED.run()');
})();
