(()=>{
'use strict';
try{self.WOFDISPIN?.stop?.();}catch(_){}
const RAW='https://raw.githubusercontent.com/ouyong520/wof-ai-private/main/';
const sleep=ms=>new Promise(r=>setTimeout(r,ms));let stopped=false;
const load=async f=>{const r=await fetch(RAW+f+'?x='+Date.now(),{cache:'no-store'});if(!r.ok)throw new Error('fetch failed '+r.status+' '+f);return (0,eval)(await r.text());};
async function ensure(){if(!self.__WOF_ROM_LOC_CACHE)await load('wof_rom_focus_inspect.js');for(let i=0;i<300&&!self.__WOF_ROM_LOC_CACHE;i++)await sleep(50);if(!self.__WOF_ROM_LOC_CACHE)throw new Error('ROM cache unavailable');}
function env(){const MOD=_0x515056,C=self.__WOF_ROM_LOC_CACHE,M=MOD.HEAPU8,base=C.base,SW=!!C.swap16,MAX=Math.min(0x100000,M.length-base),DELTA=C.offlineDelta|0;const r8=o=>M[base+(SW?(o^1):o)]>>>0,r16=o=>((r8(o)<<8)|r8(o+1))>>>0,r32=o=>(r8(o)*0x1000000+r8(o+1)*0x10000+r8(o+2)*0x100+r8(o+3))>>>0,s8=v=>v&0x80?v-0x100:v,s16=v=>v&0x8000?v-0x10000:v,h=x=>'0x'+(x>>>0).toString(16).toUpperCase().padStart(6,'0'),off=x=>h((x-DELTA)>>>0),hw=x=>'0x'+(x&0xffff).toString(16).toUpperCase().padStart(4,'0');return{MAX,r8,r16,r32,s8,s16,h,off,hw};}
function eaWords(m,r,size){if(m<=4)return 0;if(m===5||m===6)return 1;if(m===7){if(r===0||r===2||r===3)return 1;if(r===1)return 2;if(r===4)return size==='L'?2:1;}return 0;}
function ctl(E,p){const w=E.r16(p),g=w>>>12,m=(w>>3)&7,r=w&7;if(g===6){const cc=(w>>8)&15,d=w&255,len=d===0?4:2,disp=d===0?E.s16(E.r16(p+2)):E.s8(d),target=(p+2+disp)>>>0;return{at:p,len,target,kind:cc===0?'BRA':cc===1?'BSR':'BCC',fall:cc!==0};}if((w&0xFFC0)===0x4E80||(w&0xFFC0)===0x4EC0){let target=null,len=2+eaWords(m,r,'L')*2,kind=(w&0xFFC0)===0x4E80?'JSR':'JMP';if(m===7&&r===0)target=E.s16(E.r16(p+2))>>>0;else if(m===7&&r===1)target=E.r32(p+2);else if(m===7&&r===2)target=(p+2+E.s16(E.r16(p+2)))>>>0;return{at:p,len,target,kind,fall:kind==='JSR'};}return null;}
function d0(E,p){const w=E.r16(p),g=w>>>12;if(g===1||g===2||g===3){const size=g===1?'B':g===2?'L':'W',sm=(w>>3)&7,sr=w&7,dm=(w>>6)&7,dr=(w>>9)&7;if(dm===0&&dr===0){let src='EA';if(sm===0)src='D'+sr;else if(sm===1)src='A'+sr;else if(sm===2)src='(A'+sr+')';else if(sm===3)src='(A'+sr+')+';else if(sm===4)src='-(A'+sr+')';else if(sm===5)src=E.s16(E.r16(p+2))+'(A'+sr+')';else if(sm===6){const x=E.r16(p+2);src=E.s8(x&255)+'(A'+sr+','+(x&0x8000?'A':'D')+((x>>12)&7)+(x&0x0800?'.L':'.W')+')';}return{at:p,text:'MOVE.'+size+' '+src+',D0',source:src};}}if((w&0xF100)===0x7000&&((w>>9)&7)===0)return{at:p,text:'MOVEQ #'+E.s8(w&255)+',D0',source:'#'+E.s8(w&255)};if(g===14&&((w>>6)&3)!==3&&(w&7)===0){const cnt=((w>>9)&7)||8,dir=(w&0x0100)?'L':'R',typ=['AS','LS','ROX','RO'][(w>>3)&3];return{at:p,text:typ+dir+' D0 #'+cnt,source:'D0-transform'};}if((g===13||g===9)&&((w>>9)&7)===0){return{at:p,text:(g===13?'ADD':'SUB')+' ...,D0',source:'D0-transform'};}return null;}
function prevD0(E,at,back=0x80){const out=[];for(let p=Math.max(0,at-back)&~1;p<at;p+=2){const z=d0(E,p);if(z)out.push({...z,distance:at-p,offline:E.off(p)});}return out.sort((a,b)=>a.distance-b.distance).slice(0,8);}
async function run(){stopped=false;await ensure();const E=env(),T=[0x25B6,0x25C8],edges=[];for(let p=0;p<E.MAX-6;p+=2){const c=ctl(E,p);if(c&&c.target!=null&&T.includes(c.target))edges.push({target:E.h(c.target),at:E.h(p),offline:E.off(p),kind:c.kind,distance:(c.target-p),prevD0:prevD0(E,p,0x80)[0]?.text||'',prevD0At:prevD0(E,p,0x80)[0]?E.h(prevD0(E,p,0x80)[0].at):''});if((p&0x1ffff)===0x1fffe)await sleep(0);}const ptr32=[];for(let p=0;p<E.MAX-4;p+=2){const v=E.r32(p);if(T.includes(v))ptr32.push({at:E.h(p),offline:E.off(p),target:E.h(v)});}const localFall=[];for(const t of T){for(let p=Math.max(0,t-12)&~1;p<t;p+=2){const c=ctl(E,p);if(c&&c.fall&&p+c.len===t)localFall.push({target:E.h(t),at:E.h(p),offline:E.off(p),kind:c.kind});}}
 console.log('=== DISPATCH INCOMING CONTROL EDGES ===');console.table(edges);console.log('=== DISPATCH 32-BIT POINTER REFS ===');console.table(ptr32.slice(0,80));console.log('=== DISPATCH LOCAL FALLTHROUGH ===');console.table(localFall);
 for(const e of edges){const at=parseInt(e.at,16);console.log('=== D0 PROVENANCE BEFORE '+e.at+' -> '+e.target+' ===');console.table(prevD0(E,at,0x100).map(z=>({at:E.h(z.at),offline:z.offline,distance:z.distance,text:z.text,source:z.source})));}
 const verdict={directIncomingEdges:edges.length,edges25B6:edges.filter(x=>x.target==='0x0025B6').length,edges25C8:edges.filter(x=>x.target==='0x0025C8').length,pointer32Refs:ptr32.length,fallthroughEdges:localFall.length,topAt:edges[0]?.at||'',topKind:edges[0]?.kind||'',topTarget:edges[0]?.target||'',topPrevD0At:edges[0]?.prevD0At||'',topPrevD0:edges[0]?.prevD0||''};console.log('=== DISPATCH INCOMING VERDICT ===');console.table([verdict]);
 if(edges.length)console.log('🎯 找到 dispatcher 的 direct branch/jump 入口；下一步沿 top edge 的真实 CFG 反追 D0。');else if(ptr32.length)console.warn('⚠️ 无 direct branch/jump，但存在 ROM pointer refs：优先验证 jump-table/state-machine 入口。');else console.warn('⚠️ direct incoming/pointer refs 都为 0：下一步查间接 JMP(Ax)/RTS trampoline 到 dispatcher。');
 const out={version:'wof-dispatch-incoming-v1',verdict,edges,ptr32,fallthrough:localFall};self.__WOF_DISPATCH_INCOMING=out;return out;}
self.WOFDISPIN={version:'wof-dispatch-incoming-v1',run,stop(){stopped=true;}};console.log('✅ WOF dispatcher incoming-edge scan loaded');console.log('执行 await WOFDISPIN.run()');
})();