(async()=>{
'use strict';
const RAW='https://raw.githubusercontent.com/ouyong520/wof-ai-private/main/';
const load=async f=>{const r=await fetch(RAW+f+'?x='+Date.now(),{cache:'no-store'});if(!r.ok)throw new Error('fetch failed '+r.status+' '+f);return(0,eval)(await r.text());};
async function ensureWasmModule(){const good=v=>!!(v&&v.HEAPU8 instanceof Uint8Array&&v.HEAPU32 instanceof Uint32Array&&v.HEAPU8.buffer===v.HEAPU32.buffer);if(good(self._0x515056))return self._0x515056;const until=performance.now()+8000;while(performance.now()<until){for(const k of Object.getOwnPropertyNames(self)){let v;try{v=self[k]}catch(_){continue}if(good(v)){self._0x515056=v;self.__WOF_MODULE_GLOBAL_KEY=k;return v;}}await new Promise(r=>setTimeout(r,50));}throw new Error('WOF WASM module not found; select live gstyphoon.js Worker.');}
await ensureWasmModule();if(!self.__WOF_DISPATCH_INCOMING){await load('wof_dispatch_incoming_edges.js');await WOFDISPIN.run();}if(!self.__WOF_ROM_LOC_CACHE)throw new Error('ROM cache missing after resume');
const current={
 version:'wof-resume-dispatch-selector-v44',copyIdPolicy:'Reject returned data unless copyId/project/version/marker match the expected run.',selectorSolved:true,selectorField:'enemy+0x7E authoritative target;0/4/8=P1/P2/P3',selectedPointerCache:'enemy+0x6A supporting only when BE1C/BEFC/BFDC',activeAttackField:'enemy+0x70 U16 0->nonzero ACTIVE-start convention, not exact damage/hitbox onset',xyFields:'object+4/+8 confirmed X/Y 16.16; Z unconfirmed',retargetPolicy:'Always use live enemy+0x7E',
 v25Result:'10ms polling falsified broad T16 FAST<=100 and MID<=250 as universal. FAST6/11 strict with late180.2/260/440.4 and2 hard misses; MID6/9 strict with320.4 late and2 hard misses. Tuple alone insufficient.',
 v26Result:'Correct WOF-026 with strong T16 coverage: FAST17 evaluable=>16 strict,1 late119.9,0 hardMiss; MID3/3 strict. All16 strict FAST resolved as attack6432 and every trace reached exact pre-active phase FE851AE/NX84C44/VFFFF, timer34=1, action2A=4,b2B=4 about10.3..20.4ms before ACTIVE. Sole late FAST was attack4840 and diverged to FE851AE/NX84DD0/V200.',
 v30Result:'Correct WOF-030,120s,10ms. T16_6432_B4_40 had65/65 strict <=40ms, all attack6432, targetSame65/65, sideStable65/65, leads9.0..21.1ms; exact B4 phase production-shadow. T30_FAST_100 had3/3 strict at19.0/20.0/20.1ms but remains unresolved historically. 4840 divergence remains discovery-only.',
 v31Result:'Correct WOF-031,120s,10ms,51115 enemy samples and282 ACTIVE edges. Mining found T34/T33 attack3232 countdown candidates, T27 attack5064 B4 candidate, and T23 attack5888 B4 candidate. Persistent T20/T34 broad phases are not imminent warnings.',
 v32Result:'Correct WOF-032,120s,10ms. T16 reconfirmed2/2. T34 TM6 had3/3 strict attack3232 at99.9..102.4ms. T33 TM6 had5/5 strict attack3232 at100..108.4ms including a RIGHT-side sample. Broad T30 degraded to8/10 strict with2 hard misses at TM1 absDx190/151, so broad T30 was demoted to discriminator work.',
 v33Result:'Correct WOF-033,120s,10ms,32989 enemy samples and291 ACTIVE edges. Room types were mainly T24,T18,T21 with some T30. Every fixed rule/discriminator had zero raw matches and zero transition entries, including T16,T33,T34,T30 splits,T27,T23. Therefore this run adds no positive or negative evidence to those rule accuracies; it demonstrates a coverage problem: fixed validators can waste a full run in rooms where the relevant internal phase never occurs. Switch next step to a coverage-adaptive terminal miner that always extracts useful pre-ACTIVE evidence from whatever types/attacks occur.',
 productionCorrection:'T16 exact terminal B4 remains production-shadow. T34/T33 exact TM6 attack3232 remain production-shadow-candidates based on WOF-032 prospective all-hit samples; WOF-033 zero coverage does not demote them. Broad T30_FAST remains demoted. T27/T23 remain discovery-prospective pending coverage.',
 v34Plan:'Run a coverage-adaptive miner for120s at10ms. Opportunistically validate known T16/T33/T34 gates, but regardless of coverage mine every ACTIVE edge: exact last-zero terminal fingerprint, recent pre-ACTIVE transition chain, and20/50/100/150/250/500ms fingerprints, grouped by type+actual attack with target/side stability. This specifically prevents another zero-value run and should expose the dominant T24/T18/T21/T30 attack terminal phases in the current room. All mined signatures remain discovery evidence until a later prospective validator confirms them.',
 nextScript:'wof_future_danger_adaptive_terminal_miner_v34.js',nextCopyId:'WOF-034',nextMarker:'=== WOF FUTURE DANGER ADAPTIVE TERMINAL MINER V34 JSON ===',
 exclusions:'Do not interpret WOF-033 zero matches as failures of T16/T33/T34; they had no coverage. Do not promote mined WOF-034 correlations directly; prospectively validate first. Do not promote broad T30_FAST, call absDx130 a hitbox, promote persistent T20/T34 broad phases as imminent, demote validated T16 B4, promote 4840 divergence, or restart solved selector/identity/pointer/dispatcher work.'
};self.__WOF_RESUME_FRONTIER=current;console.log('=== CURRENT SELECTOR FRONTIER ===');console.table([current]);console.log('NEXT:',current.nextCopyId,current.nextScript);return current;
})().catch(e=>{console.error('WOF_RESUME_ERROR',e);throw e;});