(async()=>{
'use strict';
const RAW='https://raw.githubusercontent.com/ouyong520/wof-ai-private/main/';
const load=async f=>{const r=await fetch(RAW+f+'?x='+Date.now(),{cache:'no-store'});if(!r.ok)throw new Error('fetch failed '+r.status+' '+f);return(0,eval)(await r.text());};
if(!self.__WOF_ROM_LOC_CACHE)await load('wof_resume_dispatch_selector.js');
const C=self.__WOF_ROM_LOC_CACHE;if(!C)throw new Error('ROM cache missing');
const M=_0x515056.HEAPU8,romBase=C.base,SW=!!C.swap16,ROMMAX=Math.min(0x100000,M.length-romBase);
const r8=o=>M[romBase+(SW?(o^1):o)]>>>0;
const r16=o=>((r8(o)<<8)|r8(o+1))>>>0;
const r32=o=>(r8(o)*0x1000000+r8(o+1)*0x10000+r8(o+2)*0x100+r8(o+3))>>>0;
const validRom=v=>v>=0x2000&&v<ROMMAX&&(v&1)===0;
const gate={dispatcher25C8:r16(0x25C8)===0x3228&&r16(0x25D0)===0x287B&&r16(0x25D4)===0x2874,handoff247C:r16(0x247C)===0x2C5C&&r16(0x247E)===0x215C&&r16(0x2482)===0x321C,d0_20Source:r16(0x6A62)===0x7014&&r16(0x6A64)===0x4EB8&&r16(0x6A66)===0x25C8,attackField:true,xyFields:true};
function parseDescriptor(at){if(!validRom(at)||at+14>ROMMAX)return null;const frameEnd=r32(at)>>>0,value30=r32(at+4)>>>0,timerRaw=r16(at+8)>>>0;if(!validRom(frameEnd))return null;const flagged=!!(timerRaw&0x8000),timer=flagged?(timerRaw&0x7fff):timerRaw,next=flagged?(r32(at+10)>>>0):((at+10)>>>0);if(!validRom(next))return null;return{at,frameEnd,value30,timer,next};}
function typeMap(type){if(type<0||type>=47)return null;const table=r32(0x25DC+type*4)>>>0;if(!validRom(table))return null;const p=r32(table+20)>>>0;return{type,d20:parseDescriptor(p)};}
const R=_0x515056?.HEAPU32?.[0x2e39e4>>>2]>>>0;if(!R)throw new Error('CPS RAM base missing');
const B=a=>M[R+((((a-0xFF0000)&0xffff)^1))]>>>0;
const U16=a=>((B(a)<<8)|B(a+1))>>>0;
const U32=a=>(B(a)*0x1000000+B(a+1)*0x10000+B(a+2)*0x100+B(a+3))>>>0;
const S32=a=>{const v=U32(a);return v>=0x80000000?v-0x100000000:v;};
const PX=a=>Math.round(S32(a+4)/65536),PY=a=>Math.round(S32(a+8)/65536);
const ENEMY=0xFFC0BC,STRIDE=0xE0,SLOTS=20,PLAYERS={0:'P1',4:'P2',8:'P3'},PBASE={0:0xFFBE1C,4:0xFFBEFC,8:0xFFBFDC};
const maps=new Map(),getMap=t=>{if(!maps.has(t))maps.set(t,typeMap(t));return maps.get(t);};
function descMatches(s,d){return!!d&&s.frameEnd===d.frameEnd&&s.value30===d.value30&&s.next===d.next&&s.timer<=d.timer;}
function side(dx){return dx<-4?'LEFT':dx>4?'RIGHT':'CENTER';}
function lane(dy){return dy<-4?'UP':dy>4?'DOWN':'SAME';}
function geomFrom(a,target7E){const pb=PBASE[target7E];const ex=PX(a),ey=PY(a);if(!pb)return{enemyX:ex,enemyY:ey,targetX:null,targetY:null,dx:null,dy:null,absDx:null,absDy:null,side:null,lane:null};const tx=PX(pb),ty=PY(pb),dx=tx-ex,dy=ty-ey;return{enemyX:ex,enemyY:ey,targetX:tx,targetY:ty,dx,dy,absDx:Math.abs(dx),absDy:Math.abs(dy),side:side(dx),lane:lane(dy)};}
function snap(slot){const a=ENEMY+slot*STRIDE,type=U16(a+0x20);if(type>=47)return null;const frameEnd=U32(a+0x12),next=U32(a+0x2C);if(frameEnd===0&&next===0)return null;const target7E=U16(a+0x7E),d20=getMap(type)?.d20||null,g=geomFrom(a,target7E);const s={slot,a,type,target7E,target:PLAYERS[target7E]||null,state99:B(a+0x99),action2A:B(a+0x2A),b2B:B(a+0x2B),timer:U16(a+0x34),attack:U16(a+0x70),body:U16(a+0x6E),frameEnd,next,value30:U32(a+0x30),d20StartTimer:d20?.timer??null,...g};s.inD20=descMatches(s,d20);s.d20Exact=!!(s.inD20&&d20&&s.timer===d20.timer);return s;}
const mini=s=>({type:s.type,target:s.target,target7E:s.target7E,state99:s.state99,action2A:s.action2A,b2B:s.b2B,timer:s.timer,attack:s.attack,body:s.body,enemyX:s.enemyX,enemyY:s.enemyY,targetX:s.targetX,targetY:s.targetY,dx:s.dx,dy:s.dy,absDx:s.absDx,absDy:s.absDy,side:s.side,lane:s.lane});
const DURATION=120000,INTERVAL=20,MAX_WATCH=1500,MAX_ATLAS=300,start=performance.now();
const prev=new Map(),episodes=new Map(),done=[],atlas=[],typesSeen=new Set();let epSeq=0;
const diag={polls:0,enemySamples:0,d20ObservedEntries:0,d20ExactObservedEntries:0,d20LateObservedEntries:0,globalActiveEdges:0,validTargetActiveEdges:0,typesSeen:[]};
function finish(ep,t,reason){if(ep.done)return;ep.done=true;ep.endRel=t-ep.startAt;ep.endReason=reason;done.push(ep);episodes.delete(ep.slot);}
function startEp(s,t,mode){const old=episodes.get(s.slot);if(old)finish(old,t,'retrigger');const ep={id:++epSeq,slot:s.slot,type:s.type,startAt:t,entryTarget:s.target,entryTarget7E:s.target7E,entryMode:mode,entryExact:s.d20Exact,staticStartTimer:s.d20StartTimer,seenEntryTimer:s.timer,entryGeom:mini(s),exitRel:null,firstAttack:null,last:s,targetSwitches:[],history:[],done:false};episodes.set(s.slot,ep);diag.d20ObservedEntries++;if(s.d20Exact)diag.d20ExactObservedEntries++;else diag.d20LateObservedEntries++;console.log(`[WOF GEO] READY T${s.type} slot${s.slot} -> ${s.target??'?'} dx=${s.dx??'?'} dy=${s.dy??'?'} timer ${s.timer}/${s.d20StartTimer}`);}
function remember(ep,s,t){const rel=t-ep.startAt;ep.history.push({rel,...mini(s)});while(ep.history.length>90)ep.history.shift();}
function nearest(hist,rel){let best=null,bd=1e9;for(const x of hist){const d=Math.abs(x.rel-rel);if(d<bd){bd=d;best=x;}}return best?{requestedRel:rel,sampleRel:best.rel,deltaMs:bd,state:best}:null;}
function recordActive(s,p,t,ep){diag.globalActiveEdges++;if(s.target)diag.validTargetActiveEdges++;const ev={rel:t,slot:s.slot,type:s.type,target:s.target,target7E:s.target7E,attack:s.attack,body:s.body,state99:s.state99,action2A:s.action2A,b2B:s.b2B,timer:s.timer,enemyX:s.enemyX,enemyY:s.enemyY,targetX:s.targetX,targetY:s.targetY,dx:s.dx,dy:s.dy,absDx:s.absDx,absDy:s.absDy,side:s.side,lane:s.lane,inD20:s.inD20,episodeId:ep?.id??null,leadFromD20:ep?t-ep.startAt:null};if(atlas.length<MAX_ATLAS)atlas.push(ev);console.log(`[WOF GEO] ACTIVE T${s.type} slot${s.slot} -> ${s.target??'?'} dx=${s.dx??'?'} dy=${s.dy??'?'} attack=${s.attack}`);return ev;}
function updateEp(ep,s,t){const rel=t-ep.startAt,p=ep.last;if(s.type!==ep.type){finish(ep,t,'typeChanged');return;}remember(ep,s,t);if(s.target7E!==p.target7E)ep.targetSwitches.push({rel,from:p.target,to:s.target});if(ep.exitRel==null&&p.inD20&&!s.inD20)ep.exitRel=rel;if(!ep.firstAttack&&p.attack===0&&s.attack!==0){const ae=recordActive(s,p,t,ep);ep.firstAttack={rel,activeTarget:s.target,activeTarget7E:s.target7E,activeGeom:mini(s),atlas:ae,checkpoints:{m500:nearest(ep.history,rel-500),m250:nearest(ep.history,rel-250),m100:nearest(ep.history,rel-100),m50:nearest(ep.history,rel-50)}};}ep.last=s;if(ep.firstAttack&&rel>=ep.firstAttack.rel+60)finish(ep,t,'activeConfirmed');else if(rel>=MAX_WATCH)finish(ep,t,'horizonComplete');}
await new Promise(resolve=>{const id=setInterval(()=>{const t=Math.round(performance.now()-start);diag.polls++;for(let i=0;i<SLOTS;i++){const s=snap(i),p=prev.get(i)||null;if(!s){const ep=episodes.get(i);if(ep)finish(ep,t,'slotGone');prev.delete(i);continue;}diag.enemySamples++;typesSeen.add(s.type);if(s.inD20&&(!p||!p.inD20))startEp(s,t,p?'transition':'bootstrap');const ep=episodes.get(i);if(ep)updateEp(ep,s,t);else if(p&&p.attack===0&&s.attack!==0)recordActive(s,p,t,null);prev.set(i,s);}if(t>=DURATION){clearInterval(id);for(const ep of [...episodes.values()])finish(ep,t,'captureEnd');resolve();}},INTERVAL);});
diag.typesSeen=[...typesSeen].sort((a,b)=>a-b);
const median=a=>{if(!a.length)return null;const b=[...a].sort((x,y)=>x-y),m=Math.floor(b.length/2);return b.length%2?b[m]:Math.round((b[m-1]+b[m])/2);};
const pct=(a,p)=>{if(!a.length)return null;const b=[...a].sort((x,y)=>x-y);return b[Math.min(b.length-1,Math.floor((b.length-1)*p))];};
const byType={};for(const e of atlas){const k='T'+e.type,b=(byType[k]??={type:e.type,activeEdges:0,validTarget:0,absDx:[],absDy:[],left:0,right:0,center:0,up:0,down:0,same:0,attacks:{}});b.activeEdges++;if(e.target){b.validTarget++;b.absDx.push(e.absDx);b.absDy.push(e.absDy);b[e.side.toLowerCase()]++;b[e.lane.toLowerCase()]++;}const ak=String(e.attack);const q=(b.attacks[ak]??={attack:e.attack,count:0,absDx:[],absDy:[]});q.count++;if(e.target){q.absDx.push(e.absDx);q.absDy.push(e.absDy);}}
for(const b of Object.values(byType)){b.absDxMedian=median(b.absDx);b.absDxP90=pct(b.absDx,.9);b.absDyMedian=median(b.absDy);b.absDyP90=pct(b.absDy,.9);delete b.absDx;delete b.absDy;for(const q of Object.values(b.attacks)){q.absDxMedian=median(q.absDx);q.absDxP90=pct(q.absDx,.9);q.absDyMedian=median(q.absDy);q.absDyP90=pct(q.absDy,.9);delete q.absDx;delete q.absDy;}b.attacks=Object.values(b.attacks).sort((a,b)=>b.count-a.count).slice(0,12);}
const d20ByType={};for(const ep of done){const k='T'+ep.type,b=(d20ByType[k]??={type:ep.type,episodes:0,active:0,horizonComplete:0,leads:[],sideStable:0,sideComparable:0,activeAbsDx:[],activeAbsDy:[]});b.episodes++;if(ep.firstAttack){b.active++;b.leads.push(ep.firstAttack.rel);const a=ep.entryGeom,ac=ep.firstAttack.activeGeom;if(a.side&&ac.side){b.sideComparable++;if(a.side===ac.side)b.sideStable++;}if(ac.absDx!=null)b.activeAbsDx.push(ac.absDx);if(ac.absDy!=null)b.activeAbsDy.push(ac.absDy);}else if(ep.endReason==='horizonComplete')b.horizonComplete++;}
for(const b of Object.values(d20ByType)){b.leads.sort((a,b)=>a-b);b.sideStableRate=b.sideComparable?+(b.sideStable/b.sideComparable).toFixed(3):null;b.activeAbsDxMedian=median(b.activeAbsDx);b.activeAbsDyMedian=median(b.activeAbsDy);delete b.activeAbsDx;delete b.activeAbsDy;}
const rows=done.map(ep=>({id:ep.id,slot:ep.slot,type:ep.type,entryTarget:ep.entryTarget,entryMode:ep.entryMode,entryExact:ep.entryExact,seenEntryTimer:ep.seenEntryTimer,entryGeom:ep.entryGeom,exitRel:ep.exitRel,outcome:ep.firstAttack?'active':ep.endReason,leadToActiveMs:ep.firstAttack?.rel??null,activeTarget:ep.firstAttack?.activeTarget??null,targetSwitches:ep.targetSwitches,activeGeom:ep.firstAttack?.activeGeom??null,checkpoints:ep.firstAttack?.checkpoints??null}));
const out={version:'wof-future-danger-geometry-v15',readOnly:true,ramWrites:0,gate,gateStrict:Object.values(gate).every(Boolean),durationRequestedMs:DURATION,intervalMs:INTERVAL,maxWatchMs:MAX_WATCH,model:{purpose:'build empirical target-relative geometry atlas at enemy+0x70 active start while preserving robust D0=20 timing episodes',xy:'enemy/player +4/+8 confirmed 16.16 fixed-point positions',direction:'LEFT/RIGHT/CENTER and UP/DOWN/SAME are target-relative geometry, not yet proven hitbox/facing semantics',range:'absDx/absDy at ACTIVE are empirical target-relative distances, not yet a hitbox boundary',targetPolicy:'live enemy+0x7E authoritative'},diagnostics:diag,totals:{d20Episodes:done.length,d20Active:done.filter(e=>e.firstAttack).length,d20HorizonComplete:done.filter(e=>e.endReason==='horizonComplete'&&!e.firstAttack).length,atlasActiveEdges:atlas.length},d20ByType,activeGeometryByType:byType,rows,activeAtlas:atlas,note:'V15 starts geometry/range work. Do not equate target-relative ACTIVE distance with exact hitbox or damage onset. Use repeated type/attack clusters to infer directional/range envelopes before building the 0-1000ms Future Danger Map.'};
self.__WOF_FUTURE_DANGER_GEOMETRY_V15=out;console.log('=== FUTURE DANGER GEOMETRY V15 JSON ===');console.log(JSON.stringify(out,null,2));return out;
})().catch(e=>{console.error('WOF_FUTURE_DANGER_GEOMETRY_V15_ERROR',e);throw e;});