(async()=>{
'use strict';
const RAW='https://raw.githubusercontent.com/ouyong520/wof-ai-private/main/';
const load=async f=>{const r=await fetch(RAW+f+'?x='+Date.now(),{cache:'no-store'});if(!r.ok)throw new Error('fetch failed '+r.status+' '+f);return(0,eval)(await r.text());};
if(!self.__WOF_ROM_LOC_CACHE)await load('wof_resume_dispatch_selector.js');
const C=self.__WOF_ROM_LOC_CACHE;if(!C)throw new Error('ROM cache missing');
const M=_0x515056.HEAPU8,romBase=C.base,SW=!!C.swap16,ROMMAX=Math.min(0x100000,M.length-romBase);
const r8=o=>M[romBase+(SW?(o^1):o)]>>>0;
const r16=o=>((r8(o)<<8)|r8(o+1))>>>0;
const r32=o=>(r8(o)*0x1000000+r8(o+1)*0x10000+r8(o+2)*0x100+r8(o+3))>>>0;
const validRom=v=>v>=0x2000&&v<ROMMAX&&(v&1)===0;
const gate={dispatcher25C8:r16(0x25C8)===0x3228&&r16(0x25D0)===0x287B&&r16(0x25D4)===0x2874,handoff247C:r16(0x247C)===0x2C5C&&r16(0x247E)===0x215C&&r16(0x2482)===0x321C,d0_20Source:r16(0x6A62)===0x7014&&r16(0x6A64)===0x4EB8&&r16(0x6A66)===0x25C8,attackField:true,xyFields:true};
function parseDescriptor(at){if(!validRom(at)||at+14>ROMMAX)return null;const frameEnd=r32(at)>>>0,value30=r32(at+4)>>>0,timerRaw=r16(at+8)>>>0;if(!validRom(frameEnd))return null;const flagged=!!(timerRaw&0x8000),timer=flagged?(timerRaw&0x7fff):timerRaw,next=flagged?(r32(at+10)>>>0):((at+10)>>>0);if(!validRom(next))return null;return{at,frameEnd,value30,timer,next};}
function typeMap(type){if(type<0||type>=47)return null;const table=r32(0x25DC+type*4)>>>0;if(!validRom(table))return null;const p=r32(table+20)>>>0;return{type,d20:parseDescriptor(p)};}
const R=_0x515056?.HEAPU32?.[0x2e39e4>>>2]>>>0;if(!R)throw new Error('CPS RAM base missing');
const B=a=>M[R+((((a-0xFF0000)&0xffff)^1))]>>>0;
const U16=a=>((B(a)<<8)|B(a+1))>>>0;
const U32=a=>(B(a)*0x1000000+B(a+1)*0x10000+B(a+2)*0x100+B(a+3))>>>0;
const S32=a=>{const v=U32(a);return v>=0x80000000?v-0x100000000:v;};
const PX=a=>Math.round(S32(a+4)/65536),PY=a=>Math.round(S32(a+8)/65536);
const ENEMY=0xFFC0BC,STRIDE=0xE0,SLOTS=20,PLAYERS={0:'P1',4:'P2',8:'P3'},PBASE={0:0xFFBE1C,4:0xFFBEFC,8:0xFFBFDC};
const maps=new Map(),getMap=t=>{if(!maps.has(t))maps.set(t,typeMap(t));return maps.get(t);};
function descMatches(s,d){return!!d&&s.frameEnd===d.frameEnd&&s.value30===d.value30&&s.next===d.next&&s.timer<=d.timer;}
const side=dx=>dx<-4?'LEFT':dx>4?'RIGHT':'CENTER';
const lane=dy=>dy<-4?'UP':dy>4?'DOWN':'SAME';
function geom(a,target7E){const ex=PX(a),ey=PY(a),pb=PBASE[target7E];if(!pb)return{enemyX:ex,enemyY:ey,targetX:null,targetY:null,dx:null,dy:null,absDx:null,absDy:null,side:null,lane:null};const tx=PX(pb),ty=PY(pb),dx=tx-ex,dy=ty-ey;return{enemyX:ex,enemyY:ey,targetX:tx,targetY:ty,dx,dy,absDx:Math.abs(dx),absDy:Math.abs(dy),side:side(dx),lane:lane(dy)};}
function snap(slot){const a=ENEMY+slot*STRIDE,type=U16(a+0x20);if(type>=47)return null;const frameEnd=U32(a+0x12),next=U32(a+0x2C);if(frameEnd===0&&next===0)return null;const target7E=U16(a+0x7E),d20=getMap(type)?.d20||null;const s={slot,a,type,target7E,target:PLAYERS[target7E]||null,state99:B(a+0x99),action2A:B(a+0x2A),b2B:B(a+0x2B),timer:U16(a+0x34),attack:U16(a+0x70),body:U16(a+0x6E),frameEnd,next,value30:U32(a+0x30),d20StartTimer:d20?.timer??null,...geom(a,target7E)};s.inD20=descMatches(s,d20);s.d20Exact=!!(s.inD20&&d20&&s.timer===d20.timer);return s;}
const RULES={T13_ENTRY_250:{type:13,trigger:'ENTRY',horizon:250,level:'IMMINENT',confidence:'provisional-high'},T9_ENTRY_500:{type:9,trigger:'ENTRY',horizon:500,level:'DANGER_SOON',confidence:'high-observed'},T10_ENTRY_500:{type:10,trigger:'ENTRY',horizon:500,level:'DANGER_SOON',confidence:'high-observed'},T33_ENTRY_500:{type:33,trigger:'ENTRY',horizon:500,level:'DANGER_SOON',confidence:'high-observed'},T21_EXIT_250:{type:21,trigger:'EXIT',horizon:250,level:'IMMINENT',confidence:'provisional-high'}};
const ENTRY_RULE_BY_TYPE={13:'T13_ENTRY_250',9:'T9_ENTRY_500',10:'T10_ENTRY_500',33:'T33_ENTRY_500'};
const ATTACK_ENVELOPES={9:{3232:{x:332,y:59,n:19},2832:{x:378,y:10,n:7},2808:{x:206,y:8,n:5},5336:{x:296,y:15,n:4}},10:{3232:{x:271,y:27,n:15},5336:{x:333,y:23,n:8},2808:{x:151,y:33,n:7},2936:{x:129,y:5,n:5}},13:{6888:{x:323,y:29,n:24},6896:{x:322,y:36,n:10},4280:{x:97,y:6,n:7},4288:{x:2,y:1,n:4}},30:{2536:{x:156,y:6,n:13},2528:{x:75,y:1,n:6}}};
const DURATION=120000,INTERVAL=20,MAX_WATCH=1500,POST_ACTIVE=60,start=performance.now();
const prev=new Map(),episodes=new Map(),done=[],signals=[],events=[],activeEdges=[];let epSeq=0,sigSeq=0,evSeq=0;
const diag={polls:0,enemySamples:0,d20ObservedEntries:0,d20ExactObservedEntries:0,d20LateObservedEntries:0,globalActiveEdges:0,validTargetActiveEdges:0,seedAttackEnvelopeEdges:0};
const mini=s=>({type:s.type,target:s.target,target7E:s.target7E,state99:s.state99,action2A:s.action2A,b2B:s.b2B,timer:s.timer,attack:s.attack,body:s.body,frameEnd:s.frameEnd,next:s.next,value30:s.value30,enemyX:s.enemyX,enemyY:s.enemyY,targetX:s.targetX,targetY:s.targetY,dx:s.dx,dy:s.dy,absDx:s.absDx,absDy:s.absDy,side:s.side,lane:s.lane});
const coarseKey=s=>`T${s.type}|S${s.state99}|A${s.action2A}|B${s.b2B}|BODY${s.body}`;
const descKey=s=>`${coarseKey(s)}|FE${s.frameEnd.toString(16)}|NX${s.next.toString(16)}|V${s.value30.toString(16)}`;
function log(kind,ep,s,t,extra={}){const e={id:++evSeq,rel:t,kind,episode:ep?.id??null,slot:s?.slot??ep?.slot??null,type:s?.type??ep?.type??null,target:s?.target??ep?.last?.target??null,...extra};events.push(e);console.log(`[WOF V17] ${kind} T${e.type} slot${e.slot} -> ${e.target??'?'}${e.horizonMs!=null?' <='+e.horizonMs+'ms':''}${e.rule?' '+e.rule:''}`);}
function emit(ep,s,t,rule){if(ep.ruleSeen.has(rule))return;ep.ruleSeen.add(rule);const cfg=RULES[rule],q={id:++sigSeq,epId:ep.id,rule,level:cfg.level,horizonMs:cfg.horizon,atRel:t-ep.startAt,target7EAtSignal:s.target7E,targetAtSignal:s.target,sideAtSignal:s.side,resolved:false,hit:null,expired:false,leadToActiveMs:null,targetSameAtActive:null,sideSameAtActive:null};signals.push(q);ep.signals.push(q);log(cfg.level,ep,s,t,{rule,horizonMs:cfg.horizon});}
function resolveExpired(ep,s,t){const rel=t-ep.startAt;for(const q of ep.signals){if(q.resolved)continue;if(rel-q.atRel>q.horizonMs){q.resolved=true;q.hit=false;q.expired=true;log('EXPIRE',ep,s,t,{rule:q.rule,horizonMs:q.horizonMs});}}}
function finish(ep,t,reason){if(ep.done)return;ep.done=true;ep.endRel=t-ep.startAt;ep.endReason=reason;for(const q of ep.signals){if(!q.resolved&&ep.endRel-q.atRel>=q.horizonMs){q.resolved=true;q.hit=false;q.expired=true;}}done.push(ep);episodes.delete(ep.slot);}
function startEp(s,t,mode){const old=episodes.get(s.slot);if(old)finish(old,t,'retrigger');const ep={id:++epSeq,slot:s.slot,type:s.type,startAt:t,entryMode:mode,entryExact:s.d20Exact,seenEntryTimer:s.timer,entry:mini(s),coarseSignature:coarseKey(s),descriptorSignature:descKey(s),firstAttack:null,exitRel:null,last:s,targetSwitches:[],signals:[],ruleSeen:new Set(),done:false};episodes.set(s.slot,ep);diag.d20ObservedEntries++;if(s.d20Exact)diag.d20ExactObservedEntries++;else diag.d20LateObservedEntries++;log('ATTACK_READY',ep,s,t,{signature:ep.coarseSignature});const rule=ENTRY_RULE_BY_TYPE[s.type];if(rule)emit(ep,s,t,rule);}
function recordActive(s,t,ep){diag.globalActiveEdges++;if(s.target)diag.validTargetActiveEdges++;const seed=ATTACK_ENVELOPES[s.type]?.[s.attack]||null,seedInside=seed&&s.target?!!(s.absDx<=seed.x&&s.absDy<=seed.y):null;if(seed)diag.seedAttackEnvelopeEdges++;const e={rel:t,slot:s.slot,type:s.type,target:s.target,target7E:s.target7E,attack:s.attack,body:s.body,state99:s.state99,action2A:s.action2A,b2B:s.b2B,absDx:s.absDx,absDy:s.absDy,side:s.side,lane:s.lane,seedEnvelope:seed,seedInside,episodeId:ep?.id??null};activeEdges.push(e);return e;}
function updateEp(ep,s,t){const rel=t-ep.startAt,p=ep.last;if(s.type!==ep.type){finish(ep,t,'typeChanged');return;}if(s.target7E!==p.target7E)ep.targetSwitches.push({rel,from:p.target,to:s.target});if(ep.exitRel==null&&p.inD20&&!s.inD20){ep.exitRel=rel;if(s.type===21&&s.attack===0)emit(ep,s,t,'T21_EXIT_250');}if(!ep.firstAttack&&p.attack===0&&s.attack!==0){const ae=recordActive(s,t,ep);ep.firstAttack={rel,target:s.target,target7E:s.target7E,side:s.side,attack:s.attack,body:s.body,absDx:s.absDx,absDy:s.absDy,seedInside:ae.seedInside};for(const q of ep.signals){if(q.resolved)continue;const lead=rel-q.atRel;q.leadToActiveMs=lead;q.hit=lead>=0&&lead<=q.horizonMs;q.targetSameAtActive=q.target7EAtSignal===s.target7E;q.sideSameAtActive=q.sideAtSignal===s.side;q.resolved=true;}log('ACTIVE',ep,s,t,{attack:s.attack,leadMs:rel,seedInside:ae.seedInside});}resolveExpired(ep,s,t);ep.last=s;if(ep.firstAttack&&rel>=ep.firstAttack.rel+POST_ACTIVE)finish(ep,t,'activeConfirmed');else if(rel>=MAX_WATCH)finish(ep,t,'horizonComplete');}
await new Promise(resolve=>{const id=setInterval(()=>{const t=Math.round(performance.now()-start);diag.polls++;for(let i=0;i<SLOTS;i++){const s=snap(i),p=prev.get(i)||null;if(!s){const ep=episodes.get(i);if(ep)finish(ep,t,'slotGone');prev.delete(i);continue;}diag.enemySamples++;if(s.inD20&&(!p||!p.inD20))startEp(s,t,p?'transition':'bootstrap');const ep=episodes.get(i);if(ep)updateEp(ep,s,t);else if(p&&p.attack===0&&s.attack!==0)recordActive(s,t,null);prev.set(i,s);}if(t>=DURATION){clearInterval(id);for(const ep of [...episodes.values()])finish(ep,t,'captureEnd');resolve();}},INTERVAL);});
const median=a=>{if(!a.length)return null;const b=[...a].sort((x,y)=>x-y),m=Math.floor(b.length/2);return b.length%2?b[m]:Math.round((b[m-1]+b[m])/2);};
const pct=(a,p)=>{if(!a.length)return null;const b=[...a].sort((x,y)=>x-y),i=Math.ceil(p*b.length)-1;return b[Math.max(0,Math.min(b.length-1,i))];};
const ruleStats={};for(const q of signals){const r=(ruleStats[q.rule]??={rule:q.rule,level:q.level,horizonMs:q.horizonMs,signals:0,evaluable:0,hit:0,miss:0,censored:0,expired:0,leads:[],targetSame:0,targetTotal:0,sideSame:0,sideTotal:0});r.signals++;if(!q.resolved){r.censored++;continue;}r.evaluable++;if(q.hit){r.hit++;r.leads.push(q.leadToActiveMs);}else r.miss++;if(q.expired)r.expired++;if(q.targetSameAtActive!=null){r.targetTotal++;if(q.targetSameAtActive)r.targetSame++;}if(q.sideSameAtActive!=null){r.sideTotal++;if(q.sideSameAtActive)r.sideSame++;}}for(const r of Object.values(ruleStats)){r.precision=r.evaluable?+(r.hit/r.evaluable).toFixed(3):null;r.targetSameRate=r.targetTotal?+(r.targetSame/r.targetTotal).toFixed(3):null;r.sideStableRate=r.sideTotal?+(r.sideSame/r.sideTotal).toFixed(3):null;r.leads.sort((a,b)=>a-b);}
const typeStats={};for(const ep of done){const b=(typeStats['T'+ep.type]??={type:ep.type,episodes:0,active:0,horizonComplete:0,leads:[],lte250:0,lte500:0,lte1000:0,retargets:0});b.episodes++;b.retargets+=ep.targetSwitches.length;if(ep.firstAttack){b.active++;const l=ep.firstAttack.rel;b.leads.push(l);if(l<=250)b.lte250++;if(l<=500)b.lte500++;if(l<=1000)b.lte1000++;}else if(ep.endReason==='horizonComplete')b.horizonComplete++;}for(const b of Object.values(typeStats))b.leads.sort((a,b)=>a-b);
const sigMap={};for(const ep of done){const k=ep.coarseSignature,b=(sigMap[k]??={signature:k,type:ep.type,episodes:0,active:0,horizonComplete:0,leads:[],lte250:0,lte500:0,lte1000:0,attacks:{},entryAbsDx:[],entryAbsDy:[],activeAbsDx:[],activeAbsDy:[],targetSame:0,targetTotal:0,sideSame:0,sideTotal:0,descriptorSignatures:{}});b.episodes++;b.descriptorSignatures[ep.descriptorSignature]=(b.descriptorSignatures[ep.descriptorSignature]||0)+1;if(ep.entry.absDx!=null)b.entryAbsDx.push(ep.entry.absDx);if(ep.entry.absDy!=null)b.entryAbsDy.push(ep.entry.absDy);if(ep.firstAttack){b.active++;const l=ep.firstAttack.rel;b.leads.push(l);if(l<=250)b.lte250++;if(l<=500)b.lte500++;if(l<=1000)b.lte1000++;const ak=String(ep.firstAttack.attack);b.attacks[ak]=(b.attacks[ak]||0)+1;if(ep.firstAttack.absDx!=null)b.activeAbsDx.push(ep.firstAttack.absDx);if(ep.firstAttack.absDy!=null)b.activeAbsDy.push(ep.firstAttack.absDy);if(ep.entry.target7E!=null&&ep.firstAttack.target7E!=null){b.targetTotal++;if(ep.entry.target7E===ep.firstAttack.target7E)b.targetSame++;}if(ep.entry.side&&ep.firstAttack.side){b.sideTotal++;if(ep.entry.side===ep.firstAttack.side)b.sideSame++;}}else if(ep.endReason==='horizonComplete')b.horizonComplete++;}
const signatureStats=Object.values(sigMap).map(b=>{b.leads.sort((a,b)=>a-b);b.activeRate=b.episodes?+(b.active/b.episodes).toFixed(3):null;b.p250=b.episodes?+(b.lte250/b.episodes).toFixed(3):null;b.p500=b.episodes?+(b.lte500/b.episodes).toFixed(3):null;b.p1000=b.episodes?+(b.lte1000/b.episodes).toFixed(3):null;b.targetSameRate=b.targetTotal?+(b.targetSame/b.targetTotal).toFixed(3):null;b.sideStableRate=b.sideTotal?+(b.sideSame/b.sideTotal).toFixed(3):null;b.entryAbsDxMedian=median(b.entryAbsDx);b.entryAbsDyMedian=median(b.entryAbsDy);b.activeAbsDxMedian=median(b.activeAbsDx);b.activeAbsDyMedian=median(b.activeAbsDy);b.attackCounts=Object.entries(b.attacks).map(([attack,count])=>({attack:+attack,count})).sort((a,b)=>b.count-a.count);b.descriptorSignatures=Object.entries(b.descriptorSignatures).map(([signature,count])=>({signature,count})).sort((a,b)=>b.count-a.count);delete b.attacks;delete b.entryAbsDx;delete b.entryAbsDy;delete b.activeAbsDx;delete b.activeAbsDy;return b;}).sort((a,b)=>b.episodes-a.episodes);
const clusterMap={};for(const e of activeEdges){const k=`T${e.type}|A${e.attack}`,b=(clusterMap[k]??={key:k,type:e.type,attack:e.attack,count:0,absDx:[],absDy:[],left:0,right:0,center:0,up:0,down:0,same:0,seedEnvelope:e.seedEnvelope||null,seedInside:0,seedTotal:0});b.count++;if(e.absDx!=null)b.absDx.push(e.absDx);if(e.absDy!=null)b.absDy.push(e.absDy);if(e.side)b[e.side.toLowerCase()]++;if(e.lane)b[e.lane.toLowerCase()]++;if(e.seedInside!=null){b.seedTotal++;if(e.seedInside)b.seedInside++;}}
const attackClusters=Object.values(clusterMap).map(b=>{b.absDxMedian=median(b.absDx);b.absDxP90=pct(b.absDx,.9);b.absDyMedian=median(b.absDy);b.absDyP90=pct(b.absDy,.9);b.seedContainmentRate=b.seedTotal?+(b.seedInside/b.seedTotal).toFixed(3):null;delete b.absDx;delete b.absDy;return b;}).sort((a,b)=>b.count-a.count);
const rows=done.map(ep=>({id:ep.id,slot:ep.slot,type:ep.type,entryMode:ep.entryMode,entryExact:ep.entryExact,seenEntryTimer:ep.seenEntryTimer,coarseSignature:ep.coarseSignature,descriptorSignature:ep.descriptorSignature,entryTarget:ep.entry.target,entryState99:ep.entry.state99,entryAction2A:ep.entry.action2A,entryB2B:ep.entry.b2B,entryBody:ep.entry.body,entryAbsDx:ep.entry.absDx,entryAbsDy:ep.entry.absDy,exitRel:ep.exitRel,outcome:ep.firstAttack?'active':ep.endReason,leadToActiveMs:ep.firstAttack?.rel??null,activeTarget:ep.firstAttack?.target??null,activeAttack:ep.firstAttack?.attack??null,activeBody:ep.firstAttack?.body??null,activeAbsDx:ep.firstAttack?.absDx??null,activeAbsDy:ep.firstAttack?.absDy??null,seedInside:ep.firstAttack?.seedInside??null,targetSwitches:ep.targetSwitches,signals:ep.signals}));
const out={version:'wof-future-danger-branch-geometry-v17',readOnly:true,ramWrites:0,gate,gateStrict:Object.values(gate).every(Boolean),durationRequestedMs:DURATION,intervalMs:INTERVAL,maxWatchMs:MAX_WATCH,model:{timingCorrection:'V16 falsified T30 ENTRY<=500 as a low-false-positive live warning: 2/4 fresh evaluable signals hit. V17 removes T30 from DANGER_SOON and keeps it as ATTACK_READY/branch-learning only.',liveExpiry:'warning horizons now expire on time and downgrade naturally instead of remaining stale until episode finish',branchGoal:'learn D0-entry state/body signatures -> active probability, horizon and eventual attack family',geometryGoal:'validate V15 attack-specific ACTIVE-start envelopes and rebuild type+attack clusters in a fresh room',targetPolicy:'live enemy+0x7E authoritative'},rules:RULES,seedAttackEnvelopes:ATTACK_ENVELOPES,diagnostics:diag,totals:{episodes:done.length,active:done.filter(e=>e.firstAttack).length,horizonComplete:done.filter(e=>e.endReason==='horizonComplete'&&!e.firstAttack).length,signals:signals.length,activeEdges:activeEdges.length,signatureGroups:signatureStats.length,attackClusters:attackClusters.length,retargets:done.reduce((n,e)=>n+e.targetSwitches.length,0)},ruleStats,typeStats,signatureStats,attackClusters,rows,events,note:'V17 is a branch-aware geometry calibrator, not a hitbox proof. T30 fixed <=500 warning is removed after V16 2/4 fresh precision. Use repeated entry signatures to predict attack family/range, and only promote geometry when attack-specific clusters repeat across rooms.'};
self.__WOF_FUTURE_DANGER_BRANCH_GEOMETRY_V17=out;console.log('=== FUTURE DANGER BRANCH GEOMETRY V17 JSON ===');console.log(JSON.stringify(out,null,2));return out;
})().catch(e=>{console.error('WOF_FUTURE_DANGER_BRANCH_GEOMETRY_V17_ERROR',e);throw e;});