(()=>{
'use strict';
try{self.WOFSTATE72EXACT?.stop?.();}catch(_){}
const RAW='https://raw.githubusercontent.com/ouyong520/wof-ai-private/main/';
const sleep=ms=>new Promise(r=>setTimeout(r,ms));let stopped=false;
const load=async f=>{const r=await fetch(RAW+f+'?x='+Date.now(),{cache:'no-store'});if(!r.ok)throw new Error('fetch failed '+r.status+' '+f);return (0,eval)(await r.text());};
async function ensure(){if(!self.__WOF_ROM_LOC_CACHE){await load('wof_rom_focus_inspect.js');for(let i=0;i<300&&!self.__WOF_ROM_LOC_CACHE;i++)await sleep(50);}if(!self.__WOF_ROM_LOC_CACHE)throw new Error('ROM cache unavailable');if(!self.__WOF_STATE72_TRANSITION?.transitions?.length)console.warn('transition result missing; using locked targets 35 and 3');}
function env(){const MOD=_0x515056,C=self.__WOF_ROM_LOC_CACHE,M=MOD.HEAPU8,base=C.base,SW=!!C.swap16,MAX=Math.min(0x100000,M.length-base),DELTA=C.offlineDelta|0;const r8=o=>M[base+(SW?(o^1):o)]>>>0,r16=o=>((r8(o)<<8)|r8(o+1))>>>0,r32=o=>(r8(o)*0x1000000+r8(o+1)*0x10000+r8(o+2)*0x100+r8(o+3))>>>0,s8=v=>v&0x80?v-0x100:v,s16=v=>v&0x8000?v-0x10000:v,h=x=>'0x'+(x>>>0).toString(16).toUpperCase().padStart(6,'0'),off=x=>h((x-DELTA)>>>0),hw=x=>'0x'+(x&0xffff).toString(16).toUpperCase().padStart(4,'0');return{MAX,r8,r16,r32,s8,s16,h,off,hw};}
function eaWords(m,r,size){if(m<=4)return 0;if(m===5||m===6)return 1;if(m===7){if(r===0||r===2||r===3)return 1;if(r===1)return 2;if(r===4)return size==='L'?2:1;}return 0;}
function decode(E,p){const w=E.r16(p),g=w>>>12,m=(w>>3)&7,r=w&7;let len=2,kind='OP',target=null,terminal=false,fall=true;
 if(w===0x4E75||w===0x4E73||w===0x4E77){kind='RET';terminal=true;fall=false;}
 else if(w===0x4E72){kind='STOP';len=4;terminal=true;fall=false;}
 else if((w&0xFFC0)===0x4E80){kind='JSR';len=2+eaWords(m,r,'L')*2;if(m===7&&r===0)target=E.s16(E.r16(p+2))>>>0;else if(m===7&&r===1)target=E.r32(p+2);else if(m===7&&r===2)target=(p+2+E.s16(E.r16(p+2)))>>>0;}
 else if((w&0xFFC0)===0x4EC0){kind='JMP';fall=false;len=2+eaWords(m,r,'L')*2;if(m===7&&r===0)target=E.s16(E.r16(p+2))>>>0;else if(m===7&&r===1)target=E.r32(p+2);else if(m===7&&r===2)target=(p+2+E.s16(E.r16(p+2)))>>>0;}
 else if(g===6){const cc=(w>>8)&15,d=w&255;len=d===0?4:2;target=d===0?(p+2+E.s16(E.r16(p+2)))>>>0:(p+2+E.s8(d))>>>0;kind=cc===0?'BRA':cc===1?'BSR':'BCC';if(cc===0)fall=false;}
 else if(g===1||g===2||g===3){const size=g===1?'B':g===2?'L':'W',sm=(w>>3)&7,sr=w&7,dm=(w>>6)&7,dr=(w>>9)&7;len=2+(eaWords(sm,sr,size)+eaWords(dm,dr,size))*2;}
 else if(g===5){const sz=(w>>6)&3;if(sz===3&&m===1){kind='DBCC';len=4;target=(p+2+E.s16(E.r16(p+2)))>>>0;}else len=2+eaWords(m,r,sz===2?'L':sz===1?'W':'B')*2;}
 else if(g===0){if([0x003C,0x007C,0x023C,0x027C,0x0A3C,0x0A7C].includes(w))len=4;else{const op=(w>>8)&15,sz=(w>>6)&3;if([0,2,4,6,10,12].includes(op)&&sz!==3){const s=sz===2?'L':sz===1?'W':'B';len=2+(s==='L'?4:2)+eaWords(m,r,s)*2;}}}
 else if(g===4){if((w&0xFFF8)===0x4E50)len=4;else if((w&0xFB80)===0x4880&&m>=2)len=4+eaWords(m,r,(w&0x40)?'L':'W')*2;else if((w&0xF1C0)===0x41C0)len=2+eaWords(m,r,'L')*2;else len=2+eaWords(m,r,((w>>6)&3)===2?'L':'W')*2;}
 else if(g===8||g===9||g===11||g===12||g===13)len=2+eaWords(m,r,((w>>6)&3)===2?'L':'W')*2;
 else if(g===14&&((w>>6)&3)===3)len=2+eaWords(m,r,'W')*2;
 else if(g===10||g===15){kind='LINE';terminal=true;fall=false;}
 len=Math.max(2,len);if(target!=null&&(target<0||target>=E.MAX))target=null;return{at:p,w,len,next:p+len,kind,target,terminal,fall};}
function graph(E,start,cap=0x1400){const hi=Math.min(E.MAX,start+cap),q=[start&~1],seen=new Set();while(q.length&&seen.size<9000){const p=q.shift();if(p<start||p>=hi||(p&1)||seen.has(p))continue;seen.add(p);const d=decode(E,p);if(d.kind==='BRA'){if(d.target!=null&&d.target>=start&&d.target<hi)q.push(d.target&~1);continue;}if(d.kind==='BCC'||d.kind==='DBCC'){if(d.next<hi)q.push(d.next);if(d.target!=null&&d.target>=start&&d.target<hi)q.push(d.target&~1);continue;}if(d.kind==='JMP'){if(d.target!=null&&d.target>=start&&d.target<hi)q.push(d.target&~1);continue;}if(d.terminal)continue;if(d.next<hi)q.push(d.next);}return seen;}
function findStart(E,at){for(let p=at&~1;p>=Math.max(0,at-0x600);p-=2){const w=E.r16(p);if((w&0xFFF8)===0x4E50||w===0x48E7)return p;if(w===0x4E75||w===0x4E73||w===0x4E77)return p+2;}return Math.max(0,(at-0x200)&~1);}
function moveMeta(E,p){const w=E.r16(p),g=w>>>12;if(![1,2,3].includes(g))return null;const size=g===1?'B':g===2?'L':'W',sm=(w>>3)&7,sr=w&7,dm=(w>>6)&7,dr=(w>>9)&7,sw=eaWords(sm,sr,size),dstExt=p+2+sw*2;let disp=null;if(dm===5)disp=E.s16(E.r16(dstExt));let imm=null;if(sm===7&&sr===4){imm=size==='L'?E.r32(p+2):E.r16(p+2);if(size==='B')imm&=0xff;}return{size,sm,sr,dm,dr,disp,imm};}
function directStateWrite(E,p){const m=moveMeta(E,p);if(!m||m.dm!==5||m.disp!==0x72)return null;const srcReg=m.sm===0?'D'+m.sr:m.sm===1?'A'+m.sr:'';return{kind:'MOVE.'+m.size,baseReg:'A'+m.dr,srcReg,imm:m.imm,width:m.size==='L'?4:m.size==='W'?2:1};}
function immLoadToD(E,p,reg){const w=E.r16(p),g=w>>>12;if((w&0xF100)===0x7000&&((w>>9)&7)===reg)return E.s8(w&255)&0xff;if([1,2,3].includes(g)){const m=moveMeta(E,p);if(m&&m.dm===0&&m.dr===reg&&m.imm!=null)return m.imm&0xff;}return null;}
function localRoot(E,start,at,reg,targets){let p=start,ins=[];while(p<at&&ins.length<1200){const d=decode(E,p);ins.push(p);p+=Math.max(2,d.len);}const idx=ins.lastIndexOf(at);for(let i=(idx<0?ins.length-1:idx-1),n=0;i>=0&&n<40;i--,n++){const q=ins[i],v=immLoadToD(E,q,reg);if(v!=null)return{rootAt:q,value:v,match:targets.has(v)};}return null;}
async function run(){stopped=false;await ensure();const E=env(),targets=new Set([35,3]),raw=[];for(let p=0;p+8<E.MAX;p+=2){if(stopped)throw new Error('stopped');const w=directStateWrite(E,p);if(!w)continue;if(w.width!==1)continue;raw.push({at:p,...w});if((raw.length&31)===0)await sleep(0);}console.log('raw direct +0x72 byte writes',raw.length);
 const rows=[];const cache=new Map();for(const x of raw){const fs=findStart(E,x.at);let seen=cache.get(fs);if(!seen){seen=graph(E,fs);cache.set(fs,seen);}if(!seen.has(x.at))continue;let stateValue=x.imm==null?null:(x.imm&0xff),root=null;if(stateValue==null&&/^D[0-7]$/.test(x.srcReg)){root=localRoot(E,fs,x.at,+x.srcReg.slice(1),targets);if(root)stateValue=root.value;}const match=stateValue!=null&&targets.has(stateValue);let nearbyPlayerRefs=0,nearby35=0,nearby3=0;for(let q=Math.max(fs,x.at-0x80)&~1;q<Math.min(E.MAX,x.at+0x80);q+=2){const v=E.r16(q),a=(v&0x8000)?(0xFF0000|v):v;if(a===0xFFBE1C||a===0xFFBEFC||a===0xFFBFDC)nearbyPlayerRefs++;if((v&0xff)===35)nearby35++;if((v&0xff)===3)nearby3++;}
 rows.push({at:E.h(x.at),offlineAt:E.off(x.at),routine:E.h(fs),offlineRoutine:E.off(fs),kind:x.kind,baseReg:x.baseReg,srcReg:x.srcReg,imm:x.imm==null?'':x.imm,stateValue:stateValue==null?'':stateValue,rootAt:root?E.h(root.rootAt):'',matches35or3:match,nearbyPlayerRefs,score:(match?800:0)+(nearbyPlayerRefs*120)+(x.imm!=null?100:0)+(root?.match?180:0)});}
 rows.sort((a,b)=>b.score-a.score||a.at.localeCompare(b.at));console.log('=== EXACT STATE72 DIRECT WRITERS ===');console.table(rows.slice(0,80));const exact=rows.filter(x=>x.matches35or3),player=exact.filter(x=>x.nearbyPlayerRefs>0),top=player[0]||exact[0]||rows[0]||null;
 const tr=self.__WOF_STATE72_TRANSITION?.transitions||[];const lock=tr.filter(x=>x.type===16&&((x.oldState===32&&x.newState===35)||(x.oldState===35&&x.newState===3))).map(x=>({type:x.type,oldState:x.oldState,newState:x.newState,count:x.count,ref3A:x.ref3AChangeRate,ref6A:x.ref6AChangeRate,vec:x.vecChangeRate,oldHandler:x.oldHandler,newHandler:x.newHandler}));console.log('=== LOCKED TYPE16 TRANSITIONS ===');console.table(lock);
 const verdict={targetType:16,transitionA:'32->35',transitionB:'35->3',rawDirect72Writes:raw.length,validatedDirect72Writes:rows.length,exact35or3Writers:exact.length,exactWithPlayerRefs:player.length,topAt:top?.at||'',topRoutine:top?.routine||'',topBaseReg:top?.baseReg||'',topSrcReg:top?.srcReg||'',topStateValue:top?.stateValue??'',topRootAt:top?.rootAt||'',topPlayerRefs:top?.nearbyPlayerRefs??0};console.log('=== EXACT TRANSITION WRITER VERDICT ===');console.table([verdict]);if(exact.length)console.log('🎯 找到能生成 state 35/3 的真实 +0x72 writer；下一步只反汇编 top writer routine 并追玩家证据。');else console.warn('⚠️ 没有直接 d16(Ax) writer 生成 35/3；下一步只查 indexed/MOVEM/alias helper 或动态 PC hook，不再扩大普通 direct scan。');self.__WOF_STATE72_EXACT={version:'state72-exact-transition-writer-v1',verdict,rows,lockedTransitions:lock};return self.__WOF_STATE72_EXACT;}
self.WOFSTATE72EXACT={run,stop(){stopped=true;}};console.log('✅ WOF exact state72 transition writer scan loaded');console.log('执行 await WOFSTATE72EXACT.run()');
})();