import assert from'node:assert/strict';import fs from'node:fs';import{createRequire}from'node:module';import{webcrypto,createHash}from'node:crypto';
if(!globalThis.crypto)Object.defineProperty(globalThis,'crypto',{value:webcrypto});
const require=createRequire(import.meta.url),C=require('./proof_core.js'),A=require('./proof_authority_v2_contract.js');
let n=0;async function T(name,fn){await fn();n++;console.log('PASS',name)}
const ROM=C.ROM,EP='a'.repeat(32),EP2='b'.repeat(32),SESSION='1'.repeat(32),NONCE='2'.repeat(32);
const authority=(x={})=>({session:SESSION,workerGeneration:7,runtimeEpoch:EP,pairGeneration:3,pairNonce:NONCE,launcherIdentitySha:ROM,channel:'WOF_ALPHA_'+SESSION,...x});
const authText=a=>[a.session,a.workerGeneration,a.runtimeEpoch,a.pairGeneration,a.pairNonce,a.launcherIdentitySha,a.channel].join('|');
const liveText=(proofSessionId,nonce,a)=>['WOF_ALPHA_DUAL_LIVE_V2',proofSessionId,nonce,authText(a)].join('|');
const gapText=w=>['WOF_ALPHA_DUAL_GAP_V2',w.proofSessionId,w.requestId,w.transactionId,w.startedAt,w.endedAt,w.durationMs,w.ok===true?'1':'0',authText(w.authority)].join('|');
async function signer(){const k=await crypto.subtle.generateKey({name:'ECDSA',namedCurve:'P-256'},true,['sign','verify']),raw=await crypto.subtle.exportKey('raw',k.publicKey),fp=createHash('sha256').update(Buffer.from(raw)).digest('hex');return{...k,fp}}
const enc=s=>new TextEncoder().encode(s);async function sig(k,t){return crypto.subtle.sign({name:'ECDSA',hash:'SHA-256'},k.privateKey,enc(t))}
async function liveSession(name='proof-regression',a=authority(),k=null){k=k||await signer();const s=new C.Session(name);assert.equal(s.pinTrustedSigner(k.fp),true);assert.equal(s.observeAuthority(a).ok,true);const q=s.beginLiveWitness();assert(q);const signature=await sig(k,liveText(name,q.nonce,a));assert.equal(await s.acceptLiveWitness({proofSessionId:name,nonce:q.nonce,authority:a,signerFingerprint:k.fp,publicKey:k.publicKey,signature}),true);assert.equal(s.observeRuntimeSafety({readOnly:true,ramWrites:0,inputInjection:false,workerReplacement:false}),true);return{s,k,a,cap:s.capability()}}
const db=(ep=EP)=>({width:800,height:600,contentRect:{x:0,y:0,width:800,height:600},mappingVersion:1,fullscreen:false,epoch:ep,projectionEpoch:ep});
const enemyMapKey=(ep=EP)=>[800,600,0,0,800,600,1,'win','enemy-proof-v2',ep].join(':');
function enemyEvent(a,{target7E=0,target='P1',label='1P',at=1000,samples=3,epoch=EP,dbEpoch=EP,lifecycle='enemy-slot-2@g1#'+'c'.repeat(32),generation=1}={}){const input={markers:[{slot:2,type:3,target7E,target,sampleAt:at-5,confidence:1,epoch}],projection:{epoch,proofId:'enemy-proof-v2'},drawingBufferState:db(dbEpoch)},plan={labels:[{slot:2,label,target,anchorDb:{x:10,y:20},mappingKey:enemyMapKey(epoch)}]},ctx={authority:a,enemies:{'2':{proofLifecycleId:lifecycle,lifecycleGeneration:generation,lifecycleStable:true,lifecycleContinuitySamples:samples,lifecycleContinuityProven:true,continuityToken:'c'.repeat(32)}}};return C.enemyEvents(input,plan,at,ctx)[0]}
const playerMapKey=(ep=EP)=>[800,600,0,0,800,600,1,'win','player-projection-v2'].join(':');
function playerEvent(a,{warningSampleAt=990,sampleAt=995,at=1000,epoch=EP,dbEpoch=EP}={}){const input={warningSampleAt,warningEpoch:epoch,players:{P1:{sampleAt,confidence:1}},projection:{epoch,version:'player-projection-v2'},drawingBufferState:db(dbEpoch)},plan={anchored:[{player:'P1',anchor:{xDb:10,yDb:20,ageMs:5,confidence:1,mappingKey:playerMapKey(epoch)}}]},ctx={authority:a,players:{P1:{proofLifecycleId:'P1@g1#'+'d'.repeat(32),lifecycleGeneration:1,lifecycleStable:true,lifecycleContinuitySamples:3,lifecycleContinuityProven:true,continuityToken:'d'.repeat(32)}}};return C.playerEvents(input,plan,at,ctx)[0]}
await T('trusted root rejects witness signed by a different self-generated key',async()=>{const trusted=await signer(),forged=await signer(),a=authority(),s=new C.Session('root-reject');s.pinTrustedSigner(trusted.fp);s.observeAuthority(a);const q=s.beginLiveWitness(),signature=await sig(forged,liveText('root-reject',q.nonce,a));assert.equal(await s.acceptLiveWitness({proofSessionId:'root-reject',nonce:q.nonce,authority:a,signerFingerprint:forged.fp,publicKey:forged.publicKey,signature}),false);assert.equal(s.hasLiveWitness(),false)});
await T('workerGeneration/runtime/pair authority changes revoke old capability and challenge',async()=>{const{x:s,a,cap}=await liveSession('authority-change');assert(cap);const changed=authority({workerGeneration:8});const r=s.observeAuthority(changed);assert.equal(r.changed,true);assert.equal(r.workerChanged,true);assert.equal(s.hasLiveWitness(),false);assert.equal(s.trustedSignerPinned(),false);assert.equal(s.beginLiveWitness(),null);assert.equal(s.observeAuthority({...changed,workerGeneration:'8'}).ok,false);assert.equal(s.observeAuthority({...changed,pairGeneration:'4'}).ok,false)});
await T('same-authority V2 retarget remains scoreable only inside one lifecycle',async()=>{const{s,a}=await liveSession('retarget-v2'),e1=enemyEvent(a,{target7E:0,target:'P1',label:'1P',at:1000,samples:3}),e2=enemyEvent(a,{target7E:4,target:'P2',label:'2P',at:1050,samples:4});s.record([e1,e2]);assert(C.authorityTuple(s.enemy[0]));assert(C.authorityTuple(s.enemy[1]));assert.equal(s.markRetarget('v2-retarget'),true);assert.equal(s.status().phases.liveRetarget.enemyTargetLabels,'PASS')});
await T('same-slot replacement lifecycle cannot be retarget',async()=>{const{s,a}=await liveSession('replacement-v2'),e1=enemyEvent(a,{target:'P1',at:1000,samples:3,lifecycle:'enemy-slot-2@g1#'+'c'.repeat(32),generation:1}),e2=enemyEvent(a,{target7E:4,target:'P2',label:'2P',at:1050,samples:3,lifecycle:'enemy-slot-2@g2#'+'e'.repeat(32),generation:2});s.record([e1,e2]);assert.equal(s.markRetarget(),false)});
await T('cross-epoch drawing buffer mapping and coercible epochs fail closed',async()=>{const{s,a}=await liveSession('mapping-v2'),bad=enemyEvent(a,{dbEpoch:EP2});s.record([bad]);assert.equal(C.authorityTuple(s.enemy.at(-1)),null);const boxed=enemyEvent(a);boxed.epochs.runtime=new String(EP);s.record([boxed]);assert.equal(C.authorityTuple(s.enemy.at(-1)),null)});
await T('warningSampleAt must be primitive finite and target7E must be primitive exact',async()=>{const{s,a}=await liveSession('strict-primitives');for(const v of [null,'990',new Number(990),NaN,Infinity]){const e=playerEvent(a,{warningSampleAt:v});s.record([e]);assert.equal(C.authorityTuple(s.player.at(-1)),null)}const e=enemyEvent(a,{target7E:'4',target:'P2',label:'2P'});s.record([e]);assert.equal(e.target7E,null);assert.equal(C.authorityTuple(s.enemy.at(-1)),null)});
await T('player respawn and enemy lifecycle replacement invalidate old calibration/profile authority',async()=>{const{s,a,cap}=await liveSession('profile-life'),common={verdict:'IMPLEMENTATION_READY',projection:{camera:{address:'0xFF1234',read:'u16be'},native:{width:384,height:224,xFormula:'worldX-camera+xBias',xBias:7,yModel:'Y-Z'}}},pc={stable:true,bodyYBiasNative:10,headClearanceNative:20,validationBounds:{minX:0,maxX:383,minY:0,maxY:223},proofId:'proof-12345678',projectionVersion:'proj-12345678',proofSessionId:'profile-life',lifecycleId:'P1@g1#'+'d'.repeat(32),headLifecycleId:'P1@g1#'+'d'.repeat(32),lifecycleGeneration:1};const meta={proofId:pc.proofId,projectionVersion:pc.projectionVersion,proofSessionId:'profile-life',liveCapability:cap,authority:a,currentLifecycle:{proofLifecycleId:'P1@g2#'+'f'.repeat(32),lifecycleGeneration:2,lifecycleStable:true}};assert.notEqual(C.playerProfile(common,pc,meta).ok,true);const rows=[{stable:true,captureCount:2,type:3,slot:2,enemyHeadOffsetNative:-18,proofSessionId:'profile-life',lifecycleId:'enemy-slot-2@g1#'+'c'.repeat(32),lifecycleGeneration:1,proofId:'proof-12345678'}],em={proofId:'proof-12345678',proofSessionId:'profile-life',liveCapability:cap,authority:a,currentEnemies:[{type:3,slot:2,proofLifecycleId:'enemy-slot-2@g2#'+'e'.repeat(32),lifecycleGeneration:2,lifecycleStable:true}]};assert.equal(C.enemyProfile(common,rows,em).ok,false)});
await T('signed authority-gap transaction is fresh, same-authority and one-shot',async()=>{const{s,k,a}=await liveSession('gap-v2'),w={proofSessionId:'gap-v2',requestId:'req-1',transactionId:'gap-12345678',startedAt:1000,endedAt:1450,durationMs:450,ok:true,authority:a};w.signature=await sig(k,gapText(w));const events=[{at:1200,surface:'player-head-warning',decision:'FIXED_HUD',evidenceRef:'authority-gap:req-1',authority:a},{at:1250,surface:'enemy-target-label',decision:'SUPPRESSED',evidenceRef:'authority-gap:req-1',authority:a}];assert.equal(await s.acceptAuthorityGapWitness(w,events,{nowMs:1500}),true);assert.equal(await s.acceptAuthorityGapWitness(w,events,{nowMs:1500}),false);const stale={...w,transactionId:'gap-87654321'};stale.signature=await sig(k,gapText(stale));assert.equal(await s.acceptAuthorityGapWitness(stale,events,{nowMs:5000}),false)});
await T('public mutable or serialized state cannot force terminal IMPLEMENTATION_READY',async()=>{const{s}=await liveSession('mutable-v2');s.bind.player='PROVED';s.bind.enemy='PROVED';for(const p of Object.values(s.phases)){p.coverage='PASS';p.playerHeadWarning='PASS';p.enemyTargetLabels='PASS'}s.visual.playerWarningAttached=true;s.visual.enemyLabelsAttached=true;s.visual.operatorDecision='VISUAL_OK';s.authority.stale.coverage='PASS';const serialized=JSON.parse(JSON.stringify(s));serialized.verdict='IMPLEMENTATION_READY';assert.notEqual(s.verdict(),'IMPLEMENTATION_READY');assert.notEqual(s.terminal({}, {}, {}).verdict,'IMPLEMENTATION_READY')});
await T('runnable sources are authority-v2 and contain no worker self-authentication path',async()=>{const worker=fs.readFileSync(new URL('./wof_alpha_v1_dual_live_proof_worker.js',import.meta.url),'utf8'),top=fs.readFileSync(new URL('./wof_alpha_v1_dual_live_proof_top.js',import.meta.url),'utf8'),loader=fs.readFileSync(new URL('./wof_alpha_v1_dual_live_proof.js',import.meta.url),'utf8'),contract=fs.readFileSync(new URL('./proof_authority_v2_contract.js',import.meta.url),'utf8');assert.match(worker,/workerGeneration/);assert.match(worker,/WOF_ALPHA_DUAL_LIVE_V2|A\.liveText/);assert.match(worker,/readLifecycleAuthority/);assert.match(worker,/lifecycleContinuityProven:true/);assert.doesNotMatch(worker,/generateKey\s*\(/);assert.doesNotMatch(worker,/keyPairPromise/);assert.doesNotMatch(worker,/Math\.abs\([^\n]+st\.(?:x|y|z)/);for(const name of ['pinTrustedSigner','observeAuthority','observeRuntimeSafety','observeLifecycles','confirmProfileBinding'])assert.match(top,new RegExp('s\\.'+name+'\\('));assert.doesNotMatch(top,/s\.bind\.(?:player|enemy)\s*=/);assert.doesNotMatch(top,/s\.visual\.[A-Za-z]+\s*=/);assert.doesNotMatch(top,/pinTrustedSigner\s*\(\s*m(?:sg)?\./);assert.match(loader,/signerProvider\(manifest\.implementationCommit\)/);assert.match(loader,/trustedRoot\(manifest\.implementationCommit\)/);assert.doesNotMatch(loader,/generateKey\s*\(/);assert.match(contract,/immutableGlobal/);assert.match(contract,/configurable!==false/);assert.match(contract,/wof-alpha-proof-lifecycle-authority-v2/)});
await T('authority-v2 contract rejects coercible authority and stale/mutable trust roots',async()=>{assert.equal(A.validAuthority(authority()),true);assert.equal(A.validAuthority(authority({workerGeneration:'7'})),false);assert.equal(A.validAuthority(authority({runtimeEpoch:new String(EP)})),false);assert.equal(A.validAuthority(authority({pairGeneration:3.0})),true);assert.equal(A.validAuthority(authority({pairGeneration:3.5})),false);const now=10000,good=Object.freeze({schema:A.TRUST_SCHEMA,source:'TRUSTED_LAUNCH',authorityRootId:'root-1234',signerFingerprint:'f'.repeat(64),candidateCommit:'1'.repeat(40),issuedAt:9000,expiresAt:20000});assert.equal(A.validTrust(good,'1'.repeat(40),now),true);assert.equal(A.validTrust({...good,expiresAt:9999},'1'.repeat(40),now),false);assert.equal(A.validTrust({...good,signerFingerprint:'F'.repeat(64)},'1'.repeat(40),now),false)});
console.log(`PASS — ${n} / ${n} authority-v2 implementation regression`);
