(function(r,f){const a=f(r);if(typeof module!=='undefined'&&module.exports)module.exports=a;r.WOFAlphaDualProofCore=a;})(typeof self!=='undefined'?self:globalThis,function(ROOT){
'use strict';
const E='REAL_BROWSER_WOF_BOUNDED_DYNAMIC_LIVE_PROOF';
const S='wof-alpha-v1-anchored-overlays-bounded-live-proof-v1';
const ROM='5c369ce2de4f53d8cef87eca5623a1f0d39a779e885532d6f185b81357878f62';
const P=['fastHorizontal','depthMovement','fullJump','rapidStageCameraScroll','simultaneousPlayerCamera','movingEnemy','liveRetarget','multiEnemy','resizeFullscreenRemap'];
const A=['stale','identity','epoch','confidence','bounds','nonFinite'];
const HEX32=/^[0-9a-f]{32}$/;
const HEX64=/^[0-9a-f]{64}$/;
const TARGETS=Object.freeze({0:'P1',4:'P2',8:'P3'});
const fin=Number.isFinite;
function cp(x){if(x==null||typeof x!=='object')return x;if(Array.isArray(x))return x.map(cp);let p;try{p=Object.getPrototypeOf(x)}catch(_){return null}if(p!==Object.prototype&&p!==null)return null;const o={};for(const[k,v]of Object.entries(x))o[k]=cp(v);return o}
const phase=()=>({coverage:'NOT_OBSERVED',playerHeadWarning:'NOT_OBSERVED',enemyTargetLabels:'NOT_OBSERVED',evidenceRefs:[],authorityTuples:[]});
const auth=()=>({coverage:'NOT_OBSERVED',anchoredCueDuringInvalidAuthority:false,events:[]});
const capBrand=new WeakSet(),capMeta=new WeakMap(),priv=new WeakMap();
const primitiveFinite=v=>typeof v==='number'&&fin(v);
const validEpoch=v=>typeof v==='string'&&HEX32.test(v);
const validPin=v=>typeof v==='string'&&HEX64.test(v);
const validTarget7E=v=>typeof v==='number'&&fin(v)&&Number.isInteger(v)&&!Object.is(v,-0)&&Object.prototype.hasOwnProperty.call(TARGETS,String(v));
const targetFor=v=>validTarget7E(v)?TARGETS[v]:null;
function addr(v){return Number.isInteger(v)?v:typeof v==='string'&&/^0x[0-9a-f]+$/i.test(v)?parseInt(v,16):null}
function facts(c){const p=c?.projection||c,n=p?.native||{},cam=p?.camera||{},z=n.yModel==='Y-Z'?-1:n.yModel==='Y+Z'?1:n.yModel==='Y'?0:null,a=addr(cam.address);return a===null||cam.read!=='u16be'||n.width!==384||n.height!==224||n.xFormula!=='worldX-camera+xBias'||!primitiveFinite(n.xBias)||z===null?null:{cameraAddress:a,cameraRead:'u16be',cameraSign:1,cameraScale:1,worldXScale:1,xBias:n.xBias,yModel:n.yModel,floorYScale:1,zScale:z}}
function validAuthority(a){return !!a&&typeof a.session==='string'&&HEX32.test(a.session)&&Number.isSafeInteger(a.workerGeneration)&&a.workerGeneration>0&&validEpoch(a.runtimeEpoch)&&Number.isSafeInteger(a.pairGeneration)&&a.pairGeneration>0&&typeof a.pairNonce==='string'&&HEX32.test(a.pairNonce)&&a.launcherIdentitySha===ROM&&a.channel==='WOF_ALPHA_'+a.session}
function authorityText(a){return[a.session,a.workerGeneration,a.runtimeEpoch,a.pairGeneration,a.pairNonce,a.launcherIdentitySha,a.channel].join('|')}
function sameAuthority(a,b){return validAuthority(a)&&validAuthority(b)&&authorityText(a)===authorityText(b)}
function liveText(sessionId,nonce,a){return['WOF_ALPHA_DUAL_LIVE_V2',sessionId,nonce,authorityText(a)].join('|')}
function gapText(w){return['WOF_ALPHA_DUAL_GAP_V2',w.proofSessionId,w.requestId,w.transactionId,w.startedAt,w.endedAt,w.durationMs,w.ok===true?'1':'0',authorityText(w.authority)].join('|')}
function bytes(v){if(v instanceof ArrayBuffer)return new Uint8Array(v);if(ArrayBuffer.isView(v))return new Uint8Array(v.buffer,v.byteOffset,v.byteLength);return null}
async function digestHex(v){try{const b=bytes(v);if(!b||!ROOT?.crypto?.subtle)return null;const d=await ROOT.crypto.subtle.digest('SHA-256',b);return[...new Uint8Array(d)].map(x=>x.toString(16).padStart(2,'0')).join('')}catch(_){return null}}
async function publicKeyFingerprint(publicKey){try{if(!ROOT?.crypto?.subtle||!publicKey||typeof publicKey!=='object'||publicKey.type!=='public')return null;const raw=await ROOT.crypto.subtle.exportKey('raw',publicKey);return digestHex(raw)}catch(_){return null}}
async function verify(publicKey,text,signature){try{const sig=bytes(signature);if(!sig||!ROOT?.crypto?.subtle||!publicKey||typeof publicKey!=='object')return false;return await ROOT.crypto.subtle.verify({name:'ECDSA',hash:'SHA-256'},publicKey,sig,new TextEncoder().encode(text))}catch(_){return false}}
function capRecord(cap){return cap&&capBrand.has(cap)?capMeta.get(cap)||null:null}
function capValid(cap,proofSessionId,authority){const m=capRecord(cap);return !!m&&m.active===true&&m.proofSessionId===proofSessionId&&sameAuthority(m.authority,authority)}
function profileAuthority(m){return m?.authority||capRecord(m?.liveCapability)?.authority||null}
function playerProfile(c,o,m={}){
  const f=facts(c),cap=m.liveCapability,a=profileAuthority(m),cm=m.currentLifecycle||null;
  if(!o||o.proofSessionId!==m.proofSessionId||typeof o.lifecycleId!=='string'||o.lifecycleId.length<4||o.lifecycleId!==o.headLifecycleId||!Number.isSafeInteger(o.lifecycleGeneration)||o.lifecycleGeneration<=0)return{ok:false,reason:'PLAYER_LIFECYCLE_NOT_PROVED'};
  if(!cm||cm.proofLifecycleId!==o.lifecycleId||cm.lifecycleGeneration!==o.lifecycleGeneration||cm.lifecycleStable!==true)return{ok:false,reason:'PLAYER_CURRENT_LIFECYCLE_MISMATCH'};
  if(!capValid(cap,m.proofSessionId,a))return{ok:false,reason:'LIVE_CAPABILITY_REQUIRED'};
  if(!f)return{ok:false,reason:'COMMON_PROJECTION_INCOMPLETE'};
  if(c?.verdict!=='IMPLEMENTATION_READY')return{ok:false,reason:'COMMON_PROJECTION_NOT_READY'};
  if(!primitiveFinite(o.bodyYBiasNative)||!primitiveFinite(o.headClearanceNative)||o.headClearanceNative<0)return{ok:false,reason:'PLAYER_Y_SPLIT_INCOMPLETE'};
  if(o.stable!==true)return{ok:false,reason:'PLAYER_CLEARANCE_NOT_STABLE'};
  const b=o.validationBounds||{minX:0,maxX:383,minY:0,maxY:223},id=String(m.proofId||o.proofId||''),v=String(m.projectionVersion||o.projectionVersion||'');
  if(id.length<8||v.length<8)return{ok:false,reason:'PLAYER_PROFILE_IDENTITY_INCOMPLETE'};
  if(![b.minX,b.maxX,b.minY,b.maxY].every(primitiveFinite)||b.minX<0||b.maxX>384||b.minY<0||b.maxY>224||b.minX>b.maxX||b.minY>b.maxY)return{ok:false,reason:'PLAYER_VALIDATION_BOUNDS_INVALID'};
  return{ok:true,profile:{schema:'wof-alpha-player-head-projection-v1',status:'PROVED',activation:'PROOF_ONLY_RUNTIME_BINDING',projectionKind:'world-camera-floor-z-affine-v1',proofId:id,proofSessionId:m.proofSessionId,projectionVersion:v,source:'REAL_BROWSER_WOF_BOUNDED_DYNAMIC_LIVE_PROOF_CANDIDATE_RUNTIME_ONLY',nativeWidth:384,nativeHeight:224,...f,yBias:o.bodyYBiasNative,headClearanceNative:o.headClearanceNative,validationBounds:cp(b),proofOnlyRuntimeBinding:true,evidenceClass:E,guessedConstants:false,proofAuthority:cp(a),proofLifecycle:{id:o.lifecycleId,generation:o.lifecycleGeneration}}}}
function enemyProfile(c,rows,m={}){
  const f=facts(c),cap=m.liveCapability,a=profileAuthority(m),valid=[],current=Array.isArray(m.currentEnemies)?m.currentEnemies:[];
  for(const o of Array.isArray(rows)?rows:[]){
    if(o?.proofSessionId!==m.proofSessionId||o.stable!==true||!Number.isSafeInteger(o.captureCount)||o.captureCount<2||typeof o.lifecycleId!=='string'||o.lifecycleId.length<4||!Number.isSafeInteger(o.lifecycleGeneration)||o.lifecycleGeneration<=0||!Number.isInteger(o.slot)||o.slot<0||o.slot>=20||!Number.isInteger(o.type)||o.type<0||o.type>=47||!primitiveFinite(o.enemyHeadOffsetNative))continue;
    const live=current.filter(x=>x?.type===o.type&&x?.lifecycleStable===true);
    if(live.length!==1)continue;
    const x=live[0];
    if(x.proofLifecycleId!==o.lifecycleId||x.lifecycleGeneration!==o.lifecycleGeneration||x.slot!==o.slot)continue;
    valid.push(o);
  }
  const byType=new Map;
  for(const o of valid){if(!byType.has(o.type))byType.set(o.type,new Set);byType.get(o.type).add(o.lifecycleId+'|'+o.lifecycleGeneration+'|'+o.slot)}
  const unambiguous=valid.filter(o=>byType.get(o.type)?.size===1);
  if(!unambiguous.length)return{ok:false,reason:'ENEMY_HEAD_OFFSETS_NOT_LIFECYCLE_PROVED'};
  if(!capValid(cap,m.proofSessionId,a))return{ok:false,reason:'LIVE_CAPABILITY_REQUIRED'};
  if(!f)return{ok:false,reason:'COMMON_PROJECTION_INCOMPLETE'};
  if(c?.verdict!=='IMPLEMENTATION_READY')return{ok:false,reason:'COMMON_PROJECTION_NOT_READY'};
  const off={},life={};
  for(const o of unambiguous){off[String(o.type)]=o.enemyHeadOffsetNative;life[String(o.type)]={id:o.lifecycleId,generation:o.lifecycleGeneration,slot:o.slot}}
  const id=String(m.proofId||unambiguous[0]?.proofId||'');
  if(id.length<8)return{ok:false,reason:'ENEMY_PROFILE_IDENTITY_INCOMPLETE'};
  return{ok:true,profile:{schema:'wof-alpha-enemy-head-projection-v1',verdict:'IMPLEMENTATION_READY',proofId:id,proofSessionId:m.proofSessionId,romSha256:m.romSha256||ROM,nativeWidth:384,nativeHeight:224,cameraAddress:f.cameraAddress,cameraRead:f.cameraRead,cameraSign:f.cameraSign,cameraScale:f.cameraScale,xBias:f.xBias,yModel:f.yModel,enemyHeadOffsetsByType:off,evidence:'REAL_BROWSER_WOF_BOUNDED_DYNAMIC_LIVE_PROOF_CANDIDATE_RUNTIME_ONLY',status:'PROOF_ONLY_RUNTIME_BINDING',proofOnlyRuntimeBinding:true,evidenceClass:E,guessedConstants:false,proofAuthority:cp(a),proofLifecycleByType:life}}}
function ak(x){x=String(x||'').toUpperCase();if(x.includes('STALE')||x.includes('BEFORE_WARNING_SAMPLE')||x.includes('MISSING_MARKERS'))return'stale';if(x.includes('IDENTITY')||x.includes('ABSENT')||x.includes('REPLACED')||x.includes('SLOT')||x.includes('LIFECYCLE'))return'identity';if(x.includes('EPOCH'))return'epoch';if(x.includes('CONFIDENCE'))return'confidence';if(x.includes('BOUNDS'))return'bounds';if(x.includes('NONFINITE')||x.includes('INVALID_PLAYER_XYZ')||x.includes('INVALID_CAMERA')||x.includes('INVALID_WARNING_SAMPLE_TIME')||x.includes('INVALID_TARGET'))return'nonFinite';return null}
const conf=v=>primitiveFinite(v)?v:null;
const str=v=>typeof v==='string'?v:null;
function rectOf(db){const r=db?.contentRect||{x:0,y:0,width:db?.width,height:db?.height},v=[db?.width,db?.height,r?.x,r?.y,r?.width,r?.height];if(!v.every(primitiveFinite)||v[0]<=0||v[1]<=0||v[4]<=0||v[5]<=0)return null;if(r.x<0||r.y<0||r.x+r.width>db.width||r.y+r.height>db.height)return null;return{x:r.x,y:r.y,width:r.width,height:r.height}}
function mappingVersion(v){return typeof v==='string'||(typeof v==='number'&&fin(v)&&Number.isInteger(v))?v:null}
function mappingAuthority(db){const r=rectOf(db),mv=mappingVersion(db?.mappingVersion),ep=db?.epoch,pe=db?.projectionEpoch;if(!r||mv===null||!validEpoch(ep)||!validEpoch(pe)||ep!==pe)return null;return[db.width,db.height,r.x,r.y,r.width,r.height,mv,db?.fullscreen===true?'fs':'win',ep,pe].join('|')}
function expectedSurfaceMapping(surface,db,pr){const r=rectOf(db),mv=mappingVersion(db?.mappingVersion);if(!r||mv===null)return null;const head=[db.width,db.height,r.x,r.y,r.width,r.height,mv,db?.fullscreen===true?'fs':'win'];if(surface==='player-head-warning')return typeof pr?.version==='string'&&pr.version.length?head.concat(pr.version).join(':'):null;if(surface==='enemy-target-label')return typeof pr?.proofId==='string'&&pr.proofId.length&&validEpoch(pr?.epoch)?head.concat(pr.proofId,pr.epoch).join(':'):null;return null}
function lifeFields(l={}){return{actorIdentity:typeof l.proofLifecycleId==='string'?l.proofLifecycleId:null,lifecycleId:typeof l.proofLifecycleId==='string'?l.proofLifecycleId:null,lifecycleGeneration:Number.isSafeInteger(l.lifecycleGeneration)?l.lifecycleGeneration:null,lifecycleStable:l.lifecycleStable===true,lifecycleContinuitySamples:Number.isSafeInteger(l.lifecycleContinuitySamples)?l.lifecycleContinuitySamples:null,lifecycleContinuityProven:l.lifecycleContinuityProven===true,continuityToken:typeof l.continuityToken==='string'?l.continuityToken:null}}
function playerEvents(a,p,t=Date.now(),ctx={}){
  const out=[],ps=a?.players||{},pr=a?.projection||{},db=a?.drawingBufferState||{},lc=ctx.players||{},authority=cp(ctx.authority||null),mk=mappingAuthority(db),expected=expectedSurfaceMapping('player-head-warning',db,pr);
  for(const x of p?.anchored||[]){const q=ps[x.player]||{},z=x.anchor||{},l=lifeFields(lc[x.player]);out.push({at:primitiveFinite(t)?t:null,surface:'player-head-warning',...l,player:x.player||null,target7E:null,target:x.player||null,label:'危险',sampleAt:primitiveFinite(q.sampleAt)?q.sampleAt:null,ageMs:primitiveFinite(z.ageMs)?z.ageMs:null,confidence:conf(z.confidence),epochs:{runtime:str(a?.warningEpoch),projection:str(pr.epoch),drawingBuffer:str(db.epoch),drawingBufferProjection:str(db.projectionEpoch)},authority,mappingKey:mk,surfaceMappingKey:typeof z.mappingKey==='string'?z.mappingKey:null,expectedSurfaceMappingKey:expected,anchorDb:primitiveFinite(z.xDb)&&primitiveFinite(z.yDb)?{x:z.xDb,y:z.yDb}:null,decision:'ANCHORED_DRAW',reason:null,evidenceRef:null,warningSampleAtRaw:a?.warningSampleAt})}
  for(const x of p?.fixed||[]){const q=ps[x.player]||{},l=lifeFields(lc[x.player]);out.push({at:primitiveFinite(t)?t:null,surface:'player-head-warning',...l,player:x.player||null,target7E:null,target:x.player||null,label:'危险',sampleAt:primitiveFinite(q.sampleAt)?q.sampleAt:null,ageMs:null,confidence:conf(q.confidence),epochs:{runtime:str(a?.warningEpoch),projection:str(pr.epoch),drawingBuffer:str(db.epoch),drawingBufferProjection:str(db.projectionEpoch)},authority,mappingKey:null,surfaceMappingKey:null,expectedSurfaceMappingKey:expected,anchorDb:null,decision:'FIXED_HUD',reason:x.reason||'FIXED_HUD',evidenceRef:null,warningSampleAtRaw:a?.warningSampleAt})}
  return out
}
function enemyEvents(a,p,t=Date.now(),ctx={}){
  const out=[],ms=a?.markers||[],pr=a?.projection||{},db=a?.drawingBufferState||{},by=new Map(ms.map(m=>[m?.slot,m])),lc=ctx.enemies||{},authority=cp(ctx.authority||null),mk=mappingAuthority(db),expected=expectedSurfaceMapping('enemy-target-label',db,pr);
  for(const x of p?.labels||[]){const m=by.get(x.slot)||{},l=lifeFields(lc[String(x.slot)]||{}),raw=validTarget7E(m.target7E)?m.target7E:null;out.push({at:primitiveFinite(t)?t:null,surface:'enemy-target-label',...l,player:null,target7E:raw,target:typeof m.target==='string'?m.target:null,label:typeof x.label==='string'?x.label:null,sampleAt:primitiveFinite(m.sampleAt)?m.sampleAt:null,ageMs:primitiveFinite(m.sampleAt)&&primitiveFinite(t)?Math.max(0,t-m.sampleAt):null,confidence:conf(m.confidence),epochs:{runtime:str(m.epoch),projection:str(pr.epoch),drawingBuffer:str(db.epoch),drawingBufferProjection:str(db.projectionEpoch)},authority,mappingKey:mk,surfaceMappingKey:typeof (x.mappingKey??p?.mappingKey)==='string'?(x.mappingKey??p?.mappingKey):null,expectedSurfaceMappingKey:expected,anchorDb:x.anchorDb&&primitiveFinite(x.anchorDb.x)&&primitiveFinite(x.anchorDb.y)?cp(x.anchorDb):null,decision:'ANCHORED_DRAW',reason:null,evidenceRef:null,enemyType:Number.isInteger(m.type)?m.type:null,slot:Number.isInteger(m.slot)?m.slot:null})}
  for(const x of p?.suppressed||[]){const m=by.get(x.slot)||{},l=lifeFields(lc[String(x.slot)]||{});out.push({at:primitiveFinite(t)?t:null,surface:'enemy-target-label',...l,player:null,target7E:validTarget7E(m.target7E)?m.target7E:null,target:typeof m.target==='string'?m.target:null,label:null,sampleAt:primitiveFinite(m.sampleAt)?m.sampleAt:null,ageMs:primitiveFinite(m.sampleAt)&&primitiveFinite(t)?Math.max(0,t-m.sampleAt):null,confidence:conf(m.confidence),epochs:{runtime:str(m.epoch),projection:str(pr.epoch),drawingBuffer:str(db.epoch),drawingBufferProjection:str(db.projectionEpoch)},authority,mappingKey:null,surfaceMappingKey:null,expectedSurfaceMappingKey:expected,anchorDb:null,decision:'SUPPRESSED',reason:x.reason||p?.reason||'SUPPRESSED',evidenceRef:null,enemyType:Number.isInteger(m.type)?m.type:null,slot:Number.isInteger(m.slot)?m.slot:null})}
  return out
}
function tuple(e){
  const q=e?.epochs||{},mk=e?.mappingKey,a=e?.authority;
  if(e?.decision!=='ANCHORED_DRAW'||e?.lifecycleStable!==true||typeof e?.lifecycleId!=='string'||!Number.isSafeInteger(e?.lifecycleGeneration)||e.lifecycleGeneration<=0||!primitiveFinite(e?.at)||!primitiveFinite(e?.sampleAt)||!validAuthority(a)||typeof e?.proofSessionId!=='string'||e.proofSessionId.length<1)return null;
  if(!validEpoch(q.runtime)||!validEpoch(q.projection)||!validEpoch(q.drawingBuffer)||!validEpoch(q.drawingBufferProjection)||q.runtime!==q.projection||q.runtime!==q.drawingBuffer||q.runtime!==q.drawingBufferProjection||q.runtime!==a.runtimeEpoch)return null;
  if(typeof mk!=='string'||!mk.length||typeof e.surfaceMappingKey!=='string'||typeof e.expectedSurfaceMappingKey!=='string'||e.surfaceMappingKey!==e.expectedSurfaceMappingKey)return null;
  if(e.surface==='player-head-warning'){
    if(!['P1','P2','P3'].includes(e.player)||e.target!==e.player||!primitiveFinite(e.warningSampleAtRaw)||e.sampleAt<e.warningSampleAtRaw)return null;
  }else if(e.surface==='enemy-target-label'){
    const target=targetFor(e.target7E);if(!target||e.target!==target||e.label!==(target==='P1'?'1P':target==='P2'?'2P':'3P'))return null;
  }else return null;
  return{authority:authorityText(a),runtime:q.runtime,projection:q.projection,drawingBuffer:q.drawingBuffer,drawingBufferProjection:q.drawingBufferProjection,mappingKey:mk,proofSessionId:e.proofSessionId}
}
const tupleKey=t=>t?[t.authority,t.runtime,t.projection,t.drawingBuffer,t.drawingBufferProjection,t.mappingKey,t.proofSessionId].join('|'):null;
function sameTuple(a,b){const x=tuple(a),y=tuple(b);return !!x&&!!y&&tupleKey(x)===tupleKey(y)}
function freshState(){return{player:[],enemy:[],bind:{player:'NOT_BOUND',enemy:'NOT_BOUND'},boundLifecycle:{player:null,enemies:{}},phases:Object.fromEntries(P.map(k=>[k,phase()])),authority:Object.fromEntries(A.map(k=>[k,auth()])),visual:{playerWarningAttached:false,enemyLabelsAttached:false,visibleRepeatableDrift:false,wrongIdentity:false,wrongTarget:false,staleCueObserved:false,operatorDecision:null,evidenceRefs:[]},fail:[],need:[],boundaries:{browserWofActuallyRun:false,liveWorkerWitnessVerified:false,syntheticEvidenceUsedAsLiveProof:false,manualAddressSelection:false,manualCoordinateTranscription:false,manualArithmetic:false,productSemanticsModified:false},safety:{readOnly:null,ramWrites:null,inputInjection:null,workerReplacement:null}}}
function resetEvidence(st,reason){const keep=st.state.boundaries;const safety=st.state.safety;st.state=freshState();st.state.boundaries.browserWofActuallyRun=keep.browserWofActuallyRun;st.state.boundaries.liveWorkerWitnessVerified=keep.liveWorkerWitnessVerified;st.state.safety=cp(safety);st.resetReason=reason||null}
function deactivateCap(st){if(st.cap){const m=capMeta.get(st.cap);if(m)m.active=false}st.cap=null;st.signerKey=null;st.authority=null;st.challenge=null}
function pub(s,st){const x=st.state;s.bind=cp(x.bind);s.phases=cp(x.phases);s.authority=cp(x.authority);s.visual=cp(x.visual);s.fail=cp(x.fail);s.need=cp(x.need);s.boundaries=cp(x.boundaries);s.safety=cp(x.safety)}
function eventForAuthority(e,sessionId,a){return !!e&&e.proofSessionId===sessionId&&sameAuthority(e.authority,a)}
class Session{
  constructor(id){this.id=String(id||'');this.start=new Date().toISOString();this.player=[];this.enemy=[];const st={trustedSignerPin:null,observedAuthority:null,challenge:null,cap:null,signerKey:null,authority:null,transactions:new Set(),state:freshState(),resetReason:null};priv.set(this,st);pub(this,st)}
  pinTrustedSigner(pin){const st=priv.get(this),v=typeof pin==='string'?pin.trim().toLowerCase():'';if(!validPin(v))return false;if(st.trustedSignerPin&&st.trustedSignerPin!==v){deactivateCap(st);resetEvidence(st,'SIGNER_PIN_CHANGED')}st.trustedSignerPin=v;pub(this,st);return true}
  trustedSignerPinned(){return validPin(priv.get(this)?.trustedSignerPin)}
  observedAuthority(){return cp(priv.get(this)?.observedAuthority||null)}
  observeAuthority(a){const st=priv.get(this);if(!validAuthority(a))return{ok:false,changed:false,reason:'INVALID_AUTHORITY'};const next=cp(a),prev=st.observedAuthority;st.observedAuthority=next;if(st.authority&& !sameAuthority(st.authority,next)){const workerChanged=st.authority.workerGeneration!==next.workerGeneration;deactivateCap(st);resetEvidence(st,'AUTHORITY_CHANGED');if(workerChanged)st.trustedSignerPin=null;pub(this,st);return{ok:true,changed:true,workerChanged,requiresFreshChallenge:true}}if(prev&&!sameAuthority(prev,next)&&st.challenge)st.challenge=null;pub(this,st);return{ok:true,changed:!!prev&&!sameAuthority(prev,next),workerChanged:!!prev&&prev.workerGeneration!==next.workerGeneration,requiresFreshChallenge:!!prev&&!sameAuthority(prev,next)}}
  beginLiveWitness(){const st=priv.get(this),b=new Uint8Array(24);if(!validPin(st.trustedSignerPin)||!validAuthority(st.observedAuthority)||!ROOT?.crypto?.getRandomValues)return null;ROOT.crypto.getRandomValues(b);st.challenge=[...b].map(x=>x.toString(16).padStart(2,'0')).join('');return{proofSessionId:this.id,nonce:st.challenge,authority:cp(st.observedAuthority)}}
  hasLiveWitness(){const st=priv.get(this);return !!st?.cap&&capValid(st.cap,this.id,st.authority)}
  capability(){const st=priv.get(this);return this.hasLiveWitness()?st.cap:null}
  currentAuthority(){return cp(priv.get(this)?.authority||null)}
  async acceptLiveWitness(w){const st=priv.get(this);if(!st?.challenge||!validPin(st.trustedSignerPin)||w?.proofSessionId!==this.id||w?.nonce!==st.challenge||!validAuthority(w?.authority)||!sameAuthority(w.authority,st.observedAuthority)||w?.signerFingerprint!==st.trustedSignerPin)return false;const fp=await publicKeyFingerprint(w.publicKey);if(fp!==st.trustedSignerPin)return false;const ok=await verify(w.publicKey,liveText(this.id,st.challenge,w.authority),w.signature);if(!ok)return false;deactivateCap(st);resetEvidence(st,'FRESH_LIVE_WITNESS');const cap=Object.freeze({});const meta={active:true,proofSessionId:this.id,authority:cp(w.authority),signerFingerprint:fp};capBrand.add(cap);capMeta.set(cap,meta);st.cap=cap;st.signerKey=w.publicKey;st.authority=cp(w.authority);st.challenge=null;st.state.boundaries.browserWofActuallyRun=true;st.state.boundaries.liveWorkerWitnessVerified=true;pub(this,st);return true}
  revokeLiveAuthority(reason='REVOKED'){const st=priv.get(this);deactivateCap(st);resetEvidence(st,reason);pub(this,st);return true}
  observeRuntimeSafety(s){const st=priv.get(this),safe={readOnly:s?.readOnly===true,ramWrites:s?.ramWrites===0?0:null,inputInjection:s?.inputInjection===false?false:null,workerReplacement:s?.workerReplacement===false?false:null};st.state.safety=safe;if(!(safe.readOnly===true&&safe.ramWrites===0&&safe.inputInjection===false&&safe.workerReplacement===false)&&!st.state.fail.includes('safety_boundary'))st.state.fail.push('safety_boundary');pub(this,st);return safe.readOnly===true&&safe.ramWrites===0&&safe.inputInjection===false&&safe.workerReplacement===false}
  record(es){const st=priv.get(this);for(const e of es||[]){const x=cp(e);x.proofSessionId=this.id;const pubArr=x.surface==='player-head-warning'?this.player:x.surface==='enemy-target-label'?this.enemy:null;if(!pubArr)continue;pubArr.push(cp(x));if(!this.hasLiveWitness()||!eventForAuthority(x,this.id,st.authority))continue;const t=tuple(x);if(x.decision==='ANCHORED_DRAW'&&!t)continue;const arr=x.surface==='player-head-warning'?st.state.player:st.state.enemy;arr.push(x);if(x.decision==='ANCHORED_DRAW')x.surface==='player-head-warning'?st.state.visual.playerWarningAttached=true:st.state.visual.enemyLabelsAttached=true;const k=ak(x.reason);if(k&&k!=='stale'){st.state.authority[k].coverage='PASS';st.state.authority[k].events.push(x);if(x.decision==='ANCHORED_DRAW'){st.state.authority[k].coverage='FAIL';st.state.authority[k].anchoredCueDuringInvalidAuthority=true;st.state.fail.push('authority_'+k)}}}pub(this,st);return this}
  markWindow(n,t0,t1,{player=false,enemy=false,ref=null}={}){const st=priv.get(this),x=st.state.phases[n];if(!this.hasLiveWitness()||!x||!primitiveFinite(t0)||!primitiveFinite(t1)||t1<t0)return false;const pe=st.state.player.filter(e=>e.at>=t0&&e.at<=t1&&tuple(e)),ee=st.state.enemy.filter(e=>e.at>=t0&&e.at<=t1&&tuple(e));let pair=null;if(player&&enemy){outer:for(const p of pe)for(const e of ee)if(sameTuple(p,e)){pair=[p,e];break outer}}const pOk=player?(enemy?!!pair:pe.length>0):false,eOk=enemy?(player?!!pair:ee.length>0):false;x.coverage=(player||enemy)&&(pOk||eOk)?'PASS':'NOT_OBSERVED';x.playerHeadWarning=player?(pOk?'PASS':'NOT_OBSERVED'):'NOT_OBSERVED';x.enemyTargetLabels=enemy?(eOk?'PASS':'NOT_OBSERVED'):'NOT_OBSERVED';const src=pair?.[0]||(player?pe[0]:ee[0]),k=tupleKey(tuple(src));if(k&&!x.authorityTuples.includes(k))x.authorityTuples.push(k);if(typeof ref==='string'&&ref&&!x.evidenceRefs.includes(ref))x.evidenceRefs.push(ref);pub(this,st);return player&&enemy?!!pair:(player?pOk:eOk)}
  markRetarget(ref='retarget'){const st=priv.get(this);if(!this.hasLiveWitness())return false;const q=st.state.enemy.filter(e=>tuple(e)&&e.decision==='ANCHORED_DRAW'&&e.lifecycleStable===true&&typeof e.lifecycleId==='string'&&e.target&&Number.isSafeInteger(e.lifecycleGeneration));const by=new Map;for(const e of q){const k=e.lifecycleId+'|'+e.lifecycleGeneration+'|'+e.enemyType;if(!by.has(k))by.set(k,[]);by.get(k).push(e)}for(const [k,a] of by){a.sort((u,v)=>u.at-v.at);for(let i=1;i<a.length;i++){const u=a[i-1],v=a[i];if(v.target!==u.target&&sameTuple(v,u)&&u.lifecycleId===v.lifecycleId&&u.lifecycleGeneration===v.lifecycleGeneration&&Number.isSafeInteger(u.lifecycleContinuitySamples)&&Number.isSafeInteger(v.lifecycleContinuitySamples)&&u.lifecycleContinuitySamples>=3&&v.lifecycleContinuitySamples>u.lifecycleContinuitySamples&&v.lifecycleContinuitySamples-u.lifecycleContinuitySamples<=6){const x=st.state.phases.liveRetarget;x.coverage='PASS';x.enemyTargetLabels='PASS';if(!x.evidenceRefs.includes(ref+':'+k))x.evidenceRefs.push(ref+':'+k);const tk=tupleKey(tuple(v));if(tk&&!x.authorityTuples.includes(tk))x.authorityTuples.push(tk);pub(this,st);return true}}}return false}
  confirmProfileBinding({authority,currentPlayer,currentEnemies=[],playerCalibration,enemyCalibrations=[]}={}){const st=priv.get(this);if(!this.hasLiveWitness()||!sameAuthority(authority,st.authority))return false;if(!playerCalibration||!currentPlayer||currentPlayer.proofLifecycleId!==playerCalibration.lifecycleId||currentPlayer.lifecycleGeneration!==playerCalibration.lifecycleGeneration||currentPlayer.lifecycleStable!==true)return false;const enemyMap={};for(const o of enemyCalibrations){const live=currentEnemies.filter(x=>x?.type===o.type&&x?.lifecycleStable===true);if(live.length!==1||live[0].proofLifecycleId!==o.lifecycleId||live[0].lifecycleGeneration!==o.lifecycleGeneration||live[0].slot!==o.slot)return false;enemyMap[String(o.type)]={id:o.lifecycleId,generation:o.lifecycleGeneration,slot:o.slot}}if(!Object.keys(enemyMap).length)return false;st.state.bind.player='PROVED';st.state.bind.enemy='PROVED';st.state.boundLifecycle.player={id:playerCalibration.lifecycleId,generation:playerCalibration.lifecycleGeneration};st.state.boundLifecycle.enemies=enemyMap;pub(this,st);return true}
  observeLifecycles({players={},enemies={}}={}){const st=priv.get(this),bp=st.state.boundLifecycle.player,be=st.state.boundLifecycle.enemies||{};if(st.state.bind.player!=='PROVED'&&st.state.bind.enemy!=='PROVED')return{ok:true,invalidated:false};let bad=false;if(bp){const p=players.P1;if(!p||p.proofLifecycleId!==bp.id||p.lifecycleGeneration!==bp.generation||p.lifecycleStable!==true)bad=true}const list=Array.isArray(enemies)?enemies:Object.values(enemies);for(const [type,b] of Object.entries(be)){const q=list.filter(x=>x?.type===Number(type)&&x?.lifecycleStable===true);if(q.length!==1||q[0].proofLifecycleId!==b.id||q[0].lifecycleGeneration!==b.generation||q[0].slot!==b.slot){bad=true;break}}if(bad){resetEvidence(st,'BOUND_LIFECYCLE_CHANGED');pub(this,st);return{ok:false,invalidated:true,reason:'BOUND_LIFECYCLE_CHANGED'}}return{ok:true,invalidated:false}}
  setVisualDecision(v){const st=priv.get(this);if(v!=='VISUAL_OK'&&v!=='FAIL_VISIBLE_REPEATABLE_DRIFT')return false;st.state.visual.operatorDecision=v;if(v!=='VISUAL_OK')st.state.visual.visibleRepeatableDrift=true;pub(this,st);return true}
  markVisualFailure(k){const st=priv.get(this);if(!['visibleRepeatableDrift','wrongIdentity','wrongTarget','staleCueObserved'].includes(k))return false;st.state.visual[k]=true;pub(this,st);return true}
  flagFailure(k){const st=priv.get(this);if(typeof k!=='string'||!k)return false;if(!st.state.fail.includes(k))st.state.fail.push(k);pub(this,st);return true}
  requireObservation(k){const st=priv.get(this);if(typeof k!=='string'||!k)return false;if(!st.state.need.includes(k))st.state.need.push(k);pub(this,st);return true}
  async acceptAuthorityGapWitness(w,events,{nowMs=Date.now()}={}){const st=priv.get(this);if(!this.hasLiveWitness()||!st.signerKey||!validAuthority(w?.authority)||w?.proofSessionId!==this.id||!sameAuthority(w.authority,st.authority)||w?.ok!==true||typeof w?.requestId!=='string'||w.requestId.length<1||typeof w?.transactionId!=='string'||w.transactionId.length<8||!primitiveFinite(w?.startedAt)||!primitiveFinite(w?.endedAt)||!primitiveFinite(w?.durationMs)||!primitiveFinite(nowMs)||w.durationMs<350||w.durationMs>900||w.endedAt<w.startedAt||w.endedAt-w.startedAt>w.durationMs+600||w.endedAt>nowMs+250||nowMs-w.endedAt>2000||st.transactions.has(w.transactionId))return false;const ok=await verify(st.signerKey,gapText(w),w.signature);if(!ok)return false;const accepted=[];for(const e of events||[]){if(e?.evidenceRef!=='authority-gap:'+w.requestId||!primitiveFinite(e?.at)||e.at<w.startedAt-100||e.at>w.endedAt+250||!sameAuthority(e?.authority,st.authority))continue;if(!((e.surface==='player-head-warning'&&e.decision==='FIXED_HUD')||(e.surface==='enemy-target-label'&&e.decision==='SUPPRESSED')))continue;const x=cp(e);x.proofSessionId=this.id;x.authorityTransactionId=w.transactionId;accepted.push(x)}if(!accepted.some(e=>e.surface==='player-head-warning')||!accepted.some(e=>e.surface==='enemy-target-label'))return false;st.transactions.add(w.transactionId);for(const x of accepted)(x.surface==='player-head-warning'?st.state.player:st.state.enemy).push(x);st.state.authority.stale.coverage='PASS';st.state.authority.stale.events.push(...accepted);pub(this,st);return true}
  status(){const st=priv.get(this);return{liveWitness:this.hasLiveWitness(),trustedSignerPinned:validPin(st.trustedSignerPin),acceptedAuthority:cp(st.authority),observedAuthority:cp(st.observedAuthority),bind:cp(st.state.bind),phases:cp(st.state.phases),authority:cp(st.state.authority),visual:cp(st.state.visual),safety:cp(st.state.safety),resetReason:st.resetReason}}
  verdict(){const st=priv.get(this),x=st.state;if(!this.hasLiveWitness())return'INCOMPLETE_OBSERVATION:live_runtime_witness';if(!(x.safety.readOnly===true&&x.safety.ramWrites===0&&x.safety.inputInjection===false&&x.safety.workerReplacement===false))return'FAILED_COMPONENT:safety_boundary';if(x.fail.length)return'FAILED_COMPONENT:'+x.fail[0].replace(/[^a-z0-9_-]+/gi,'_').toLowerCase();if(x.need.length)return'INCOMPLETE_OBSERVATION:'+x.need[0];if(x.bind.player!=='PROVED')return'INCOMPLETE_OBSERVATION:player_profile_binding';if(x.bind.enemy!=='PROVED')return'INCOMPLETE_OBSERVATION:enemy_profile_binding';if(!x.visual.playerWarningAttached)return'INCOMPLETE_OBSERVATION:player_warning';if(!x.visual.enemyLabelsAttached)return'INCOMPLETE_OBSERVATION:enemy_labels';for(const k of ['visibleRepeatableDrift','wrongIdentity','wrongTarget','staleCueObserved'])if(x.visual[k])return'FAILED_COMPONENT:'+k.replace(/[A-Z]/g,m=>'_'+m.toLowerCase());if(x.visual.operatorDecision!=='VISUAL_OK')return'INCOMPLETE_OBSERVATION:visual_confirmation';const req={fastHorizontal:['coverage','playerHeadWarning','enemyTargetLabels'],depthMovement:['coverage','playerHeadWarning'],fullJump:['coverage','playerHeadWarning'],rapidStageCameraScroll:['coverage','playerHeadWarning','enemyTargetLabels'],simultaneousPlayerCamera:['coverage','playerHeadWarning','enemyTargetLabels'],movingEnemy:['coverage','enemyTargetLabels'],liveRetarget:['coverage','enemyTargetLabels'],resizeFullscreenRemap:['coverage','playerHeadWarning','enemyTargetLabels']};for(const [n,fs] of Object.entries(req))if(fs.some(f=>x.phases[n][f]!=='PASS'))return'INCOMPLETE_OBSERVATION:'+n.replace(/[A-Z]/g,m=>'_'+m.toLowerCase());const se=x.authority.stale.events;if(x.authority.stale.coverage!=='PASS'||!se.every(e=>typeof e.authorityTransactionId==='string'&&sameAuthority(e.authority,st.authority)))return'INCOMPLETE_OBSERVATION:invalid_authority_no_draw';if(!se.some(e=>e.surface==='player-head-warning'&&e.decision==='FIXED_HUD'))return'INCOMPLETE_OBSERVATION:player_invalid_authority_fallback';if(!se.some(e=>e.surface==='enemy-target-label'&&e.decision==='SUPPRESSED'))return'INCOMPLETE_OBSERVATION:enemy_invalid_authority_no_draw';return'IMPLEMENTATION_READY'}
  terminal(repo,run,common){const st=priv.get(this),x=st.state,v=this.verdict();return{schema:S,evidenceClass:E,verdict:v,generatedAt:new Date().toISOString(),session:{proofSessionId:this.id,uninterrupted:true,startedAt:this.start,endedAt:new Date().toISOString(),liveWorkerWitnessVerified:this.hasLiveWitness(),acceptedAuthority:cp(st.authority),trustedSignerFingerprint:st.trustedSignerPin||null},repository:cp(repo),runtime:cp(run),commonProjection:cp(common),safety:cp(x.safety),surfaces:{playerHeadWarning:{profileBinding:x.bind.player,liveObserved:!!x.player.length,followVerdict:x.visual.playerWarningAttached?'PASS':'NOT_OBSERVED',failClosedVerdict:x.player.some(e=>e.decision==='FIXED_HUD')?'PASS':'NOT_OBSERVED',events:cp(x.player)},enemyTargetLabels:{profileBinding:x.bind.enemy,liveObserved:!!x.enemy.length,followVerdict:x.visual.enemyLabelsAttached?'PASS':'NOT_OBSERVED',failClosedVerdict:x.enemy.some(e=>e.decision==='SUPPRESSED')?'PASS':'NOT_OBSERVED',events:cp(x.enemy)}},phases:cp(x.phases),authorityWindows:cp(x.authority),visual:cp(x.visual),boundaries:cp(x.boundaries)}}
}
function shape(x){const er=[];if(x?.schema!==S)er.push('schema');if(x?.evidenceClass!==E)er.push('evidenceClass');if(!/^(IMPLEMENTATION_READY|FAILED_COMPONENT:[a-z0-9_-]+|INCOMPLETE_OBSERVATION:[a-z0-9_-]+)$/.test(x?.verdict||''))er.push('verdict');for(const k of P)if(!x?.phases?.[k])er.push('phase:'+k);for(const k of A)if(!x?.authorityWindows?.[k])er.push('authority:'+k);return{ok:!er.length,errors:er}}
return{EVIDENCE_CLASS:E,EVIDENCE_SCHEMA:S,ROM,PHASES:P,AUTHORITY_WINDOWS:A,validAuthority,authorityText,sameAuthority,publicKeyFingerprint,liveText,gapText,facts,playerProfile,enemyProfile,authorityKind:ak,mappingAuthority,expectedSurfaceMapping,playerEvents,enemyEvents,authorityTuple:tuple,sameAuthorityTuple:sameTuple,Session,shape};
});