(async()=>{
'use strict';
const VERSION='wof-alpha-v1-dual-live-proof-worker-authority-v2';
const CHANNEL='wof-alpha-v1-dual-live-proof-recovery-v2';
const G=globalThis,A=G.WOFAlphaProofAuthorityV2;
try{G.WOFAlphaV1DualProofWorker?.stop?.()}catch(_){}
if(!A||A.VERSION!=='WOF_ALPHA_AUTHORITY_V2')throw new Error('authority-v2 contract unavailable');
const boot=G.__WOF_ALPHA_DUAL_PROOF_BOOTSTRAP_V2,commit=boot?.manifest?.implementationCommit;
if(typeof commit!=='string'||!A.HEX40.test(commit))throw new Error('coherent proof manifest unavailable');
const signer=A.signerProvider(commit);
if(!signer)throw new Error('independent authority-v2 signer unavailable/stale');
const fp=await A.fingerprint(signer.publicKey);
if(fp!==signer.signerFingerprint)throw new Error('authority-v2 signer fingerprint mismatch');
const mod=G._0x515056,M=mod?.HEAPU8,R=mod?.HEAPU32?.[0x2e39e4>>>2]>>>0;
if(!M||!R)throw new Error('CPS RAM base unavailable');
const binding=G.__WOF_ALPHA_REAL_ADAPTER_BINDING||null;
if(!binding||binding.readOnly!==true)throw new Error('read-only real adapter binding unavailable');
const bc=new BroadcastChannel(CHANNEL);
const B=a=>M[R+((((a-0xFF0000)&0xffff)^1))]>>>0;
const U16=a=>((B(a)<<8)|B(a+1))>>>0;
const U32=a=>(B(a)*0x1000000+B(a+1)*0x10000+B(a+2)*0x100+B(a+3))>>>0;
const S32=a=>{const v=U32(a);return v>=0x80000000?v-0x100000000:v};
const F16=a=>S32(a)/65536;
const PLAYER_BASES={P1:0xFFBE1C,P2:0xFFBEFC,P3:0xFFBFDC};
const ENEMY=0xFFC0BC,STRIDE=0xE0,SLOTS=20;
const enc=s=>new TextEncoder().encode(s),hex=n=>{const b=new Uint8Array(n);G.crypto.getRandomValues(b);return[...b].map(x=>x.toString(16).padStart(2,'0')).join('')};
let running=true,timer=0,seq=0,lastProfiles=null,rebindBusy=false,snapBusy=false,lastAuthorityKey=null,lastSnapshot=null;
const witnessSessions=new Map(),playerContinuity=new Map(),enemyContinuity=Array.from({length:SLOTS},()=>({id:null,samples:0}));
function currentSigner(){const x=A.signerProvider(commit);return x&&x===signer?x:null}
function authority(){return currentSigner()?A.fromBinding(binding,signer.workerGeneration):null}
function resetAuthorityState(){witnessSessions.clear();lastProfiles=null;playerContinuity.clear();for(const x of enemyContinuity){x.id=null;x.samples=0}}
function syncAuthority(a){const k=A.authorityText(a);if(!k)return false;if(lastAuthorityKey&&lastAuthorityKey!==k)resetAuthorityState();lastAuthorityKey=k;return true}
async function sign(text){const x=currentSigner();if(!x||typeof text!=='string'||!text.length)throw new Error('trusted signer unavailable/stale');const sig=await x.sign(text);if(!(sig instanceof ArrayBuffer)&&!ArrayBuffer.isView(sig))throw new Error('invalid signer result');return sig}
function rawPlayers(at){const out={};for(const[name,a]of Object.entries(PLAYER_BASES)){const present=!!B(a);out[name]={present,x:present?F16(a+4):null,y:present?F16(a+8):null,z:present?F16(a+12):null,sampleAt:at,confidence:1}}return out}
function rawEnemies(at){const out=[];for(let i=0;i<SLOTS;i++){const a=ENEMY+i*STRIDE,type=U16(a+0x20),frameEnd=U32(a+0x12),next=U32(a+0x2C),present=type<47&&!!(frameEnd||next);if(!present)continue;out.push({slot:i,type,target7E:U16(a+0x7E),enemyX:F16(a+4),enemyY:F16(a+8),enemyZ:F16(a+12),sampleAt:at,confidence:1})}return out}
function continuity(cache,key,generation,token){const id=key+'@g'+generation+'#'+token;if(cache.id===id)cache.samples++;else{cache.id=id;cache.samples=1}return{id,samples:cache.samples}}
function failPlayer(raw,a){return{...raw,epoch:a?.runtimeEpoch||null,projectionEpoch:a?.runtimeEpoch||null,proofLifecycleId:null,lifecycleGeneration:null,lifecycleStable:false,lifecycleContinuitySamples:0,lifecycleContinuityProven:false,continuityToken:null}}
function failEnemy(raw,a){return{...raw,sourceId:'enemy-slot-'+raw.slot,epoch:a?.runtimeEpoch||null,projectionEpoch:a?.runtimeEpoch||null,proofLifecycleId:null,lifecycleGeneration:null,lifecycleStable:false,lifecycleContinuitySamples:0,lifecycleContinuityProven:false,continuityToken:null}}
async function lifecycleSnapshot(a,at,playersRaw,enemiesRaw){let env=null;try{env=A.lifecycleEnvelope(await signer.readLifecycleAuthority(),a,at)}catch(_){env=null}
const players={};for(const[name,r]of Object.entries(playersRaw)){const x=env?.players?.[name],rec=A.lifeRecord(x,{present:r.present});if(!rec?.xPresent){playerContinuity.delete(name);players[name]=failPlayer(r,a);continue}let c=playerContinuity.get(name);if(!c){c={id:null,samples:0};playerContinuity.set(name,c)}const q=continuity(c,name,rec.generation,rec.token);players[name]={...r,epoch:a.runtimeEpoch,projectionEpoch:a.runtimeEpoch,proofLifecycleId:q.id,lifecycleGeneration:rec.generation,lifecycleStable:q.samples>=3,lifecycleContinuitySamples:q.samples,lifecycleContinuityProven:true,continuityToken:rec.token}}
const enemies=[];for(const r of enemiesRaw){const x=env?.enemies?.find?.(v=>v?.slot===r.slot),rec=A.lifeRecord(x,{present:true,type:r.type,slot:r.slot}),cache=enemyContinuity[r.slot];if(!rec?.xPresent){cache.id=null;cache.samples=0;enemies.push(failEnemy(r,a));continue}const q=continuity(cache,'enemy-slot-'+r.slot,rec.generation,rec.token);enemies.push({...r,sourceId:'enemy-slot-'+r.slot,epoch:a.runtimeEpoch,projectionEpoch:a.runtimeEpoch,proofLifecycleId:q.id,lifecycleGeneration:rec.generation,lifecycleStable:q.samples>=3,lifecycleContinuitySamples:q.samples,lifecycleContinuityProven:true,continuityToken:rec.token})}
const liveSlots=new Set(enemiesRaw.map(x=>x.slot));for(let i=0;i<SLOTS;i++)if(!liveSlots.has(i)){enemyContinuity[i].id=null;enemyContinuity[i].samples=0}
return{players,enemies,lifecycleAuthorityFresh:!!env}}
function commonCamera(){try{const s=G.WOFHUDANCHOR?.result?.(),c=s?.lockedCamera||s?.camera?.selected||null;return c?{address:c.address??null,read:c.read??'u16be',value:A.finite(c.value)?c.value:null}:null}catch(_){return null}}
function post(kind,payload={}){try{bc.postMessage({schema:CHANNEL,kind,version:VERSION,at:Date.now(),...payload})}catch(_){}}
async function snapshot(){if(snapBusy||!running)return;snapBusy=true;try{const at=Date.now(),a=authority();if(!a||!syncAuthority(a)){post('authority-v2-error',{reason:'INVALID_OR_STALE_AUTHORITY'});return}const rp=rawPlayers(at),re=rawEnemies(at),life=await lifecycleSnapshot(a,at,rp,re);lastSnapshot={at,authority:a,...life};post('live-snapshot',{seq:++seq,authority:a,binding:{session:a.session,workerGeneration:a.workerGeneration,runtimeEpoch:a.runtimeEpoch,pairGeneration:a.pairGeneration,pairNonce:a.pairNonce,launcherIdentitySha:a.launcherIdentitySha,channel:a.channel},safety:{readOnly:binding.readOnly===true,ramWrites:0,inputInjection:false,workerReplacement:false},camera:commonCamera(),players:life.players,enemies:life.enemies,lifecycleAuthorityFresh:life.lifecycleAuthorityFresh,alphaTransportStatus:G.__WOF_ALPHA_REAL_TRANSPORT?.status?.()||null})}finally{snapBusy=false}}
async function witness(m){const a=authority();if(!a||!syncAuthority(a)||!A.sameAuthority(m?.authority,a))return;if(typeof m?.proofSessionId!=='string'||m.proofSessionId.length<8||typeof m?.nonce!=='string'||!A.HEX32.test(m.nonce))return;const text=A.liveText(m.proofSessionId,m.nonce,a);if(!text)return;try{const signature=await sign(text);witnessSessions.set(m.proofSessionId,{nonce:m.nonce,createdAt:Date.now(),authorityKey:A.authorityText(a)});post('live-witness',{proofSessionId:m.proofSessionId,nonce:m.nonce,authority:a,signerFingerprint:signer.signerFingerprint,publicKey:signer.publicKey,signature})}catch(error){post('live-witness-error',{proofSessionId:m.proofSessionId,reason:String(error?.message||error)})}}
function liveSessionFor(payload){const a=authority(),x=witnessSessions.get(payload?.proofSessionId);return a&&x&&Date.now()-x.createdAt<15*60*1000&&payload?.witnessNonce===x.nonce&&x.authorityKey===A.authorityText(a)?x:null}
function currentLifeMatchesProfile(p,e){if(!lastSnapshot)return false;const cp=lastSnapshot.players?.P1;if(!cp?.lifecycleStable||cp.proofLifecycleId!==p?.proofLifecycle?.id||cp.lifecycleGeneration!==p?.proofLifecycle?.generation)return false;const byType=e?.proofLifecycleByType||{};for(const[type,v]of Object.entries(byType)){const q=(lastSnapshot.enemies||[]).filter(x=>x.type===Number(type)&&x.lifecycleStable);if(q.length!==1||q[0].proofLifecycleId!==v?.id||q[0].lifecycleGeneration!==v?.generation||q[0].slot!==v?.slot)return false}return Object.keys(byType).length>0}
function validCandidateProfiles(payload){const a=authority(),p=payload?.playerProfile,e=payload?.enemyProfile;if(!a||!liveSessionFor(payload))return{ok:false,reason:'LIVE_WORKER_CAPABILITY_REQUIRED'};if(!p||!e||p.proofOnlyRuntimeBinding!==true||e.proofOnlyRuntimeBinding!==true)return{ok:false,reason:'PROOF_ONLY_PROFILE_TAG_MISSING'};if(p.proofSessionId!==payload.proofSessionId||e.proofSessionId!==payload.proofSessionId)return{ok:false,reason:'PROOF_SESSION_MISMATCH'};if(!A.sameAuthority(p.proofAuthority,a)||!A.sameAuthority(e.proofAuthority,a))return{ok:false,reason:'PROFILE_AUTHORITY_MISMATCH'};if(!currentLifeMatchesProfile(p,e))return{ok:false,reason:'PROFILE_LIFECYCLE_MISMATCH'};if(p.evidenceClass!=='REAL_BROWSER_WOF_BOUNDED_DYNAMIC_LIVE_PROOF'||e.evidenceClass!=='REAL_BROWSER_WOF_BOUNDED_DYNAMIC_LIVE_PROOF')return{ok:false,reason:'REAL_LIVE_EVIDENCE_GUARD_MISSING'};const pv=G.WOFAlphaPlayerHeadWarning?.validateProofProfile?.(p),ev=G.WOFAlphaEnemyTargetLabels?.validateProofProfile?.(e);if(!pv?.ok)return{ok:false,reason:pv?.reason||'PLAYER_PROFILE_REJECTED'};if(!ev?.ok)return{ok:false,reason:ev?.reason||'ENEMY_PROFILE_REJECTED'};if(!G.WOFAlphaTransportAuthority?.install)return{ok:false,reason:'ALPHA_TRANSPORT_INSTALL_API_UNAVAILABLE'};return{ok:true,authority:a}}
async function reinstallWithProfiles(payload){if(rebindBusy)return{ok:false,reason:'REBIND_BUSY'};const valid=validCandidateProfiles(payload);if(!valid.ok)return valid;rebindBusy=true;const originalFetch=G.fetch;if(typeof originalFetch!=='function'){rebindBusy=false;return{ok:false,reason:'FETCH_UNAVAILABLE'}}const playerProfile=JSON.parse(JSON.stringify(payload.playerProfile)),enemyProfile=JSON.parse(JSON.stringify(payload.enemyProfile)),responseFor=value=>({ok:true,status:200,json:async()=>JSON.parse(JSON.stringify(value)),text:async()=>JSON.stringify(value)});G.fetch=async function(input,init){const url=String(input?.url||input||'');if(url.includes('/product/alpha/wof_alpha_player_head_projection.json'))return responseFor(playerProfile);if(url.includes('/product/alpha/wof_alpha_enemy_head_projection.json'))return responseFor(enemyProfile);return originalFetch.call(this,input,init)};try{const status=await G.WOFAlphaTransportAuthority.install(G,binding);lastProfiles={playerProfile,enemyProfile,proofId:payload.proofId||playerProfile.proofId,proofSessionId:payload.proofSessionId,witnessNonce:payload.witnessNonce,authority:A.clone(valid.authority),installedAt:Date.now()};return{ok:true,status,lastProfiles:{proofId:lastProfiles.proofId,proofSessionId:lastProfiles.proofSessionId,installedAt:lastProfiles.installedAt}}}catch(error){return{ok:false,reason:String(error?.message||error)}}finally{G.fetch=originalFetch;rebindBusy=false}}
async function authorityGap(ms,requestId,proofSessionId,witnessNonce){const a0=authority();if(!lastProfiles||!a0||!A.sameAuthority(lastProfiles.authority,a0)||lastProfiles.proofSessionId!==proofSessionId||lastProfiles.witnessNonce!==witnessNonce||!liveSessionFor({proofSessionId,witnessNonce}))return{ok:false,reason:'NO_LIVE_BOUND_PROFILES'};const duration=Math.max(350,Math.min(900,typeof ms==='number'&&Number.isFinite(ms)?ms:450)),startedAt=Date.now(),transactionId='gap-'+hex(16);try{G.__WOF_ALPHA_REAL_TRANSPORT?.stop?.('proof-authority-gap')}catch(_){}post('authority-gap-start',{durationMs:duration,requestId,transactionId,authority:a0});await new Promise(resolve=>setTimeout(resolve,duration));const a1=authority();if(!A.sameAuthority(a0,a1))return{ok:false,reason:'AUTHORITY_CHANGED_DURING_GAP',transactionWitness:null};const result=await reinstallWithProfiles({...lastProfiles,proofSessionId,witnessNonce,proofId:lastProfiles.proofId}),endedAt=Date.now();if(!result.ok)return{...result,transactionWitness:null};const w={proofSessionId,requestId,transactionId,startedAt,endedAt,durationMs:duration,ok:true,authority:a1},text=A.gapText(w);if(!text)return{ok:false,reason:'INVALID_GAP_WITNESS',transactionWitness:null};w.signature=await sign(text);post('authority-gap-end',{durationMs:duration,requestId,transactionId,result,authority:a1});return{...result,transactionWitness:w}}
bc.onmessage=e=>{const m=e.data;if(m?.schema!==CHANNEL)return;if(m.kind==='request-snapshot')snapshot().catch(()=>{});else if(m.kind==='live-witness-challenge')witness(m);else if(m.kind==='bind-live-profiles')reinstallWithProfiles(m).then(result=>post('bind-live-profiles-result',{requestId:m.requestId||null,result}));else if(m.kind==='exercise-authority-gap')authorityGap(m.durationMs,m.requestId||'',m.proofSessionId,m.witnessNonce).then(result=>post('exercise-authority-gap-result',{requestId:m.requestId||null,result}))};
timer=setInterval(()=>snapshot().catch(e=>post('authority-v2-error',{reason:String(e?.message||e)})),50);await snapshot();
Object.defineProperty(G,'WOFAlphaV1DualProofWorker',{value:Object.freeze({version:VERSION,status(){return{running,seq,rebindBusy,binding:!!binding,workerGeneration:signer.workerGeneration,signerFingerprint:signer.signerFingerprint,witnessSessions:witnessSessions.size,lastProfiles:lastProfiles?{proofId:lastProfiles.proofId,proofSessionId:lastProfiles.proofSessionId,installedAt:lastProfiles.installedAt}:null}},stop(){if(!running)return;running=false;if(timer)clearInterval(timer);try{bc.close()}catch(_){}}}),writable:false,configurable:true});
console.log('✅ Alpha V1 dual live-proof Worker observer ready · authority-v2');
})().catch(e=>console.error('❌ Alpha V1 dual proof Worker failed closed',e));
