(async()=>{
'use strict';
const C=window.WOFAlphaDualProofCore,A=window.WOFAlphaProofAuthorityV2,CH='wof-alpha-v1-dual-live-proof-recovery-v2';
if(!C||!A||A.VERSION!=='WOF_ALPHA_AUTHORITY_V2'||!window.WOFHUDANCHOR?.result||!window.WOFAlphaPlayerHeadWarning?.buildPlan||!window.WOFAlphaEnemyTargetLabels?.buildPlan||!window.WOFALPHAHUD?.status)throw new Error('authority-v2/common/Alpha helpers/HUD not ready');
try{window.WOFAlphaDualProof?.stop?.()}catch(_){}
const boot=window.__WOF_ALPHA_DUAL_PROOF_BOOTSTRAP_V2,manifest=boot?.manifest,commit=manifest?.implementationCommit;
if(!boot?.preflightOk||typeof commit!=='string'||!A.HEX40.test(commit))throw new Error('coherent proof bootstrap unavailable');
const initialTrust=A.trustedRoot(commit);
if(!initialTrust)throw new Error('independent trusted authority root unavailable/stale');
const cv=window.I_GF1TC||document.getElementById('whathis'),gl=window.I_fdC8Q;if(!cv||!gl)throw new Error('WebGL canvas unavailable');
const bc=new BroadcastChannel(CH),rand=()=>{const b=new Uint8Array(16);crypto.getRandomValues(b);return[...b].map(x=>x.toString(16).padStart(2,'0')).join('')},id='dual-'+rand(),proofId='dual-proof-'+rand(),s=new C.Session(id),clone=x=>x==null?x:JSON.parse(JSON.stringify(x)),fin=v=>typeof v==='number'&&Number.isFinite(v);
if(!s.pinTrustedSigner(initialTrust.signerFingerprint))throw new Error('trusted signer pin rejected');
let run=true,snap=null,snaps=[],body=null,bound=false,cand=null,mode=null,seq=0,status0=null,pending=new Map(),enemyCaps=new Map(),lastP=0,lastE=0,gapCapture=null,currentChallenge=null,challengeAt=0,witnessNonce=null;
const origP=window.WOFAlphaPlayerHeadWarning.buildPlan,origE=window.WOFAlphaEnemyTargetLabels.buildPlan;
function layout(){const W=gl.drawingBufferWidth||cv.width,H=gl.drawingBufferHeight||cv.height,v=Array.from(gl.getParameter(gl.VIEWPORT));return{drawingBufferWidth:W,drawingBufferHeight:H,viewport:{x:v[0],y:H-(v[1]+v[3]),width:v[2],height:v[3]},dpr:devicePixelRatio||1,fullscreen:!!document.fullscreenElement}}
const initialLayout=layout();
function commonRaw(){try{return window.WOFHUDANCHOR.result()}catch(_){return null}}
function commonOut(r=commonRaw()){const p=r?.projection||{},e=r?.evidence||{},n=p.native||{},cam=p.camera||{},d=p.drawingBuffer||{};return{verdict:r?.verdict==='IMPLEMENTATION_READY'?'IMPLEMENTATION_READY':'FAILED',proofId,projectionVersion:'dual-proof-authority-v2',camera:{address:cam.address??null,read:cam.read||'u16be',qualityPassed:!!r?.camera?.quality?.ok,locked:!!cam.address},native:{width:n.width??384,height:n.height??224,xFormula:n.xFormula||'worldX-camera+xBias',xBias:n.xBias??0,yModel:n.yModel||'Y',yFormula:n.yFormula||'worldY+yBias',yBiasOrAnchorOffset:n.aboveCharacterOffsetNative??n.yBias??0},drawingBuffer:{source:d.source||'live WebGL VIEWPORT',formula:d.formula||'',layoutChangeCount:e?.layout?.changeCount||0,recovered:!!e?.layout?.recovered},objectiveEvidence:{worldXExcursion:e?.ranges?.worldX||0,cameraExcursion:e?.ranges?.camera||0,floorYExcursion:e?.ranges?.floorY||0,zExcursion:e?.ranges?.z||0,webglHookCount:e?.webgl?.hookCount||0,markerDrawCount:e?.webgl?.markerDrawCount||0}}}
function native(cx,cy){const r=cv.getBoundingClientRect(),L=layout(),v=L.viewport,x=(cx-r.left)/r.width*L.drawingBufferWidth,y=(cy-r.top)/r.height*L.drawingBufferHeight;if(x<v.x||x>v.x+v.width||y<v.y||y>v.y+v.height)return null;return{x:(x-v.x)/v.width*384,y:(y-v.y)/v.height*224}}
function repo(){const p={},q={};for(const[k,v]of Object.entries(manifest?.productBlobs||{}))p[k]=v.sha;for(const[k,v]of Object.entries(manifest?.proofToolBlobs||{}))q[k]=v.sha;return{head:boot?.head||commit,implementationCommit:commit,productBlobs:p,proofToolBlobs:q}}
function runtime(){const a=s.currentAuthority()||snap?.authority||null;return{romSha256:a?.launcherIdentitySha||manifest?.romSha256||C.ROM,runtimeEpoch:a?.runtimeEpoch||null,projectionEpoch:a?.runtimeEpoch||null,workerGeneration:a?.workerGeneration??null,pairGeneration:a?.pairGeneration??null,pairNonce:a?.pairNonce??null,browserBuild:navigator.userAgent||null,wofBuild:null,initialLayout,finalLayout:layout()}}
function request(kind,x={}){const requestId='r'+(++seq)+'-'+Date.now(),promise=new Promise((res,rej)=>{const t=setTimeout(()=>{pending.delete(requestId);rej(Error(kind+' timeout'))},7000);pending.set(requestId,{res:v=>{clearTimeout(t);res(v)}})});bc.postMessage({schema:CH,kind,requestId,...x});return{requestId,promise}}
function strictLife(v){const ok=v?.lifecycleStable===true&&v?.lifecycleContinuityProven===true&&typeof v?.continuityToken==='string'&&A.HEX32.test(v.continuityToken)&&typeof v?.proofLifecycleId==='string'&&v.proofLifecycleId.length>=4&&Number.isSafeInteger(v?.lifecycleGeneration)&&v.lifecycleGeneration>0;return{...v,lifecycleStable:ok,lifecycleContinuityProven:ok,proofLifecycleId:ok?v.proofLifecycleId:null,lifecycleGeneration:ok?v.lifecycleGeneration:null,lifecycleContinuitySamples:ok&&Number.isSafeInteger(v.lifecycleContinuitySamples)?v.lifecycleContinuitySamples:0,continuityToken:ok?v.continuityToken:null}}
function proofContext(){const players={},enemies={};for(const[k,v]of Object.entries(snap?.players||{}))players[k]=strictLife(v);for(const e of snap?.enemies||[])enemies[String(e.slot)]=strictLife(e);return{players,enemies,authority:s.currentAuthority()}}
function currentPlayer(){return strictLife(snap?.players?.P1||{})}
function currentEnemies(){return(snap?.enemies||[]).map(strictLife)}
function clearCalibration(reason){body=null;enemyCaps.clear();cand=null;bound=false;if(reason)note?.('authority/lifecycle invalidated: '+reason)}
function reconcileCalibration(){const p=currentPlayer();if(body&&(body.lifecycleId!==p.proofLifecycleId||body.lifecycleGeneration!==p.lifecycleGeneration))clearCalibration('PLAYER_LIFECYCLE_CHANGED');for(const[type,rows]of [...enemyCaps]){const live=currentEnemies().filter(x=>x.type===type&&x.lifecycleStable);const keep=live.length===1?rows.filter(r=>r.lifecycleId===live[0].proofLifecycleId&&r.lifecycleGeneration===live[0].lifecycleGeneration):[];if(keep.length)enemyCaps.set(type,keep);else enemyCaps.delete(type)}}
function currentTrust(){const x=A.trustedRoot(commit);return x&&x.signerFingerprint===initialTrust.signerFingerprint&&x.authorityRootId===initialTrust.authorityRootId?x:null}
function ensureChallenge(force=false){if(s.hasLiveWitness())return true;if(!currentTrust()){s.revokeLiveAuthority('TRUST_ROOT_STALE');currentChallenge=null;witnessNonce=null;bound=false;return false}if(!s.trustedSignerPinned()&&!s.pinTrustedSigner(initialTrust.signerFingerprint))return false;const now=Date.now();if(!force&&currentChallenge&&now-challengeAt<2000)return true;const q=s.beginLiveWitness();if(!q)return false;currentChallenge=q;challengeAt=now;bc.postMessage({schema:CH,kind:'live-witness-challenge',...q});return true}
function acceptSnapshotAuthority(m){if(!A.validAuthority(m?.authority))return false;const r=s.observeAuthority(m.authority);if(!r.ok)return false;if(r.changed){clearCalibration('AUTHORITY_CHANGED');currentChallenge=null;witnessNonce=null;if(!s.trustedSignerPinned())s.pinTrustedSigner(initialTrust.signerFingerprint)}if(!s.observeRuntimeSafety(m.safety))return false;const lc=s.observeLifecycles({players:m.players||{},enemies:m.enemies||[]});if(lc?.invalidated){clearCalibration(lc.reason||'BOUND_LIFECYCLE_CHANGED')}return true}
window.WOFAlphaPlayerHeadWarning.buildPlan=function(a){const p=origP.call(this,a);try{const es=C.playerEvents(a,p,Date.now(),proofContext());s.record(es);if(es.some(e=>e.decision==='ANCHORED_DRAW'&&C.authorityTuple(e))){lastP=Date.now()}phases()}catch(_){}return p};
window.WOFAlphaEnemyTargetLabels.buildPlan=function(a){const p=origE.call(this,a);try{const es=C.enemyEvents(a,p,Date.now(),proofContext());s.record(es);if(es.some(e=>e.decision==='ANCHORED_DRAW'&&C.authorityTuple(e))){lastE=Date.now()}s.markRetarget();multi();phases()}catch(_){}return p};
const span=a=>a.length?Math.max(...a)-Math.min(...a):0,vals=(x,f)=>x.map(f).filter(fin);
function mark(n,t0,t1,player,enemy){return s.markWindow(n,t0,t1,{player,enemy,ref:n+':'+t1})}
function stablePlayerRows(rows){const p=currentPlayer(),lid=p.proofLifecycleId;if(!lid)return[];return rows.filter(x=>strictLife(x.players?.P1||{}).proofLifecycleId===lid&&strictLife(x.players?.P1||{}).lifecycleStable)}
function phases(){if(!bound||snaps.length<2)return;const now=Date.now(),r=stablePlayerRows(snaps.filter(x=>x.at>=now-1200)),l=stablePlayerRows(snaps.filter(x=>x.at>=now-2600));if(r.length>=2){const px=vals(r,x=>x.players?.P1?.x),py=vals(r,x=>x.players?.P1?.y),ca=vals(r,x=>x.camera?.value);if(span(px)>=24)mark('fastHorizontal',r[0].at,now,true,true);if(span(py)>=8)mark('depthMovement',r[0].at,now,true,false);if(span(ca)>=6)mark('rapidStageCameraScroll',r[0].at,now,true,true);if(span(px)>=8&&span(ca)>=4)mark('simultaneousPlayerCamera',r[0].at,now,true,true)}if(l.length>5){const z=vals(l,x=>x.players?.P1?.z);if(z.length>5&&span(z)>=8&&Math.abs(z[0]-Math.min(...z))<=2&&Math.abs(z.at(-1)-Math.min(...z))<=2)mark('fullJump',l[0].at,now,true,false)}const er=snaps.filter(x=>x.at>=now-1200),by=new Map;for(const x of er)for(const e of x.enemies||[]){const q=strictLife(e);if(!q.lifecycleStable)continue;if(!by.has(q.proofLifecycleId))by.set(q.proofLifecycleId,[]);by.get(q.proofLifecycleId).push({...q,at:x.at})}for(const q of by.values())if(q.length>=3&&(span(vals(q,e=>e.enemyX))>=8||span(vals(q,e=>e.enemyY))>=6)){mark('movingEnemy',q[0].at,now,false,true);break}const cr=commonRaw(),pm=new Set(s.player.filter(e=>C.authorityTuple(e)).map(e=>e.mappingKey)),em=new Set(s.enemy.filter(e=>C.authorityTuple(e)).map(e=>e.mappingKey));if(cr?.evidence?.layout?.changeCount>0&&cr?.evidence?.layout?.recovered&&pm.size>1&&em.size>1)mark('resizeFullscreenRemap',Math.max(0,now-5000),now,true,true)}
function multi(){const q=s.enemy.filter(e=>C.authorityTuple(e));for(const x of q)if(new Set(q.filter(e=>Math.abs(e.at-x.at)<=40).map(e=>e.actorIdentity)).size>=2){s.markWindow('multiEnemy',x.at-40,x.at+40,{enemy:true,ref:'multi'});return}}
function baseY(x,m){return m==='Y-Z'?x.y-x.z:m==='Y+Z'?x.y+x.z:x.y}function eBase(x,m){return m==='Y-Z'?x.enemyY-x.enemyZ:m==='Y+Z'?x.enemyY+x.enemyZ:x.enemyY}
function enemyObs(){const out=[];for(const[type,q]of enemyCaps){const groups=new Map;for(const x of q){if(!groups.has(x.lifecycleId))groups.set(x.lifecycleId,[]);groups.get(x.lifecycleId).push(x)}if(groups.size!==1)continue;const a=[...groups.values()][0],current=currentEnemies().find(e=>e.proofLifecycleId===a[0]?.lifecycleId&&e.type===type&&e.lifecycleStable);if(!current||a.length<2||a.at(-1).observedAt-a[0].observedAt<60)continue;const v=a.map(x=>x.enemyHeadOffsetNative),spread=Math.max(...v)-Math.min(...v);if(spread>4)continue;out.push({...a.at(-1),enemyHeadOffsetNative:v.reduce((u,v)=>u+v,0)/v.length,stable:true,captureCount:a.length,spreadNative:spread})}return out}
function nearestHeadLifecycle(at){if(!fin(at))return null;let best=null,d=Infinity;for(const x of snaps){const p=strictLife(x.players?.P1||{}),dd=Math.abs(x.at-at);if(dd<d&&dd<=150&&p?.present&&p.lifecycleStable){best=p;d=dd}}return best}
function click(e){if(!mode||e.target?.closest?.('#dual-proof'))return;const n=native(e.clientX,e.clientY),r=commonRaw();if(!n||!snap||Date.now()-snap.at>250||r?.verdict!=='IMPLEMENTATION_READY'||!s.hasLiveWitness()){note('采集失败：live authority/common/snapshot 不新鲜');mode=null;return}const f=C.facts(r),cam=snap.camera?.value;if(!f||!fin(cam)){note('common camera/projection 不完整');mode=null;return}if(mode==='body'){const p=currentPlayer(),hy=r.calibration?.nativeClick?.y,head=nearestHeadLifecycle(r.calibration?.at);if(!p?.present||!p.lifecycleStable||!head||head.proofLifecycleId!==p.proofLifecycleId||head.continuityToken!==p.continuityToken||!fin(hy)){note('P1 head/body lifecycle authority 不同；重做同生命周期 calibration');mode=null;return}const y=n.y-baseY(p,f.yModel),h=n.y-hy,ok=fin(y)&&fin(h)&&h>=0&&Math.abs(n.x-(p.x-cam+f.xBias))<=28;body={stable:ok,bodyYBiasNative:y,headClearanceNative:h,validationBounds:{minX:0,maxX:383,minY:0,maxY:223},proofId,proofSessionId:id,projectionVersion:'dual-proof-authority-v2',observedAt:Date.now(),lifecycleId:p.proofLifecycleId,headLifecycleId:head.proofLifecycleId,lifecycleGeneration:p.lifecycleGeneration,continuityToken:p.continuityToken};note(ok?'P1 authority-v2 lifecycle calibration 已采集':'P1 body click 不稳定，fail-closed')}else{const q=currentEnemies().filter(x=>x.lifecycleStable).map(x=>({x,dx:Math.abs(x.enemyX-cam+f.xBias-n.x)})).filter(x=>x.dx<=28).sort((a,b)=>a.dx-b.dx);if(!q.length||(q[1]&&q[1].dx-q[0].dx<4)){note('敌人重叠/identity authority 不唯一，未采集');mode=null;return}const x=q[0].x,o={stable:true,type:x.type,enemyHeadOffsetNative:n.y-eBase(x,f.yModel),proofId,proofSessionId:id,observedAt:Date.now(),lifecycleId:x.proofLifecycleId,lifecycleGeneration:x.lifecycleGeneration,continuityToken:x.continuityToken,slot:x.slot,target7E:x.target7E};if(!enemyCaps.has(x.type))enemyCaps.set(x.type,[]);enemyCaps.get(x.type).push(o);note('enemy type '+x.type+' lifecycle '+x.proofLifecycleId+' capture '+enemyCaps.get(x.type).length)}mode=null;render()}
addEventListener('click',click,true);
async function bind(){const cap=s.capability(),a=s.currentAuthority(),p=currentPlayer(),en=currentEnemies();if(!cap||!a||!currentTrust()){note('live trusted authority 未建立，拒绝 bind');return}const r=commonRaw(),eo=enemyObs(),meta={proofId,proofSessionId:id,projectionVersion:'dual-proof-authority-v2',liveCapability:cap,authority:a,currentLifecycle:p,currentEnemies:en},pp=C.playerProfile(r,body,meta),ep=C.enemyProfile(r,eo,{...meta,romSha256:a.launcherIdentitySha});if(!pp.ok||!ep.ok){note('profile binder fail-closed: '+(pp.reason||ep.reason));return}cand={playerProfile:pp.profile,enemyProfile:ep.profile};try{const q=request('bind-live-profiles',{...cand,proofId,proofSessionId:id,witnessNonce,authority:a}),x=await q.promise;if(!x?.result?.ok){bound=false;note('rebind 失败: '+(x?.result?.reason||'?'));return}bound=s.confirmProfileBinding({authority:a,currentPlayer:p,currentEnemies:en,playerCalibration:body,enemyCalibrations:eo});note(bound?'proof-only live profile 已 authority-v2 lifecycle bind':'core profile binding fail-closed')}catch(e){bound=false;note(e.message)}render()}
async function gap(){if(!bound||!s.hasLiveWitness()||!currentTrust()||Date.now()-lastP>2000||Date.now()-lastE>2000){note('先完成 rooted bind 且同时出现 player warning + enemy label');return}const a=s.currentAuthority(),q=request('exercise-authority-gap',{durationMs:450,proofSessionId:id,witnessNonce,authority:a});gapCapture={requestId:q.requestId,authority:a,events:[],seen:new Set};try{const x=await q.promise,g=gapCapture;gapCapture=null;const ok=await s.acceptAuthorityGapWitness(x?.result?.transactionWitness,g?.events||[],{nowMs:Date.now()});note(ok?'authority-v2 gap transaction witness PASS':'authority gap replay/stale/fallback 不完整，fail-closed')}catch(e){gapCapture=null;note(e.message)}render()}
function hud(){let x;try{x=window.WOFALPHAHUD.status()}catch(_){return}if(!currentTrust()&&s.hasLiveWitness()){s.revokeLiveAuthority('TRUST_ROOT_STALE');clearCalibration('TRUST_ROOT_STALE');currentChallenge=null;witnessNonce=null}if(bound&&status0&&gapCapture){const ep=gapCapture.authority?.runtimeEpoch,ref='authority-gap:'+gapCapture.requestId,authority=gapCapture.authority;if(status0.enemyTargetLabels?.count>0&&!x.enemyTargetLabels?.connected&&!gapCapture.seen.has('enemy')){gapCapture.seen.add('enemy');gapCapture.events.push({at:Date.now(),surface:'enemy-target-label',actorIdentity:null,player:null,target7E:null,target:null,label:null,sampleAt:Date.now(),decision:'SUPPRESSED',reason:'STALE_OR_MISSING_MARKERS',evidenceRef:ref,authority,epochs:{runtime:ep,projection:ep,drawingBuffer:ep,drawingBufferProjection:ep},mappingKey:null})}if(status0.playerHeadWarning?.anchored>0&&!x.playerHeadWarning?.connected&&x.playerHeadWarning?.fixed>0&&!gapCapture.seen.has('player')){gapCapture.seen.add('player');const p=currentPlayer();gapCapture.events.push({at:Date.now(),surface:'player-head-warning',actorIdentity:p.proofLifecycleId||null,lifecycleId:p.proofLifecycleId||null,lifecycleGeneration:p.lifecycleGeneration??null,lifecycleStable:false,player:'P1',target7E:null,target:'P1',label:'危险',sampleAt:Date.now(),decision:'FIXED_HUD',reason:'STALE_PLAYER_SPATIAL_TRANSPORT_GAP',evidenceRef:ref,authority,epochs:{runtime:ep,projection:ep,drawingBuffer:ep,drawingBufferProjection:ep},mappingKey:null})}}status0=x}
const timer=setInterval(hud,50),challengeTimer=setInterval(()=>ensureChallenge(false),500);
bc.onmessage=async e=>{const m=e.data;if(m?.schema!==CH)return;if(m.kind==='live-snapshot'){if(!acceptSnapshotAuthority(m)){if(s.hasLiveWitness())s.revokeLiveAuthority('INVALID_RUNTIME_AUTHORITY');bound=false;render();return}snap=m;snaps.push(m);if(snaps.length>240)snaps.shift();reconcileCalibration();ensureChallenge(false);phases();render();return}if(m.kind==='live-witness'){if(!currentTrust())return;if(await s.acceptLiveWitness(m)){witnessNonce=m.nonce;currentChallenge=null;note('independently rooted live Worker capability ✓')}render();return}const p=pending.get(m.requestId);if(p){pending.delete(m.requestId);p.res(m)}};bc.postMessage({schema:CH,kind:'request-snapshot'});
const box=document.createElement('div');box.id='dual-proof';box.style.cssText='position:fixed;right:10px;top:10px;z-index:2147483647;width:410px;padding:10px;background:#111e;color:#fff;font:12px system-ui;border:1px solid #ddd';box.innerHTML='<b>Alpha V1 双头顶 Live Proof · Authority V2</b><div id="n">authority bootstrap…</div><pre id="st"></pre><button id="b">P1身体基准</button> <button id="e">敌人头顶×2</button> <button id="r">live rebind</button> <button id="g">450ms authority gap</button> <button id="f">可见漂移 FAIL</button> <button id="ok">最终视觉 OK</button> <button id="j">生成 JSON</button><textarea id="o" style="display:none;width:100%;height:120px"></textarea>';document.documentElement.appendChild(box);const note=x=>box.querySelector('#n').textContent=x;
box.querySelector('#b').onclick=e=>{e.stopPropagation();mode='body';note('下一次点 P1 身体基准；必须与 common head click 同 authority-v2 lifecycle')};box.querySelector('#e').onclick=e=>{e.stopPropagation();mode='enemy';note('同一独立 lifecycle token 的 enemy 至少采两次头顶')};box.querySelector('#r').onclick=e=>{e.stopPropagation();bind()};box.querySelector('#g').onclick=e=>{e.stopPropagation();gap()};box.querySelector('#f').onclick=e=>{e.stopPropagation();s.setVisualDecision('FAIL_VISIBLE_REPEATABLE_DRIFT');render()};box.querySelector('#ok').onclick=e=>{e.stopPropagation();s.setVisualDecision('VISUAL_OK');note('视觉 OK 已记录；仍需全部 private/core objective gate');render()};box.querySelector('#j').onclick=e=>{e.stopPropagation();result()};
function render(){const st=box.querySelector('#st'),cs=s.status();if(!st)return;st.textContent='manifest ✓ trust '+(currentTrust()?'✓':'×')+' witness '+(s.hasLiveWitness()?'✓':'·')+' common '+(commonRaw()?.verdict||'PENDING')+' worker '+(snap?'✓':'·')+'\nworkerGeneration '+(snap?.authority?.workerGeneration??'·')+' lifecycleAuthority '+(snap?.lifecycleAuthorityFresh?'✓':'×')+' bind '+(bound?'✓':'·')+'\nP1 calibration '+(body?.stable?'✓':'·')+' enemy proved types ['+enemyObs().map(x=>x.type).join(',')+']\nplayer anchored '+s.player.filter(e=>C.authorityTuple(e)).length+' enemy anchored '+s.enemy.filter(e=>C.authorityTuple(e)).length+' staleTx '+(cs.authority?.stale?.coverage||'NOT_OBSERVED')}
function result(){const r=commonRaw();if(!boot.preflightOk)s.flagFailure('product_blob_binding');if(r?.verdict!=='IMPLEMENTATION_READY')s.requireObservation('common_projection');if(!bound)s.requireObservation('live_profile_rebind');let x=s.terminal(repo(),runtime(),commonOut(r));x.proofOnly={candidateProfiles:cand,playerClearanceObservation:body,enemyHeadOffsetObservations:enemyObs(),productionProfilesWritten:false,authorityRootId:initialTrust.authorityRootId,authorityRootSource:initialTrust.source};const v=C.shape(x);if(!v.ok){s.flagFailure('schema_generation');x=s.terminal(repo(),runtime(),commonOut(r));x.schemaErrors=v.errors}const t=JSON.stringify(x),o=box.querySelector('#o');o.style.display='block';o.value=t;console.log(t);navigator.clipboard?.writeText?.(t).catch(()=>{});note(x.verdict);return x}
window.WOFAlphaDualProof={proofSessionId:id,status:()=>({preflight:clone(boot.preflightOk),trustedRoot:currentTrust()?{authorityRootId:initialTrust.authorityRootId,source:initialTrust.source}:null,core:s.status(),bound,body:clone(body),enemy:enemyObs()}),result,bindProfiles:bind,exerciseAuthorityGap:gap,stop(){if(!run)return;run=false;clearInterval(timer);clearInterval(challengeTimer);removeEventListener('click',click,true);try{bc.close()}catch(_){}window.WOFAlphaPlayerHeadWarning.buildPlan=origP;window.WOFAlphaEnemyTargetLabels.buildPlan=origE;box.remove();delete window.WOFAlphaDualProof}};
note('authority-v2 trust root pinned；等待 strict Worker authority/lifecycle witness');render();console.log('✅ Alpha V1 dual live-proof Top ready · authority-v2',id);
})().catch(e=>console.error('❌ Alpha V1 dual proof Top failed closed',e));
