(async()=>{
'use strict';
const C=window.WOFAlphaDualProofCore,CH='wof-alpha-v1-dual-live-proof-recovery-v2',BASE='https://raw.githubusercontent.com/ouyong520/wof-ai-private/main/parallel/ALPHA_V1_ANCHORED_OVERLAYS_ONE_SESSION_LIVE_PROOF_TOOLING/';
if(!C||!window.WOFHUDANCHOR?.result||!window.WOFAlphaPlayerHeadWarning?.buildPlan||!window.WOFAlphaEnemyTargetLabels?.buildPlan||!window.WOFALPHAHUD?.status)throw new Error('common proof / Alpha helpers / HUD not ready');
try{window.WOFAlphaDualProof?.stop?.()}catch(_){}
const cv=window.I_GF1TC||document.getElementById('whathis'),gl=window.I_fdC8Q;if(!cv||!gl)throw new Error('WebGL canvas unavailable');
const bc=new BroadcastChannel(CH),rand=()=>{const b=new Uint8Array(16);crypto.getRandomValues(b);return[...b].map(x=>x.toString(16).padStart(2,'0')).join('')},id='dual-'+rand(),proofId='dual-proof-'+rand(),s=new C.Session(id),clone=x=>x==null?x:JSON.parse(JSON.stringify(x)),fin=Number.isFinite;
let run=true,snap=null,snaps=[],manifest=null,pre={ok:false,errors:['PENDING'],head:null},body=null,bound=false,cand=null,mode=null,seq=0,status0=null,pending=new Map(),enemyCaps=new Map(),lastP=0,lastE=0;
const origP=window.WOFAlphaPlayerHeadWarning.buildPlan,origE=window.WOFAlphaEnemyTargetLabels.buildPlan;
function layout(){const W=gl.drawingBufferWidth||cv.width,H=gl.drawingBufferHeight||cv.height,v=Array.from(gl.getParameter(gl.VIEWPORT)),y=H-(v[1]+v[3]);return{drawingBufferWidth:W,drawingBufferHeight:H,viewport:{x:v[0],y,width:v[2],height:v[3]},dpr:devicePixelRatio||1,fullscreen:!!document.fullscreenElement}}
const initialLayout=layout();
function commonRaw(){try{return window.WOFHUDANCHOR.result()}catch(_){return null}}
function commonOut(r=commonRaw()){const p=r?.projection||{},e=r?.evidence||{},n=p.native||{},cam=p.camera||{},d=p.drawingBuffer||{};return{verdict:r?.verdict==='IMPLEMENTATION_READY'?'IMPLEMENTATION_READY':'FAILED',proofId,projectionVersion:'dual-proof-recovery-v2',camera:{address:cam.address??null,read:cam.read||'u16be',qualityPassed:!!r?.camera?.quality?.ok,locked:!!cam.address},native:{width:n.width??384,height:n.height??224,xFormula:n.xFormula||'worldX-camera+xBias',xBias:n.xBias??0,yModel:n.yModel||'Y',yFormula:n.yFormula||'worldY+yBias',yBiasOrAnchorOffset:n.aboveCharacterOffsetNative??n.yBias??0},drawingBuffer:{source:d.source||'live WebGL VIEWPORT',formula:d.formula||'',layoutChangeCount:e?.layout?.changeCount||0,recovered:!!e?.layout?.recovered},objectiveEvidence:{worldXExcursion:e?.ranges?.worldX||0,cameraExcursion:e?.ranges?.camera||0,floorYExcursion:e?.ranges?.floorY||0,zExcursion:e?.ranges?.z||0,webglHookCount:e?.webgl?.hookCount||0,markerDrawCount:e?.webgl?.markerDrawCount||0}}}
function native(cx,cy){const r=cv.getBoundingClientRect(),L=layout(),v=L.viewport,x=(cx-r.left)/r.width*L.drawingBufferWidth,y=(cy-r.top)/r.height*L.drawingBufferHeight;if(x<v.x||x>v.x+v.width||y<v.y||y>v.y+v.height)return null;return{x:(x-v.x)/v.width*384,y:(y-v.y)/v.height*224}}
async function blob(path){const q=await fetch('https://raw.githubusercontent.com/ouyong520/wof-ai-private/main/'+path+'?pin='+Date.now(),{cache:'no-store'});if(!q.ok)throw new Error(path+' '+q.status);const b=await q.arrayBuffer(),h=new TextEncoder().encode('blob '+b.byteLength+'\0'),a=new Uint8Array(h.length+b.byteLength);a.set(h);a.set(new Uint8Array(b),h.length);return[...new Uint8Array(await crypto.subtle.digest('SHA-1',a))].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function preflight(){const er=[];try{const q=await fetch(BASE+'RUN_MANIFEST.json?'+Date.now(),{cache:'no-store'});if(!q.ok)throw Error('manifest '+q.status);manifest=await q.json()}catch(e){return{ok:false,errors:['MANIFEST:'+e.message],head:null}}for(const g of [manifest.productBlobs||{},manifest.proofToolBlobs||{}])for(const [k,v] of Object.entries(g))try{if(await blob(v.path)!==v.sha)er.push('BLOB_MISMATCH:'+k)}catch(e){er.push('BLOB_FETCH:'+k)}let head=null;try{const q=await fetch('https://api.github.com/repos/ouyong520/wof-ai-private/commits/main?x='+Date.now(),{cache:'no-store'});head=(await q.json()).sha}catch(e){er.push('HEAD_FETCH')}if(!/^[0-9a-f]{40}$/.test(head||''))er.push('HEAD_INVALID');return{ok:!er.length,errors:er,head}}
function repo(){const a={},b={};for(const[k,v]of Object.entries(manifest?.productBlobs||{}))a[k]=v.sha;for(const[k,v]of Object.entries(manifest?.proofToolBlobs||{}))b[k]=v.sha;return{head:pre.head||manifest?.implementationCommit||'0'.repeat(40),productBlobs:a,proofToolBlobs:b}}
function runtime(){const ep=snap?.binding?.runtimeEpoch||'unknown';return{romSha256:snap?.binding?.launcherIdentitySha||manifest?.romSha256||C.ROM,runtimeEpoch:String(ep),projectionEpoch:String(ep),browserBuild:navigator.userAgent||null,wofBuild:null,initialLayout,finalLayout:layout()}}
function send(kind,x={}){const requestId='r'+(++seq)+'-'+Date.now();bc.postMessage({schema:CH,kind,requestId,...x});return new Promise((res,rej)=>{const t=setTimeout(()=>{pending.delete(requestId);rej(Error(kind+' timeout'))},6000);pending.set(requestId,{res:v=>{clearTimeout(t);res(v)}})})}
window.WOFAlphaPlayerHeadWarning.buildPlan=function(a){const p=origP.call(this,a);try{s.record(C.playerEvents(a,p,Date.now()));if(p.anchored?.length){lastP=Date.now();if(bound)s.bind.player='PROVED'}phases()}catch(_){}return p};
window.WOFAlphaEnemyTargetLabels.buildPlan=function(a){const p=origE.call(this,a);try{s.record(C.enemyEvents(a,p,Date.now()));if(p.labels?.length){lastE=Date.now();if(bound)s.bind.enemy='PROVED'}retarget();multi();phases()}catch(_){}return p};
const span=a=>a.length?Math.max(...a)-Math.min(...a):0,vals=(x,f)=>x.map(f).filter(fin),ev=(a,t0,t1)=>a.filter(x=>x.at>=t0&&x.at<=t1&&x.decision==='ANCHORED_DRAW');
function mark(n,t0,t1){s.mark(n,'PASS',ev(s.player,t0,t1).length?'PASS':'NOT_OBSERVED',ev(s.enemy,t0,t1).length?'PASS':'NOT_OBSERVED',n+':'+t1)}
function phases(){if(!bound||snaps.length<2)return;const now=Date.now(),r=snaps.filter(x=>x.at>=now-1200),l=snaps.filter(x=>x.at>=now-2600);if(r.length<2)return;const px=vals(r,x=>x.players?.P1?.x),py=vals(r,x=>x.players?.P1?.y),ca=vals(r,x=>x.camera?.value);if(span(px)>=24)mark('fastHorizontal',r[0].at,now);if(span(py)>=8)mark('depthMovement',r[0].at,now);if(span(ca)>=6)mark('rapidStageCameraScroll',r[0].at,now);if(span(px)>=8&&span(ca)>=4)mark('simultaneousPlayerCamera',r[0].at,now);const z=vals(l,x=>x.players?.P1?.z);if(z.length>5&&span(z)>=8&&Math.abs(z[0]-Math.min(...z))<=2&&Math.abs(z.at(-1)-Math.min(...z))<=2)mark('fullJump',l[0].at,now);const by=new Map;for(const x of r)for(const e of x.enemies||[]){if(!by.has(e.sourceId))by.set(e.sourceId,[]);by.get(e.sourceId).push(e)}for(const[id,q]of by)if(span(vals(q,e=>e.enemyX))>=8||span(vals(q,e=>e.enemyY))>=6){const ee=ev(s.enemy,r[0].at,now).filter(e=>e.actorIdentity===id);s.mark('movingEnemy','PASS','NOT_OBSERVED',ee.length?'PASS':'NOT_OBSERVED','moving:'+id);break}const cr=commonRaw(),pm=new Set(s.player.filter(e=>e.decision==='ANCHORED_DRAW'&&e.mappingKey).map(e=>e.mappingKey)),em=new Set(s.enemy.filter(e=>e.decision==='ANCHORED_DRAW'&&e.mappingKey).map(e=>e.mappingKey));if(cr?.evidence?.layout?.changeCount>0&&cr?.evidence?.layout?.recovered)s.mark('resizeFullscreenRemap','PASS',pm.size>1?'PASS':'NOT_OBSERVED',em.size>1?'PASS':'NOT_OBSERVED','remap')}
function retarget(){const m=new Map;for(const e of s.enemy.filter(e=>e.decision==='ANCHORED_DRAW'&&e.actorIdentity&&e.target)){if(!m.has(e.actorIdentity))m.set(e.actorIdentity,[]);m.get(e.actorIdentity).push(e)}for(const[id,q]of m)for(let i=1;i<q.length;i++)if(q[i].target!==q[i-1].target){s.mark('liveRetarget','PASS','NOT_OBSERVED','PASS','retarget:'+id);return}}
function multi(){const q=s.enemy.filter(e=>e.decision==='ANCHORED_DRAW');for(const x of q)if(new Set(q.filter(e=>Math.abs(e.at-x.at)<=40).map(e=>e.actorIdentity)).size>=2){s.mark('multiEnemy','PASS','NOT_OBSERVED','PASS','multi');return}}
function baseY(x,m){return m==='Y-Z'?x.y-x.z:m==='Y+Z'?x.y+x.z:x.y}function eBase(x,m){return m==='Y-Z'?x.enemyY-x.enemyZ:m==='Y+Z'?x.enemyY+x.enemyZ:x.enemyY}
function enemyObs(){const out=[];for(const[type,q]of enemyCaps){const v=q.map(x=>x.enemyHeadOffsetNative),spread=Math.max(...v)-Math.min(...v);out.push({...q.at(-1),enemyHeadOffsetNative:v.reduce((a,b)=>a+b,0)/v.length,stable:spread<=4,captureCount:q.length,spreadNative:spread})}return out}
function click(e){if(!mode||e.target?.closest?.('#dual-proof'))return;const n=native(e.clientX,e.clientY),r=commonRaw();if(!n||!snap||Date.now()-snap.at>250||r?.verdict!=='IMPLEMENTATION_READY'){note('采集失败：common/live snapshot 不新鲜');mode=null;return}const f=C.facts(r),cam=snap.camera?.value;if(!f||!fin(cam)){note('common camera/projection 不完整');mode=null;return}if(mode==='body'){const p=snap.players?.P1,hy=r.calibration?.nativeClick?.y;if(!p?.present||!fin(hy)){note('P1/head calibration 不完整');mode=null;return}const y=n.y-baseY(p,f.yModel),h=n.y-hy,ok=fin(y)&&fin(h)&&h>=0&&Math.abs(n.x-(p.x-cam+f.xBias))<=28;body={evidenceClass:C.EVIDENCE_CLASS,source:'LIVE_OBSERVATION',browserWofActuallyRun:true,synthetic:false,stable:ok,bodyYBiasNative:y,headClearanceNative:h,validationBounds:{minX:0,maxX:383,minY:0,maxY:223},proofId,projectionVersion:'dual-proof-recovery-v2',observedAt:Date.now()};note(ok?'P1 live yBias/headClearance 已采集':'P1 body click 不稳定，fail-closed')}else{const q=(snap.enemies||[]).map(x=>({x,dx:Math.abs(x.enemyX-cam+f.xBias-n.x)})).filter(x=>x.dx<=28).sort((a,b)=>a.dx-b.dx);if(!q.length||(q[1]&&q[1].dx-q[0].dx<4)){note('敌人重叠/身份不唯一，未采集');mode=null;return}const x=q[0].x,o={evidenceClass:C.EVIDENCE_CLASS,source:'LIVE_OBSERVATION',browserWofActuallyRun:true,synthetic:false,stable:true,type:x.type,enemyHeadOffsetNative:n.y-eBase(x,f.yModel),proofId,observedAt:Date.now(),actorIdentity:x.sourceId,slot:x.slot,target7E:x.target7E};if(!enemyCaps.has(x.type))enemyCaps.set(x.type,[]);enemyCaps.get(x.type).push(o);note('enemy type '+x.type+' live head offset 已采集')}mode=null;render()}
addEventListener('click',click,true);
async function bind(){const r=commonRaw(),eo=enemyObs(),pp=C.playerProfile(r,body,{proofId,projectionVersion:'dual-proof-recovery-v2'}),ep=C.enemyProfile(r,eo,{proofId,romSha256:snap?.binding?.launcherIdentitySha});if(!pp.ok||!ep.ok){note('profile binder fail-closed: '+(pp.reason||ep.reason));return}cand={playerProfile:pp.profile,enemyProfile:ep.profile};try{const x=await send('bind-live-profiles',{...cand,proofId});bound=!!x?.result?.ok;note(bound?'proof-only live profile 已 rebind；production 未写入':'rebind 失败: '+(x?.result?.reason||'?'))}catch(e){note(e.message)}render()}
async function gap(){if(!bound||Date.now()-lastP>2000||Date.now()-lastE>2000){note('先同时出现真实 player warning + enemy label');return}try{const x=await send('exercise-authority-gap',{durationMs:450});note(x?.result?.ok?'authority gap 完成，等待 stale no-draw/fallback 记录':'gap fail')}catch(e){note(e.message)}}
function hud(){let x;try{x=window.WOFALPHAHUD.status()}catch(_){return}if(bound&&status0){const ep=snap?.binding?.runtimeEpoch;if(status0.enemyTargetLabels?.count>0&&!x.enemyTargetLabels?.connected)s.record([{at:Date.now(),surface:'enemy-target-label',actorIdentity:null,player:null,target7E:null,target:null,label:null,sampleAt:Date.now(),ageMs:null,confidence:null,epochs:{runtime:ep,projection:ep,drawingBuffer:ep},mappingKey:null,anchorDb:null,decision:'SUPPRESSED',reason:'STALE_OR_MISSING_MARKERS',evidenceRef:'authority-gap'}]);if(status0.playerHeadWarning?.anchored>0&&!x.playerHeadWarning?.connected&&x.playerHeadWarning?.fixed>0)s.record([{at:Date.now(),surface:'player-head-warning',actorIdentity:'P1',player:'P1',target7E:null,target:'P1',label:'危险',sampleAt:Date.now(),ageMs:null,confidence:null,epochs:{runtime:ep,projection:ep,drawingBuffer:ep},mappingKey:null,anchorDb:null,decision:'FIXED_HUD',reason:'STALE_PLAYER_SPATIAL_TRANSPORT_GAP',evidenceRef:'authority-gap'}])}status0=x}const timer=setInterval(hud,50);
bc.onmessage=e=>{const m=e.data;if(m?.schema!==CH)return;if(m.kind==='live-snapshot'){snap=m;snaps.push(m);if(snaps.length>180)snaps.shift();phases();render();return}const p=pending.get(m.requestId);if(p){pending.delete(m.requestId);p.res(m)}};bc.postMessage({schema:CH,kind:'request-snapshot'});
const box=document.createElement('div');box.id='dual-proof';box.style.cssText='position:fixed;right:10px;top:10px;z-index:2147483647;width:390px;padding:10px;background:#111e;color:#fff;font:12px system-ui;border:1px solid #ddd';box.innerHTML='<b>Alpha V1 双头顶 Live Proof</b><div id="n">preflight…</div><pre id="st"></pre><button id="b">P1身体基准</button> <button id="e">敌人头顶</button> <button id="r">live rebind</button> <button id="g">450ms authority gap</button> <button id="f">可见漂移 FAIL</button> <button id="ok">最终视觉 OK</button> <button id="j">生成 JSON</button><textarea id="o" style="display:none;width:100%;height:120px"></textarea>';document.documentElement.appendChild(box);const note=x=>box.querySelector('#n').textContent=x;
box.querySelector('#b').onclick=e=>{e.stopPropagation();mode='body';note('下一次点 P1 脚底/身体 world-reference 映射点')};box.querySelector('#e').onclick=e=>{e.stopPropagation();mode='enemy';note('下一次点一个不重叠 live enemy 头顶')};box.querySelector('#r').onclick=e=>{e.stopPropagation();bind()};box.querySelector('#g').onclick=e=>{e.stopPropagation();gap()};box.querySelector('#f').onclick=e=>{e.stopPropagation();s.visual.visibleRepeatableDrift=true;s.visual.operatorDecision='FAIL_VISIBLE_REPEATABLE_DRIFT'};box.querySelector('#ok').onclick=e=>{e.stopPropagation();s.visual.operatorDecision='VISUAL_OK';note('视觉 OK 已记录；仍需全部 objective gate')};box.querySelector('#j').onclick=e=>{e.stopPropagation();result()};
function render(){box.querySelector('#st').textContent='preflight '+(pre.ok?'✓':'·')+' common '+(commonRaw()?.verdict||'PENDING')+' worker '+(snap?'✓':'·')+'\nP1 split '+(body?.stable?'✓':'·')+' enemy types ['+[...enemyCaps.keys()].join(',')+'] bind '+(bound?'✓':'·')+'\nplayer anchored '+s.player.filter(e=>e.decision==='ANCHORED_DRAW').length+' enemy anchored '+s.enemy.filter(e=>e.decision==='ANCHORED_DRAW').length+' stale '+s.authority.stale.coverage}
function result(){const r=commonRaw();if(!pre.ok)s.fail.push('product_blob_binding');if(r?.verdict!=='IMPLEMENTATION_READY')s.need.push('common_projection');if(!bound)s.need.push('live_profile_rebind');const x=s.terminal(repo(),runtime(),commonOut(r));x.proofOnly={candidateProfiles:cand,playerClearanceObservation:body,enemyHeadOffsetObservations:enemyObs(),productionProfilesWritten:false};const v=C.shape(x);if(!v.ok){s.fail.push('schema_generation');x.verdict=s.verdict();x.schemaErrors=v.errors}const t=JSON.stringify(x),o=box.querySelector('#o');o.style.display='block';o.value=t;console.log(t);navigator.clipboard?.writeText?.(t).catch(()=>{});note(x.verdict);return x}
window.WOFAlphaDualProof={proofSessionId:id,status:()=>({preflight:clone(pre),bound,body:clone(body),enemy:enemyObs(),phases:clone(s.phases),authority:clone(s.authority)}),result,bindProfiles:bind,exerciseAuthorityGap:gap,stop(){if(!run)return;run=false;clearInterval(timer);removeEventListener('click',click,true);try{bc.close()}catch(_){}window.WOFAlphaPlayerHeadWarning.buildPlan=origP;window.WOFAlphaEnemyTargetLabels.buildPlan=origE;box.remove();delete window.WOFAlphaDualProof}};
pre=await preflight();note(pre.ok?'preflight PASS；先完成 HUDANCHOR common proof':'preflight fail-closed: '+pre.errors.join('|'));render();console.log('✅ Alpha V1 dual live-proof Top ready',id);
})().catch(e=>console.error('❌ Alpha V1 dual proof Top failed',e));
