(()=>{
'use strict';
const CHANNEL='wof-alpha-v1',STALE_MS=500,STARTUP_MS=8000;
const canvas=window.I_GF1TC||document.getElementById('whathis'),gl=window.I_fdC8Q;
if(!canvas||!gl||typeof gl.drawArrays!=='function')throw new Error('WOF Alpha: game WebGL canvas/context not found');
const isGL2=typeof WebGL2RenderingContext!=='undefined'&&gl instanceof WebGL2RenderingContext;
let bridge=window.__WOF_GL_HOOK;
if(!bridge||bridge.gl!==gl||typeof bridge.wrapper!=='function'||typeof bridge.nativeDraw!=='function'){
  const proto=isGL2?WebGL2RenderingContext.prototype:WebGLRenderingContext.prototype,nativeDraw=proto.drawArrays;if(typeof nativeDraw!=='function')throw new Error('WOF Alpha: native drawArrays missing');
  bridge={gl,nativeDraw,callback:null,inCallback:false,installs:0,wrapper:null,gameDraws:0};
  bridge.wrapper=function(mode,first,count){const r=bridge.nativeDraw.apply(this,arguments);if(this===gl)bridge.gameDraws++;const cb=bridge.callback;if(this===gl&&cb&&!bridge.inCallback){bridge.inCallback=true;try{cb(mode,first,count);}catch(e){bridge.lastError=String(e?.stack||e);}finally{bridge.inCallback=false;}}return r;};
  try{Object.defineProperty(gl,'drawArrays',{value:bridge.wrapper,writable:true,configurable:true});}catch(_){gl.drawArrays=bridge.wrapper;}if(gl.drawArrays!==bridge.wrapper)throw new Error('WOF Alpha: persistent WebGL hook failed');window.__WOF_GL_HOOK=bridge;
}else if(gl.drawArrays!==bridge.wrapper){try{Object.defineProperty(gl,'drawArrays',{value:bridge.wrapper,writable:true,configurable:true});}catch(_){gl.drawArrays=bridge.wrapper;}}
bridge.installs++;
try{window.WOFALPHAHUD?.dispose?.();}catch(_){}
try{window.WOFHUD?.hide?.();}catch(_){}
const V=`${isGL2?'#version 300 es\n':''}${isGL2?'in':'attribute'} vec4 a;${isGL2?'out':'varying'} vec2 v;void main(){gl_Position=vec4(a.xy,0.,1.);v=a.zw;}`;
const F=`${isGL2?'#version 300 es\n':''}precision mediump float;${isGL2?'in':'varying'} vec2 v;uniform sampler2D t;${isGL2?'out vec4 o;':''}void main(){${isGL2?'o=texture(t,v);':'gl_FragColor=texture2D(t,v);'}}`;
const shader=(type,src)=>{const s=gl.createShader(type);gl.shaderSource(s,src);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS)){const m=gl.getShaderInfoLog(s)||'shader';gl.deleteShader(s);throw new Error(m);}return s;};
const vs=shader(gl.VERTEX_SHADER,V),fs=shader(gl.FRAGMENT_SHADER,F),prog=gl.createProgram();gl.attachShader(prog,vs);gl.attachShader(prog,fs);gl.bindAttribLocation(prog,0,'a');gl.linkProgram(prog);gl.deleteShader(vs);gl.deleteShader(fs);if(!gl.getProgramParameter(prog,gl.LINK_STATUS)){const m=gl.getProgramInfoLog(prog)||'link';gl.deleteProgram(prog);throw new Error(m);}
const uTex=gl.getUniformLocation(prog,'t'),buf=gl.createBuffer(),tex=gl.createTexture(),hud=document.createElement('canvas');hud.width=340;hud.height=100;const c=hud.getContext('2d');
let lastMsg=null,lastRx=0,lastKey='',disposed=false,diag=null;const loadedAt=Date.now(),startupUntil=loadedAt+STARTUP_MS;
function snapGL(){const active=gl.getParameter(gl.ACTIVE_TEXTURE),activeTex=gl.getParameter(gl.TEXTURE_BINDING_2D);gl.activeTexture(gl.TEXTURE0);const tex0=gl.getParameter(gl.TEXTURE_BINDING_2D);gl.activeTexture(active);return{program:gl.getParameter(gl.CURRENT_PROGRAM),array:gl.getParameter(gl.ARRAY_BUFFER_BINDING),active,activeTex,tex0,viewport:Array.from(gl.getParameter(gl.VIEWPORT)),blend:gl.isEnabled(gl.BLEND),depth:gl.isEnabled(gl.DEPTH_TEST),cull:gl.isEnabled(gl.CULL_FACE),scissor:gl.isEnabled(gl.SCISSOR_TEST),srcRGB:gl.getParameter(gl.BLEND_SRC_RGB),dstRGB:gl.getParameter(gl.BLEND_DST_RGB),srcA:gl.getParameter(gl.BLEND_SRC_ALPHA),dstA:gl.getParameter(gl.BLEND_DST_ALPHA),eqRGB:gl.getParameter(gl.BLEND_EQUATION_RGB),eqA:gl.getParameter(gl.BLEND_EQUATION_ALPHA),mask:Array.from(gl.getParameter(gl.COLOR_WRITEMASK)),flip:gl.getParameter(gl.UNPACK_FLIP_Y_WEBGL),premul:gl.getParameter(gl.UNPACK_PREMULTIPLY_ALPHA_WEBGL),a0:{enabled:!!gl.getVertexAttrib(0,gl.VERTEX_ATTRIB_ARRAY_ENABLED),buf:gl.getVertexAttrib(0,gl.VERTEX_ATTRIB_ARRAY_BUFFER_BINDING),size:gl.getVertexAttrib(0,gl.VERTEX_ATTRIB_ARRAY_SIZE),type:gl.getVertexAttrib(0,gl.VERTEX_ATTRIB_ARRAY_TYPE),norm:!!gl.getVertexAttrib(0,gl.VERTEX_ATTRIB_ARRAY_NORMALIZED),stride:gl.getVertexAttrib(0,gl.VERTEX_ATTRIB_ARRAY_STRIDE),offset:gl.getVertexAttribOffset(0,gl.VERTEX_ATTRIB_ARRAY_POINTER)}};}
function restoreGL(s){s.blend?gl.enable(gl.BLEND):gl.disable(gl.BLEND);s.depth?gl.enable(gl.DEPTH_TEST):gl.disable(gl.DEPTH_TEST);s.cull?gl.enable(gl.CULL_FACE):gl.disable(gl.CULL_FACE);s.scissor?gl.enable(gl.SCISSOR_TEST):gl.disable(gl.SCISSOR_TEST);gl.blendFuncSeparate(s.srcRGB,s.dstRGB,s.srcA,s.dstA);gl.blendEquationSeparate(s.eqRGB,s.eqA);gl.colorMask(...s.mask);gl.viewport(...s.viewport);if(s.a0.buf){gl.bindBuffer(gl.ARRAY_BUFFER,s.a0.buf);gl.vertexAttribPointer(0,s.a0.size,s.a0.type,s.a0.norm,s.a0.stride,s.a0.offset);}s.a0.enabled?gl.enableVertexAttribArray(0):gl.disableVertexAttribArray(0);gl.useProgram(s.program);gl.activeTexture(gl.TEXTURE0);gl.bindTexture(gl.TEXTURE_2D,s.tex0);gl.activeTexture(s.active);if(s.active!==gl.TEXTURE0)gl.bindTexture(gl.TEXTURE_2D,s.activeTex);gl.pixelStorei(gl.UNPACK_FLIP_Y_WEBGL,s.flip);gl.pixelStorei(gl.UNPACK_PREMULTIPLY_ALPHA_WEBGL,s.premul);gl.bindBuffer(gl.ARRAY_BUFFER,s.array);}
function upload(){const s=snapGL();try{gl.activeTexture(gl.TEXTURE0);gl.bindTexture(gl.TEXTURE_2D,tex);gl.pixelStorei(gl.UNPACK_FLIP_Y_WEBGL,true);gl.pixelStorei(gl.UNPACK_PREMULTIPLY_ALPHA_WEBGL,false);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,gl.RGBA,gl.UNSIGNED_BYTE,hud);}finally{restoreGL(s);}}
const sideText=s=>s==='LEFT'?'左侧':s==='RIGHT'?'右侧':s==='CENTER'?'近身':'方向未知';
function paintWarning(w){const main=w.attackSpecific?`A${w.attack} 危险`:'危险',line2=`${w.target} · ${sideText(w.threatSide)}`,line3=w.validatedLeadLabel||w.timingClass||'';const key=['w',main,line2,line3,w.ruleId].join('|');if(key===lastKey)return;lastKey=key;c.clearRect(0,0,340,100);c.fillStyle='rgba(0,0,0,.90)';c.fillRect(1,1,338,98);c.strokeStyle='rgba(255,255,255,.99)';c.lineWidth=2;c.strokeRect(2,2,336,96);c.fillStyle='#fff';c.textAlign='center';c.textBaseline='middle';c.font='bold 30px sans-serif';c.fillText(main,170,28);c.font='bold 18px sans-serif';c.fillText(line2,170,60);c.font='bold 13px sans-serif';c.fillText(line3,170,83);upload();}
function paintStatus(text){const key='s|'+text;if(key===lastKey)return;lastKey=key;c.clearRect(0,0,340,100);c.fillStyle='rgba(0,0,0,.88)';c.fillRect(1,1,338,52);c.strokeStyle='rgba(255,255,255,.99)';c.lineWidth=2;c.strokeRect(2,2,336,50);c.fillStyle='#fff';c.textAlign='center';c.textBaseline='middle';c.font='bold 18px sans-serif';c.fillText(text,170,27);upload();}
function drawTexture(x,y,w,h){const W=gl.drawingBufferWidth||canvas.width,H=gl.drawingBufferHeight||canvas.height;if(!(W>0&&H>0))return;const l=x/W*2-1,r=(x+w)/W*2-1,t=1-y/H*2,b=1-(y+h)/H*2,v=new Float32Array([l,t,0,1,l,b,0,0,r,b,1,0,l,t,0,1,r,b,1,0,r,t,1,1]),s=snapGL();try{gl.viewport(0,0,W,H);gl.disable(gl.DEPTH_TEST);gl.disable(gl.CULL_FACE);gl.disable(gl.SCISSOR_TEST);gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA);gl.colorMask(true,true,true,true);gl.useProgram(prog);gl.bindBuffer(gl.ARRAY_BUFFER,buf);gl.bufferData(gl.ARRAY_BUFFER,v,gl.STREAM_DRAW);gl.enableVertexAttribArray(0);gl.vertexAttribPointer(0,4,gl.FLOAT,false,0,0);gl.activeTexture(gl.TEXTURE0);gl.bindTexture(gl.TEXTURE_2D,tex);gl.uniform1i(uTex,0);bridge.nativeDraw.call(gl,gl.TRIANGLES,0,6);}finally{restoreGL(s);}}
function draw(){if(disposed)return;const now=Date.now(),W=gl.drawingBufferWidth||canvas.width,H=gl.drawingBufferHeight||canvas.height;if(!(W>0&&H>0))return;const fresh=lastRx&&now-lastRx<=STALE_MS,w=fresh?lastMsg?.warnings?.[0]:null;if(w){paintWarning(w);const ww=Math.min(340,W-8),hh=Math.min(100,H-8);drawTexture((W-ww)/2,Math.max(4,H-hh-8),ww,hh);return;}if(diag&&now-diag.at<STARTUP_MS){paintStatus('ALPHA 未启用 · '+diag.reason);const ww=Math.min(340,W-8);drawTexture((W-ww)/2,8,ww,54);return;}if(now<startupUntil){paintStatus('WOF Alpha RC1 已加载');const ww=Math.min(340,W-8);drawTexture((W-ww)/2,8,ww,54);}}
bridge.callback=draw;
const bc=new BroadcastChannel(CHANNEL);bc.onmessage=e=>{const m=e.data;if(m?.schema!==CHANNEL)return;if(m.kind==='state'){lastMsg=m;lastRx=Date.now();diag=null;}else if(m.kind==='diagnostic'){lastMsg=null;lastRx=0;diag={reason:m.reason||m.state||'disabled',at:Date.now()};}};
function dispose(){if(disposed)return;disposed=true;if(bridge.callback===draw)bridge.callback=null;try{bc.close();}catch(_){}try{gl.deleteTexture(tex);gl.deleteBuffer(buf);gl.deleteProgram(prog);}catch(_){};}
window.WOFALPHAHUD={version:'wof-alpha-hud-rc1',status(){return{connected:!!lastRx&&Date.now()-lastRx<=STALE_MS,ageMs:lastRx?Date.now()-lastRx:null,warning:lastMsg?.warnings?.[0]||null,diagnostic:diag,drawHooked:gl.drawArrays===bridge.wrapper,lastError:bridge.lastError||null};},dispose};
try{paintStatus('WOF Alpha RC1 已加载');const W=gl.drawingBufferWidth||canvas.width;drawTexture(Math.max(4,(W-Math.min(340,W-8))/2),8,Math.min(340,W-8),54);}catch(_){}
console.log('✅ WOF Alpha HUD RC1 installed | SAFE/UNKNOWN silent | stale fail-closed');
})();
